import GenMarkoff.Core.Statements

/-!
# The equal-coefficient generalized Markoff family

This module fixes the restricted coefficient triple `(c, c, c)`.  Coordinate
permutations preserve this family.  The symmetric development therefore
supports both the original rotation group generated by two-Vieta words and
the selected one-step group obtained by adjoining the affine half-steps.
-/

namespace GenMarkoff.Symmetric

universe u

/-- The equal-coefficient triple `(c, c, c)`. -/
def coefficients {R : Type u} (c : R) : Coefficients R :=
  ⟨c, c, c⟩

@[simp]
theorem coefficients_a1 {R : Type u} (c : R) :
    (coefficients c).a1 = c :=
  rfl

@[simp]
theorem coefficients_a2 {R : Type u} (c : R) :
    (coefficients c).a2 = c :=
  rfl

@[simp]
theorem coefficients_a3 {R : Type u} (c : R) :
    (coefficients c).a3 = c :=
  rfl

@[simp]
theorem coefficients_multiplier {R : Type u} [CommRing R] (c : R) :
    (coefficients c).multiplier = 3 * (1 + c) := by
  simp [coefficients, Coefficients.multiplier]
  ring

/-- The cubic multiplier of the equal-coefficient family. -/
def multiplier {R : Type u} [CommRing R] (c : R) : R :=
  3 * (1 + c)

@[simp]
theorem multiplier_eq_coefficients_multiplier
    {R : Type u} [CommRing R] (c : R) :
    multiplier c = (coefficients c).multiplier := by
  simp [multiplier]

/-- The trace parameter attached to a fixed coordinate `u`. -/
def trace {R : Type u} [CommRing R] (c u : R) : R :=
  multiplier c * u - c

theorem trace_eq {R : Type u} [CommRing R] (c u : R) :
    trace c u = (coefficients c).multiplier * u - c := by
  simp [trace]

/-- Away from the vanishing multiplier, the affine-origin trace `-c` occurs
exactly at the zero coordinate. -/
theorem trace_eq_neg_self_iff {K : Type u} [Field K]
    (c u : K) (hs : multiplier c ≠ 0) :
    trace c u = -c ↔ u = 0 := by
  rw [trace]
  constructor
  · intro h
    apply (mul_eq_zero.mp (by linear_combination h)).resolve_left hs
  · rintro rfl
    ring

@[simp]
theorem polynomial_mk {R : Type u} [CommRing R]
    (c x₁ x₂ x₃ : R) :
    polynomial (coefficients c) ⟨x₁, x₂, x₃⟩ =
      x₁ ^ 2 + x₂ ^ 2 + x₃ ^ 2 +
        c * (x₂ * x₃ + x₃ * x₁ + x₁ * x₂) -
          multiplier c * x₁ * x₂ * x₃ := by
  simp [polynomial, coefficients, Coefficients.multiplier, multiplier]
  ring

/-- On the first-coordinate fiber, the surface equation is an affine conic
whose mixed coefficient is the negative trace parameter. -/
theorem polynomial_fixed_first {R : Type u} [CommRing R]
    (c u y z : R) :
    polynomial (coefficients c) ⟨u, y, z⟩ =
      y ^ 2 + z ^ 2 - trace c u * y * z +
        c * u * (y + z) + u ^ 2 := by
  simp [trace, multiplier]
  ring

/-- Equal integral coefficients are nondegenerate exactly when the multiplier
and the single repeated coefficient avoid their exceptional values. -/
theorem integrallyNondegenerate_coefficients_iff (c : ℤ) :
    IntegrallyNondegenerate (coefficients c) ↔
      3 * (1 + c) ≠ 0 ∧ c ^ 2 ≠ 4 := by
  simp only [IntegrallyNondegenerate, coefficients_multiplier,
    coefficients_a1, coefficients_a2, coefficients_a3]
  tauto

@[simp]
theorem intCast_coefficients (c : ℤ) (R : Type u) [CommRing R] :
    Coefficients.intCast (coefficients c) R = coefficients (c : R) := by
  rfl

@[simp]
theorem modCoefficients_coefficients (c : ℤ) (p : ℕ) :
    modCoefficients (coefficients c) p = coefficients (c : ZMod p) := by
  rfl

/-- The affine trace-coordinate polynomial for the symmetric family. -/
def tracePolynomial {R : Type u} [CommRing R] (c : R) (t : Point R) : R :=
  t.x1 ^ 2 + t.x2 ^ 2 + t.x3 ^ 2 - t.x1 * t.x2 * t.x3 +
    c * (c + 2) * (t.x1 + t.x2 + t.x3) + c ^ 2 * (2 * c + 3)

/-- Apply the fixed-coordinate trace change in all three coordinates. -/
def tracePoint {R : Type u} [CommRing R] (c : R) (x : Point R) : Point R :=
  ⟨trace c x.x1, trace c x.x2, trace c x.x3⟩

@[simp]
theorem tracePoint_x1 {R : Type u} [CommRing R] (c : R) (x : Point R) :
    (tracePoint c x).x1 = trace c x.x1 :=
  rfl

@[simp]
theorem tracePoint_x2 {R : Type u} [CommRing R] (c : R) (x : Point R) :
    (tracePoint c x).x2 = trace c x.x2 :=
  rfl

@[simp]
theorem tracePoint_x3 {R : Type u} [CommRing R] (c : R) (x : Point R) :
    (tracePoint c x).x3 = trace c x.x3 :=
  rfl

/-- Division-free trace-coordinate identity.  This is the symmetric
replacement for the classical normalized Markoff equation. -/
theorem tracePolynomial_tracePoint {R : Type u} [CommRing R]
    (c : R) (x : Point R) :
    tracePolynomial c (tracePoint c x) =
      multiplier c ^ 2 * polynomial (coefficients c) x := by
  simp [tracePolynomial, tracePoint, trace, multiplier, polynomial,
    coefficients, Coefficients.multiplier]
  ring

/-- Over a field where the cubic multiplier is nonzero, the trace change
identifies the symmetric surface with `tracePolynomial = 0`. -/
theorem isSolution_iff_tracePolynomial_tracePoint
    {K : Type u} [Field K] (c : K) (x : Point K)
    (hs : multiplier c ≠ 0) :
    IsSolution (coefficients c) x ↔
      tracePolynomial c (tracePoint c x) = 0 := by
  rw [IsSolution, tracePolynomial_tracePoint]
  exact (mul_eq_zero_iff_left (pow_ne_zero 2 hs)).symm

/-- The restricted eventual strong-approximation statement. -/
def EventualStrongApproximationStatement : Prop :=
  ∀ c : ℤ, 3 * (1 + c) ≠ 0 → c ^ 2 ≠ 4 →
    EventuallyRotationStrongApproximation (coefficients c)

end GenMarkoff.Symmetric
