import GenMarkoff.Assembly.EventualStrongApproximation
import GenMarkoff.Symmetric.OneStepAction

/-!
# Strong approximation for the symmetric one-step action

These statements concern the group generated by the symmetry-enabled affine
half-steps.  They are deliberately distinct from the fixed-coefficient
`RotationGroup` statements: each old rotation is the square of a one-step
generator, but the two actions need not have the same orbits.
-/

namespace GenMarkoff.Symmetric

/-- Strong approximation at one prime for the symmetric one-step group. -/
def OneStepStrongApproximationAt (c : ℤ) (p : ℕ) (hp : p.Prime) : Prop :=
  letI : Fact p.Prime := ⟨hp⟩
  ∀ x y : PuncturedSolutionSurface (coefficients (c : ZMod p)),
    ∃ g : OneStepGroup (c : ZMod p), g • x = y

/-- Eventual strong approximation for the symmetric one-step group. -/
def EventuallyOneStepStrongApproximation (c : ℤ) : Prop :=
  ∃ p₀ : ℕ, ∀ (p : ℕ) (hp : p.Prime), p₀ ≤ p →
    OneStepStrongApproximationAt c p hp

/-- The number of punctured points outside the one-step orbit of `x`. -/
noncomputable def oneStepOrbitComplementCard
    {p : ℕ} {c : ZMod p}
    (x : PuncturedSolutionSurface (coefficients c)) : ℕ :=
  (Set.univ \ puncturedOneStepOrbit x).ncard

/-- At `p`, the symmetric surface has a one-step orbit whose complement has
at most `p ^ epsilon` points. -/
def HasGiantOneStepOrbitAt
    (c : ℤ) (p : ℕ) (hp : p.Prime) (epsilon : ℝ) : Prop :=
  letI : Fact p.Prime := ⟨hp⟩
  ∃ x : PuncturedSolutionSurface (coefficients (c : ZMod p)),
    (oneStepOrbitComplementCard x : ℝ) ≤ Real.rpow p epsilon

/-- Every positive exponent eventually gives a giant one-step orbit. -/
def EventuallyHasGiantOneStepOrbit (c : ℤ) : Prop :=
  ∀ epsilon : ℝ, 0 < epsilon →
    ∃ p₀ : ℕ, ∀ (p : ℕ) (hp : p.Prime), p₀ ≤ p →
      HasGiantOneStepOrbitAt c p hp epsilon

/-- The one-step giant-orbit theorem sought for the equal-coefficient family. -/
def OneStepGiantOrbitStatement : Prop :=
  ∀ c : ℤ, 3 * (1 + c) ≠ 0 → c ^ 2 ≠ 4 →
    EventuallyHasGiantOneStepOrbit c

/-- The eventual strong-approximation target for the one-step action. -/
def EventualOneStepStrongApproximationStatement : Prop :=
  ∀ c : ℤ, 3 * (1 + c) ≠ 0 → c ^ 2 ≠ 4 →
    EventuallyOneStepStrongApproximation c

/-- Every old two-Vieta rotation orbit is contained in the corresponding
one-step orbit. -/
theorem puncturedRotationOrbit_subset_puncturedOneStepOrbit
    {R : Type*} [CommRing R] (c : R)
    (x : PuncturedSolutionSurface (coefficients c)) :
    puncturedRotationOrbit x ⊆ puncturedOneStepOrbit x := by
  intro y hy
  obtain ⟨g, hg⟩ := MulAction.mem_orbit_iff.mp hy
  apply MulAction.mem_orbit_iff.mpr
  let g' : OneStepGroup c :=
    ⟨g.1, RotationGroup_le_OneStepGroup c g.2⟩
  refine ⟨g', ?_⟩
  apply Subtype.ext
  exact congrArg Subtype.val hg

/-- Enlarging a rotation orbit to its one-step orbit can only shrink the
complement. -/
theorem oneStepOrbitComplementCard_le_rotationOrbitComplementCard
    {p : ℕ} [NeZero p] (c : ZMod p)
    (x : PuncturedSolutionSurface (coefficients c)) :
    oneStepOrbitComplementCard x ≤ rotationOrbitComplementCard x := by
  classical
  apply Set.ncard_le_ncard (ht := Set.toFinite _)
  intro y hy
  refine ⟨Set.mem_univ y, ?_⟩
  intro hry
  exact hy.2 (puncturedRotationOrbit_subset_puncturedOneStepOrbit c x hry)

/-- A one-step orbit with complement smaller than `p` is the whole punctured
surface if every old rotation orbit has cardinality divisible by `p`.

The use of rotation divisibility is sound because the one-step orbit is
invariant under the contained rotation subgroup. -/
theorem oneStepStrongApproximationAt_of_small_complement_and_rotationOrbitCard_dvd
    (c : ℤ) (p : ℕ) (hp : p.Prime)
    (x : PuncturedSolutionSurface (coefficients (c : ZMod p)))
    (hsmall : oneStepOrbitComplementCard x < p)
    (hdiv : RotationOrbitDivisibilityAt (coefficients c) p hp) :
    OneStepStrongApproximationAt c p hp := by
  letI : Fact p.Prime := ⟨hp⟩
  change ∀ a b : PuncturedSolutionSurface (coefficients (c : ZMod p)),
    ∃ g : OneStepGroup (c : ZMod p), g • a = b
  change ∀ y : PuncturedSolutionSurface (coefficients (c : ZMod p)),
    p ∣ (puncturedRotationOrbit y).ncard at hdiv
  have hxAll :
      ∀ y : PuncturedSolutionSurface (coefficients (c : ZMod p)),
        y ∈ puncturedOneStepOrbit x := by
    intro y
    by_contra hy
    have horbitSubset :
        puncturedRotationOrbit y ⊆
          Set.univ \ puncturedOneStepOrbit x := by
      intro z hz
      refine ⟨Set.mem_univ z, ?_⟩
      intro hzx
      apply hy
      have hzy : puncturedOneStepOrbit z = puncturedOneStepOrbit y :=
        MulAction.orbit_eq_iff.mpr
          (puncturedRotationOrbit_subset_puncturedOneStepOrbit
            (c : ZMod p) y hz)
      have hzx' : puncturedOneStepOrbit z = puncturedOneStepOrbit x :=
        MulAction.orbit_eq_iff.mpr hzx
      exact MulAction.orbit_eq_iff.mp (hzy.symm.trans hzx')
    have horbitPos : 0 < (puncturedRotationOrbit y).ncard :=
      (Set.ncard_pos (Set.toFinite _)).2
        ⟨y, MulAction.mem_orbit_self y⟩
    have hpLeOrbit : p ≤ (puncturedRotationOrbit y).ncard :=
      Nat.le_of_dvd horbitPos (hdiv y)
    have horbitLeComplement :
        (puncturedRotationOrbit y).ncard ≤
          oneStepOrbitComplementCard x := by
      rw [oneStepOrbitComplementCard]
      exact Set.ncard_le_ncard horbitSubset
    omega
  intro a b
  obtain ⟨ga, hga⟩ := MulAction.mem_orbit_iff.mp (hxAll a)
  obtain ⟨gb, hgb⟩ := MulAction.mem_orbit_iff.mp (hxAll b)
  refine ⟨gb * ga⁻¹, ?_⟩
  calc
    (gb * ga⁻¹) • a = gb • (ga⁻¹ • a) := mul_smul _ _ _
    _ = gb • x := by rw [← hga, inv_smul_smul]
    _ = b := hgb

/-- A `p ^ epsilon` one-step complement bound with `epsilon < 1` is strictly
smaller than `p`. -/
theorem exists_oneStepOrbitComplementCard_lt_prime_of_hasGiantOneStepOrbitAt
    (c : ℤ) (p : ℕ) (hp : p.Prime)
    (epsilon : ℝ) (hepsilon : epsilon < 1)
    (hgiant : HasGiantOneStepOrbitAt c p hp epsilon) :
    letI : Fact p.Prime := ⟨hp⟩
    ∃ x : PuncturedSolutionSurface (coefficients (c : ZMod p)),
      oneStepOrbitComplementCard x < p := by
  letI : Fact p.Prime := ⟨hp⟩
  obtain ⟨x, hx⟩ := hgiant
  refine ⟨x, ?_⟩
  have hpReal : (1 : ℝ) < (p : ℝ) := by
    exact_mod_cast hp.one_lt
  have hrpow : (p : ℝ) ^ epsilon < (p : ℝ) := by
    simpa only [Real.rpow_one] using
      Real.rpow_lt_rpow_of_exponent_lt hpReal hepsilon
  have hreal : (oneStepOrbitComplementCard x : ℝ) < (p : ℝ) :=
    hx.trans_lt hrpow
  exact_mod_cast hreal

/-- The one-prime assembly for the symmetric one-step action. -/
theorem oneStepStrongApproximationAt_of_hasGiantOneStepOrbitAt_and_rotationOrbitDivisibility
    (c : ℤ) (p : ℕ) (hp : p.Prime)
    (epsilon : ℝ) (hepsilon : epsilon < 1)
    (hgiant : HasGiantOneStepOrbitAt c p hp epsilon)
    (hdiv : RotationOrbitDivisibilityAt (coefficients c) p hp) :
    OneStepStrongApproximationAt c p hp := by
  letI : Fact p.Prime := ⟨hp⟩
  obtain ⟨x, hx⟩ :=
    exists_oneStepOrbitComplementCard_lt_prime_of_hasGiantOneStepOrbitAt
      c p hp epsilon hepsilon hgiant
  exact
    oneStepStrongApproximationAt_of_small_complement_and_rotationOrbitCard_dvd
      c p hp x hx hdiv

/-- Eventual one-step giant-orbit control with an exponent below one, together
with eventual rotation-orbit divisibility, implies eventual one-step strong
approximation. -/
theorem eventuallyOneStepStrongApproximation_of_giantOrbit_and_rotationOrbitDivisibility
    (c : ℤ) (epsilon : ℝ) (hepsilon : epsilon < 1)
    (hgiant : ∃ p₀ : ℕ, ∀ (p : ℕ) (hp : p.Prime), p₀ ≤ p →
      HasGiantOneStepOrbitAt c p hp epsilon)
    (hdiv : EventuallyRotationOrbitDivisibility (coefficients c)) :
    EventuallyOneStepStrongApproximation c := by
  obtain ⟨giantThreshold, hgiant⟩ := hgiant
  obtain ⟨divisibilityThreshold, hdiv⟩ := hdiv
  refine ⟨max giantThreshold divisibilityThreshold, ?_⟩
  intro p hp hpLarge
  have hpGiant : giantThreshold ≤ p :=
    (Nat.le_max_left _ _).trans hpLarge
  have hpDivisibility : divisibilityThreshold ≤ p :=
    (Nat.le_max_right _ _).trans hpLarge
  exact
    oneStepStrongApproximationAt_of_hasGiantOneStepOrbitAt_and_rotationOrbitDivisibility
      c p hp epsilon hepsilon (hgiant p hp hpGiant)
        (hdiv p hp hpDivisibility)

/-- The one-step giant-orbit statement is the sole remaining geometric input
for eventual one-step strong approximation in the symmetric family. -/
theorem eventualOneStepStrongApproximationStatement_of_giantOrbit
    (hgiant : OneStepGiantOrbitStatement) :
    EventualOneStepStrongApproximationStatement := by
  intro c hs hc
  have ha : IntegrallyNondegenerate (coefficients c) :=
    (integrallyNondegenerate_coefficients_iff c).2 ⟨hs, hc⟩
  exact
    eventuallyOneStepStrongApproximation_of_giantOrbit_and_rotationOrbitDivisibility
      c (1 / 2 : ℝ) (by norm_num)
        ((hgiant c hs hc) (1 / 2 : ℝ) (by norm_num))
        ha.eventually_rotationOrbitDivisibility

end GenMarkoff.Symmetric
