import BGS.HasseWeil.ExactConstantExtensionConstants
import BGS.HasseWeil.ExactConstantExtensionFrobeniusTwist

/-!
# Exact constants of Frobenius-twist fields

Let `T = S ⊗[C] N` be an exact finite constant extension and let `F_g`
be the fixed field of the cyclic group generated by `(Frob, g)`.  This file
proves that `C` is the exact constant field of every `F_g`.

Indeed, an element of `F_g` algebraic over `C` is algebraic over `S` in `T`,
so exactness of the constants of `T` puts it in the embedded copy of `S`.
Since the element is fixed by `(Frob, g)`, its representative in `S` is fixed
by Frobenius and hence belongs to `C`.

The order calculation for `(Frob, g)` is not needed for this descent, so the
result is stronger than the version with the usual divisibility hypothesis.
-/

open scoped Polynomial TensorProduct

namespace BGS.HasseWeil

noncomputable section

set_option synthInstance.maxHeartbeats 200000
set_option maxHeartbeats 800000

variable (C L N S : Type*) [Field C] [Field L] [Field N] [Field S]
  [Algebra C L] [Algebra L N] [Algebra C N] [IsScalarTower C L N]
  [Algebra C S] [FiniteDimensional C S] [IsGalois C S]
  [FiniteDimensional L N] [IsGalois L N]
  [Fintype C] [Finite S]

omit [FiniteDimensional L N] [IsGalois L N] in
/-- Every Frobenius-twist fixed field has exact constant field `C`.

No divisibility condition on the order of `Gal(N/L)` is required: only the
restriction of the twist generator to `S`, which is the `C`-Frobenius, enters
the proof. -/
theorem exactConstantExtensionFrobeniusTwistField_algebraicClosure_eq_bot
    (hExact : algebraicClosure C N =
      (⊥ : IntermediateField C N))
    (g : N ≃ₐ[L] N) :
    letI := exactConstantExtensionField C N S hExact
    letI := exactConstantExtensionBaseAlgebra C L N S
    let F := exactConstantExtensionFrobeniusTwistField C L N S hExact g
    letI : Algebra C F := Algebra.restrictScalars C L F
    algebraicClosure C F = (⊥ : IntermediateField C F) := by
  let T := ExactConstantExtension C N S
  letI : Field T := exactConstantExtensionField C N S hExact
  letI : Algebra L T := exactConstantExtensionBaseAlgebra C L N S
  letI : Algebra C T := Algebra.restrictScalars C L T
  letI : SMul C T := Algebra.toSMul
  letI : IsScalarTower C L T := IsScalarTower.of_algebraMap_eq' rfl
  let F := exactConstantExtensionFrobeniusTwistField C L N S hExact g
  letI : Algebra C F := Algebra.restrictScalars C L F
  letI : IsScalarTower C L F := IsScalarTower.of_algebraMap_eq' rfl
  letI : Algebra S T := Algebra.TensorProduct.leftAlgebra
  letI : SMul S T := Algebra.toSMul
  have hCS : algebraMap C T =
      (algebraMap S T).comp (algebraMap C S) := by
    ext c
    change (1 : S) ⊗ₜ algebraMap L N (algebraMap C L c) =
      algebraMap C S c ⊗ₜ (1 : N)
    rw [← IsScalarTower.algebraMap_apply C L N]
    exact (Algebra.TensorProduct.tmul_one_eq_one_tmul c).symm
  letI : IsScalarTower C S T := IsScalarTower.of_algebraMap_eq' hCS
  have hTopExact : algebraicClosure S T =
      (⊥ : IntermediateField S T) :=
    exactConstantExtension_algebraicClosure_eq_bot C N S hExact
  apply eq_bot_iff.mpr
  intro z hz
  have hzC : IsAlgebraic C z := mem_algebraicClosure_iff.mp hz
  have hzCT : IsAlgebraic C (z : T) := by
    exact IsAlgebraic.algHom (F.val.restrictScalars C) hzC
  have hzST : IsAlgebraic S (z : T) :=
    IsAlgebraic.tower_top S hzCT
  have hzBotS : (z : T) ∈ (⊥ : IntermediateField S T) := by
    rw [← hTopExact]
    exact mem_algebraicClosure_iff.mpr hzST
  obtain ⟨s, hs⟩ := IntermediateField.mem_bot.mp hzBotS
  let τ := exactConstantExtensionFrobeniusTwist C L N S hExact g
  have hzFix : τ (z : T) = (z : T) := by
    apply (IntermediateField.mem_fixedField_iff
      (exactConstantExtensionFrobeniusTwistSubgroup C L N S hExact g)
      (z : T)).mp z.property
    exact Subgroup.mem_zpowers τ
  have hsFix : FiniteField.frobeniusAlgEquivOfAlgebraic C S s = s := by
    apply (algebraMap S T).injective
    calc
      algebraMap S T (FiniteField.frobeniusAlgEquivOfAlgebraic C S s) =
          τ (algebraMap S T s) := by
        change
          (FiniteField.frobeniusAlgEquivOfAlgebraic C S s) ⊗ₜ (1 : N) =
            τ (s ⊗ₜ (1 : N))
        simp [τ, exactConstantExtensionFrobeniusTwist,
          exactConstantExtensionCombinedAutHom,
          exactConstantExtensionConstantAutHom,
          exactConstantExtensionFunctionAutHom,
          exactConstantExtensionConstantAlgEquivOverBase,
          exactConstantExtensionFunctionAlgEquivOverBase]
      _ = τ (z : T) := congrArg τ hs
      _ = (z : T) := hzFix
      _ = algebraMap S T s := hs.symm
  have hspow : s ^ Fintype.card C = s := by
    simpa [FiniteField.coe_frobeniusAlgEquivOfAlgebraic] using hsFix
  let p : C[X] := Polynomial.X ^ Fintype.card C - Polynomial.X
  have hpSplit : p.Splits := by
    dsimp [p]
    simpa [Nat.card_eq_fintype_card] using
      (Polynomial.splits_X_pow_nat_card_sub_X (K := C))
  have hp0 : p ≠ 0 := by
    dsimp [p]
    exact FiniteField.X_pow_card_sub_X_ne_zero C Fintype.one_lt_card
  have hroot : (p.map (algebraMap C S)).IsRoot s := by
    simp [p, hspow]
  obtain ⟨c, hc⟩ := hpSplit.mem_range_of_isRoot hp0 hroot
  apply IntermediateField.mem_bot.mpr
  refine ⟨c, ?_⟩
  apply Subtype.ext
  change algebraMap C T c = (z : T)
  rw [hCS]
  change algebraMap S T (algebraMap C S c) = (z : T)
  rw [hc, hs]

end

end BGS.HasseWeil
