import BGS.HasseWeil.ExactConstantExtensionQuotient
import BGS.HasseWeil.FrobeniusTwistGroup

/-!
# Fixed fields of Frobenius twists

Let `C ⊆ L ⊆ N`, let `C` be algebraically closed in `N`, and let
`S / C` be a finite Galois extension of finite fields.  The exact constant
extension `T = S ⊗[C] N` has Galois group

`Gal(T/L) ≃ Gal(S/C) × Gal(N/L)`.

For `g ∈ Gal(N/L)`, this file constructs the automorphism of `T` represented
by `(Frob, g)`, its cyclic subgroup, and its fixed field.  If
`|Gal(N/L)|` divides `[S : C]`, the cyclic subgroup has order `[S : C]`
and meets the original function-field factor trivially.  Consequently `T`
is a finite Galois extension of the twist field of degree `[S : C]`, while
the twist field has degree `[N : L]` over `L`.

These are the structural assertions in the setup of Stichtenoth,
Proposition 5.2.8.  Exactness of the constant field of the twist requires,
in addition, stability of relative algebraic closedness under finite
separable base change; that separate regular-base-change lemma is not
assumed here.
-/

open scoped TensorProduct

namespace BGS.HasseWeil

noncomputable section

variable (C L N S : Type*) [Field C] [Field L] [Field N] [Field S]
  [Algebra C L] [Algebra L N] [Algebra C N] [IsScalarTower C L N]
  [Algebra C S] [FiniteDimensional C S] [IsGalois C S]
  [FiniteDimensional L N] [IsGalois L N]

section FiniteConstants

variable [Fintype C] [Finite S]

/-- The automorphism of the exact constant extension represented by
`(Frob, g)` under the direct-product description of its Galois group. -/
noncomputable def exactConstantExtensionFrobeniusTwist
    (hExact : algebraicClosure C N = (⊥ : IntermediateField C N))
    (g : N ≃ₐ[L] N) :
    letI := exactConstantExtensionField C N S hExact
    letI := exactConstantExtensionBaseAlgebra C L N S
    ExactConstantExtension C N S ≃ₐ[L]
      ExactConstantExtension C N S := by
  letI := exactConstantExtensionField C N S hExact
  letI := exactConstantExtensionBaseAlgebra C L N S
  exact exactConstantExtensionCombinedAutHom C L N S
    (FiniteField.frobeniusAlgEquivOfAlgebraic C S, g)

/-- The cyclic subgroup generated by a Frobenius twist. -/
noncomputable def exactConstantExtensionFrobeniusTwistSubgroup
    (hExact : algebraicClosure C N = (⊥ : IntermediateField C N))
    (g : N ≃ₐ[L] N) :
    letI := exactConstantExtensionField C N S hExact
    letI := exactConstantExtensionBaseAlgebra C L N S
    Subgroup (ExactConstantExtension C N S ≃ₐ[L]
      ExactConstantExtension C N S) := by
  letI := exactConstantExtensionField C N S hExact
  letI := exactConstantExtensionBaseAlgebra C L N S
  exact Subgroup.zpowers
    (exactConstantExtensionFrobeniusTwist C L N S hExact g)

/-- The fixed field of the cyclic subgroup generated by a Frobenius twist. -/
noncomputable def exactConstantExtensionFrobeniusTwistField
    (hExact : algebraicClosure C N = (⊥ : IntermediateField C N))
    (g : N ≃ₐ[L] N) :
    letI := exactConstantExtensionField C N S hExact
    letI := exactConstantExtensionBaseAlgebra C L N S
    IntermediateField L (ExactConstantExtension C N S) := by
  letI := exactConstantExtensionField C N S hExact
  letI := exactConstantExtensionBaseAlgebra C L N S
  exact IntermediateField.fixedField
    (exactConstantExtensionFrobeniusTwistSubgroup C L N S hExact g)

/-- The extended base inside the exact constant extension, characterized as
the fixed field of the original function-field factor.  In the rational
function specialization this is the copy of `S(X)`. -/
noncomputable def exactConstantExtensionExtendedBaseField
    (hExact : algebraicClosure C N = (⊥ : IntermediateField C N)) :
    letI := exactConstantExtensionField C N S hExact
    letI := exactConstantExtensionBaseAlgebra C L N S
    IntermediateField L (ExactConstantExtension C N S) := by
  letI := exactConstantExtensionField C N S hExact
  letI := exactConstantExtensionBaseAlgebra C L N S
  exact IntermediateField.fixedField
    (exactConstantExtensionConstantQuotient C L N S hExact).ker

set_option linter.unusedSectionVars false in
omit [Algebra C L] [IsScalarTower C L N]
  [IsGalois L N] [Fintype C] [Finite S] in
/-- The exact constant extension is finite-dimensional over the original
base.  This local bridge makes the finite Galois correspondence available
for the twist fields. -/
private theorem finiteDimensional_exactConstantExtension_over_base
    (hExact : algebraicClosure C N = (⊥ : IntermediateField C N)) :
    letI := exactConstantExtensionField C N S hExact
    letI := exactConstantExtensionBaseAlgebra C L N S
    FiniteDimensional L (ExactConstantExtension C N S) := by
  letI := exactConstantExtensionField C N S hExact
  letI := exactConstantExtensionBaseAlgebra C L N S
  letI := exactConstantExtensionAlgebra C N S
  letI := exactConstantExtensionBaseTower C L N S
  let e := exactConstantExtensionLinearEquiv C N S
  letI : Module.Finite N (N ⊗[C] S) := Module.Finite.base_change C N S
  letI : Module.Finite N (ExactConstantExtension C N S) := Module.Finite.equiv e
  letI : Module.Finite L (ExactConstantExtension C N S) :=
    Module.Finite.trans N (ExactConstantExtension C N S)
  infer_instance

omit [FiniteDimensional C S] [FiniteDimensional L N] [IsGalois L N] in
/-- Every Frobenius twist has order `[S : C]` when the order of the original
function-field Galois group divides `[S : C]`. -/
theorem orderOf_exactConstantExtensionFrobeniusTwist
    (hExact : algebraicClosure C N = (⊥ : IntermediateField C N))
    (g : N ≃ₐ[L] N)
    (hdiv : Nat.card (N ≃ₐ[L] N) ∣ Module.finrank C S) :
    letI := exactConstantExtensionField C N S hExact
    letI := exactConstantExtensionBaseAlgebra C L N S
    orderOf (exactConstantExtensionFrobeniusTwist C L N S hExact g) =
      Module.finrank C S := by
  letI := exactConstantExtensionField C N S hExact
  letI := exactConstantExtensionBaseAlgebra C L N S
  change orderOf (exactConstantExtensionCombinedAutHom C L N S
    (FiniteField.frobeniusAlgEquivOfAlgebraic C S, g)) = _
  rw [orderOf_injective (exactConstantExtensionCombinedAutHom C L N S)
    (exactConstantExtensionCombinedAutHom_injective C L N S)]
  rw [orderOf_prod_eq_left_of_natCard_dvd]
  · exact FiniteField.orderOf_frobeniusAlgEquivOfAlgebraic C S
  · rwa [FiniteField.orderOf_frobeniusAlgEquivOfAlgebraic C S]

omit [FiniteDimensional C S] [FiniteDimensional L N] [IsGalois L N] in
/-- The cyclic subgroup generated by a Frobenius twist has cardinality
`[S : C]`. -/
theorem natCard_exactConstantExtensionFrobeniusTwistSubgroup
    (hExact : algebraicClosure C N = (⊥ : IntermediateField C N))
    (g : N ≃ₐ[L] N)
    (hdiv : Nat.card (N ≃ₐ[L] N) ∣ Module.finrank C S) :
    letI := exactConstantExtensionField C N S hExact
    letI := exactConstantExtensionBaseAlgebra C L N S
    Nat.card
        (exactConstantExtensionFrobeniusTwistSubgroup C L N S hExact g) =
      Module.finrank C S := by
  letI := exactConstantExtensionField C N S hExact
  letI := exactConstantExtensionBaseAlgebra C L N S
  rw [show exactConstantExtensionFrobeniusTwistSubgroup C L N S hExact g =
      Subgroup.zpowers
        (exactConstantExtensionFrobeniusTwist C L N S hExact g) by rfl,
    Nat.card_zpowers,
    orderOf_exactConstantExtensionFrobeniusTwist C L N S hExact g hdiv]

/-- The twist subgroup meets the kernel of restriction to the enlarged
constants trivially. -/
theorem exactConstantExtensionFrobeniusTwistSubgroup_inf_quotientKer
    (hExact : algebraicClosure C N = (⊥ : IntermediateField C N))
    (g : N ≃ₐ[L] N)
    (hdiv : Nat.card (N ≃ₐ[L] N) ∣ Module.finrank C S) :
    letI := exactConstantExtensionField C N S hExact
    letI := exactConstantExtensionBaseAlgebra C L N S
    exactConstantExtensionFrobeniusTwistSubgroup C L N S hExact g ⊓
        (exactConstantExtensionConstantQuotient C L N S hExact).ker = ⊥ := by
  letI := exactConstantExtensionField C N S hExact
  letI := exactConstantExtensionBaseAlgebra C L N S
  apply le_antisymm
  · intro x hx
    rw [Subgroup.mem_bot]
    obtain ⟨k, hk⟩ := Subgroup.mem_zpowers_iff.mp hx.1
    rw [show exactConstantExtensionFrobeniusTwistSubgroup C L N S hExact g =
      Subgroup.zpowers
        (exactConstantExtensionFrobeniusTwist C L N S hExact g) by rfl] at hx
    rw [← hk]
    have hFrob :
        (FiniteField.frobeniusAlgEquivOfAlgebraic C S) ^ k = 1 := by
      have hker := MonoidHom.mem_ker.mp hx.2
      rw [← hk, map_zpow] at hker
      simpa [exactConstantExtensionFrobeniusTwist,
        exactConstantExtensionConstantQuotient_combined] using hker
    have hkdiv : (Module.finrank C S : ℤ) ∣ k := by
      rw [← FiniteField.orderOf_frobeniusAlgEquivOfAlgebraic C S]
      exact orderOf_dvd_iff_zpow_eq_one.mpr hFrob
    rw [← orderOf_dvd_iff_zpow_eq_one,
      orderOf_exactConstantExtensionFrobeniusTwist C L N S hExact g hdiv]
    exact hkdiv
  · exact bot_le

/-- Equivalently, the twist subgroup meets the embedded original
function-field Galois group trivially. -/
theorem exactConstantExtensionFrobeniusTwistSubgroup_inf_functionRange
    (hExact : algebraicClosure C N = (⊥ : IntermediateField C N))
    (g : N ≃ₐ[L] N)
    (hdiv : Nat.card (N ≃ₐ[L] N) ∣ Module.finrank C S) :
    letI := exactConstantExtensionField C N S hExact
    letI := exactConstantExtensionBaseAlgebra C L N S
    exactConstantExtensionFrobeniusTwistSubgroup C L N S hExact g ⊓
        (exactConstantExtensionFunctionAutHom C L N S).range = ⊥ := by
  letI := exactConstantExtensionField C N S hExact
  letI := exactConstantExtensionBaseAlgebra C L N S
  rw [← exactConstantExtensionConstantQuotient_ker C L N S hExact]
  exact exactConstantExtensionFrobeniusTwistSubgroup_inf_quotientKer
    C L N S hExact g hdiv

/-- A twist field and the extended base generate the entire exact constant
extension.  This is the fixed-field form of `T = T_g S` in Stichtenoth,
Proposition 5.2.8(b). -/
theorem frobeniusTwistField_sup_extendedBaseField_eq_top
    (hExact : algebraicClosure C N = (⊥ : IntermediateField C N))
    (g : N ≃ₐ[L] N)
    (hdiv : Nat.card (N ≃ₐ[L] N) ∣ Module.finrank C S) :
    letI := exactConstantExtensionField C N S hExact
    letI := exactConstantExtensionBaseAlgebra C L N S
    exactConstantExtensionFrobeniusTwistField C L N S hExact g ⊔
        exactConstantExtensionExtendedBaseField C L N S hExact = ⊤ := by
  letI := exactConstantExtensionField C N S hExact
  letI := exactConstantExtensionBaseAlgebra C L N S
  letI : FiniteDimensional L (ExactConstantExtension C N S) :=
    finiteDimensional_exactConstantExtension_over_base C L N S hExact
  letI : IsGalois L (ExactConstantExtension C N S) :=
    exactConstantExtension_isGalois C L N S hExact
  let F := exactConstantExtensionFrobeniusTwistField C L N S hExact g
  let B := exactConstantExtensionExtendedBaseField C L N S hExact
  have hfix : (F ⊔ B).fixingSubgroup = ⊥ := by
    rw [IntermediateField.fixingSubgroup_sup]
    change
      (IntermediateField.fixedField
          (exactConstantExtensionFrobeniusTwistSubgroup
            C L N S hExact g)).fixingSubgroup ⊓
        (IntermediateField.fixedField
          (exactConstantExtensionConstantQuotient
            C L N S hExact).ker).fixingSubgroup = ⊥
    rw [IntermediateField.fixingSubgroup_fixedField,
      IntermediateField.fixingSubgroup_fixedField]
    exact exactConstantExtensionFrobeniusTwistSubgroup_inf_quotientKer
      C L N S hExact g hdiv
  calc
    F ⊔ B = IntermediateField.fixedField (F ⊔ B).fixingSubgroup :=
      (IsGalois.fixedField_fixingSubgroup (F ⊔ B)).symm
    _ = IntermediateField.fixedField (⊥ : Subgroup
        (ExactConstantExtension C N S ≃ₐ[L]
          ExactConstantExtension C N S)) := by rw [hfix]
    _ = ⊤ := IntermediateField.fixedField_bot

omit [IsGalois L N] in
/-- The exact constant extension has degree `[S : C]` over the Frobenius
twist field. -/
theorem finrank_exactConstantExtension_over_frobeniusTwistField
    (hExact : algebraicClosure C N = (⊥ : IntermediateField C N))
    (g : N ≃ₐ[L] N)
    (hdiv : Nat.card (N ≃ₐ[L] N) ∣ Module.finrank C S) :
    letI := exactConstantExtensionField C N S hExact
    letI := exactConstantExtensionBaseAlgebra C L N S
    Module.finrank
        (exactConstantExtensionFrobeniusTwistField C L N S hExact g)
        (ExactConstantExtension C N S) = Module.finrank C S := by
  letI := exactConstantExtensionField C N S hExact
  letI := exactConstantExtensionBaseAlgebra C L N S
  letI : FiniteDimensional L (ExactConstantExtension C N S) :=
    finiteDimensional_exactConstantExtension_over_base C L N S hExact
  rw [show exactConstantExtensionFrobeniusTwistField C L N S hExact g =
      IntermediateField.fixedField
        (exactConstantExtensionFrobeniusTwistSubgroup C L N S hExact g) by
      rfl,
    IntermediateField.finrank_fixedField_eq_card,
    natCard_exactConstantExtensionFrobeniusTwistSubgroup
      C L N S hExact g hdiv]

omit [IsGalois L N] [Finite S] in
/-- The exact constant extension is finite-dimensional over every Frobenius
twist field. -/
theorem finiteDimensional_exactConstantExtension_over_frobeniusTwistField
    (hExact : algebraicClosure C N = (⊥ : IntermediateField C N))
    (g : N ≃ₐ[L] N) :
    letI := exactConstantExtensionField C N S hExact
    letI := exactConstantExtensionBaseAlgebra C L N S
    FiniteDimensional
      (exactConstantExtensionFrobeniusTwistField C L N S hExact g)
      (ExactConstantExtension C N S) := by
  letI := exactConstantExtensionField C N S hExact
  letI := exactConstantExtensionBaseAlgebra C L N S
  letI : FiniteDimensional L (ExactConstantExtension C N S) :=
    finiteDimensional_exactConstantExtension_over_base C L N S hExact
  infer_instance

omit [IsGalois L N] [Finite S] in
/-- The exact constant extension is Galois over every Frobenius twist field.
This only uses the general theorem that a field is Galois over the fixed
field of a finite group action. -/
theorem isGalois_exactConstantExtension_over_frobeniusTwistField
    (hExact : algebraicClosure C N = (⊥ : IntermediateField C N))
    (g : N ≃ₐ[L] N) :
    letI := exactConstantExtensionField C N S hExact
    letI := exactConstantExtensionBaseAlgebra C L N S
    IsGalois
      (exactConstantExtensionFrobeniusTwistField C L N S hExact g)
      (ExactConstantExtension C N S) := by
  letI := exactConstantExtensionField C N S hExact
  letI := exactConstantExtensionBaseAlgebra C L N S
  letI : FiniteDimensional L (ExactConstantExtension C N S) :=
    finiteDimensional_exactConstantExtension_over_base C L N S hExact
  let H := exactConstantExtensionFrobeniusTwistSubgroup C L N S hExact g
  change IsGalois (IntermediateField.fixedField H)
    (ExactConstantExtension C N S)
  exact IsGalois.of_fixed_field (ExactConstantExtension C N S) H

omit [IsGalois L N] in
/-- Every Frobenius twist field has the same degree over `L` as the original
function field `N`. -/
theorem finrank_frobeniusTwistField_over_base
    (hExact : algebraicClosure C N = (⊥ : IntermediateField C N))
    (g : N ≃ₐ[L] N)
    (hdiv : Nat.card (N ≃ₐ[L] N) ∣ Module.finrank C S) :
    letI := exactConstantExtensionField C N S hExact
    letI := exactConstantExtensionBaseAlgebra C L N S
    Module.finrank L
        (exactConstantExtensionFrobeniusTwistField C L N S hExact g) =
      Module.finrank L N := by
  letI := exactConstantExtensionField C N S hExact
  letI := exactConstantExtensionBaseAlgebra C L N S
  letI : FiniteDimensional L (ExactConstantExtension C N S) :=
    finiteDimensional_exactConstantExtension_over_base C L N S hExact
  let F := exactConstantExtensionFrobeniusTwistField C L N S hExact g
  have hmul := Module.finrank_mul_finrank L F
    (ExactConstantExtension C N S)
  rw [finrank_exactConstantExtension_over_frobeniusTwistField
      C L N S hExact g hdiv,
    exactConstantExtension_finrank_over_base C L N S] at hmul
  exact Nat.mul_right_cancel (Module.finrank_pos (R := C) (M := S)) hmul

omit [IsGalois L N] in
/-- The Galois group over a Frobenius twist field has cardinality `[S : C]`. -/
theorem natCard_aut_exactConstantExtension_over_frobeniusTwistField
    (hExact : algebraicClosure C N = (⊥ : IntermediateField C N))
    (g : N ≃ₐ[L] N)
    (hdiv : Nat.card (N ≃ₐ[L] N) ∣ Module.finrank C S) :
    letI := exactConstantExtensionField C N S hExact
    letI := exactConstantExtensionBaseAlgebra C L N S
    Nat.card
        (ExactConstantExtension C N S ≃ₐ[
          exactConstantExtensionFrobeniusTwistField C L N S hExact g]
          ExactConstantExtension C N S) = Module.finrank C S := by
  letI := exactConstantExtensionField C N S hExact
  letI := exactConstantExtensionBaseAlgebra C L N S
  letI : FiniteDimensional L (ExactConstantExtension C N S) :=
    finiteDimensional_exactConstantExtension_over_base C L N S hExact
  letI : IsGalois
      (exactConstantExtensionFrobeniusTwistField C L N S hExact g)
      (ExactConstantExtension C N S) :=
    isGalois_exactConstantExtension_over_frobeniusTwistField
      C L N S hExact g
  rw [IsGalois.card_aut_eq_finrank,
    finrank_exactConstantExtension_over_frobeniusTwistField
      C L N S hExact g hdiv]

end FiniteConstants

end


end BGS.HasseWeil
