import BGS.HasseWeil.ExactConstantExtensionFrobeniusTwistFinitePlaceBridge

/-!
# Unramified finite places over Frobenius-twist fields

The Galois group of the exact constant extension over a Frobenius-twist
field is the cyclic subgroup generated by the twist.  Restriction to the
enlarged constants is injective on this subgroup.  An inertia automorphism
acts trivially on every residue class, hence in particular on the embedded
constant field.  It therefore lies in the kernel of constant restriction and
must be the identity.  Thus every finite place is unramified in the exact
constant extension over a twist field.
-/

open scoped Pointwise Polynomial TensorProduct

namespace BGS.HasseWeil

noncomputable section

open BGS.CorvajaZannier
open IsDedekindDomain

set_option synthInstance.maxHeartbeats 500000
set_option maxHeartbeats 1000000

variable (C N S : Type*) [Field C] [Fintype C]
  [DecidableEq C] [DecidableEq (RatFunc C)]
  [Field N] [Algebra (RatFunc C) N]
  [FiniteDimensional (RatFunc C) N]
  [Algebra.IsSeparable (RatFunc C) N]
  [Field S] [Algebra C S] [FiniteDimensional C S] [IsGalois C S]
  [Finite S] [DecidableEq S] [DecidableEq (RatFunc S)]

local instance unramifiedConstantAlgebra : Algebra C N :=
  bridgeBaseConstantAlgebra C N

local instance unramifiedConstantTower :
    IsScalarTower C (RatFunc C) N :=
  IsScalarTower.of_algebraMap_eq' rfl

omit [DecidableEq C] [DecidableEq (RatFunc C)]
  [FiniteDimensional (RatFunc C) N]
  [Algebra.IsSeparable (RatFunc C) N]
  [Finite S]
  [DecidableEq S] [DecidableEq (RatFunc S)] in
/-- A power of the canonical twist acts on the enlarged constants by the
same power of finite-field Frobenius.  This is the constant-factor part of
the tensor-product action and does not require `N / C(X)` to be normal. -/
private theorem exactConstantExtensionFrobeniusTwist_zpow_includeLeft
    (hExact : algebraicClosure C N =
      (⊥ : IntermediateField C N))
    (g : N ≃ₐ[RatFunc C] N) (k : ℤ) (s : S) :
    letI : Field (ExactConstantExtension C N S) :=
      exactConstantExtensionField C N S hExact
    letI : Algebra (RatFunc C) (ExactConstantExtension C N S) :=
      exactConstantExtensionBaseAlgebra C (RatFunc C) N S
    ((exactConstantExtensionFrobeniusTwist
        C (RatFunc C) N S hExact g) ^ k)
        (Algebra.TensorProduct.includeLeft
          (R := C) (S := C) (A := S) (B := N) s) =
      Algebra.TensorProduct.includeLeft
        (R := C) (S := C) (A := S) (B := N)
        (((FiniteField.frobeniusAlgEquivOfAlgebraic C S) ^ k) s) := by
  letI : Field (ExactConstantExtension C N S) :=
    exactConstantExtensionField C N S hExact
  letI : Algebra (RatFunc C) (ExactConstantExtension C N S) :=
    exactConstantExtensionBaseAlgebra C (RatFunc C) N S
  change
    ((exactConstantExtensionCombinedAutHom C (RatFunc C) N S
        (FiniteField.frobeniusAlgEquivOfAlgebraic C S, g)) ^ k)
        (Algebra.TensorProduct.includeLeft
          (R := C) (S := C) (A := S) (B := N) s) = _
  rw [← map_zpow]
  simp [Algebra.TensorProduct.includeLeft_apply,
    exactConstantExtensionCombinedAutHom,
    exactConstantExtensionConstantAutHom,
    exactConstantExtensionFunctionAutHom,
    exactConstantExtensionConstantAlgEquivOverBase,
    exactConstantExtensionFunctionAlgEquivOverBase]

/-- The canonical twist generates the full Galois group over its fixed
field.  This is a direct consequence of defining that fixed field from the
cyclic subgroup generated by the ambient twist. -/
theorem exactConstantExtensionFrobeniusTwistOverFixedField_zpowers_eq_top
    (hExact : algebraicClosure C N =
      (⊥ : IntermediateField C N))
    (g : N ≃ₐ[RatFunc C] N) :
    letI : Field (ExactConstantExtension C N S) :=
      exactConstantExtensionField C N S hExact
    letI : Algebra (RatFunc C) (ExactConstantExtension C N S) :=
      exactConstantExtensionBaseAlgebra C (RatFunc C) N S
    Subgroup.zpowers
        (exactConstantExtensionFrobeniusTwistOverFixedField
          C N S hExact g) = ⊤ := by
  let T := ExactConstantExtension C N S
  letI : Field T := exactConstantExtensionField C N S hExact
  letI : Algebra (RatFunc C) T :=
    exactConstantExtensionBaseAlgebra C (RatFunc C) N S
  letI : SMul (RatFunc C) T := Algebra.toSMul
  letI : Module (RatFunc C) T := Algebra.toModule
  letI : FiniteDimensional (RatFunc C) T :=
    finiteDimensional_exactConstantExtension_over_baseRatFunc C S N hExact
  let sigma := exactConstantExtensionFrobeniusTwist
    C (RatFunc C) N S hExact g
  let H := exactConstantExtensionFrobeniusTwistSubgroup
    C (RatFunc C) N S hExact g
  let e := IntermediateField.subgroupEquivAlgEquiv H
  let u : H := ⟨sigma, Subgroup.mem_zpowers sigma⟩
  change Subgroup.zpowers (e u) = ⊤
  apply (Subgroup.eq_top_iff' _).mpr
  intro tau
  let h : H := e.symm tau
  obtain ⟨k, hk⟩ := Subgroup.mem_zpowers_iff.mp h.2
  apply Subgroup.mem_zpowers_iff.mpr
  refine ⟨k, ?_⟩
  calc
    (e u) ^ k = e (u ^ k) := (map_zpow e u k).symm
    _ = e h := congrArg e (Subtype.ext hk)
    _ = tau := e.apply_symm_apply tau

/-- If one generator of a relative Galois group fixes a top finite place,
then generation, unramifiedness, and maximal possible top degree force the
restricted finite place to have degree one. -/
theorem finitePlaceUnder_degree_eq_one_of_generator_fixed
    (K M T : Type*) [Field K] [DecidableEq K]
    [DecidableEq (RatFunc K)]
    [Field M] [Algebra (RatFunc K) M]
    [FiniteDimensional (RatFunc K) M]
    [Algebra.IsSeparable (RatFunc K) M]
    [Field T] [Algebra (RatFunc K) T]
    [FiniteDimensional (RatFunc K) T]
    [Algebra.IsSeparable (RatFunc K) T]
    [Algebra M T] [IsScalarTower (RatFunc K) M T]
    [FiniteDimensional M T] [IsGalois M T]
    (sigma : T ≃ₐ[M] T)
    (hgen : Subgroup.zpowers sigma = ⊤)
    (Q : FiniteExtensionFinitePlace K T)
    (hfixed : finitePlaceGalSmul K M T sigma Q = Q)
    (hunramified : finitePlaceRelativeRamificationIdx K M T Q = 1)
    (htopDegree : finiteExtensionPlaceDegree K T (.inl Q) =
      Module.finrank M T) :
    finiteExtensionPlaceDegree K M
      (.inl (finitePlaceUnder K M T Q)) = 1 := by
  let P := finitePlaceUnder K M T Q
  let Q₀ : FinitePlaceUnderFiber K M T P := ⟨Q, rfl⟩
  letI := finitePlaceGalAction K M T
  have hsigma : sigma ∈
      MulAction.stabilizer (T ≃ₐ[M] T) Q := by
    rw [MulAction.mem_stabilizer_iff]
    exact hfixed
  have hall (tau : T ≃ₐ[M] T) :
      finitePlaceGalSmul K M T tau Q = Q := by
    have hle : Subgroup.zpowers sigma ≤
        MulAction.stabilizer (T ≃ₐ[M] T) Q :=
      Subgroup.zpowers_le.mpr hsigma
    have htau : tau ∈ MulAction.stabilizer (T ≃ₐ[M] T) Q := by
      apply hle
      rw [hgen]
      exact Subgroup.mem_top tau
    have hfix := MulAction.mem_stabilizer_iff.mp htau
    change finitePlaceGalSmul K M T tau Q = Q at hfix
    exact hfix
  letI := finitePlaceUnderFiberGalAction K M T P
  letI : MulAction.IsPretransitive (T ≃ₐ[M] T)
      (FinitePlaceUnderFiber K M T P) :=
    finitePlaceUnderFiberGalAction_isPretransitive K M T P
  have hcard : Fintype.card (FinitePlaceUnderFiber K M T P) = 1 := by
    apply Fintype.card_eq_one_iff.mpr
    refine ⟨Q₀, ?_⟩
    intro R
    obtain ⟨tau, htau⟩ :=
      MulAction.exists_smul_eq (T ≃ₐ[M] T) Q₀ R
    calc
      R = tau • Q₀ := htau.symm
      _ = Q₀ := by
        apply Subtype.ext
        exact hall tau
  have hfundamental :=
    finitePlaceUnderFiber_card_mul_ramificationIdx_mul_inertiaDeg_eq_field_finrank
      K M T P Q₀
  dsimp [Q₀] at hfundamental
  have hinertia : finitePlaceRelativeInertiaDeg K M T Q =
      Module.finrank M T := by
    simpa only [hcard, hunramified, one_mul] using hfundamental
  have htower :=
    finiteExtensionPlaceDegree_inl_eq_mul_relativeInertiaDeg K M T Q
  rw [htopDegree, hinertia] at htower
  apply Nat.eq_of_mul_eq_mul_right (Module.finrank_pos (R := M) (M := T))
  simpa only [one_mul] using htower.symm

/-- Conversely, under the same degree-divisibility hypothesis used for the
unique-lift theorem, every lift of a rational finite place has top degree
equal to the relative field degree. -/
theorem rationalFinitePlace_lift_degree_eq_finrank_of_finrank_dvd_degree
    (K M T : Type*) [Field K] [DecidableEq K]
    [DecidableEq (RatFunc K)]
    [Field M] [Algebra (RatFunc K) M]
    [FiniteDimensional (RatFunc K) M]
    [Algebra.IsSeparable (RatFunc K) M]
    [Field T] [Algebra (RatFunc K) T]
    [FiniteDimensional (RatFunc K) T]
    [Algebra.IsSeparable (RatFunc K) T]
    [Algebra M T] [IsScalarTower (RatFunc K) M T]
    [FiniteDimensional M T] [IsGalois M T]
    (hdegree : ∀ Q : FiniteExtensionFinitePlace K T,
      Module.finrank M T ∣ finiteExtensionPlaceDegree K T (.inl Q))
    (P : FiniteExtensionRationalFinitePlace K M)
    (Q : FiniteExtensionFinitePlace K T)
    (hQ : finitePlaceUnder K M T Q = P.1) :
    finiteExtensionPlaceDegree K T (.inl Q) = Module.finrank M T := by
  let Q₀ : FinitePlaceUnderFiber K M T P.1 := ⟨Q, hQ⟩
  have htower :=
    finiteExtensionPlaceDegree_inl_eq_mul_relativeInertiaDeg K M T Q
  have hrelative : finitePlaceRelativeInertiaDeg K M T Q =
      finiteExtensionPlaceDegree K T (.inl Q) := by
    rw [hQ] at htower
    simpa only [P.2, one_mul] using htower.symm
  have hm_dvd_f : Module.finrank M T ∣
      finitePlaceRelativeInertiaDeg K M T Q := by
    rw [hrelative]
    exact hdegree Q
  have hfundamental :=
    finitePlaceUnderFiber_card_mul_ramificationIdx_mul_inertiaDeg_eq_field_finrank
      K M T P.1 Q₀
  dsimp [Q₀] at hfundamental
  have hf_dvd_m : finitePlaceRelativeInertiaDeg K M T Q ∣
      Module.finrank M T := by
    rw [← hfundamental]
    exact dvd_mul_left _ _
  exact hrelative.symm.trans (Nat.dvd_antisymm hf_dvd_m hm_dvd_f)

/-- Rational finite places are equivalent to generator-fixed top finite
places of relative-degree-sized absolute degree, once the relative extension
is unramified and every top degree is divisible by the relative degree. -/
noncomputable def rationalFinitePlaceEquivGeneratorFixedPlace
    (K M T : Type*) [Field K] [DecidableEq K]
    [DecidableEq (RatFunc K)]
    [Field M] [Algebra (RatFunc K) M]
    [FiniteDimensional (RatFunc K) M]
    [Algebra.IsSeparable (RatFunc K) M]
    [Field T] [Algebra (RatFunc K) T]
    [FiniteDimensional (RatFunc K) T]
    [Algebra.IsSeparable (RatFunc K) T]
    [Algebra M T] [IsScalarTower (RatFunc K) M T]
    [FiniteDimensional M T] [IsGalois M T]
    (hdegree : ∀ Q : FiniteExtensionFinitePlace K T,
      Module.finrank M T ∣ finiteExtensionPlaceDegree K T (.inl Q))
    (sigma : T ≃ₐ[M] T)
    (hgen : Subgroup.zpowers sigma = ⊤)
    (hunramified : ∀ Q : FiniteExtensionFinitePlace K T,
      finitePlaceRelativeRamificationIdx K M T Q = 1) :
    FiniteExtensionRationalFinitePlace K M ≃
      {Q : FiniteExtensionFinitePlace K T //
        finiteExtensionPlaceDegree K T (.inl Q) = Module.finrank M T ∧
          finitePlaceGalSmul K M T sigma Q = Q} := by
  let e := rationalFinitePlaceEquivLift K M T hdegree
  refine
    { toFun := fun P => by
        let x := e P
        exact ⟨x.2.1,
          rationalFinitePlace_lift_degree_eq_finrank_of_finrank_dvd_degree
            K M T hdegree x.1 x.2.1 x.2.2,
          rationalFinitePlaceLift_fixed K M T hdegree sigma x⟩
      invFun := fun Q =>
        ⟨finitePlaceUnder K M T Q.1,
          finitePlaceUnder_degree_eq_one_of_generator_fixed K M T sigma
            hgen Q.1 Q.2.2 (hunramified Q.1) Q.2.1⟩
      left_inv := ?_
      right_inv := ?_ }
  · intro P
    apply Subtype.ext
    let x := e P
    have hx1 : x.1 = P := by
      change e.symm (e P) = P
      exact e.symm_apply_apply P
    exact x.2.2.trans (congrArg Subtype.val hx1)
  · intro Q
    apply Subtype.ext
    let P : FiniteExtensionRationalFinitePlace K M :=
      ⟨finitePlaceUnder K M T Q.1,
        finitePlaceUnder_degree_eq_one_of_generator_fixed K M T sigma
          hgen Q.1 Q.2.2 (hunramified Q.1) Q.2.1⟩
    let x := e P
    have hx1 : x.1 = P := by
      change e.symm (e P) = P
      exact e.symm_apply_apply P
    let xFiber : FinitePlaceUnderFiber K M T P.1 :=
      ⟨x.2.1, x.2.2.trans (congrArg Subtype.val hx1)⟩
    let qFiber : FinitePlaceUnderFiber K M T P.1 := ⟨Q.1, rfl⟩
    have hcard :=
      rationalFinitePlace_fiber_card_eq_one_of_finrank_dvd_degree
        K M T hdegree P
    obtain ⟨z, hz⟩ := Fintype.card_eq_one_iff.mp hcard
    have hxy : xFiber = qFiber := (hz xFiber).trans (hz qFiber).symm
    change x.2.1 = Q.1
    exact congrArg Subtype.val hxy

/-- Relative automorphisms over two intermediate fields induce the same
action on top finite places when their underlying top-field maps agree. -/
theorem finitePlaceGalSmul_eq_of_apply_eq
    (K M₁ M₂ T : Type*) [Field K] [DecidableEq K]
    [DecidableEq (RatFunc K)]
    [Field M₁] [Algebra (RatFunc K) M₁]
    [FiniteDimensional (RatFunc K) M₁]
    [Algebra.IsSeparable (RatFunc K) M₁]
    [Field M₂] [Algebra (RatFunc K) M₂]
    [FiniteDimensional (RatFunc K) M₂]
    [Algebra.IsSeparable (RatFunc K) M₂]
    [Field T] [Algebra (RatFunc K) T]
    [FiniteDimensional (RatFunc K) T]
    [Algebra.IsSeparable (RatFunc K) T]
    [Algebra M₁ T] [IsScalarTower (RatFunc K) M₁ T]
    [FiniteDimensional M₁ T] [IsGalois M₁ T]
    [Algebra M₂ T] [IsScalarTower (RatFunc K) M₂ T]
    [FiniteDimensional M₂ T] [IsGalois M₂ T]
    (g₁ : T ≃ₐ[M₁] T) (g₂ : T ≃ₐ[M₂] T)
    (happly : ∀ x : T, g₁ x = g₂ x)
    (Q : FiniteExtensionFinitePlace K T) :
    finitePlaceGalSmul K M₁ T g₁ Q =
      finitePlaceGalSmul K M₂ T g₂ Q := by
  let A := RatFuncFiniteIntegralClosure K T
  let A₁ := RatFuncFiniteIntegralClosure K M₁
  let A₂ := RatFuncFiniteIntegralClosure K M₂
  letI : Algebra K[X] M₁ :=
    RingHom.toAlgebra
      ((algebraMap (RatFunc K) M₁).comp (algebraMap K[X] (RatFunc K)))
  letI : IsScalarTower K[X] (RatFunc K) M₁ :=
    IsScalarTower.of_algebraMap_eq' rfl
  letI : Algebra K[X] M₂ :=
    RingHom.toAlgebra
      ((algebraMap (RatFunc K) M₂).comp (algebraMap K[X] (RatFunc K)))
  letI : IsScalarTower K[X] (RatFunc K) M₂ :=
    IsScalarTower.of_algebraMap_eq' rfl
  letI : Algebra K[X] T :=
    RingHom.toAlgebra
      ((algebraMap (RatFunc K) T).comp (algebraMap K[X] (RatFunc K)))
  letI : IsScalarTower K[X] (RatFunc K) T :=
    IsScalarTower.of_algebraMap_eq' rfl
  letI : Algebra A₁ A := (finiteIntegralClosureMap K M₁ T).toAlgebra
  letI : SMul A₁ A := Algebra.toSMul
  letI : Module A₁ A := Algebra.toModule
  letI : IsScalarTower A₁ M₁ T := inferInstance
  letI : Algebra.IsIntegral K[X] A₁ :=
    IsIntegralClosure.isIntegral_algebra K[X] M₁
  letI : IsScalarTower K[X] A₁ T := by
    apply IsScalarTower.of_algebraMap_eq
    intro x
    change algebraMap (RatFunc K) T
          (algebraMap K[X] (RatFunc K) x) =
        algebraMap M₁ T
          (algebraMap (RatFunc K) M₁
            (algebraMap K[X] (RatFunc K) x))
    exact IsScalarTower.algebraMap_apply (RatFunc K) M₁ T _
  letI : IsScalarTower A₁ A T :=
    ⟨fun r t x => by
      simp only [Algebra.smul_def, map_mul]
      rw [show algebraMap A T (algebraMap A₁ A r) =
          algebraMap A₁ T r by rfl]
      ring⟩
  letI : IsIntegralClosure A A₁ T :=
    IsIntegralClosure.tower_top (R := K[X])
  letI : Algebra A₂ A := (finiteIntegralClosureMap K M₂ T).toAlgebra
  letI : SMul A₂ A := Algebra.toSMul
  letI : Module A₂ A := Algebra.toModule
  letI : IsScalarTower A₂ M₂ T := inferInstance
  letI : Algebra.IsIntegral K[X] A₂ :=
    IsIntegralClosure.isIntegral_algebra K[X] M₂
  letI : IsScalarTower K[X] A₂ T := by
    apply IsScalarTower.of_algebraMap_eq
    intro x
    change algebraMap (RatFunc K) T
          (algebraMap K[X] (RatFunc K) x) =
        algebraMap M₂ T
          (algebraMap (RatFunc K) M₂
            (algebraMap K[X] (RatFunc K) x))
    exact IsScalarTower.algebraMap_apply (RatFunc K) M₂ T _
  letI : IsScalarTower A₂ A T :=
    ⟨fun r t x => by
      simp only [Algebra.smul_def, map_mul]
      rw [show algebraMap A T (algebraMap A₂ A r) =
          algebraMap A₂ T r by rfl]
      ring⟩
  letI : IsIntegralClosure A A₂ T :=
    IsIntegralClosure.tower_top (R := K[X])
  letI : MulSemiringAction (T ≃ₐ[M₁] T) A :=
    finiteIntegralClosureGalAction K M₁ T
  letI : MulSemiringAction (T ≃ₐ[M₂] T) A :=
    finiteIntegralClosureGalAction K M₂ T
  have hsmul (a₁ : T ≃ₐ[M₁] T) (a₂ : T ≃ₐ[M₂] T)
      (ha : ∀ x : T, a₁ x = a₂ x) (x : A) : a₁ • x = a₂ • x := by
    apply Subtype.ext
    calc
      ((a₁ • x : A) : T) = a₁ (x : T) := by
        change algebraMap A T ((galRestrict A₁ M₁ T A a₁) x) =
          a₁ (algebraMap A T x)
        exact algebraMap_galRestrict_apply A₁ a₁ x
      _ = a₂ (x : T) := ha _
      _ = ((a₂ • x : A) : T) := by
        change a₂ (algebraMap A T x) =
          algebraMap A T ((galRestrict A₂ M₂ T A a₂) x)
        exact (algebraMap_galRestrict_apply A₂ a₂ x).symm
  have happly_inv (x : T) : g₁⁻¹ x = g₂⁻¹ x := by
    apply g₂.injective
    calc
      g₂ (g₁⁻¹ x) = g₁ (g₁⁻¹ x) := (happly _).symm
      _ = x := g₁.apply_symm_apply x
      _ = g₂ (g₂⁻¹ x) := (g₂.apply_symm_apply x).symm
  apply HeightOneSpectrum.ext
  change g₁ • Q.asIdeal = g₂ • Q.asIdeal
  ext x
  rw [Ideal.mem_pointwise_smul_iff_inv_smul_mem,
    Ideal.mem_pointwise_smul_iff_inv_smul_mem,
    hsmul g₁⁻¹ g₂⁻¹ happly_inv x]

/-- Every finite place of the exact constant extension is unramified over a
Frobenius-twist fixed field, provided the twist has the full
constant-extension order. -/
theorem frobeniusTwistField_finitePlace_ramificationIdx_eq_one
    (hExact : algebraicClosure C N =
      (⊥ : IntermediateField C N))
    (g : N ≃ₐ[RatFunc C] N)
    (hdiv : Nat.card (N ≃ₐ[RatFunc C] N) ∣ Module.finrank C S) :
    letI : Field (ExactConstantExtension C N S) :=
      exactConstantExtensionField C N S hExact
    letI : Algebra (RatFunc C) (ExactConstantExtension C N S) :=
      exactConstantExtensionBaseAlgebra C (RatFunc C) N S
    letI : SMul (RatFunc C) (ExactConstantExtension C N S) :=
      Algebra.toSMul
    letI : Module (RatFunc C) (ExactConstantExtension C N S) :=
      Algebra.toModule
    letI : FiniteDimensional (RatFunc C)
        (ExactConstantExtension C N S) :=
      finiteDimensional_exactConstantExtension_over_baseRatFunc
        C S N hExact
    letI : Algebra.IsSeparable (RatFunc C)
        (ExactConstantExtension C N S) :=
      isSeparable_exactConstantExtension_over_baseRatFunc C S N hExact
    let F := exactConstantExtensionFrobeniusTwistField
      C (RatFunc C) N S hExact g
    letI : Algebra (RatFunc C) F :=
      SubalgebraClass.toAlgebra F.toSubalgebra
    letI : SMul (RatFunc C) F := Algebra.toSMul
    letI : Module (RatFunc C) F := Algebra.toModule
    letI : FiniteDimensional (RatFunc C) F :=
      finiteDimensional_frobeniusTwistField_over_ratFunc C N S hExact g
    letI : Algebra.IsSeparable (RatFunc C) F :=
      isSeparable_frobeniusTwistField_over_ratFunc C N S hExact g
    letI : Algebra F (ExactConstantExtension C N S) := F.toAlgebra
    letI : SMul F (ExactConstantExtension C N S) := Algebra.toSMul
    letI : Module F (ExactConstantExtension C N S) := Algebra.toModule
    letI : IsScalarTower (RatFunc C) F
        (ExactConstantExtension C N S) := inferInstance
    letI : FiniteDimensional F (ExactConstantExtension C N S) :=
      finiteDimensional_exactConstantExtension_over_frobeniusTwistField
        C (RatFunc C) N S hExact g
    letI : IsGalois F (ExactConstantExtension C N S) :=
      isGalois_exactConstantExtension_over_frobeniusTwistField
        C (RatFunc C) N S hExact g
    ∀ Q : FiniteExtensionFinitePlace C (ExactConstantExtension C N S),
      finitePlaceRelativeRamificationIdx C F
        (ExactConstantExtension C N S) Q = 1 := by
  let T := ExactConstantExtension C N S
  letI : Field T := exactConstantExtensionField C N S hExact
  letI : Algebra (RatFunc C) T :=
    exactConstantExtensionBaseAlgebra C (RatFunc C) N S
  letI : SMul (RatFunc C) T := Algebra.toSMul
  letI : Module (RatFunc C) T := Algebra.toModule
  letI : FiniteDimensional (RatFunc C) T :=
    finiteDimensional_exactConstantExtension_over_baseRatFunc C S N hExact
  letI : Algebra.IsSeparable (RatFunc C) T :=
    isSeparable_exactConstantExtension_over_baseRatFunc C S N hExact
  let F := exactConstantExtensionFrobeniusTwistField
    C (RatFunc C) N S hExact g
  letI : Algebra (RatFunc C) F :=
    SubalgebraClass.toAlgebra F.toSubalgebra
  letI : SMul (RatFunc C) F := Algebra.toSMul
  letI : Module (RatFunc C) F := Algebra.toModule
  letI : FiniteDimensional (RatFunc C) F :=
    finiteDimensional_frobeniusTwistField_over_ratFunc C N S hExact g
  letI : Algebra.IsSeparable (RatFunc C) F :=
    isSeparable_frobeniusTwistField_over_ratFunc C N S hExact g
  letI : Algebra F T := F.toAlgebra
  letI : SMul F T := Algebra.toSMul
  letI : Module F T := Algebra.toModule
  letI : IsScalarTower (RatFunc C) F T := inferInstance
  letI : FiniteDimensional F T :=
    finiteDimensional_exactConstantExtension_over_frobeniusTwistField
      C (RatFunc C) N S hExact g
  letI : IsGalois F T :=
    isGalois_exactConstantExtension_over_frobeniusTwistField
      C (RatFunc C) N S hExact g
  letI : Algebra C[X] T :=
    RingHom.toAlgebra
      ((algebraMap (RatFunc C) T).comp (algebraMap C[X] (RatFunc C)))
  letI : IsScalarTower C[X] (RatFunc C) T :=
    IsScalarTower.of_algebraMap_eq' rfl
  let A := RatFuncFiniteIntegralClosure C T
  let AF := RatFuncFiniteIntegralClosure C F
  letI : Algebra AF A := (finiteIntegralClosureMap C F T).toAlgebra
  letI : SMul AF A := Algebra.toSMul
  letI : Module AF A := Algebra.toModule
  letI : Algebra S A :=
    exactConstantExtensionFiniteIntegralClosureConstantAlgebra C N S hExact
  letI : IsScalarTower AF F T := inferInstance
  letI : Algebra.IsIntegral C[X] AF :=
    IsIntegralClosure.isIntegral_algebra C[X] F
  letI : IsScalarTower C[X] AF T := by
    apply IsScalarTower.of_algebraMap_eq
    intro x
    change algebraMap (RatFunc C) T
          (algebraMap C[X] (RatFunc C) x) =
        algebraMap F T
          (algebraMap (RatFunc C) F
            (algebraMap C[X] (RatFunc C) x))
    exact IsScalarTower.algebraMap_apply (RatFunc C) F T _
  letI : IsScalarTower AF A T :=
    ⟨fun r t x => by
      simp only [Algebra.smul_def, map_mul]
      rw [show algebraMap A T (algebraMap AF A r) =
          algebraMap AF T r by rfl]
      ring⟩
  letI : IsIntegralClosure A AF T :=
    IsIntegralClosure.tower_top (R := C[X])
  letI : IsDedekindDomain A := inferInstance
  letI : MulSemiringAction (T ≃ₐ[F] T) A :=
    finiteIntegralClosureGalAction C F T
  dsimp only
  intro Q
  letI : Q.asIdeal.IsMaximal := Q.isMaximal
  rw [← finitePlaceInertiaGroup_card_eq_ramificationIdx C F T Q]
  have hInertia : finitePlaceInertiaGroup C F T Q = ⊥ := by
    ext tau
    constructor
    · intro htau
      rw [Subgroup.mem_bot]
      let sigma := exactConstantExtensionFrobeniusTwist
        C (RatFunc C) N S hExact g
      let H := exactConstantExtensionFrobeniusTwistSubgroup
        C (RatFunc C) N S hExact g
      let e := IntermediateField.subgroupEquivAlgEquiv H
      let h : H := e.symm tau
      have he_apply (z : H) (x : T) : e z x = z.1 x := by
        change z.1.toEquiv x = z.1 x
        rfl
      have htau_apply (x : T) : tau x = h.1 x := by
        calc
          tau x = e h x := by
            exact congrArg (fun z : T ≃ₐ[F] T => z x)
              (e.apply_symm_apply tau).symm
          _ = h.1 x := he_apply h x
      obtain ⟨k, hk⟩ := Subgroup.mem_zpowers_iff.mp h.2
      let frob := FiniteField.frobeniusAlgEquivOfAlgebraic C S
      have hfrob_apply (s : S) : (frob ^ k) s = s := by
        let a : A := algebraMap S A s
        have haction : tau • a = algebraMap S A ((frob ^ k) s) := by
          apply Subtype.ext
          calc
            ((tau • a : A) : T) = tau (a : T) := by
              change algebraMap A T ((galRestrict AF F T A tau) a) =
                tau (algebraMap A T a)
              exact algebraMap_galRestrict_apply AF tau a
            _ = h.1 (a : T) := htau_apply (a : T)
            _ = h.1 (Algebra.TensorProduct.includeLeft
                (R := C) (S := C) (A := S) (B := N) s) := by
              exact congrArg h.1
                (exactConstantExtensionFiniteIntegralClosure_algebraMap_val
                  C N S hExact s)
            _ = (sigma ^ k) (Algebra.TensorProduct.includeLeft
                (R := C) (S := C) (A := S) (B := N) s) := by
              exact congrArg
                (fun z : T ≃ₐ[RatFunc C] T =>
                  z (Algebra.TensorProduct.includeLeft
                    (R := C) (S := C) (A := S) (B := N) s))
                hk |>.symm
            _ = Algebra.TensorProduct.includeLeft
                (R := C) (S := C) (A := S) (B := N)
                ((frob ^ k) s) := by
              exact exactConstantExtensionFrobeniusTwist_zpow_includeLeft
                C N S hExact g k s
            _ = ((algebraMap S A ((frob ^ k) s) : A) : T) := by
              exact
                (exactConstantExtensionFiniteIntegralClosure_algebraMap_val
                  C N S hExact ((frob ^ k) s)).symm
        have hmem : tau • a - a ∈ Q.asIdeal := htau a
        have hmem' : algebraMap S A ((frob ^ k) s - s) ∈ Q.asIdeal := by
          have heq : algebraMap S A ((frob ^ k) s - s) = tau • a - a := by
            calc
              algebraMap S A ((frob ^ k) s - s) =
                  algebraMap S A ((frob ^ k) s) - algebraMap S A s :=
                map_sub (algebraMap S A) _ _
              _ = algebraMap S A ((frob ^ k) s) - a := rfl
              _ = tau • a - a := congrArg (fun z : A => z - a) haction.symm
          exact heq.symm ▸ hmem
        let J : Ideal S := Q.asIdeal.comap (algebraMap S A)
        have hmemJ : (frob ^ k) s - s ∈ J := hmem'
        have hJne : J ≠ ⊤ := by
          exact Ideal.comap_ne_top (algebraMap S A) Q.isPrime.ne_top
        have hJ : J = ⊥ := (Ideal.eq_bot_or_top J).resolve_right hJne
        have hs : (frob ^ k) s - s = 0 := by
          rw [hJ] at hmemJ
          simpa only [Ideal.mem_bot] using hmemJ
        exact sub_eq_zero.mp hs
      have hFrob : frob ^ k = 1 := by
        ext s
        exact hfrob_apply s
      have hkdiv : (Module.finrank C S : ℤ) ∣ k := by
        rw [← FiniteField.orderOf_frobeniusAlgEquivOfAlgebraic C S]
        exact orderOf_dvd_iff_zpow_eq_one.mpr hFrob
      have hsigma : sigma ^ k = 1 := by
        rw [← orderOf_dvd_iff_zpow_eq_one,
          orderOf_exactConstantExtensionFrobeniusTwist
            C (RatFunc C) N S hExact g hdiv]
        exact hkdiv
      have hambient : (h.1 : T ≃ₐ[RatFunc C] T) = 1 := by
        calc
          (h.1 : T ≃ₐ[RatFunc C] T) = sigma ^ k := hk.symm
          _ = 1 := hsigma
      have hh : h = 1 := Subtype.ext hambient
      calc
        tau = e h := (e.apply_symm_apply tau).symm
        _ = e 1 := congrArg e hh
        _ = 1 := map_one e
    · intro htau
      rw [Subgroup.mem_bot] at htau
      simp [htau]
  rw [hInertia]
  exact Nat.card_unique

/-- A top finite place of degree `[S : C]` fixed by the canonical twist
descends to a rational finite place of the Frobenius-twist fixed field. -/
theorem frobeniusTwistField_fixed_finitePlace_under_degree_eq_one
    (hExact : algebraicClosure C N =
      (⊥ : IntermediateField C N))
    (g : N ≃ₐ[RatFunc C] N)
    (hdiv : Nat.card (N ≃ₐ[RatFunc C] N) ∣ Module.finrank C S) :
    letI : Field (ExactConstantExtension C N S) :=
      exactConstantExtensionField C N S hExact
    letI : Algebra (RatFunc C) (ExactConstantExtension C N S) :=
      exactConstantExtensionBaseAlgebra C (RatFunc C) N S
    letI : SMul (RatFunc C) (ExactConstantExtension C N S) :=
      Algebra.toSMul
    letI : Module (RatFunc C) (ExactConstantExtension C N S) :=
      Algebra.toModule
    letI : FiniteDimensional (RatFunc C)
        (ExactConstantExtension C N S) :=
      finiteDimensional_exactConstantExtension_over_baseRatFunc
        C S N hExact
    letI : Algebra.IsSeparable (RatFunc C)
        (ExactConstantExtension C N S) :=
      isSeparable_exactConstantExtension_over_baseRatFunc C S N hExact
    let F := exactConstantExtensionFrobeniusTwistField
      C (RatFunc C) N S hExact g
    letI : Algebra (RatFunc C) F :=
      SubalgebraClass.toAlgebra F.toSubalgebra
    letI : SMul (RatFunc C) F := Algebra.toSMul
    letI : Module (RatFunc C) F := Algebra.toModule
    letI : FiniteDimensional (RatFunc C) F :=
      finiteDimensional_frobeniusTwistField_over_ratFunc C N S hExact g
    letI : Algebra.IsSeparable (RatFunc C) F :=
      isSeparable_frobeniusTwistField_over_ratFunc C N S hExact g
    letI : Algebra F (ExactConstantExtension C N S) := F.toAlgebra
    letI : SMul F (ExactConstantExtension C N S) := Algebra.toSMul
    letI : Module F (ExactConstantExtension C N S) := Algebra.toModule
    letI : IsScalarTower (RatFunc C) F
        (ExactConstantExtension C N S) := inferInstance
    letI : FiniteDimensional F (ExactConstantExtension C N S) :=
      finiteDimensional_exactConstantExtension_over_frobeniusTwistField
        C (RatFunc C) N S hExact g
    letI : IsGalois F (ExactConstantExtension C N S) :=
      isGalois_exactConstantExtension_over_frobeniusTwistField
        C (RatFunc C) N S hExact g
    ∀ Q : FiniteExtensionFinitePlace C (ExactConstantExtension C N S),
      finiteExtensionPlaceDegree C (ExactConstantExtension C N S) (.inl Q) =
          Module.finrank C S →
        finitePlaceGalSmul C F (ExactConstantExtension C N S)
            (exactConstantExtensionFrobeniusTwistOverFixedField
              C N S hExact g) Q = Q →
          finiteExtensionPlaceDegree C F
            (.inl (finitePlaceUnder C F
              (ExactConstantExtension C N S) Q)) = 1 := by
  let T := ExactConstantExtension C N S
  letI : Field T := exactConstantExtensionField C N S hExact
  letI : Algebra (RatFunc C) T :=
    exactConstantExtensionBaseAlgebra C (RatFunc C) N S
  letI : SMul (RatFunc C) T := Algebra.toSMul
  letI : Module (RatFunc C) T := Algebra.toModule
  letI : FiniteDimensional (RatFunc C) T :=
    finiteDimensional_exactConstantExtension_over_baseRatFunc C S N hExact
  letI : Algebra.IsSeparable (RatFunc C) T :=
    isSeparable_exactConstantExtension_over_baseRatFunc C S N hExact
  let F := exactConstantExtensionFrobeniusTwistField
    C (RatFunc C) N S hExact g
  letI : Algebra (RatFunc C) F :=
    SubalgebraClass.toAlgebra F.toSubalgebra
  letI : SMul (RatFunc C) F := Algebra.toSMul
  letI : Module (RatFunc C) F := Algebra.toModule
  letI : FiniteDimensional (RatFunc C) F :=
    finiteDimensional_frobeniusTwistField_over_ratFunc C N S hExact g
  letI : Algebra.IsSeparable (RatFunc C) F :=
    isSeparable_frobeniusTwistField_over_ratFunc C N S hExact g
  letI : Algebra F T := F.toAlgebra
  letI : SMul F T := Algebra.toSMul
  letI : Module F T := Algebra.toModule
  letI : IsScalarTower (RatFunc C) F T := inferInstance
  letI : FiniteDimensional F T :=
    finiteDimensional_exactConstantExtension_over_frobeniusTwistField
      C (RatFunc C) N S hExact g
  letI : IsGalois F T :=
    isGalois_exactConstantExtension_over_frobeniusTwistField
      C (RatFunc C) N S hExact g
  dsimp only
  intro Q hdegree hfixed
  apply finitePlaceUnder_degree_eq_one_of_generator_fixed
    C F T
    (exactConstantExtensionFrobeniusTwistOverFixedField C N S hExact g)
    (exactConstantExtensionFrobeniusTwistOverFixedField_zpowers_eq_top
      C N S hExact g)
    Q hfixed
  · exact frobeniusTwistField_finitePlace_ramificationIdx_eq_one
      C N S hExact g hdiv Q
  · calc
      finiteExtensionPlaceDegree C T (.inl Q) = Module.finrank C S := hdegree
      _ = Module.finrank F T :=
        (finrank_exactConstantExtension_over_frobeniusTwistField
          C (RatFunc C) N S hExact g hdiv).symm

/-- The canonical twist over its fixed field and the ambient twist over
`C(X)` induce exactly the same action on finite places. -/
theorem exactConstantExtensionFrobeniusTwist_finitePlaceGalSmul_eq_overFixedField
    [IsGalois (RatFunc C) N]
    (hExact : algebraicClosure C N =
      (⊥ : IntermediateField C N))
    (g : N ≃ₐ[RatFunc C] N) :
    letI : Field (ExactConstantExtension C N S) :=
      exactConstantExtensionField C N S hExact
    letI : Algebra (RatFunc C) (ExactConstantExtension C N S) :=
      exactConstantExtensionBaseAlgebra C (RatFunc C) N S
    letI : SMul (RatFunc C) (ExactConstantExtension C N S) :=
      Algebra.toSMul
    letI : Module (RatFunc C) (ExactConstantExtension C N S) :=
      Algebra.toModule
    letI : DistribMulAction (RatFunc C)
        (ExactConstantExtension C N S) := Module.toDistribMulAction
    letI : MulAction (RatFunc C) (ExactConstantExtension C N S) :=
      DistribMulAction.toMulAction
    letI : FiniteDimensional (RatFunc C)
        (ExactConstantExtension C N S) :=
      finiteDimensional_exactConstantExtension_over_baseRatFunc
        C S N hExact
    letI : IsGalois (RatFunc C) (ExactConstantExtension C N S) :=
      exactConstantExtension_isGalois C (RatFunc C) N S hExact
    letI : Algebra.IsSeparable (RatFunc C)
        (ExactConstantExtension C N S) :=
      isSeparable_exactConstantExtension_over_baseRatFunc C S N hExact
    let F := exactConstantExtensionFrobeniusTwistField
      C (RatFunc C) N S hExact g
    letI : Algebra (RatFunc C) F :=
      SubalgebraClass.toAlgebra F.toSubalgebra
    letI : SMul (RatFunc C) F := Algebra.toSMul
    letI : Module (RatFunc C) F := Algebra.toModule
    letI : FiniteDimensional (RatFunc C) F :=
      finiteDimensional_frobeniusTwistField_over_ratFunc C N S hExact g
    letI : Algebra.IsSeparable (RatFunc C) F :=
      isSeparable_frobeniusTwistField_over_ratFunc C N S hExact g
    letI : Algebra F (ExactConstantExtension C N S) := F.toAlgebra
    letI : SMul F (ExactConstantExtension C N S) := Algebra.toSMul
    letI : Module F (ExactConstantExtension C N S) := Algebra.toModule
    letI : IsScalarTower (RatFunc C) F
        (ExactConstantExtension C N S) := inferInstance
    letI : FiniteDimensional F (ExactConstantExtension C N S) :=
      finiteDimensional_exactConstantExtension_over_frobeniusTwistField
        C (RatFunc C) N S hExact g
    letI : IsGalois F (ExactConstantExtension C N S) :=
      isGalois_exactConstantExtension_over_frobeniusTwistField
        C (RatFunc C) N S hExact g
    ∀ Q : FiniteExtensionFinitePlace C (ExactConstantExtension C N S),
      finitePlaceGalSmul C F (ExactConstantExtension C N S)
          (exactConstantExtensionFrobeniusTwistOverFixedField
            C N S hExact g) Q =
        finitePlaceGalSmul C (RatFunc C) (ExactConstantExtension C N S)
          (exactConstantExtensionFrobeniusTwist
            C (RatFunc C) N S hExact g) Q := by
  let T := ExactConstantExtension C N S
  letI : Field T := exactConstantExtensionField C N S hExact
  letI : Algebra (RatFunc C) T :=
    exactConstantExtensionBaseAlgebra C (RatFunc C) N S
  letI : SMul (RatFunc C) T := Algebra.toSMul
  letI : Module (RatFunc C) T := Algebra.toModule
  letI : DistribMulAction (RatFunc C) T := Module.toDistribMulAction
  letI : MulAction (RatFunc C) T := DistribMulAction.toMulAction
  letI : FiniteDimensional (RatFunc C) T :=
    finiteDimensional_exactConstantExtension_over_baseRatFunc C S N hExact
  letI : IsGalois (RatFunc C) T :=
    exactConstantExtension_isGalois C (RatFunc C) N S hExact
  letI : Algebra.IsSeparable (RatFunc C) T :=
    isSeparable_exactConstantExtension_over_baseRatFunc C S N hExact
  let F := exactConstantExtensionFrobeniusTwistField
    C (RatFunc C) N S hExact g
  letI : Algebra (RatFunc C) F :=
    SubalgebraClass.toAlgebra F.toSubalgebra
  letI : SMul (RatFunc C) F := Algebra.toSMul
  letI : Module (RatFunc C) F := Algebra.toModule
  letI : FiniteDimensional (RatFunc C) F :=
    finiteDimensional_frobeniusTwistField_over_ratFunc C N S hExact g
  letI : Algebra.IsSeparable (RatFunc C) F :=
    isSeparable_frobeniusTwistField_over_ratFunc C N S hExact g
  letI : Algebra F T := F.toAlgebra
  letI : SMul F T := Algebra.toSMul
  letI : Module F T := Algebra.toModule
  letI : IsScalarTower (RatFunc C) F T := inferInstance
  letI : FiniteDimensional F T :=
    finiteDimensional_exactConstantExtension_over_frobeniusTwistField
      C (RatFunc C) N S hExact g
  letI : IsGalois F T :=
    isGalois_exactConstantExtension_over_frobeniusTwistField
      C (RatFunc C) N S hExact g
  dsimp only
  intro Q
  apply finitePlaceGalSmul_eq_of_apply_eq C F (RatFunc C) T
  intro x
  exact exactConstantExtensionFrobeniusTwistOverFixedField_apply
    C N S hExact g x

/-- Ambient fixedness by the Frobenius twist is therefore the exact
fixedness condition needed for descent to a rational twist-field place. -/
theorem frobeniusTwistField_ambientFixed_finitePlace_under_degree_eq_one
    [IsGalois (RatFunc C) N]
    (hExact : algebraicClosure C N =
      (⊥ : IntermediateField C N))
    (g : N ≃ₐ[RatFunc C] N)
    (hdiv : Nat.card (N ≃ₐ[RatFunc C] N) ∣ Module.finrank C S) :
    letI : Field (ExactConstantExtension C N S) :=
      exactConstantExtensionField C N S hExact
    letI : Algebra (RatFunc C) (ExactConstantExtension C N S) :=
      exactConstantExtensionBaseAlgebra C (RatFunc C) N S
    letI : SMul (RatFunc C) (ExactConstantExtension C N S) :=
      Algebra.toSMul
    letI : Module (RatFunc C) (ExactConstantExtension C N S) :=
      Algebra.toModule
    letI : DistribMulAction (RatFunc C)
        (ExactConstantExtension C N S) := Module.toDistribMulAction
    letI : MulAction (RatFunc C) (ExactConstantExtension C N S) :=
      DistribMulAction.toMulAction
    letI : FiniteDimensional (RatFunc C)
        (ExactConstantExtension C N S) :=
      finiteDimensional_exactConstantExtension_over_baseRatFunc
        C S N hExact
    letI : Algebra.IsSeparable (RatFunc C)
        (ExactConstantExtension C N S) :=
      isSeparable_exactConstantExtension_over_baseRatFunc C S N hExact
    letI : IsGalois (RatFunc C) (ExactConstantExtension C N S) :=
      exactConstantExtension_isGalois C (RatFunc C) N S hExact
    let F := exactConstantExtensionFrobeniusTwistField
      C (RatFunc C) N S hExact g
    letI : Algebra (RatFunc C) F :=
      SubalgebraClass.toAlgebra F.toSubalgebra
    letI : SMul (RatFunc C) F := Algebra.toSMul
    letI : Module (RatFunc C) F := Algebra.toModule
    letI : FiniteDimensional (RatFunc C) F :=
      finiteDimensional_frobeniusTwistField_over_ratFunc C N S hExact g
    letI : Algebra.IsSeparable (RatFunc C) F :=
      isSeparable_frobeniusTwistField_over_ratFunc C N S hExact g
    letI : Algebra F (ExactConstantExtension C N S) := F.toAlgebra
    letI : SMul F (ExactConstantExtension C N S) := Algebra.toSMul
    letI : Module F (ExactConstantExtension C N S) := Algebra.toModule
    letI : IsScalarTower (RatFunc C) F
        (ExactConstantExtension C N S) := inferInstance
    letI : FiniteDimensional F (ExactConstantExtension C N S) :=
      finiteDimensional_exactConstantExtension_over_frobeniusTwistField
        C (RatFunc C) N S hExact g
    letI : IsGalois F (ExactConstantExtension C N S) :=
      isGalois_exactConstantExtension_over_frobeniusTwistField
        C (RatFunc C) N S hExact g
    ∀ Q : FiniteExtensionFinitePlace C (ExactConstantExtension C N S),
      finiteExtensionPlaceDegree C (ExactConstantExtension C N S) (.inl Q) =
          Module.finrank C S →
        finitePlaceGalSmul C (RatFunc C) (ExactConstantExtension C N S)
            (exactConstantExtensionFrobeniusTwist
              C (RatFunc C) N S hExact g) Q = Q →
          finiteExtensionPlaceDegree C F
            (.inl (finitePlaceUnder C F
              (ExactConstantExtension C N S) Q)) = 1 := by
  let T := ExactConstantExtension C N S
  letI : Field T := exactConstantExtensionField C N S hExact
  letI : Algebra (RatFunc C) T :=
    exactConstantExtensionBaseAlgebra C (RatFunc C) N S
  letI : SMul (RatFunc C) T := Algebra.toSMul
  letI : Module (RatFunc C) T := Algebra.toModule
  letI : DistribMulAction (RatFunc C) T := Module.toDistribMulAction
  letI : MulAction (RatFunc C) T := DistribMulAction.toMulAction
  letI : FiniteDimensional (RatFunc C) T :=
    finiteDimensional_exactConstantExtension_over_baseRatFunc C S N hExact
  letI : Algebra.IsSeparable (RatFunc C) T :=
    isSeparable_exactConstantExtension_over_baseRatFunc C S N hExact
  letI : IsGalois (RatFunc C) T :=
    exactConstantExtension_isGalois C (RatFunc C) N S hExact
  let F := exactConstantExtensionFrobeniusTwistField
    C (RatFunc C) N S hExact g
  letI : Algebra (RatFunc C) F :=
    SubalgebraClass.toAlgebra F.toSubalgebra
  letI : SMul (RatFunc C) F := Algebra.toSMul
  letI : Module (RatFunc C) F := Algebra.toModule
  letI : FiniteDimensional (RatFunc C) F :=
    finiteDimensional_frobeniusTwistField_over_ratFunc C N S hExact g
  letI : Algebra.IsSeparable (RatFunc C) F :=
    isSeparable_frobeniusTwistField_over_ratFunc C N S hExact g
  letI : Algebra F T := F.toAlgebra
  letI : SMul F T := Algebra.toSMul
  letI : Module F T := Algebra.toModule
  letI : IsScalarTower (RatFunc C) F T := inferInstance
  letI : FiniteDimensional F T :=
    finiteDimensional_exactConstantExtension_over_frobeniusTwistField
      C (RatFunc C) N S hExact g
  letI : IsGalois F T :=
    isGalois_exactConstantExtension_over_frobeniusTwistField
      C (RatFunc C) N S hExact g
  dsimp only
  intro Q hdegree hfixed
  apply frobeniusTwistField_fixed_finitePlace_under_degree_eq_one
    C N S hExact g hdiv Q hdegree
  rw [exactConstantExtensionFrobeniusTwist_finitePlaceGalSmul_eq_overFixedField
    C N S hExact g Q]
  exact hfixed

/-- Rational finite places of the Frobenius-twist field are exactly the
degree-`[S : C]` top finite places fixed by the ambient Frobenius twist. -/
noncomputable def
    frobeniusTwistField_rationalFinitePlace_equiv_ambientFixedFinitePlace
    [IsGalois (RatFunc C) N]
    (hExact : algebraicClosure C N =
      (⊥ : IntermediateField C N))
    (g : N ≃ₐ[RatFunc C] N)
    (hdiv : Nat.card (N ≃ₐ[RatFunc C] N) ∣ Module.finrank C S) :
    letI : Field (ExactConstantExtension C N S) :=
      exactConstantExtensionField C N S hExact
    letI : Algebra (RatFunc C) (ExactConstantExtension C N S) :=
      exactConstantExtensionBaseAlgebra C (RatFunc C) N S
    letI : SMul (RatFunc C) (ExactConstantExtension C N S) :=
      Algebra.toSMul
    letI : Module (RatFunc C) (ExactConstantExtension C N S) :=
      Algebra.toModule
    letI : DistribMulAction (RatFunc C)
        (ExactConstantExtension C N S) := Module.toDistribMulAction
    letI : MulAction (RatFunc C) (ExactConstantExtension C N S) :=
      DistribMulAction.toMulAction
    letI : FiniteDimensional (RatFunc C)
        (ExactConstantExtension C N S) :=
      finiteDimensional_exactConstantExtension_over_baseRatFunc
        C S N hExact
    letI : IsGalois (RatFunc C) (ExactConstantExtension C N S) :=
      exactConstantExtension_isGalois C (RatFunc C) N S hExact
    letI : Algebra.IsSeparable (RatFunc C)
        (ExactConstantExtension C N S) :=
      isSeparable_exactConstantExtension_over_baseRatFunc C S N hExact
    let F := exactConstantExtensionFrobeniusTwistField
      C (RatFunc C) N S hExact g
    letI : Algebra (RatFunc C) F :=
      SubalgebraClass.toAlgebra F.toSubalgebra
    letI : SMul (RatFunc C) F := Algebra.toSMul
    letI : Module (RatFunc C) F := Algebra.toModule
    letI : FiniteDimensional (RatFunc C) F :=
      finiteDimensional_frobeniusTwistField_over_ratFunc C N S hExact g
    letI : Algebra.IsSeparable (RatFunc C) F :=
      isSeparable_frobeniusTwistField_over_ratFunc C N S hExact g
    letI : Algebra F (ExactConstantExtension C N S) := F.toAlgebra
    letI : SMul F (ExactConstantExtension C N S) := Algebra.toSMul
    letI : Module F (ExactConstantExtension C N S) := Algebra.toModule
    letI : IsScalarTower (RatFunc C) F
        (ExactConstantExtension C N S) := inferInstance
    letI : FiniteDimensional F (ExactConstantExtension C N S) :=
      finiteDimensional_exactConstantExtension_over_frobeniusTwistField
        C (RatFunc C) N S hExact g
    letI : IsGalois F (ExactConstantExtension C N S) :=
      isGalois_exactConstantExtension_over_frobeniusTwistField
        C (RatFunc C) N S hExact g
    FiniteExtensionRationalFinitePlace C F ≃
      {Q : FiniteExtensionFinitePlace C (ExactConstantExtension C N S) //
        finiteExtensionPlaceDegree C (ExactConstantExtension C N S) (.inl Q) =
            Module.finrank C S ∧
          finitePlaceGalSmul C (RatFunc C) (ExactConstantExtension C N S)
            (exactConstantExtensionFrobeniusTwist
              C (RatFunc C) N S hExact g) Q = Q} := by
  let T := ExactConstantExtension C N S
  letI : Field T := exactConstantExtensionField C N S hExact
  letI : Algebra (RatFunc C) T :=
    exactConstantExtensionBaseAlgebra C (RatFunc C) N S
  letI : SMul (RatFunc C) T := Algebra.toSMul
  letI : Module (RatFunc C) T := Algebra.toModule
  letI : DistribMulAction (RatFunc C) T := Module.toDistribMulAction
  letI : MulAction (RatFunc C) T := DistribMulAction.toMulAction
  letI : FiniteDimensional (RatFunc C) T :=
    finiteDimensional_exactConstantExtension_over_baseRatFunc C S N hExact
  letI : IsGalois (RatFunc C) T :=
    exactConstantExtension_isGalois C (RatFunc C) N S hExact
  letI : Algebra.IsSeparable (RatFunc C) T :=
    isSeparable_exactConstantExtension_over_baseRatFunc C S N hExact
  let F := exactConstantExtensionFrobeniusTwistField
    C (RatFunc C) N S hExact g
  letI : Algebra (RatFunc C) F :=
    SubalgebraClass.toAlgebra F.toSubalgebra
  letI : SMul (RatFunc C) F := Algebra.toSMul
  letI : Module (RatFunc C) F := Algebra.toModule
  letI : FiniteDimensional (RatFunc C) F :=
    finiteDimensional_frobeniusTwistField_over_ratFunc C N S hExact g
  letI : Algebra.IsSeparable (RatFunc C) F :=
    isSeparable_frobeniusTwistField_over_ratFunc C N S hExact g
  letI : Algebra F T := F.toAlgebra
  letI : SMul F T := Algebra.toSMul
  letI : Module F T := Algebra.toModule
  letI : IsScalarTower (RatFunc C) F T := inferInstance
  letI : FiniteDimensional F T :=
    finiteDimensional_exactConstantExtension_over_frobeniusTwistField
      C (RatFunc C) N S hExact g
  letI : IsGalois F T :=
    isGalois_exactConstantExtension_over_frobeniusTwistField
      C (RatFunc C) N S hExact g
  dsimp only
  have hfinrank : Module.finrank F T = Module.finrank C S :=
    finrank_exactConstantExtension_over_frobeniusTwistField
      C (RatFunc C) N S hExact g hdiv
  have hdegree : ∀ Q : FiniteExtensionFinitePlace C T,
      Module.finrank F T ∣ finiteExtensionPlaceDegree C T (.inl Q) := by
    intro Q
    rw [hfinrank]
    exact exactConstantExtensionFinitePlace_finrank_constants_dvd_degree
      C N S hExact Q
  let sigmaF :=
    exactConstantExtensionFrobeniusTwistOverFixedField C N S hExact g
  let eFixed := rationalFinitePlaceEquivGeneratorFixedPlace
    C F T hdegree sigmaF
      (exactConstantExtensionFrobeniusTwistOverFixedField_zpowers_eq_top
        C N S hExact g)
      (frobeniusTwistField_finitePlace_ramificationIdx_eq_one
        C N S hExact g hdiv)
  let eCompare :
      {Q : FiniteExtensionFinitePlace C T //
        finiteExtensionPlaceDegree C T (.inl Q) = Module.finrank F T ∧
          finitePlaceGalSmul C F T sigmaF Q = Q} ≃
      {Q : FiniteExtensionFinitePlace C T //
        finiteExtensionPlaceDegree C T (.inl Q) = Module.finrank C S ∧
          finitePlaceGalSmul C (RatFunc C) T
            (exactConstantExtensionFrobeniusTwist
              C (RatFunc C) N S hExact g) Q = Q} :=
    { toFun := fun Q => ⟨Q.1,
        Q.2.1.trans hfinrank,
        (exactConstantExtensionFrobeniusTwist_finitePlaceGalSmul_eq_overFixedField
          C N S hExact g Q.1).symm.trans Q.2.2⟩
      invFun := fun Q => ⟨Q.1,
        Q.2.1.trans hfinrank.symm,
        (exactConstantExtensionFrobeniusTwist_finitePlaceGalSmul_eq_overFixedField
          C N S hExact g Q.1).trans Q.2.2⟩
      left_inv := fun Q => Subtype.ext rfl
      right_inv := fun Q => Subtype.ext rfl }
  exact eFixed.trans eCompare

end

end BGS.HasseWeil
