import Mathlib.LinearAlgebra.FiniteDimensional.Lemmas

/-!
# Dimension growth in a one-point filtration

This file isolates the reusable linear-algebra step in the one-point
filtration used in Stepanov-style arguments.  If every element of a larger
subspace is congruent modulo the preceding subspace to a scalar multiple of
one pivot, then adjoining that pivot generates the larger subspace.  Hence a
single filtration step increases dimension by at most one.
-/

namespace BGS.HasseWeil

variable {K L : Type*} [Field K] [AddCommGroup L] [Module K L]

/-- If every element of `T` is congruent modulo `S` to a scalar multiple of
`y`, then `T` is generated by `S` and `y`. -/
theorem eq_sup_span_singleton_of_exists_sub_smul_mem
    {S T : Submodule K L} {y : L}
    (hST : S ≤ T) (hy : y ∈ T)
    (hmod : ∀ x ∈ T, ∃ c : K, x - c • y ∈ S) :
    T = S ⊔ K ∙ y := by
  apply le_antisymm
  · intro x hx
    obtain ⟨c, hc⟩ := hmod x hx
    rw [← sub_add_cancel x (c • y)]
    exact (S ⊔ K ∙ y).add_mem
      ((show S ≤ S ⊔ K ∙ y from le_sup_left) hc)
      ((show K ∙ y ≤ S ⊔ K ∙ y from le_sup_right)
        (Submodule.smul_mem _ c (Submodule.mem_span_singleton_self y)))
  · exact sup_le hST ((Submodule.span_singleton_le_iff_mem y T).mpr hy)

/-- A one-pivot extension of a finite-dimensional subspace is again
finite-dimensional. -/
theorem moduleFinite_of_exists_sub_smul_mem
    {S T : Submodule K L} {y : L}
    (hST : S ≤ T) (hy : y ∈ T)
    (hmod : ∀ x ∈ T, ∃ c : K, x - c • y ∈ S)
    [Module.Finite K S] :
    Module.Finite K T := by
  rw [eq_sup_span_singleton_of_exists_sub_smul_mem hST hy hmod]
  infer_instance

/-- A one-pivot extension increases finrank by at most one. -/
theorem finrank_le_add_one_of_exists_sub_smul_mem
    {S T : Submodule K L} {y : L}
    (hST : S ≤ T) (hy : y ∈ T)
    (hmod : ∀ x ∈ T, ∃ c : K, x - c • y ∈ S)
    [Module.Finite K S] :
    Module.finrank K T ≤ Module.finrank K S + 1 := by
  have hspan : Module.finrank K (K ∙ y) ≤ 1 := by
    classical
    simpa using (finrank_span_le_card (R := K) ({y} : Set L))
  rw [eq_sup_span_singleton_of_exists_sub_smul_mem hST hy hmod]
  exact (Submodule.finrank_add_le_finrank_add_finrank S (K ∙ y)).trans
    (Nat.add_le_add_left hspan (Module.finrank K S))

/-- Along a nested filtration whose successive quotients are generated by one
pivot, every stage is finite-dimensional and stage `n` has finrank at most
the initial finrank plus `n`. -/
theorem onePointFiltration_moduleFinite_and_finrank_le
    (R : ℕ → Submodule K L) (y : ℕ → L)
    (hnested : ∀ n, R n ≤ R (n + 1))
    (hpivot : ∀ n, y n ∈ R (n + 1))
    (hmod : ∀ n x, x ∈ R (n + 1) →
      ∃ c : K, x - c • y n ∈ R n)
    [Module.Finite K (R 0)] :
    ∀ n, Module.Finite K (R n) ∧
      Module.finrank K (R n) ≤ Module.finrank K (R 0) + n := by
  intro n
  induction n with
  | zero =>
      exact ⟨inferInstance, by simp⟩
  | succ n ih =>
      letI : Module.Finite K (R n) := ih.1
      have hfinite : Module.Finite K (R (n + 1)) :=
        moduleFinite_of_exists_sub_smul_mem
          (hnested n) (hpivot n) (hmod n)
      letI : Module.Finite K (R (n + 1)) := hfinite
      refine ⟨hfinite, ?_⟩
      calc
        Module.finrank K (R (n + 1)) ≤ Module.finrank K (R n) + 1 :=
          finrank_le_add_one_of_exists_sub_smul_mem
            (hnested n) (hpivot n) (hmod n)
        _ ≤ (Module.finrank K (R 0) + n) + 1 :=
          Nat.add_le_add_right ih.2 1
        _ = Module.finrank K (R 0) + (n + 1) := by
          rw [Nat.add_assoc]

end BGS.HasseWeil
