import BGS.HasseWeil.FiniteFieldSubfield

/-!
# Composita of finite fields

Suppose two finite extensions `S / C` and `K / C` are embedded in a common
finite field `T` and generate `T`.  Their degrees determine the compositum:

`[T : C] = lcm([S : C], [K : C])`.

The relative form is

`[T : S] = [K : C] / gcd([S : C], [K : C])`.

Generation is expressed by surjectivity of the canonical tensor-product map.
This formulation is designed to apply directly to residue fields after a
constant extension.
-/

open scoped TensorProduct

namespace BGS.HasseWeil

noncomputable section

/-- A finite field generated by two embedded finite subfields has degree the
least common multiple of their degrees over the common finite field. -/
theorem finiteField_finrank_eq_lcm_of_tensorLift_surjective
    (C S K T : Type*)
    [Field C] [Field S] [Field K] [Field T]
    [Algebra C S] [Algebra C K] [Algebra C T]
    [Finite C] [Finite S] [Finite K] [Finite T]
    (f : S →ₐ[C] T) (g : K →ₐ[C] T)
    (hfg : ∀ s k, Commute (f s) (g k))
    (hsurj : Function.Surjective (Algebra.TensorProduct.lift f g hfg)) :
    Module.finrank C T =
      Nat.lcm (Module.finrank C S) (Module.finrank C K) := by
  letI : Fintype C := Fintype.ofFinite C
  letI : Fintype S := Fintype.ofFinite S
  letI : Fintype K := Fintype.ofFinite K
  letI : Fintype T := Fintype.ofFinite T
  let m := Module.finrank C S
  let n := Module.finrank C K
  let l := Nat.lcm m n
  let q := Fintype.card C
  have hm : m ∣ Module.finrank C T :=
    FiniteField.nonempty_algHom_iff_finrank_dvd.mp ⟨f⟩
  have hn : n ∣ Module.finrank C T :=
    FiniteField.nonempty_algHom_iff_finrank_dvd.mp ⟨g⟩
  have hl_dvd : l ∣ Module.finrank C T :=
    Nat.lcm_dvd_iff.mpr ⟨hm, hn⟩
  have hm_l : m ∣ l := Nat.dvd_lcm_left m n
  have hn_l : n ∣ l := Nat.dvd_lcm_right m n
  have hS (s : S) : s ^ (q ^ l) = s := by
    obtain ⟨a, ha⟩ := hm_l
    rw [ha, pow_mul, ← Module.card_eq_pow_finrank]
    exact FiniteField.pow_card_pow a s
  have hK (k : K) : k ^ (q ^ l) = k := by
    obtain ⟨a, ha⟩ := hn_l
    rw [ha, pow_mul, ← Module.card_eq_pow_finrank]
    exact FiniteField.pow_card_pow a k
  let φ := FiniteField.frobeniusAlgHom C T ^ l
  have hφ (x : T) : φ x = x ^ (q ^ l) := by
    simp [φ, q, AlgHom.coe_pow, FiniteField.coe_frobeniusAlgHom,
      pow_iterate]
  have hTensor (y : S ⊗[C] K) :
      φ (Algebra.TensorProduct.lift f g hfg y) =
        Algebra.TensorProduct.lift f g hfg y := by
    induction y using TensorProduct.induction_on with
    | zero => simp
    | tmul s k =>
        rw [Algebra.TensorProduct.lift_tmul, map_mul, hφ, hφ]
        have hs : (f s) ^ (q ^ l) = f s := by
          rw [← map_pow, hS]
        have hk : (g k) ^ (q ^ l) = g k := by
          rw [← map_pow, hK]
        rw [hs, hk]
    | add x y hx hy =>
        rw [map_add, map_add, hx, hy]
  have hpow (x : T) : x ^ (q ^ l) = x := by
    obtain ⟨y, rfl⟩ := hsurj x
    rw [← hφ]
    exact hTensor y
  have hl0 : l ≠ 0 :=
    (Nat.lcm_pos Module.finrank_pos Module.finrank_pos).ne'
  have hcard : Fintype.card T ≤ q ^ l := by
    have hroots := Polynomial.card_le_degree_of_subset_roots
      (R := T) (p := Polynomial.X ^ (q ^ l) - Polynomial.X)
      (Z := Finset.univ) (fun x _ => by
        rw [Polynomial.mem_roots']
        constructor
        · exact FiniteField.X_pow_card_pow_sub_X_ne_zero T hl0
            Fintype.one_lt_card
        · simp [hpow x])
    rw [FiniteField.X_pow_card_pow_sub_X_natDegree_eq T hl0
      Fintype.one_lt_card] at hroots
    exact hroots
  have hle : Module.finrank C T ≤ l := by
    rw [← Nat.pow_le_pow_iff_right (a := q) Fintype.one_lt_card]
    rw [← Module.card_eq_pow_finrank (K := C) (V := T)]
    exact hcard
  exact Nat.le_antisymm hle (Nat.le_of_dvd
    (Module.finrank_pos (R := C) (M := T)) hl_dvd)

/-- Relative-degree form of the finite-field compositum formula. -/
theorem finiteField_finrank_over_left_eq_div_gcd_of_tensorLift_surjective
    (C S K T : Type*)
    [Field C] [Field S] [Field K] [Field T]
    [Algebra C S] [Algebra C K] [Algebra C T]
    [Finite C] [Finite S] [Finite K] [Finite T]
    [Algebra S T] [IsScalarTower C S T]
    (g : K →ₐ[C] T)
    (hsurj : Function.Surjective (Algebra.TensorProduct.lift
      (IsScalarTower.toAlgHom C S T) g
      (fun _ _ => Commute.all _ _))) :
    Module.finrank S T =
      Module.finrank C K /
        Nat.gcd (Module.finrank C S) (Module.finrank C K) := by
  let m := Module.finrank C S
  let n := Module.finrank C K
  let d := Nat.gcd m n
  let l := Nat.lcm m n
  let r := Module.finrank S T
  have htotal : Module.finrank C T = l :=
    finiteField_finrank_eq_lcm_of_tensorLift_surjective
      C S K T (IsScalarTower.toAlgHom C S T) g
      (fun _ _ => Commute.all _ _) hsurj
  have hmr : m * r = l := by
    exact (Module.finrank_mul_finrank C S T).trans htotal
  have hdr : d * r = n := by
    apply Nat.mul_left_cancel
      (Module.finrank_pos (R := C) (M := S))
    calc
      m * (d * r) = d * (m * r) := by ac_rfl
      _ = d * l := by rw [hmr]
      _ = m * n := Nat.gcd_mul_lcm m n
  have hdpos : 0 < d := Nat.gcd_pos_of_pos_left n
    (Module.finrank_pos (R := C) (M := S))
  change r = n / d
  symm
  apply Nat.div_eq_of_eq_mul_left hdpos
  simpa [mul_comm] using hdr.symm

end

end BGS.HasseWeil
