import BGS.CorvajaZannier.FiniteExtensionCanonicalWronskian
import BGS.HasseWeil.FiniteExtensionZeroCounting
import Mathlib.GroupTheory.Archimedean

/-!
# The divisor-degree index

For a finite separable extension of `K(X)`, divisor degree is an additive map
from the exhaustive divisor group to `ℤ`.  Its image is a nonzero subgroup of
`ℤ`, hence is generated by one positive natural number.  This file defines
that generator and proves its two equivalent universal properties:

* it generates every divisor degree; and
* it is the greatest common divisor of the degrees of all exhaustive places.

This is the integer `δ` introduced in Stichtenoth, Lemma 5.1.4 (printed
p. 187).  The zeta-function rationality argument initially works with `δ`
arbitrary.  The later theorem `δ = 1` is F. K. Schmidt's theorem (Corollary
5.1.11, printed p. 191); Stichtenoth proves it only after rationality and the
constant-extension identity for zeta functions.  Consequently no implication
from exact constants to `δ = 1` is asserted here: doing so at this stage would
make the intended zeta proof circular.  The exact missing conclusion is
isolated by the degree-one criterion at the end of the file.
-/

namespace BGS.HasseWeil

open BGS.CorvajaZannier
open scoped nonZeroDivisors Polynomial

noncomputable section

variable (K : Type*) [Field K] [Fintype K] [DecidableEq K]
  [DecidableEq (RatFunc K)]
variable (L : Type*) [Field L] [Algebra (RatFunc K) L]
  [FiniteDimensional (RatFunc K) L]
  [Algebra.IsSeparable (RatFunc K) L]

local instance divisorDegreeIndexInfinityIntegralClosureModuleFinite :
    Module.Finite (RatFuncInfinityIntegers K)
      (RatFuncInfinityIntegralClosure K L) :=
  IsIntegralClosure.finite (RatFuncInfinityIntegers K) (RatFunc K) L
    (RatFuncInfinityIntegralClosure K L)

local instance divisorDegreeIndexInfinityIntegralClosureIsIntegral :
    Algebra.IsIntegral (RatFuncInfinityIntegers K)
      (RatFuncInfinityIntegralClosure K L) :=
  IsIntegralClosure.isIntegral_algebra (RatFuncInfinityIntegers K) L

local instance divisorDegreeIndexInfinityBaseTorsionFreeTop :
    Module.IsTorsionFree (RatFuncInfinityIntegers K) L :=
  Module.IsTorsionFree.trans_faithfulSMul
    (RatFuncInfinityIntegers K) (RatFunc K) L

local instance divisorDegreeIndexInfinityIntegralClosureIsTorsionFree :
    Module.IsTorsionFree (RatFuncInfinityIntegers K)
      (RatFuncInfinityIntegralClosure K L) :=
  IsIntegralClosure.isTorsionFree (RatFuncInfinityIntegers K) L

omit [Fintype K] [FiniteDimensional (RatFunc K) L]
  [Algebra.IsSeparable (RatFunc K) L] in
private theorem finiteExtensionDivisorDegree_add_index
    (D E : FiniteExtensionPlace K L →₀ ℤ) :
    finiteExtensionDivisorDegree K L (D + E) =
      finiteExtensionDivisorDegree K L D +
        finiteExtensionDivisorDegree K L E := by
  classical
  simpa only [finiteExtensionDivisorDegree] using
    (Finsupp.sum_add_index (f := D) (g := E)
      (h := fun v e ↦ e * (finiteExtensionPlaceDegree K L v : ℤ))
      (by simp) (by intros; ring))

omit [Fintype K] [FiniteDimensional (RatFunc K) L]
  [Algebra.IsSeparable (RatFunc K) L] in
private theorem finiteExtensionDivisorDegree_single_index
    (P : FiniteExtensionPlace K L) (z : ℤ) :
    finiteExtensionDivisorDegree K L (Finsupp.single P z) =
      z * (finiteExtensionPlaceDegree K L P : ℤ) := by
  classical
  simp [finiteExtensionDivisorDegree]

/-- Divisor degree as an additive homomorphism to `ℤ`. -/
def finiteExtensionDivisorDegreeHom :
    (FiniteExtensionPlace K L →₀ ℤ) →+ ℤ where
  toFun := finiteExtensionDivisorDegree K L
  map_zero' := by simp [finiteExtensionDivisorDegree]
  map_add' := finiteExtensionDivisorDegree_add_index K L

private noncomputable def finiteExtensionDivisorDegreeGenerator : ℤ :=
  Classical.choose
    (Int.subgroup_cyclic (finiteExtensionDivisorDegreeHom K L).range)

/-- The positive generator of the image of divisor degree.  Equivalently,
this is the gcd of the degrees of all exhaustive places. -/
def finiteExtensionDivisorDegreeIndex : ℕ :=
  (finiteExtensionDivisorDegreeGenerator K L).natAbs

omit [Fintype K] [FiniteDimensional (RatFunc K) L]
  [Algebra.IsSeparable (RatFunc K) L] in
private theorem finiteExtensionDivisorDegreeHom_range_eq_zmultiples :
    (finiteExtensionDivisorDegreeHom K L).range =
      AddSubgroup.zmultiples
        (finiteExtensionDivisorDegreeIndex K L : ℤ) := by
  let a := finiteExtensionDivisorDegreeGenerator K L
  have ha : (finiteExtensionDivisorDegreeHom K L).range =
      AddSubgroup.closure {a} :=
    Classical.choose_spec
      (Int.subgroup_cyclic (finiteExtensionDivisorDegreeHom K L).range)
  calc
    (finiteExtensionDivisorDegreeHom K L).range =
        AddSubgroup.closure {a} := ha
    _ = AddSubgroup.zmultiples a :=
      (AddSubgroup.zmultiples_eq_closure a).symm
    _ = AddSubgroup.zmultiples
        (finiteExtensionDivisorDegreeIndex K L : ℤ) := by
      rw [finiteExtensionDivisorDegreeIndex]
      exact (Int.zmultiples_natAbs a).symm

omit [Fintype K] in
private theorem finiteExtensionDivisorDegreeHom_range_ne_bot :
    (finiteExtensionDivisorDegreeHom K L).range ≠ ⊥ := by
  let P : FiniteExtensionInfinityPlace K L :=
    Classical.choice (inferInstance : Nonempty (FiniteExtensionInfinityPlace K L))
  let D : FiniteExtensionPlace K L →₀ ℤ := Finsupp.single (.inr P) 1
  have hmem : finiteExtensionDivisorDegree K L D ∈
      (finiteExtensionDivisorDegreeHom K L).range := ⟨D, rfl⟩
  have hdegree : finiteExtensionDivisorDegree K L D =
      (finiteExtensionPlaceDegree K L (.inr P) : ℤ) := by
    rw [finiteExtensionDivisorDegree_single_index]
    simp
  intro hrange
  rw [hrange, AddSubgroup.mem_bot, hdegree] at hmem
  have hzero : finiteExtensionPlaceDegree K L (.inr P) = 0 := by
    exact_mod_cast hmem
  exact (finiteExtensionPlaceDegree_pos K L (.inr P)).ne' hzero

omit [Fintype K] in
/-- The divisor-degree index is strictly positive. -/
theorem finiteExtensionDivisorDegreeIndex_pos :
    0 < finiteExtensionDivisorDegreeIndex K L := by
  apply Nat.pos_of_ne_zero
  intro hzero
  apply finiteExtensionDivisorDegreeHom_range_ne_bot K L
  rw [finiteExtensionDivisorDegreeHom_range_eq_zmultiples K L, hzero]
  simp

omit [Fintype K] [FiniteDimensional (RatFunc K) L]
  [Algebra.IsSeparable (RatFunc K) L] in
/-- Every divisor degree is an integer multiple of the index. -/
theorem finiteExtensionDivisorDegreeIndex_dvd_divisorDegree
    (D : FiniteExtensionPlace K L →₀ ℤ) :
    (finiteExtensionDivisorDegreeIndex K L : ℤ) ∣
      finiteExtensionDivisorDegree K L D := by
  rw [← Int.mem_zmultiples_iff,
    ← finiteExtensionDivisorDegreeHom_range_eq_zmultiples K L]
  exact ⟨D, rfl⟩

omit [Fintype K] [FiniteDimensional (RatFunc K) L]
  [Algebra.IsSeparable (RatFunc K) L] in
/-- The index itself occurs as the degree of an exhaustive divisor. -/
theorem exists_finiteExtensionDivisor_degree_eq_index :
    ∃ D : FiniteExtensionPlace K L →₀ ℤ,
      finiteExtensionDivisorDegree K L D =
        (finiteExtensionDivisorDegreeIndex K L : ℤ) := by
  have hmem : (finiteExtensionDivisorDegreeIndex K L : ℤ) ∈
      AddSubgroup.zmultiples
        (finiteExtensionDivisorDegreeIndex K L : ℤ) :=
    AddSubgroup.mem_zmultiples _
  rw [← finiteExtensionDivisorDegreeHom_range_eq_zmultiples K L] at hmem
  rcases hmem with ⟨D, hD⟩
  exact ⟨D, hD⟩

omit [Fintype K] [FiniteDimensional (RatFunc K) L]
  [Algebra.IsSeparable (RatFunc K) L] in
/-- The image of divisor degree is exactly the subgroup of multiples of the
index. -/
theorem finiteExtensionDivisorDegree_mem_range_iff
    (n : ℤ) :
    n ∈ (finiteExtensionDivisorDegreeHom K L).range ↔
      (finiteExtensionDivisorDegreeIndex K L : ℤ) ∣ n := by
  rw [finiteExtensionDivisorDegreeHom_range_eq_zmultiples K L,
    Int.mem_zmultiples_iff]

omit [Fintype K] [FiniteDimensional (RatFunc K) L]
  [Algebra.IsSeparable (RatFunc K) L] in
/-- An integer occurs as a divisor degree exactly when it is a multiple of
the index. -/
theorem exists_finiteExtensionDivisor_degree_eq_iff
    (n : ℤ) :
    (∃ D : FiniteExtensionPlace K L →₀ ℤ,
      finiteExtensionDivisorDegree K L D = n) ↔
        (finiteExtensionDivisorDegreeIndex K L : ℤ) ∣ n := by
  rw [← finiteExtensionDivisorDegree_mem_range_iff K L n]
  rfl

omit [Fintype K] [FiniteDimensional (RatFunc K) L]
  [Algebra.IsSeparable (RatFunc K) L] in
/-- Natural-valued form of index divisibility, used for zeta coefficients. -/
theorem finiteExtensionDivisorDegreeIndex_dvd_nat_of_degree_eq
    (D : FiniteExtensionPlace K L →₀ ℤ) (n : ℕ)
    (hD : finiteExtensionDivisorDegree K L D = (n : ℤ)) :
    finiteExtensionDivisorDegreeIndex K L ∣ n := by
  have hdiv : (finiteExtensionDivisorDegreeIndex K L : ℤ) ∣ (n : ℤ) := by
    rw [← hD]
    exact finiteExtensionDivisorDegreeIndex_dvd_divisorDegree K L D
  exact_mod_cast hdiv

omit [Fintype K] [FiniteDimensional (RatFunc K) L]
  [Algebra.IsSeparable (RatFunc K) L] in
/-- If the index does not divide `n`, there is no divisor (and hence no
effective divisor) of degree `n`. -/
theorem not_exists_finiteExtensionDivisor_degree_eq_of_not_dvd
    (n : ℕ) (hn : ¬ finiteExtensionDivisorDegreeIndex K L ∣ n) :
    ¬ ∃ D : FiniteExtensionPlace K L →₀ ℤ,
      finiteExtensionDivisorDegree K L D = (n : ℤ) := by
  rintro ⟨D, hD⟩
  exact hn
    (finiteExtensionDivisorDegreeIndex_dvd_nat_of_degree_eq K L D n hD)

omit [Fintype K] [FiniteDimensional (RatFunc K) L]
  [Algebra.IsSeparable (RatFunc K) L] in
/-- The index divides the degree of each exhaustive place. -/
theorem finiteExtensionDivisorDegreeIndex_dvd_placeDegree
    (P : FiniteExtensionPlace K L) :
    finiteExtensionDivisorDegreeIndex K L ∣
      finiteExtensionPlaceDegree K L P := by
  have hdiv := finiteExtensionDivisorDegreeIndex_dvd_divisorDegree K L
    (Finsupp.single P 1)
  rw [finiteExtensionDivisorDegree_single_index] at hdiv
  simp only [one_mul] at hdiv
  exact_mod_cast hdiv

omit [Fintype K] [FiniteDimensional (RatFunc K) L]
  [Algebra.IsSeparable (RatFunc K) L] in
private theorem integer_dvd_finiteExtensionDivisorDegree_of_dvd_placeDegree
    (d : ℕ) (hd : ∀ P : FiniteExtensionPlace K L,
      d ∣ finiteExtensionPlaceDegree K L P)
    (D : FiniteExtensionPlace K L →₀ ℤ) :
    (d : ℤ) ∣ finiteExtensionDivisorDegree K L D := by
  classical
  induction D using Finsupp.induction with
  | zero => simp [finiteExtensionDivisorDegree]
  | single_add P z D hPD hz ih =>
      rw [finiteExtensionDivisorDegree_add_index,
        finiteExtensionDivisorDegree_single_index]
      apply dvd_add
      · obtain ⟨c, hc⟩ := hd P
        refine ⟨z * (c : ℤ), ?_⟩
        rw [hc]
        push_cast
        ring
      · exact ih

omit [Fintype K] [FiniteDimensional (RatFunc K) L]
  [Algebra.IsSeparable (RatFunc K) L] in
/-- Any natural number dividing every place degree also divides the divisor
degree index.  Together with `finiteExtensionDivisorDegreeIndex_dvd_placeDegree`,
this is the gcd universal property. -/
theorem dvd_finiteExtensionDivisorDegreeIndex_of_dvd_placeDegree
    (d : ℕ) (hd : ∀ P : FiniteExtensionPlace K L,
      d ∣ finiteExtensionPlaceDegree K L P) :
    d ∣ finiteExtensionDivisorDegreeIndex K L := by
  obtain ⟨D, hD⟩ := exists_finiteExtensionDivisor_degree_eq_index K L
  have hdiv : (d : ℤ) ∣ finiteExtensionDivisorDegree K L D :=
    integer_dvd_finiteExtensionDivisorDegree_of_dvd_placeDegree K L d hd D
  rw [hD] at hdiv
  exact_mod_cast hdiv

omit [Fintype K] [FiniteDimensional (RatFunc K) L]
  [Algebra.IsSeparable (RatFunc K) L] in
/-- Universal characterization of the divisor-degree index as the gcd of all
exhaustive place degrees. -/
theorem finiteExtensionDivisorDegreeIndex_isGCD :
    (∀ P : FiniteExtensionPlace K L,
      finiteExtensionDivisorDegreeIndex K L ∣
        finiteExtensionPlaceDegree K L P) ∧
    ∀ d : ℕ, (∀ P : FiniteExtensionPlace K L,
      d ∣ finiteExtensionPlaceDegree K L P) →
        d ∣ finiteExtensionDivisorDegreeIndex K L := by
  exact ⟨finiteExtensionDivisorDegreeIndex_dvd_placeDegree K L,
    dvd_finiteExtensionDivisorDegreeIndex_of_dvd_placeDegree K L⟩

omit [Fintype K] [FiniteDimensional (RatFunc K) L]
  [Algebra.IsSeparable (RatFunc K) L] in
/-- A positive divisor degree is at least the index. -/
theorem finiteExtensionDivisorDegreeIndex_le_of_degree_eq_nat
    (D : FiniteExtensionPlace K L →₀ ℤ) (n : ℕ) (hn : 0 < n)
    (hD : finiteExtensionDivisorDegree K L D = (n : ℤ)) :
    finiteExtensionDivisorDegreeIndex K L ≤ n := by
  have hdivNat : finiteExtensionDivisorDegreeIndex K L ∣ n :=
    finiteExtensionDivisorDegreeIndex_dvd_nat_of_degree_eq K L D n hD
  exact Nat.le_of_dvd hn hdivNat

omit [Fintype K] in
/-- The index is one exactly when there exists an exhaustive divisor of
degree one.  Thus an exact-constants-to-index-one proof must genuinely
construct (or otherwise imply) such a degree-one divisor; exact constants by
themselves only control the kernel of principal divisor, not this image. -/
theorem finiteExtensionDivisorDegreeIndex_eq_one_iff :
    finiteExtensionDivisorDegreeIndex K L = 1 ↔
      ∃ D : FiniteExtensionPlace K L →₀ ℤ,
        finiteExtensionDivisorDegree K L D = 1 := by
  constructor
  · intro hindex
    obtain ⟨D, hD⟩ := exists_finiteExtensionDivisor_degree_eq_index K L
    exact ⟨D, by simpa [hindex] using hD⟩
  · rintro ⟨D, hD⟩
    have hle : finiteExtensionDivisorDegreeIndex K L ≤ 1 :=
      finiteExtensionDivisorDegreeIndex_le_of_degree_eq_nat K L D 1
        Nat.zero_lt_one (by simpa using hD)
    have hpos := finiteExtensionDivisorDegreeIndex_pos K L
    omega

end

end BGS.HasseWeil
