import Mathlib.GroupTheory.SpecificGroups.Cyclic

/-!
# Cyclic subgroups generated by Frobenius twists

The Galois-theoretic lower-bound argument uses elements `(σ, τ)` in a direct
product.  The first component `σ` generates the constant-field Galois group,
while the order of the second finite group divides the order of `σ`.

This file records the resulting elementary group facts: every twist has the
same order as `σ`, its cyclic subgroup meets the kernel of first projection
trivially, and that cyclic subgroup has the expected cardinality.  These are
the group-theoretic inputs for taking fixed fields of Frobenius twists.
-/

namespace BGS.HasseWeil

section

variable {A B : Type*} [Group A] [Group B]

/-- If the order of the finite second factor divides the order of `a`, then
the pair `(a,b)` has the same order as `a`. -/
theorem orderOf_prod_eq_left_of_natCard_dvd
    (a : A) (b : B) (hcard : Nat.card B ∣ orderOf a) :
    orderOf (a, b) = orderOf a := by
  rw [Prod.orderOf, Nat.lcm_eq_left_iff_dvd]
  exact (orderOf_dvd_natCard b).trans hcard

/-- The cyclic subgroup generated by a Frobenius twist meets the kernel of
first projection trivially. -/
theorem zpowers_prod_inf_fst_ker_eq_bot_of_natCard_dvd
    (a : A) (b : B) (hcard : Nat.card B ∣ orderOf a) :
    Subgroup.zpowers (a, b) ⊓ (MonoidHom.fst A B).ker = ⊥ := by
  apply le_antisymm
  · intro x hx
    rw [Subgroup.mem_bot]
    obtain ⟨k, rfl⟩ := Subgroup.mem_zpowers_iff.mp hx.1
    have ha : a ^ k = 1 := by
      have hk := MonoidHom.mem_ker.mp hx.2
      change ((a, b) ^ k).1 = 1 at hk
      simpa using hk
    have hdiv : (orderOf a : ℤ) ∣ k :=
      orderOf_dvd_iff_zpow_eq_one.mpr ha
    rw [← orderOf_dvd_iff_zpow_eq_one,
      orderOf_prod_eq_left_of_natCard_dvd a b hcard]
    exact hdiv
  · exact bot_le

/-- The cyclic subgroup generated by a Frobenius twist has cardinality equal
to the order of the constant-field generator. -/
theorem natCard_zpowers_prod_eq_orderOf_left_of_natCard_dvd
    (a : A) (b : B) (hcard : Nat.card B ∣ orderOf a) :
    Nat.card (Subgroup.zpowers (a, b)) = orderOf a := by
  rw [Nat.card_zpowers, orderOf_prod_eq_left_of_natCard_dvd a b hcard]

end

end BGS.HasseWeil
