import BGS.HasseWeil.FunctionFieldConstantField
import BGS.HasseWeil.PlaneConstantField

/-!
# Constants and restriction for the function-field Galois closure

Equip the chosen normal closure of `L / K(t)` with its induced `K`-algebra
structure, take the algebraic constant field, and restrict every
`K(t)`-automorphism to those constants.  Over a finite base field the constant
field is finite Galois and its automorphism group is cyclic, generated by
Frobenius.  The restriction map is surjective: a constant fixed by its image
is fixed by the full Galois group over `K(t)`, hence lies in `K(t)`; because it
is algebraic over `K`, the exact constant-field theorem for `K(t)` puts it in
`K`.
-/

namespace BGS.HasseWeil

noncomputable section

variable (K L : Type*) [Field K] [Field L]
  [Fintype K] [DecidableEq K] [DecidableEq (RatFunc K)]
  [Algebra (RatFunc K) L]
  [FiniteDimensional (RatFunc K) L]
  [Algebra.IsSeparable (RatFunc K) L]

noncomputable instance functionFieldNormalClosureConstantAlgebra :
    Algebra K (FunctionFieldNormalClosure K L) :=
  RingHom.toAlgebra
    ((algebraMap (RatFunc K) (FunctionFieldNormalClosure K L)).comp
      (algebraMap K (RatFunc K)))

noncomputable instance functionFieldNormalClosureConstantTower :
    IsScalarTower K (RatFunc K) (FunctionFieldNormalClosure K L) :=
  IsScalarTower.of_algebraMap_eq' rfl

/-- The algebraic constant field of the chosen Galois closure. -/
abbrev FunctionFieldNormalClosureConstantField :=
  FunctionFieldConstantField K (FunctionFieldNormalClosure K L)

/-- Restriction of a `K(t)`-automorphism of the normal closure to its algebraic
constant field. -/
def functionFieldNormalClosureConstantRestriction :
    Gal((FunctionFieldNormalClosure K L) / (RatFunc K)) →*
      Gal((FunctionFieldNormalClosureConstantField K L) / K) where
  toFun g := (g.restrictScalars K).algebraicClosure
  map_one' := by
    ext x
    rfl
  map_mul' g h := by
    ext x
    rfl

omit [Fintype K] [DecidableEq K] [DecidableEq (RatFunc K)]
  [FiniteDimensional (RatFunc K) L] in
theorem functionFieldNormalClosureConstantRestriction_apply
    (g : Gal((FunctionFieldNormalClosure K L) / (RatFunc K)))
    (c : FunctionFieldNormalClosureConstantField K L) :
    functionFieldNormalClosureConstantRestriction K L g c =
      ⟨g c.1, by
        exact (map_mem_algebraicClosure_iff
          (g.restrictScalars K).toAlgHom).mpr c.2⟩ := rfl

omit [Fintype K] [DecidableEq K] [DecidableEq (RatFunc K)]
  [FiniteDimensional (RatFunc K) L] in
/-- The kernel consists exactly of automorphisms fixing every algebraic
constant. -/
theorem mem_functionFieldNormalClosureConstantRestriction_ker_iff
    (g : Gal((FunctionFieldNormalClosure K L) / (RatFunc K))) :
    g ∈ (functionFieldNormalClosureConstantRestriction K L).ker ↔
      ∀ c : FunctionFieldNormalClosureConstantField K L, g c.1 = c.1 := by
  rw [MonoidHom.mem_ker]
  constructor
  · intro hg c
    have hc := DFunLike.congr_fun hg c
    exact congrArg Subtype.val hc
  · intro hg
    apply AlgEquiv.ext
    intro c
    apply Subtype.ext
    exact hg c

omit [DecidableEq (RatFunc K)] in
/-- Every automorphism of the algebraic constant field extends to an
automorphism of the normal closure over `K(t)`.

The proof uses fixed fields rather than constructing a constant compositum.
If an algebraic constant is fixed by the image of the restriction map, then
it is fixed by every automorphism of the normal closure over `K(t)`, so the
Galois fixed-field theorem puts it in `K(t)`.  The rational function field has
no elements algebraic over `K` except `K` itself.  Thus the image has trivial
fixed field and is the full constant-field Galois group. -/
theorem functionFieldNormalClosureConstantRestriction_surjective :
    Function.Surjective
      (functionFieldNormalClosureConstantRestriction K L) := by
  let N := FunctionFieldNormalClosure K L
  let C := FunctionFieldNormalClosureConstantField K L
  let rho := functionFieldNormalClosureConstantRestriction K L
  suffices hfixed : IntermediateField.fixedField rho.range =
      (⊥ : IntermediateField K C) from
    MonoidHom.range_eq_top.mp <|
      IntermediateField.fixingSubgroup_fixedField rho.range ▸
        hfixed ▸ IntermediateField.fixingSubgroup_bot
  refine eq_bot_iff.mpr ?_
  intro c hc
  have hcFixed : ∀ g : Gal(N / (RatFunc K)), g c.1 = c.1 := by
    intro g
    have hcg := (IntermediateField.mem_fixedField_iff
      (H := rho.range) c).mp hc (rho g) ⟨g, rfl⟩
    exact congrArg Subtype.val hcg
  obtain ⟨r, hr⟩ :=
    (IsGalois.mem_range_algebraMap_iff_fixed c.1).mpr hcFixed
  have hrIntegral : IsIntegral K r := by
    apply (isIntegral_algHom_iff
      (IsScalarTower.toAlgHom K (RatFunc K) N)
      (algebraMap (RatFunc K) N).injective).mp
    have hcIntegral : IsIntegral K c.1 :=
      (mem_algebraicClosure_iff.mp c.2).isIntegral
    rw [IsScalarTower.toAlgHom_apply, hr]
    exact hcIntegral
  have hrBot : r ∈ (⊥ : IntermediateField K (RatFunc K)) := by
    rw [← ratFunc_algebraicClosure_eq_bot K]
    exact hrIntegral
  obtain ⟨k, hk⟩ := IntermediateField.mem_bot.mp hrBot
  apply IntermediateField.mem_bot.mpr
  refine ⟨k, ?_⟩
  apply Subtype.ext
  change algebraMap K N k = c.1
  rw [← hr, ← hk]
  rfl

omit [Fintype K] [DecidableEq K] [DecidableEq (RatFunc K)]
  [FiniteDimensional (RatFunc K) L] in
/-- After enlarging the base constants to the algebraic constants of the
normal closure, that field is the exact constant field: no further element of
the normal closure is algebraic over it. -/
theorem functionFieldNormalClosureConstantField_isExact :
    algebraicClosure (FunctionFieldNormalClosureConstantField K L)
        (FunctionFieldNormalClosure K L) =
      (⊥ : IntermediateField (FunctionFieldNormalClosureConstantField K L)
        (FunctionFieldNormalClosure K L)) :=
  algebraicClosure.algebraicClosure_eq_bot K (FunctionFieldNormalClosure K L)

omit [DecidableEq (RatFunc K)] in
/-- Frobenius on the finite algebraic constant field has order equal to its
degree over `K`. -/
theorem orderOf_functionFieldNormalClosureConstantFrobenius :
    orderOf (FiniteField.frobeniusAlgEquivOfAlgebraic K
      (FunctionFieldNormalClosureConstantField K L)) =
      Module.finrank K (FunctionFieldNormalClosureConstantField K L) :=
  FiniteField.orderOf_frobeniusAlgEquivOfAlgebraic K
    (FunctionFieldNormalClosureConstantField K L)

end

end BGS.HasseWeil
