import GenMarkoff.General.Assembly.CageReadyCanonicalEndgame
import GenMarkoff.General.Cage.ConnectingDirectedRelay
import GenMarkoff.General.Cage.OrbitConnectingPairPrimitiveWitness
import GenMarkoff.General.Cage.OrbitConnectingReconstruction
import GenMarkoff.General.Cage.OrbitConnectingSquareClasses
import GenMarkoff.General.Arithmetic.ExplicitCutoff
import GenMarkoff.General.Arithmetic.ReasonableCutoff

/-!
# Connecting a canonical primitive endpoint through its actual rotation coset

Suppose a cage-ready canonical first-axis endpoint has square centered norm.
The two orbit-component covers then select a new primitive trace in the
second-axis frame whose centered norm for the next fiber is nonsquare.

The essential parity point is that the reconstructed parameter is a square
multiple of the parameter representing the original point.  Thus it lies in
the actual `rotation1` coset, generated by the square of the primitive
split-torus eigenvalue.  No coordinate permutation is used.
-/

namespace GenMarkoff.General.Cage

open BGS.Markoff
open GenMarkoff.General.Assembly
open GenMarkoff.General.Endgame
open GenMarkoff.General.MiddleGame

noncomputable section

/-- A positive divisor of the split-torus order is nonzero in the prime
field. -/
private lemma natCast_ne_zero_zmod_of_dvd_card_units
    (p d : ℕ) [Fact p.Prime]
    (hd : 0 < d) (hdvd : d ∣ Nat.card (ZMod p)ˣ) :
    (d : ZMod p) ≠ 0 := by
  apply natCast_ne_zero_zmod_of_pos_of_lt hd
  have hcard : Nat.card (ZMod p)ˣ = p - 1 := by
    rw [Nat.card_units, Nat.card_zmod]
  rw [hcard] at hdvd
  have hpTwo : 2 ≤ p := (Fact.out : p.Prime).two_le
  exact lt_of_le_of_lt
    (Nat.le_of_dvd (by omega) hdvd) (by omega)

/-- In odd prime characteristic, the numeral two is nonzero. -/
private lemma two_ne_zero_zmod_of_prime_ne_two
    (p : ℕ) [Fact p.Prime] (hpTwo : p ≠ 2) :
    (2 : ZMod p) ≠ 0 := by
  intro hzero
  have hpDvd : p ∣ 2 :=
    (ZMod.natCast_eq_zero_iff 2 p).mp hzero
  have hpLe : p ≤ 2 := Nat.le_of_dvd (by norm_num) hpDvd
  exact hpTwo (Nat.le_antisymm hpLe (Fact.out : p.Prime).two_le)

/-- The normalized orbit-weight product has the square class of the
centered norm. -/
theorem orderedTraceSigma_isSquare_of_centeredNorm
    {K : Type*} [Field K] (A B C xi : K)
    (hD : xi ^ 2 - 4 ≠ 0)
    (hnorm : IsSquare (centeredNorm B C xi)) :
    IsSquare (orderedTraceSigma A B C xi) := by
  obtain ⟨r, hr⟩ := hnorm
  refine ⟨(xi + A) * r / (xi ^ 2 - 4), ?_⟩
  simp only [orderedTraceSigma, centeredNorm, discriminant] at hr ⊢
  rw [hr]
  field_simp [hD]

private theorem exists_axisTwo_of_orbitConnectingWitnessSelector
    (p : ℕ) [Fact p.Prime] (hpFive : 5 ≤ p)
    (a : Coefficients (ZMod p))
    (hA1 : a.a1 ^ 2 ≠ 4)
    (hA2 : a.a2 ^ 2 ≠ 4)
    (hA3 : a.a3 ^ 2 ≠ 4)
    (hmoving : (a.a3, a.a1) ≠ (0, 0))
    (x : SolutionSurface a)
    (hx : IsCageReadyCanonicalFirstAxisPrimitiveSplit p a x)
    (hsquare :
      IsSquare
        (centeredNorm a.a2 a.a3 (traceAt a .first x.1)))
    (P : ZMod p → Prop)
    (hselect :
      ∀ (alpha beta gamma k omegaInv : ZMod p),
        alpha ≠ 0 →
        alpha * beta =
          orderedTraceSigma a.a1 a.a2 a.a3
            (traceAt a .first x.1) →
        gamma =
          orderedTraceGamma a.a1 a.a2 a.a3
            (traceAt a .first x.1) →
        alpha * beta = k ^ 2 →
        omegaInv ≠ 0 →
        (∀ d : ℕ, d ∣ Nat.card (ZMod p)ˣ → 0 < d →
          SevenHyperellipticPlanesAbsolutelyIrreducible
            (orbitComponentPlusCosetPulledRadicand
              alpha gamma k d)
            (orbitComponentMinusCosetPulledRadicand
              alpha gamma k d)
            (Polynomial.C omegaInv *
              centeredNormPulledRadicand a.a3 a.a1 d)) →
        ∃ v : (ZMod p)ˣ,
          ∃ w :
              OrbitConnectingGoodThreeRootWitness
                alpha gamma k omegaInv a.a3 a.a1,
            w.1.middle = splitTorusTrace v ∧
              orderOf v = p - 1 ∧
                OrderedTraceCandidateRegular
                  a.a2 a.a3 a.a1 w.1.middle ∧
                  P w.1.middle) :
    ∃ y : SolutionSurface a,
      SameVietaComponent x y ∧
        ∃ v : (ZMod p)ˣ,
          traceAt a .second y.1 = splitTorusTrace v ∧
            orderOf v = Nat.card (ZMod p)ˣ ∧
              OrderedTraceCandidateRegular
                a.a2 a.a3 a.a1 (traceAt a .second y.1) ∧
                P (traceAt a .second y.1) ∧
                  ¬ IsSquare
                    (centeredNorm a.a3 a.a1
                      (traceAt a .second y.1)) := by
  obtain ⟨q, heigen, hqOrder, hready⟩ := hx
  let u : ZMod p := x.1.x1
  let xi : ZMod p := traceAt a .first x.1
  have heigenXi : xi = splitTorusTrace q := heigen
  have hcoordinate :
      xi = orderedTrace a.multiplier a.a1 u := by
    rfl
  have hregular :
      OrderedTraceCandidateRegular a.a1 a.a2 a.a3 xi := by
    simpa [xi] using hready.1
  have hobstruction :
      incidenceCenteredNormObstruction a xi ≠ 0 := by
    simpa [xi] using hready.2.2.1
  have hD : discriminant xi ≠ 0 := by
    simpa [discriminant] using hregular.1
  have hconic :
      fiberConic a.a2 a.a3 u xi x.1.x2 x.1.x3 = 0 := by
    have hsurface := x.property
    rw [IsSolution, polynomial_fixed_first] at hsurface
    simpa [u, xi, traceAt, orderedTrace] using hsurface
  obtain ⟨r, hrPair⟩ :=
    exists_unit_fiberPair_eq_of_candidateRegular
      a.multiplier a.a1 a.a2 a.a3 u xi q
        (x.1.x2, x.1.x3) hconic hcoordinate
        (by simpa [xi] using heigen) hregular
  have hrPoint :
      fiberPoint1 a u xi (q : ZMod p) (r : ZMod p) = x.1 := by
    apply Point.ext
    · rfl
    · exact congrArg Prod.fst hrPair
    · exact congrArg Prod.snd hrPair
  let alpha : ZMod p :=
    actualAlpha a.multiplier * (r : ZMod p)
  let beta : ZMod p :=
    actualBeta a.multiplier a.a2 a.a3 u xi / (r : ZMod p)
  let gamma : ZMod p :=
    actualGammaFirst a.multiplier a.a2 a.a3 u xi
  have hproduct :
      alpha * beta =
        orderedTraceSigma a.a1 a.a2 a.a3 xi := by
    calc
      alpha * beta =
          actualSigma a.multiplier a.a2 a.a3 u xi := by
        simpa [alpha, beta] using
          actual_firstDirected_coset_weights_mul
            a.multiplier a.a2 a.a3 u xi r
      _ = orderedTraceSigma a.a1 a.a2 a.a3 xi :=
        actualSigma_eq_orderedTraceSigma
          a.multiplier a.a1 a.a2 a.a3 u xi hcoordinate
  have hgamma :
      gamma = orderedTraceGamma a.a1 a.a2 a.a3 xi := by
    exact actualGammaFirst_eq_orderedTraceGamma
      a.multiplier a.a1 a.a2 a.a3 u xi hD hcoordinate
  have hsigmaSquare :
      IsSquare (orderedTraceSigma a.a1 a.a2 a.a3 xi) :=
    orderedTraceSigma_isSquare_of_centeredNorm
      a.a1 a.a2 a.a3 xi
        (by
          simpa only [eval_orderedTraceDiscriminantPolynomial] using
            hregular.1)
        (by simpa [xi] using hsquare)
  obtain ⟨k, hk⟩ := hsigmaSquare
  have hsquareProduct : alpha * beta = k ^ 2 := by
    calc
      alpha * beta =
          orderedTraceSigma a.a1 a.a2 a.a3 xi := hproduct
      _ = k ^ 2 := by simpa [pow_two] using hk
  have hmultiplier : a.multiplier ≠ 0 := by
    intro hzero
    apply hregular.sigma_ne_zero
    rw [← actualSigma_eq_orderedTraceSigma
      a.multiplier a.a1 a.a2 a.a3 u xi hcoordinate]
    simp [actualSigma, actualAlpha, actualBeta, hzero]
  have halpha : alpha ≠ 0 := by
    exact mul_ne_zero
      (actualAlpha_ne_zero a.multiplier hmultiplier)
      (Units.ne_zero r)
  have hbeta : beta ≠ 0 := by
    exact div_ne_zero
      (actualBeta_ne_zero_of_candidateRegular
        a.multiplier a.a1 a.a2 a.a3 u xi
          hcoordinate hregular)
      (Units.ne_zero r)
  have hpTwo : p ≠ 2 := by omega
  have htwo : (2 : ZMod p) ≠ 0 :=
    two_ne_zero_zmod_of_prime_ne_two p hpTwo
  have hchar : ringChar (ZMod p) ≠ 2 := by
    exact (ZMod.ringChar_zmod_n p).substr hpTwo
  obtain ⟨omegaInv, homegaInv⟩ :=
    FiniteField.exists_nonsquare hchar
  have homegaInvZero : omegaInv ≠ 0 := by
    intro hzero
    apply homegaInv
    rw [hzero]
    exact IsSquare.zero
  have habsolute :
      ∀ d : ℕ, d ∣ Nat.card (ZMod p)ˣ → 0 < d →
        SevenHyperellipticPlanesAbsolutelyIrreducible
          (orbitComponentPlusCosetPulledRadicand
            alpha gamma k d)
          (orbitComponentMinusCosetPulledRadicand
            alpha gamma k d)
          (Polynomial.C omegaInv *
            centeredNormPulledRadicand a.a3 a.a1 d) := by
    intro d hdvd hd
    exact
      orbitConnectingSevenScaledHyperellipticPlanes_absolutelyIrreducible
        htwo hA1 hA2 hA3 hmoving hregular hobstruction
          halpha hproduct hgamma hsquareProduct hd
          (natCast_ne_zero_zmod_of_dvd_card_units p d hd hdvd)
          homegaInvZero
  obtain ⟨v, w, hwTrace, hvOrder, hwRegular, hwP⟩ :=
    hselect alpha beta gamma k omegaInv halpha
      (by simpa [xi] using hproduct)
      (by simpa [xi] using hgamma)
      hsquareProduct homegaInvZero habsolute
  obtain ⟨s, hsTrace⟩ :=
    exists_squareCosetParameter_of_orbitConnectingThreeRootWitness
      htwo halpha hbeta hsquareProduct w.1
  have hqTop : Subgroup.zpowers q = ⊤ :=
    zpowers_eq_top_of_orderOf_eq_natCard q hqOrder
  have hsqSubgroup :
      Subgroup.zpowers (q ^ 2) = Subgroup.square (ZMod p)ˣ :=
    zpowers_sq_eq_square_of_zpowers_eq_top q hqTop
  have hsMem : s ^ 2 ∈ Subgroup.zpowers (q ^ 2) := by
    rw [hsqSubgroup, Subgroup.mem_square]
    exact ⟨s, by simp [pow_two]⟩
  let h : Subgroup.zpowers (q ^ 2) := ⟨s ^ 2, hsMem⟩
  obtain ⟨n, hn⟩ :=
    exists_iterate_fiberPoint1_eq_mul_zpowers_sq
      a u xi q r hD
        heigenXi hcoordinate h
  have hySolution :
      IsSolution a
        (fiberPoint1 a u xi (q : ZMod p)
          ((r * s ^ 2 : (ZMod p)ˣ) : ZMod p)) :=
    fiberPoint1_isSolution
      a u xi (q : ZMod p)
        ((r * s ^ 2 : (ZMod p)ˣ) : ZMod p)
      hD (Units.ne_zero q) (Units.ne_zero (r * s ^ 2))
      (by
        simpa only [splitTorusTrace, Units.val_inv_eq_inv_val] using
          heigenXi)
      hcoordinate
  let y : SolutionSurface a :=
    ⟨fiberPoint1 a u xi (q : ZMod p)
      ((r * s ^ 2 : (ZMod p)ˣ) : ZMod p), hySolution⟩
  have hxy : SameVietaComponent x y := by
    apply sameVietaComponent_of_iterate_rotation1 a x y n
    rw [← hrPoint]
    simpa [y, h] using hn
  have hyTraceMiddle :
      traceAt a .second y.1 = w.1.middle := by
    change
      orderedTrace a.multiplier a.a2
          (fiberPoint1 a u xi (q : ZMod p)
            ((r * s ^ 2 : (ZMod p)ˣ) : ZMod p)).x2 =
        w.1.middle
    rw [show
      ((r * s ^ 2 : (ZMod p)ˣ) : ZMod p) =
        (r : ZMod p) * ((s ^ 2 : (ZMod p)ˣ) : ZMod p) by
          rfl]
    calc
      orderedTrace a.multiplier a.a2
          (fiberPoint1 a u xi (q : ZMod p)
            ((r : ZMod p) * ((s ^ 2 : (ZMod p)ˣ) : ZMod p))).x2 =
          weightedSplitTorusTrace alpha beta (s ^ 2) + gamma := by
        simpa only [alpha, beta, gamma, Units.val_mul] using
          orderedTrace_fiberPoint1_mul_eq_weightedSplitTorusTrace
            a u xi q r (s ^ 2)
      _ = w.1.middle := hsTrace
  have hyTrace :
      traceAt a .second y.1 = splitTorusTrace v :=
    hyTraceMiddle.trans hwTrace
  have hyRegular :
      OrderedTraceCandidateRegular
        a.a2 a.a3 a.a1 (traceAt a .second y.1) := by
    rw [hyTraceMiddle]
    exact hwRegular
  have hyConnecting :
      ¬ IsSquare
        (centeredNorm a.a3 a.a1
          (traceAt a .second y.1)) := by
    rw [hyTraceMiddle]
    exact
      centeredNorm_not_isSquare_of_orbitConnectingGoodThreeRootWitness
        homegaInv w
  have hyP : P (traceAt a .second y.1) := by
    rw [hyTraceMiddle]
    exact hwP
  have hcardUnits : Nat.card (ZMod p)ˣ = p - 1 := by
    rw [Nat.card_units, Nat.card_zmod]
  have hvOrderCard : orderOf v = Nat.card (ZMod p)ˣ :=
    hvOrder.trans hcardUnits.symm
  exact
    ⟨y, hxy, v, hyTrace, hvOrderCard, hyRegular, hyP, hyConnecting⟩

/-- Pointwise orbit-connecting step in the square centered-norm case.

The output is reached inside the actual `rotation1` square coset of the
given endpoint.  Its second-axis trace is primitive, candidate-regular in
the exact frame `(a₂,a₃,a₁)`, and connecting for the next fiber. -/
theorem
    exists_sameVietaComponent_primitiveRegularConnectingAxisTwo_of_square_of_explicitInequality
    (p : ℕ) [Fact p.Prime] (hpFive : 5 ≤ p)
    (a : Coefficients (ZMod p))
    (hA1 : a.a1 ^ 2 ≠ 4)
    (hA2 : a.a2 ^ 2 ≠ 4)
    (hA3 : a.a3 ^ 2 ≠ 4)
    (hmoving : (a.a3, a.a1) ≠ (0, 0))
    (x : SolutionSurface a)
    (hx : IsCageReadyCanonicalFirstAxisPrimitiveSplit p a x)
    (hsquare :
      IsSquare
        (centeredNorm a.a2 a.a3 (traceAt a .first x.1)))
    (hexplicit :
      ((Nat.card (ZMod p)ˣ).divisors.card : ℝ) ^ 2 *
          (952 * Real.sqrt (p : ℝ)) < p) :
    ∃ y : SolutionSurface a,
      SameVietaComponent x y ∧
        ∃ v : (ZMod p)ˣ,
          traceAt a .second y.1 = splitTorusTrace v ∧
            orderOf v = Nat.card (ZMod p)ˣ ∧
              OrderedTraceCandidateRegular
                a.a2 a.a3 a.a1 (traceAt a .second y.1) ∧
                ¬ IsSquare
                  (centeredNorm a.a3 a.a1
                    (traceAt a .second y.1)) := by
  obtain ⟨y, hxy, v, hyTrace, hvOrder, hyRegular, _, hyConnecting⟩ :=
    exists_axisTwo_of_orbitConnectingWitnessSelector
      p hpFive a hA1 hA2 hA3 hmoving x hx hsquare
        (fun _ => True)
        (by
          intro alpha beta gamma k omegaInv
            halpha hproduct hgamma hsquareProduct
            homegaInvZero habsolute
          obtain ⟨v, w, hwTrace, hvOrder, hwRegular⟩ :=
            exists_primitive_candidateRegular_orbitConnectingGoodThreeRootWitness_of_explicitInequality
              p hpFive a.a2 a.a3 a.a1
                alpha gamma k omegaInv a.a3 a.a1
                hA2 hA3 homegaInvZero habsolute hexplicit
          exact
            ⟨v, w, hwTrace, hvOrder, hwRegular, trivial⟩)
  exact ⟨y, hxy, v, hyTrace, hvOrder, hyRegular, hyConnecting⟩

private theorem exists_axisThree_of_orbitConnectingWitnessSelector
    (p : ℕ) [Fact p.Prime] (hpFive : 5 ≤ p)
    (a : Coefficients (ZMod p))
    (hA1 : a.a1 ^ 2 ≠ 4)
    (hA2 : a.a2 ^ 2 ≠ 4)
    (hA3 : a.a3 ^ 2 ≠ 4)
    (hmoving : (a.a1, a.a2) ≠ (0, 0))
    (x : SolutionSurface a)
    (hx : IsCageReadyCanonicalFirstAxisPrimitiveSplit p a x)
    (hsquare :
      IsSquare
        (centeredNorm a.a2 a.a3 (traceAt a .first x.1)))
    (P : ZMod p → Prop)
    (hselect :
      ∀ (alpha beta gamma k omegaInv : ZMod p),
        alpha ≠ 0 →
        alpha * beta =
          orderedTraceSigma a.a1 a.a3 a.a2
            (traceAt a .first x.1) →
        gamma =
          orderedTraceGamma a.a1 a.a3 a.a2
            (traceAt a .first x.1) →
        alpha * beta = k ^ 2 →
        omegaInv ≠ 0 →
        (∀ d : ℕ, d ∣ Nat.card (ZMod p)ˣ → 0 < d →
          SevenHyperellipticPlanesAbsolutelyIrreducible
            (orbitComponentPlusCosetPulledRadicand
              alpha gamma k d)
            (orbitComponentMinusCosetPulledRadicand
              alpha gamma k d)
            (Polynomial.C omegaInv *
              centeredNormPulledRadicand a.a2 a.a1 d)) →
        ∃ v : (ZMod p)ˣ,
          ∃ w :
              OrbitConnectingGoodThreeRootWitness
                alpha gamma k omegaInv a.a2 a.a1,
            w.1.middle = splitTorusTrace v ∧
              orderOf v = p - 1 ∧
                OrderedTraceCandidateRegular
                  a.a3 a.a1 a.a2 w.1.middle ∧
                  P w.1.middle) :
    ∃ y : SolutionSurface a,
      SameVietaComponent x y ∧
        ∃ v : (ZMod p)ˣ,
          traceAt a .third y.1 = splitTorusTrace v ∧
            orderOf v = Nat.card (ZMod p)ˣ ∧
              OrderedTraceCandidateRegular
                a.a3 a.a1 a.a2 (traceAt a .third y.1) ∧
                P (traceAt a .third y.1) ∧
                  ¬ IsSquare
                    (centeredNorm a.a1 a.a2
                      (traceAt a .third y.1)) := by
  obtain ⟨q, heigen, hqOrder, hready⟩ := hx
  let u : ZMod p := x.1.x1
  let xi : ZMod p := traceAt a .first x.1
  have heigenXi : xi = splitTorusTrace q := heigen
  have hcoordinate :
      xi = orderedTrace a.multiplier a.a1 u := by
    rfl
  have hregularDirect :
      OrderedTraceCandidateRegular a.a1 a.a2 a.a3 xi := by
    simpa [xi] using hready.1
  have hregular :
      OrderedTraceCandidateRegular a.a1 a.a3 a.a2 xi := by
    simpa [xi] using hready.2.1
  have hobstruction :
      incidenceCenteredNormObstruction
        (reverseFirstAxisMovingCoefficients a) xi ≠ 0 := by
    simpa [xi] using hready.2.2.2
  have hD : discriminant xi ≠ 0 := by
    simpa [discriminant] using hregular.1
  have hconic :
      fiberConic a.a2 a.a3 u xi x.1.x2 x.1.x3 = 0 := by
    have hsurface := x.property
    rw [IsSolution, polynomial_fixed_first] at hsurface
    simpa [u, xi, traceAt, orderedTrace] using hsurface
  obtain ⟨r, hrPair⟩ :=
    exists_unit_fiberPair_eq_of_candidateRegular
      a.multiplier a.a1 a.a2 a.a3 u xi q
        (x.1.x2, x.1.x3) hconic hcoordinate
        heigenXi hregularDirect
  have hrPoint :
      fiberPoint1 a u xi (q : ZMod p) (r : ZMod p) = x.1 := by
    apply Point.ext
    · rfl
    · exact congrArg Prod.fst hrPair
    · exact congrArg Prod.snd hrPair
  let alpha : ZMod p :=
    (a.multiplier * (q : ZMod p)) * (r : ZMod p)
  let beta : ZMod p :=
    (a.multiplier *
      centeredFiberProduct a.a2 a.a3 u xi / (q : ZMod p)) /
        (r : ZMod p)
  let gamma : ZMod p :=
    actualGammaSecond a.multiplier a.a2 a.a3 u xi
  have hproduct :
      alpha * beta =
        orderedTraceSigma a.a1 a.a3 a.a2 xi := by
    calc
      alpha * beta =
          actualSigma a.multiplier a.a2 a.a3 u xi := by
        simpa [alpha, beta] using
          actual_secondDirected_coset_weights_mul
            a.multiplier a.a2 a.a3 u xi q r
      _ = orderedTraceSigma a.a1 a.a2 a.a3 xi :=
        actualSigma_eq_orderedTraceSigma
          a.multiplier a.a1 a.a2 a.a3 u xi hcoordinate
      _ = orderedTraceSigma a.a1 a.a3 a.a2 xi :=
        orderedTraceSigma_swap a.a1 a.a2 a.a3 xi
  have hgamma :
      gamma = orderedTraceGamma a.a1 a.a3 a.a2 xi := by
    exact actualGammaSecond_eq_orderedTraceGamma
      a.multiplier a.a1 a.a2 a.a3 u xi hD hcoordinate
  have hnormReverse :
      IsSquare (centeredNorm a.a3 a.a2 xi) := by
    have hnormEq :
        centeredNorm a.a3 a.a2 xi =
          centeredNorm a.a2 a.a3 xi := by
      simp only [centeredNorm, discriminant]
      ring
    rw [hnormEq]
    simpa [xi] using hsquare
  have hsigmaSquare :
      IsSquare (orderedTraceSigma a.a1 a.a3 a.a2 xi) :=
    orderedTraceSigma_isSquare_of_centeredNorm
      a.a1 a.a3 a.a2 xi
        (by
          simpa only [eval_orderedTraceDiscriminantPolynomial] using
            hregular.1)
        hnormReverse
  obtain ⟨k, hk⟩ := hsigmaSquare
  have hsquareProduct : alpha * beta = k ^ 2 := by
    calc
      alpha * beta =
          orderedTraceSigma a.a1 a.a3 a.a2 xi := hproduct
      _ = k ^ 2 := by simpa [pow_two] using hk
  have hmultiplier : a.multiplier ≠ 0 := by
    intro hzero
    apply hregularDirect.sigma_ne_zero
    rw [← actualSigma_eq_orderedTraceSigma
      a.multiplier a.a1 a.a2 a.a3 u xi hcoordinate]
    simp [actualSigma, actualAlpha, actualBeta, hzero]
  have halpha : alpha ≠ 0 := by
    exact mul_ne_zero
      (mul_ne_zero hmultiplier (Units.ne_zero q))
      (Units.ne_zero r)
  have hbeta : beta ≠ 0 := by
    intro hbetaZero
    apply hregular.sigma_ne_zero
    rw [← hproduct]
    simp [hbetaZero]
  have hpTwo : p ≠ 2 := by omega
  have htwo : (2 : ZMod p) ≠ 0 :=
    two_ne_zero_zmod_of_prime_ne_two p hpTwo
  have hchar : ringChar (ZMod p) ≠ 2 := by
    exact (ZMod.ringChar_zmod_n p).substr hpTwo
  obtain ⟨omegaInv, homegaInv⟩ :=
    FiniteField.exists_nonsquare hchar
  have homegaInvZero : omegaInv ≠ 0 := by
    intro hzero
    apply homegaInv
    rw [hzero]
    exact IsSquare.zero
  have hmovingReverse : (a.a2, a.a1) ≠ (0, 0) := by
    intro hzero
    apply hmoving
    apply Prod.ext
    · exact congrArg Prod.snd hzero
    · exact congrArg Prod.fst hzero
  have habsolute :
      ∀ d : ℕ, d ∣ Nat.card (ZMod p)ˣ → 0 < d →
        SevenHyperellipticPlanesAbsolutelyIrreducible
          (orbitComponentPlusCosetPulledRadicand
            alpha gamma k d)
          (orbitComponentMinusCosetPulledRadicand
            alpha gamma k d)
          (Polynomial.C omegaInv *
            centeredNormPulledRadicand a.a2 a.a1 d) := by
    intro d hdvd hd
    exact
      orbitConnectingSevenScaledHyperellipticPlanes_absolutelyIrreducible
        (a := reverseFirstAxisMovingCoefficients a)
        htwo hA1 hA3 hA2 hmovingReverse hregular hobstruction
          halpha hproduct hgamma hsquareProduct hd
          (natCast_ne_zero_zmod_of_dvd_card_units p d hd hdvd)
          homegaInvZero
  obtain ⟨v, w, hwTrace, hvOrder, hwRegular, hwP⟩ :=
    hselect alpha beta gamma k omegaInv halpha
      (by simpa [xi] using hproduct)
      (by simpa [xi] using hgamma)
      hsquareProduct homegaInvZero habsolute
  obtain ⟨s, hsTrace⟩ :=
    exists_squareCosetParameter_of_orbitConnectingThreeRootWitness
      htwo halpha hbeta hsquareProduct w.1
  have hqTop : Subgroup.zpowers q = ⊤ :=
    zpowers_eq_top_of_orderOf_eq_natCard q hqOrder
  have hsqSubgroup :
      Subgroup.zpowers (q ^ 2) = Subgroup.square (ZMod p)ˣ :=
    zpowers_sq_eq_square_of_zpowers_eq_top q hqTop
  have hsMem : s ^ 2 ∈ Subgroup.zpowers (q ^ 2) := by
    rw [hsqSubgroup, Subgroup.mem_square]
    exact ⟨s, by simp [pow_two]⟩
  let h : Subgroup.zpowers (q ^ 2) := ⟨s ^ 2, hsMem⟩
  obtain ⟨n, hn⟩ :=
    exists_iterate_fiberPoint1_eq_mul_zpowers_sq
      a u xi q r hD heigenXi hcoordinate h
  have hySolution :
      IsSolution a
        (fiberPoint1 a u xi (q : ZMod p)
          ((r * s ^ 2 : (ZMod p)ˣ) : ZMod p)) :=
    fiberPoint1_isSolution
      a u xi (q : ZMod p)
        ((r * s ^ 2 : (ZMod p)ˣ) : ZMod p)
      hD (Units.ne_zero q) (Units.ne_zero (r * s ^ 2))
      (by
        simpa only [splitTorusTrace, Units.val_inv_eq_inv_val] using
          heigenXi)
      hcoordinate
  let y : SolutionSurface a :=
    ⟨fiberPoint1 a u xi (q : ZMod p)
      ((r * s ^ 2 : (ZMod p)ˣ) : ZMod p), hySolution⟩
  have hxy : SameVietaComponent x y := by
    apply sameVietaComponent_of_iterate_rotation1 a x y n
    rw [← hrPoint]
    simpa [y, h] using hn
  have hyTraceMiddle :
      traceAt a .third y.1 = w.1.middle := by
    change
      a.multiplier *
          (fiberPair a.a2 a.a3 u xi (q : ZMod p)
            ((r * s ^ 2 : (ZMod p)ˣ) : ZMod p)).2 -
          a.a3 =
        w.1.middle
    rw [show
      ((r * s ^ 2 : (ZMod p)ˣ) : ZMod p) =
        (r : ZMod p) * ((s ^ 2 : (ZMod p)ˣ) : ZMod p) by
          rfl]
    calc
      a.multiplier *
            (fiberPair a.a2 a.a3 u xi (q : ZMod p)
              ((r : ZMod p) *
                ((s ^ 2 : (ZMod p)ˣ) : ZMod p))).2 -
          a.a3 =
          weightedSplitTorusTrace alpha beta (s ^ 2) + gamma := by
        simpa only [alpha, beta, gamma, Units.val_mul] using
          secondTrace_fiberPair_mul_eq_weightedSplitTorusTrace
            a.multiplier a.a2 a.a3 u xi q r (s ^ 2)
      _ = w.1.middle := hsTrace
  have hyTrace :
      traceAt a .third y.1 = splitTorusTrace v :=
    hyTraceMiddle.trans hwTrace
  have hyRegular :
      OrderedTraceCandidateRegular
        a.a3 a.a1 a.a2 (traceAt a .third y.1) := by
    rw [hyTraceMiddle]
    exact hwRegular
  have hyConnecting :
      ¬ IsSquare
        (centeredNorm a.a1 a.a2
          (traceAt a .third y.1)) := by
    rw [hyTraceMiddle]
    have hwConnecting :
        ¬ IsSquare (centeredNorm a.a2 a.a1 w.1.middle) :=
      centeredNorm_not_isSquare_of_orbitConnectingGoodThreeRootWitness
        homegaInv w
    have hnormEq :
        centeredNorm a.a1 a.a2 w.1.middle =
          centeredNorm a.a2 a.a1 w.1.middle := by
      simp only [centeredNorm, discriminant]
      ring
    rw [hnormEq]
    exact hwConnecting
  have hyP : P (traceAt a .third y.1) := by
    rw [hyTraceMiddle]
    exact hwP
  have hcardUnits : Nat.card (ZMod p)ˣ = p - 1 := by
    rw [Nat.card_units, Nat.card_zmod]
  have hvOrderCard : orderOf v = Nat.card (ZMod p)ˣ :=
    hvOrder.trans hcardUnits.symm
  exact
    ⟨y, hxy, v, hyTrace, hvOrderCard, hyRegular, hyP, hyConnecting⟩

/-- Reverse pointwise orbit-connecting step.  The target is the third
coordinate, so the ordered source frame is `(a₁,a₃,a₂)` and the outgoing
frame is `(a₃,a₁,a₂)`.  The coefficient triple and the point are never
permuted; the reversed coefficient record is used only in the geometric
square-class theorem. -/
theorem
    exists_sameVietaComponent_primitiveRegularConnectingAxisThree_of_square_of_explicitInequality
    (p : ℕ) [Fact p.Prime] (hpFive : 5 ≤ p)
    (a : Coefficients (ZMod p))
    (hA1 : a.a1 ^ 2 ≠ 4)
    (hA2 : a.a2 ^ 2 ≠ 4)
    (hA3 : a.a3 ^ 2 ≠ 4)
    (hmoving : (a.a1, a.a2) ≠ (0, 0))
    (x : SolutionSurface a)
    (hx : IsCageReadyCanonicalFirstAxisPrimitiveSplit p a x)
    (hsquare :
      IsSquare
        (centeredNorm a.a2 a.a3 (traceAt a .first x.1)))
    (hexplicit :
      ((Nat.card (ZMod p)ˣ).divisors.card : ℝ) ^ 2 *
          (952 * Real.sqrt (p : ℝ)) < p) :
    ∃ y : SolutionSurface a,
      SameVietaComponent x y ∧
        ∃ v : (ZMod p)ˣ,
          traceAt a .third y.1 = splitTorusTrace v ∧
            orderOf v = Nat.card (ZMod p)ˣ ∧
              OrderedTraceCandidateRegular
                a.a3 a.a1 a.a2 (traceAt a .third y.1) ∧
                ¬ IsSquare
                  (centeredNorm a.a1 a.a2
                    (traceAt a .third y.1)) := by
  obtain ⟨y, hxy, v, hyTrace, hvOrder, hyRegular, _, hyConnecting⟩ :=
    exists_axisThree_of_orbitConnectingWitnessSelector
      p hpFive a hA1 hA2 hA3 hmoving x hx hsquare
        (fun _ => True)
        (by
          intro alpha beta gamma k omegaInv
            halpha hproduct hgamma hsquareProduct
            homegaInvZero habsolute
          obtain ⟨v, w, hwTrace, hvOrder, hwRegular⟩ :=
            exists_primitive_candidateRegular_orbitConnectingGoodThreeRootWitness_of_explicitInequality
              p hpFive a.a3 a.a1 a.a2
                alpha gamma k omegaInv a.a2 a.a1
                hA3 hA1 homegaInvZero habsolute hexplicit
          exact
            ⟨v, w, hwTrace, hvOrder, hwRegular, trivial⟩)
  exact ⟨y, hxy, v, hyTrace, hvOrder, hyRegular, hyConnecting⟩

/-- The first-to-second square normalization with the extra obstruction
needed to use its output as an endpoint of a later incidence relay. -/
theorem
    exists_sameVietaComponent_obstructionReadyPrimitiveConnectingAxisTwo_of_square_of_explicitInequality
    (p : ℕ) [Fact p.Prime] (hpFive : 5 ≤ p)
    (a : Coefficients (ZMod p))
    (hA1 : a.a1 ^ 2 ≠ 4)
    (hA2 : a.a2 ^ 2 ≠ 4)
    (hA3 : a.a3 ^ 2 ≠ 4)
    (hmoving : (a.a3, a.a1) ≠ (0, 0))
    (x : SolutionSurface a)
    (hx : IsCageReadyCanonicalFirstAxisPrimitiveSplit p a x)
    (hsquare :
      IsSquare
        (centeredNorm a.a2 a.a3 (traceAt a .first x.1)))
    (hexplicit :
      ((Nat.card (ZMod p)ˣ).divisors.card : ℝ) ^ 2 *
          (984 * Real.sqrt (p : ℝ)) < p) :
    ∃ y : SolutionSurface a,
      SameVietaComponent x y ∧
        ∃ v : (ZMod p)ˣ,
          traceAt a .second y.1 = splitTorusTrace v ∧
            orderOf v = Nat.card (ZMod p)ˣ ∧
              OrderedTraceCandidateRegular
                a.a2 a.a3 a.a1 (traceAt a .second y.1) ∧
                incidenceCenteredNormObstruction
                  (directedCycleLeftCoefficients a)
                    (traceAt a .second y.1) ≠ 0 ∧
                  ¬ IsSquare
                    (centeredNorm a.a3 a.a1
                      (traceAt a .second y.1)) := by
  exact
    exists_axisTwo_of_orbitConnectingWitnessSelector
      p hpFive a hA1 hA2 hA3 hmoving x hx hsquare
        (fun t =>
          incidenceCenteredNormObstruction
            (directedCycleLeftCoefficients a) t ≠ 0)
        (by
          intro alpha beta gamma k omegaInv _ _ _ _
            homegaInvZero habsolute
          obtain
              ⟨v, w, hwTrace, hvOrder, hwRegular, hwObstruction⟩ :=
            exists_primitive_obstructionReady_orbitConnectingGoodThreeRootWitness_of_explicitInequality
              p hpFive (directedCycleLeftCoefficients a)
                alpha gamma k omegaInv a.a3 a.a1
                (by simpa [directedCycleLeftCoefficients] using hA2)
                (by simpa [directedCycleLeftCoefficients] using hA3)
                homegaInvZero habsolute hexplicit
          exact
            ⟨v, w, hwTrace, hvOrder,
              by
                simpa [directedCycleLeftCoefficients] using hwRegular,
              hwObstruction⟩)

/-- The reverse first-to-third square normalization with the extra
target-frame incidence obstruction. -/
theorem
    exists_sameVietaComponent_obstructionReadyPrimitiveConnectingAxisThree_of_square_of_explicitInequality
    (p : ℕ) [Fact p.Prime] (hpFive : 5 ≤ p)
    (a : Coefficients (ZMod p))
    (hA1 : a.a1 ^ 2 ≠ 4)
    (hA2 : a.a2 ^ 2 ≠ 4)
    (hA3 : a.a3 ^ 2 ≠ 4)
    (hmoving : (a.a1, a.a2) ≠ (0, 0))
    (x : SolutionSurface a)
    (hx : IsCageReadyCanonicalFirstAxisPrimitiveSplit p a x)
    (hsquare :
      IsSquare
        (centeredNorm a.a2 a.a3 (traceAt a .first x.1)))
    (hexplicit :
      ((Nat.card (ZMod p)ˣ).divisors.card : ℝ) ^ 2 *
          (984 * Real.sqrt (p : ℝ)) < p) :
    ∃ y : SolutionSurface a,
      SameVietaComponent x y ∧
        ∃ v : (ZMod p)ˣ,
          traceAt a .third y.1 = splitTorusTrace v ∧
            orderOf v = Nat.card (ZMod p)ˣ ∧
              OrderedTraceCandidateRegular
                a.a3 a.a1 a.a2 (traceAt a .third y.1) ∧
                incidenceCenteredNormObstruction
                  (directedCycleRightCoefficients a)
                    (traceAt a .third y.1) ≠ 0 ∧
                  ¬ IsSquare
                    (centeredNorm a.a1 a.a2
                      (traceAt a .third y.1)) := by
  exact
    exists_axisThree_of_orbitConnectingWitnessSelector
      p hpFive a hA1 hA2 hA3 hmoving x hx hsquare
        (fun t =>
          incidenceCenteredNormObstruction
            (directedCycleRightCoefficients a) t ≠ 0)
        (by
          intro alpha beta gamma k omegaInv _ _ _ _
            homegaInvZero habsolute
          obtain
              ⟨v, w, hwTrace, hvOrder, hwRegular, hwObstruction⟩ :=
            exists_primitive_obstructionReady_orbitConnectingGoodThreeRootWitness_of_explicitInequality
              p hpFive (directedCycleRightCoefficients a)
                alpha gamma k omegaInv a.a2 a.a1
                (by simpa [directedCycleRightCoefficients] using hA3)
                (by simpa [directedCycleRightCoefficients] using hA1)
                homegaInvZero habsolute hexplicit
          exact
            ⟨v, w, hwTrace, hvOrder,
              by
                simpa [directedCycleRightCoefficients] using hwRegular,
              hwObstruction⟩)

/-- A prescribed obstruction-ready reference trace in the second-axis
frame can be joined to the newly normalized endpoint by a full connecting
incidence pair. -/
theorem
    exists_sameVietaComponent_primitiveConnectingPairAxisTwo_of_square_of_explicitInequality
    (p : ℕ) [Fact p.Prime] (hpFive : 5 ≤ p)
    (a : Coefficients (ZMod p))
    (hA1 : a.a1 ^ 2 ≠ 4)
    (hA2 : a.a2 ^ 2 ≠ 4)
    (hA3 : a.a3 ^ 2 ≠ 4)
    (hmoving : (a.a3, a.a1) ≠ (0, 0))
    (eta : ZMod p)
    (hetaRegular :
      OrderedTraceCandidateRegular a.a2 a.a3 a.a1 eta)
    (hetaObstruction :
      incidenceCenteredNormObstruction
        (directedCycleLeftCoefficients a) eta ≠ 0)
    (x : SolutionSurface a)
    (hx : IsCageReadyCanonicalFirstAxisPrimitiveSplit p a x)
    (hsquare :
      IsSquare
        (centeredNorm a.a2 a.a3 (traceAt a .first x.1)))
    (hexplicit :
      ((Nat.card (ZMod p)ˣ).divisors.card : ℝ) ^ 2 *
          (1032 * Real.sqrt (p : ℝ)) < p) :
    ∃ y : SolutionSurface a,
      SameVietaComponent x y ∧
        ∃ v : (ZMod p)ˣ,
          traceAt a .second y.1 = splitTorusTrace v ∧
            orderOf v = Nat.card (ZMod p)ˣ ∧
              OrderedTraceCandidateRegular
                a.a2 a.a3 a.a1 (traceAt a .second y.1) ∧
                IsConnectingIncidencePair
                  (directedCycleLeftCoefficients a)
                    (traceAt a .second y.1) eta ∧
                  ¬ IsSquare
                    (centeredNorm a.a3 a.a1
                      (traceAt a .second y.1)) := by
  exact
    exists_axisTwo_of_orbitConnectingWitnessSelector
      p hpFive a hA1 hA2 hA3 hmoving x hx hsquare
        (fun t =>
          IsConnectingIncidencePair
            (directedCycleLeftCoefficients a) t eta)
        (by
          intro alpha beta gamma k omegaInv _ _ _ _
            homegaInvZero habsolute
          obtain ⟨v, w, hwTrace, hvOrder, hwRegular, hwPair⟩ :=
            exists_primitive_connectingPair_orbitConnectingGoodThreeRootWitness_of_explicitInequality
              p hpFive (directedCycleLeftCoefficients a) eta
                alpha gamma k omegaInv a.a3 a.a1
                (by simpa [directedCycleLeftCoefficients] using hA2)
                (by simpa [directedCycleLeftCoefficients] using hA3)
                (by
                  simpa [directedCycleLeftCoefficients] using
                    hetaRegular)
                hetaObstruction homegaInvZero habsolute hexplicit
          exact
            ⟨v, w, hwTrace, hvOrder,
              by
                simpa [directedCycleLeftCoefficients] using hwRegular,
              hwPair⟩)

/-- Reverse prescribed-reference form in the third-axis frame. -/
theorem
    exists_sameVietaComponent_primitiveConnectingPairAxisThree_of_square_of_explicitInequality
    (p : ℕ) [Fact p.Prime] (hpFive : 5 ≤ p)
    (a : Coefficients (ZMod p))
    (hA1 : a.a1 ^ 2 ≠ 4)
    (hA2 : a.a2 ^ 2 ≠ 4)
    (hA3 : a.a3 ^ 2 ≠ 4)
    (hmoving : (a.a1, a.a2) ≠ (0, 0))
    (eta : ZMod p)
    (hetaRegular :
      OrderedTraceCandidateRegular a.a3 a.a1 a.a2 eta)
    (hetaObstruction :
      incidenceCenteredNormObstruction
        (directedCycleRightCoefficients a) eta ≠ 0)
    (x : SolutionSurface a)
    (hx : IsCageReadyCanonicalFirstAxisPrimitiveSplit p a x)
    (hsquare :
      IsSquare
        (centeredNorm a.a2 a.a3 (traceAt a .first x.1)))
    (hexplicit :
      ((Nat.card (ZMod p)ˣ).divisors.card : ℝ) ^ 2 *
          (1032 * Real.sqrt (p : ℝ)) < p) :
    ∃ y : SolutionSurface a,
      SameVietaComponent x y ∧
        ∃ v : (ZMod p)ˣ,
          traceAt a .third y.1 = splitTorusTrace v ∧
            orderOf v = Nat.card (ZMod p)ˣ ∧
              OrderedTraceCandidateRegular
                a.a3 a.a1 a.a2 (traceAt a .third y.1) ∧
                IsConnectingIncidencePair
                  (directedCycleRightCoefficients a)
                    (traceAt a .third y.1) eta ∧
                  ¬ IsSquare
                    (centeredNorm a.a1 a.a2
                      (traceAt a .third y.1)) := by
  exact
    exists_axisThree_of_orbitConnectingWitnessSelector
      p hpFive a hA1 hA2 hA3 hmoving x hx hsquare
        (fun t =>
          IsConnectingIncidencePair
            (directedCycleRightCoefficients a) t eta)
        (by
          intro alpha beta gamma k omegaInv _ _ _ _
            homegaInvZero habsolute
          obtain ⟨v, w, hwTrace, hvOrder, hwRegular, hwPair⟩ :=
            exists_primitive_connectingPair_orbitConnectingGoodThreeRootWitness_of_explicitInequality
              p hpFive (directedCycleRightCoefficients a) eta
                alpha gamma k omegaInv a.a2 a.a1
                (by simpa [directedCycleRightCoefficients] using hA3)
                (by simpa [directedCycleRightCoefficients] using hA1)
                (by
                  simpa [directedCycleRightCoefficients] using
                    hetaRegular)
                hetaObstruction homegaInvZero habsolute hexplicit
          exact
            ⟨v, w, hwTrace, hvOrder,
              by
                simpa [directedCycleRightCoefficients] using hwRegular,
              hwPair⟩)

/-- Uniform sufficiently-large-prime form of the pointwise
orbit-connecting step. -/
theorem
    exists_threshold_cageReadyCanonicalFirstAxis_square_reaches_primitiveRegularConnectingAxisTwo :
    ∃ threshold : ℕ, ∀ p : ℕ, threshold ≤ p →
      [Fact p.Prime] →
      ∀ (a : Coefficients (ZMod p)),
        a.a1 ^ 2 ≠ 4 →
        a.a2 ^ 2 ≠ 4 →
        a.a3 ^ 2 ≠ 4 →
        (a.a3, a.a1) ≠ (0, 0) →
        ∀ x : SolutionSurface a,
          IsCageReadyCanonicalFirstAxisPrimitiveSplit p a x →
          IsSquare
            (centeredNorm a.a2 a.a3
              (traceAt a .first x.1)) →
          ∃ y : SolutionSurface a,
            SameVietaComponent x y ∧
              ∃ v : (ZMod p)ˣ,
                traceAt a .second y.1 = splitTorusTrace v ∧
                  orderOf v = Nat.card (ZMod p)ˣ ∧
                    OrderedTraceCandidateRegular
                      a.a2 a.a3 a.a1
                        (traceAt a .second y.1) ∧
                      ¬ IsSquare
                        (centeredNorm a.a3 a.a1
                          (traceAt a .second y.1)) := by
  obtain ⟨inequalityThreshold, hInequality⟩ :=
    exists_threshold_endgamePrimitiveTrace_explicitInequality
      952 (show (0 : ℝ) < 1 / 4 by norm_num)
  refine ⟨max inequalityThreshold 5, ?_⟩
  intro p hp _ a hA1 hA2 hA3 hmoving x hx hsquare
  have hpInequality : inequalityThreshold ≤ p :=
    (Nat.le_max_left inequalityThreshold 5).trans hp
  have hpFive : 5 ≤ p :=
    (Nat.le_max_right inequalityThreshold 5).trans hp
  have hpOneReal : (1 : ℝ) ≤ p := by
    exact_mod_cast (Fact.out : p.Prime).one_le
  have honeLe :
      (1 : ℝ) ≤ (p : ℝ) ^ ((1 : ℝ) / 2 - 1 / 4) := by
    simpa using Real.one_le_rpow hpOneReal
      (show (0 : ℝ) ≤ 1 / 2 - 1 / 4 by norm_num)
  have honeLeNatCast :
      ((1 : ℕ) : ℝ) ≤
        (p : ℝ) ^ ((1 : ℝ) / 2 - 1 / 4) := by
    simpa using honeLe
  have hexplicit := hInequality p hpInequality 1 honeLeNatCast
  have hcard : Nat.card (ZMod p)ˣ = p - 1 := by
    rw [Nat.card_units, Nat.card_zmod]
  apply
    exists_sameVietaComponent_primitiveRegularConnectingAxisTwo_of_square_of_explicitInequality
      p hpFive a hA1 hA2 hA3 hmoving x hx hsquare
  rw [hcard]
  simpa using hexplicit

/-- Uniform sufficiently-large-prime form of the reverse first-to-third
orbit-connecting step. -/
theorem
    exists_threshold_cageReadyCanonicalFirstAxis_square_reaches_primitiveRegularConnectingAxisThree :
    ∃ threshold : ℕ, ∀ p : ℕ, threshold ≤ p →
      [Fact p.Prime] →
      ∀ (a : Coefficients (ZMod p)),
        a.a1 ^ 2 ≠ 4 →
        a.a2 ^ 2 ≠ 4 →
        a.a3 ^ 2 ≠ 4 →
        (a.a1, a.a2) ≠ (0, 0) →
        ∀ x : SolutionSurface a,
          IsCageReadyCanonicalFirstAxisPrimitiveSplit p a x →
          IsSquare
            (centeredNorm a.a2 a.a3
              (traceAt a .first x.1)) →
          ∃ y : SolutionSurface a,
            SameVietaComponent x y ∧
              ∃ v : (ZMod p)ˣ,
                traceAt a .third y.1 = splitTorusTrace v ∧
                  orderOf v = Nat.card (ZMod p)ˣ ∧
                    OrderedTraceCandidateRegular
                      a.a3 a.a1 a.a2
                        (traceAt a .third y.1) ∧
                      ¬ IsSquare
                        (centeredNorm a.a1 a.a2
                          (traceAt a .third y.1)) := by
  obtain ⟨inequalityThreshold, hInequality⟩ :=
    exists_threshold_endgamePrimitiveTrace_explicitInequality
      952 (show (0 : ℝ) < 1 / 4 by norm_num)
  refine ⟨max inequalityThreshold 5, ?_⟩
  intro p hp _ a hA1 hA2 hA3 hmoving x hx hsquare
  have hpInequality : inequalityThreshold ≤ p :=
    (Nat.le_max_left inequalityThreshold 5).trans hp
  have hpFive : 5 ≤ p :=
    (Nat.le_max_right inequalityThreshold 5).trans hp
  have hpOneReal : (1 : ℝ) ≤ p := by
    exact_mod_cast (Fact.out : p.Prime).one_le
  have honeLe :
      ((1 : ℕ) : ℝ) ≤
        (p : ℝ) ^ ((1 : ℝ) / 2 - 1 / 4) := by
    simpa using Real.one_le_rpow hpOneReal
      (show (0 : ℝ) ≤ 1 / 2 - 1 / 4 by norm_num)
  have hexplicit := hInequality p hpInequality 1 honeLe
  have hcard : Nat.card (ZMod p)ˣ = p - 1 := by
    rw [Nat.card_units, Nat.card_zmod]
  apply
    exists_sameVietaComponent_primitiveRegularConnectingAxisThree_of_square_of_explicitInequality
      p hpFive a hA1 hA2 hA3 hmoving x hx hsquare
  rw [hcard]
  simpa using hexplicit

/-- Uniform large-prime first-to-second square normalization whose output
is ready to serve as an incidence endpoint. -/
theorem
    exists_threshold_cageReadyCanonicalFirstAxis_square_reaches_obstructionReadyPrimitiveConnectingAxisTwo :
    ∃ threshold : ℕ, ∀ p : ℕ, threshold ≤ p →
      [Fact p.Prime] →
      ∀ (a : Coefficients (ZMod p)),
        a.a1 ^ 2 ≠ 4 →
        a.a2 ^ 2 ≠ 4 →
        a.a3 ^ 2 ≠ 4 →
        (a.a3, a.a1) ≠ (0, 0) →
        ∀ x : SolutionSurface a,
          IsCageReadyCanonicalFirstAxisPrimitiveSplit p a x →
          IsSquare
            (centeredNorm a.a2 a.a3
              (traceAt a .first x.1)) →
          ∃ y : SolutionSurface a,
            SameVietaComponent x y ∧
              ∃ v : (ZMod p)ˣ,
                traceAt a .second y.1 = splitTorusTrace v ∧
                  orderOf v = Nat.card (ZMod p)ˣ ∧
                    OrderedTraceCandidateRegular
                      a.a2 a.a3 a.a1
                        (traceAt a .second y.1) ∧
                      incidenceCenteredNormObstruction
                        (directedCycleLeftCoefficients a)
                          (traceAt a .second y.1) ≠ 0 ∧
                        ¬ IsSquare
                          (centeredNorm a.a3 a.a1
                            (traceAt a .second y.1)) := by
  refine ⟨GenMarkoff.General.Explicit.analyticCutoff, ?_⟩
  intro p hp _ a hA1 hA2 hA3 hmoving x hx hsquare
  have hpFive : 5 ≤ p :=
    GenMarkoff.General.Explicit.five_le_analyticCutoff.trans hp
  have hexplicit :=
    GenMarkoff.General.Explicit.primitiveTrace_explicitInequality_one
      hp (coefficient := 984) (by norm_num)
  have hcard : Nat.card (ZMod p)ˣ = p - 1 := by
    rw [Nat.card_units, Nat.card_zmod]
  exact
    exists_axisTwo_of_orbitConnectingWitnessSelector
      p hpFive a hA1 hA2 hA3 hmoving x hx hsquare
        (fun t =>
          incidenceCenteredNormObstruction
            (directedCycleLeftCoefficients a) t ≠ 0)
        (by
          intro alpha beta gamma k omegaInv _ _ _ _
            homegaInvZero habsolute
          obtain
              ⟨v, w, hwTrace, hvOrder, hwRegular, hwObstruction⟩ :=
            exists_primitive_obstructionReady_orbitConnectingGoodThreeRootWitness_of_explicitInequality
              p hpFive (directedCycleLeftCoefficients a)
              alpha gamma k omegaInv a.a3 a.a1
              (by simpa [directedCycleLeftCoefficients] using hA2)
              (by simpa [directedCycleLeftCoefficients] using hA3)
              homegaInvZero habsolute
              (by rw [hcard]; simpa using hexplicit)
          exact
            ⟨v, w, hwTrace, hvOrder,
              by
                simpa [directedCycleLeftCoefficients] using hwRegular,
              hwObstruction⟩)

/-- Uniform large-prime reverse first-to-third square normalization whose
output is incidence-obstruction ready. -/
theorem
    exists_threshold_cageReadyCanonicalFirstAxis_square_reaches_obstructionReadyPrimitiveConnectingAxisThree :
    ∃ threshold : ℕ, ∀ p : ℕ, threshold ≤ p →
      [Fact p.Prime] →
      ∀ (a : Coefficients (ZMod p)),
        a.a1 ^ 2 ≠ 4 →
        a.a2 ^ 2 ≠ 4 →
        a.a3 ^ 2 ≠ 4 →
        (a.a1, a.a2) ≠ (0, 0) →
        ∀ x : SolutionSurface a,
          IsCageReadyCanonicalFirstAxisPrimitiveSplit p a x →
          IsSquare
            (centeredNorm a.a2 a.a3
              (traceAt a .first x.1)) →
          ∃ y : SolutionSurface a,
            SameVietaComponent x y ∧
              ∃ v : (ZMod p)ˣ,
                traceAt a .third y.1 = splitTorusTrace v ∧
                  orderOf v = Nat.card (ZMod p)ˣ ∧
                    OrderedTraceCandidateRegular
                      a.a3 a.a1 a.a2
                        (traceAt a .third y.1) ∧
                      incidenceCenteredNormObstruction
                        (directedCycleRightCoefficients a)
                          (traceAt a .third y.1) ≠ 0 ∧
                        ¬ IsSquare
                          (centeredNorm a.a1 a.a2
                            (traceAt a .third y.1)) := by
  obtain ⟨threshold, hthreshold⟩ :=
    exists_threshold_primitive_obstructionReady_orbitConnectingGoodThreeRootWitness
  refine ⟨max threshold 5, ?_⟩
  intro p hp _ a hA1 hA2 hA3 hmoving x hx hsquare
  have hpThreshold : threshold ≤ p :=
    (Nat.le_max_left threshold 5).trans hp
  have hpFive : 5 ≤ p :=
    (Nat.le_max_right threshold 5).trans hp
  exact
    exists_axisThree_of_orbitConnectingWitnessSelector
      p hpFive a hA1 hA2 hA3 hmoving x hx hsquare
        (fun t =>
          incidenceCenteredNormObstruction
            (directedCycleRightCoefficients a) t ≠ 0)
        (by
          intro alpha beta gamma k omegaInv _ _ _ _
            homegaInvZero habsolute
          obtain
              ⟨v, w, hwTrace, hvOrder, hwRegular, hwObstruction⟩ :=
            hthreshold p hpThreshold (directedCycleRightCoefficients a)
              alpha gamma k omegaInv a.a2 a.a1
              (by simpa [directedCycleRightCoefficients] using hA3)
              (by simpa [directedCycleRightCoefficients] using hA1)
              homegaInvZero habsolute
          exact
            ⟨v, w, hwTrace, hvOrder,
              by
                simpa [directedCycleRightCoefficients] using hwRegular,
              hwObstruction⟩)

/-- Uniform large-prime prescribed-reference connecting-pair step in the
second-axis frame. -/
theorem
    exists_threshold_cageReadyCanonicalFirstAxis_square_reaches_primitiveConnectingPairAxisTwo :
    ∃ threshold : ℕ, ∀ p : ℕ, threshold ≤ p →
      [Fact p.Prime] →
      ∀ (a : Coefficients (ZMod p)),
        a.a1 ^ 2 ≠ 4 →
        a.a2 ^ 2 ≠ 4 →
        a.a3 ^ 2 ≠ 4 →
        (a.a3, a.a1) ≠ (0, 0) →
        ∀ eta : ZMod p,
          OrderedTraceCandidateRegular a.a2 a.a3 a.a1 eta →
          incidenceCenteredNormObstruction
            (directedCycleLeftCoefficients a) eta ≠ 0 →
          ∀ x : SolutionSurface a,
            IsCageReadyCanonicalFirstAxisPrimitiveSplit p a x →
            IsSquare
              (centeredNorm a.a2 a.a3
                (traceAt a .first x.1)) →
            ∃ y : SolutionSurface a,
              SameVietaComponent x y ∧
                ∃ v : (ZMod p)ˣ,
                  traceAt a .second y.1 = splitTorusTrace v ∧
                    orderOf v = Nat.card (ZMod p)ˣ ∧
                      OrderedTraceCandidateRegular
                        a.a2 a.a3 a.a1
                          (traceAt a .second y.1) ∧
                        IsConnectingIncidencePair
                          (directedCycleLeftCoefficients a)
                            (traceAt a .second y.1) eta ∧
                          ¬ IsSquare
                            (centeredNorm a.a3 a.a1
                              (traceAt a .second y.1)) := by
  refine ⟨GenMarkoff.General.Explicit.analyticCutoff, ?_⟩
  intro p hp _ a hA1 hA2 hA3 hmoving
    eta hetaRegular hetaObstruction x hx hsquare
  have hpFive : 5 ≤ p :=
    GenMarkoff.General.Explicit.five_le_analyticCutoff.trans hp
  have hexplicit :=
    GenMarkoff.General.Explicit.primitiveTrace_explicitInequality_one
      hp (coefficient := 1032) (by norm_num)
  have hcard : Nat.card (ZMod p)ˣ = p - 1 := by
    rw [Nat.card_units, Nat.card_zmod]
  exact
    exists_axisTwo_of_orbitConnectingWitnessSelector
      p hpFive a hA1 hA2 hA3 hmoving x hx hsquare
        (fun t =>
          IsConnectingIncidencePair
            (directedCycleLeftCoefficients a) t eta)
        (by
          intro alpha beta gamma k omegaInv _ _ _ _
            homegaInvZero habsolute
          obtain ⟨v, w, hwTrace, hvOrder, hwRegular, hwPair⟩ :=
            exists_primitive_connectingPair_orbitConnectingGoodThreeRootWitness_of_explicitInequality
              p hpFive (directedCycleLeftCoefficients a) eta
              alpha gamma k omegaInv a.a3 a.a1
              (by simpa [directedCycleLeftCoefficients] using hA2)
              (by simpa [directedCycleLeftCoefficients] using hA3)
              (by
                simpa [directedCycleLeftCoefficients] using
                  hetaRegular)
              hetaObstruction homegaInvZero habsolute
              (by rw [hcard]; simpa using hexplicit)
          exact
            ⟨v, w, hwTrace, hvOrder,
              by
                simpa [directedCycleLeftCoefficients] using hwRegular,
              hwPair⟩)

/-- Uniform large-prime prescribed-reference connecting-pair step in the
third-axis frame. -/
theorem
    exists_threshold_cageReadyCanonicalFirstAxis_square_reaches_primitiveConnectingPairAxisThree :
    ∃ threshold : ℕ, ∀ p : ℕ, threshold ≤ p →
      [Fact p.Prime] →
      ∀ (a : Coefficients (ZMod p)),
        a.a1 ^ 2 ≠ 4 →
        a.a2 ^ 2 ≠ 4 →
        a.a3 ^ 2 ≠ 4 →
        (a.a1, a.a2) ≠ (0, 0) →
        ∀ eta : ZMod p,
          OrderedTraceCandidateRegular a.a3 a.a1 a.a2 eta →
          incidenceCenteredNormObstruction
            (directedCycleRightCoefficients a) eta ≠ 0 →
          ∀ x : SolutionSurface a,
            IsCageReadyCanonicalFirstAxisPrimitiveSplit p a x →
            IsSquare
              (centeredNorm a.a2 a.a3
                (traceAt a .first x.1)) →
            ∃ y : SolutionSurface a,
              SameVietaComponent x y ∧
                ∃ v : (ZMod p)ˣ,
                  traceAt a .third y.1 = splitTorusTrace v ∧
                    orderOf v = Nat.card (ZMod p)ˣ ∧
                      OrderedTraceCandidateRegular
                        a.a3 a.a1 a.a2
                          (traceAt a .third y.1) ∧
                        IsConnectingIncidencePair
                          (directedCycleRightCoefficients a)
                            (traceAt a .third y.1) eta ∧
                          ¬ IsSquare
                            (centeredNorm a.a1 a.a2
                              (traceAt a .third y.1)) := by
  obtain ⟨threshold, hthreshold⟩ :=
    exists_threshold_primitive_connectingPair_orbitConnectingGoodThreeRootWitness
  refine ⟨max threshold 5, ?_⟩
  intro p hp _ a hA1 hA2 hA3 hmoving
    eta hetaRegular hetaObstruction x hx hsquare
  have hpThreshold : threshold ≤ p :=
    (Nat.le_max_left threshold 5).trans hp
  have hpFive : 5 ≤ p :=
    (Nat.le_max_right threshold 5).trans hp
  exact
    exists_axisThree_of_orbitConnectingWitnessSelector
      p hpFive a hA1 hA2 hA3 hmoving x hx hsquare
        (fun t =>
          IsConnectingIncidencePair
            (directedCycleRightCoefficients a) t eta)
        (by
          intro alpha beta gamma k omegaInv _ _ _ _
            homegaInvZero habsolute
          obtain ⟨v, w, hwTrace, hvOrder, hwRegular, hwPair⟩ :=
            hthreshold p hpThreshold
              (directedCycleRightCoefficients a) eta
              alpha gamma k omegaInv a.a2 a.a1
              (by simpa [directedCycleRightCoefficients] using hA3)
              (by simpa [directedCycleRightCoefficients] using hA1)
              (by
                simpa [directedCycleRightCoefficients] using
                  hetaRegular)
              hetaObstruction homegaInvZero habsolute
          exact
            ⟨v, w, hwTrace, hvOrder,
              by
                simpa [directedCycleRightCoefficients] using hwRegular,
              hwPair⟩)

/-- Pointwise square obstruction-ready normalization on the second axis. -/
theorem cageReadyCanonicalFirstAxis_square_reaches_obstructionReadyPrimitiveConnectingAxisTwo_of_analyticCutoff
    (p : ℕ) (hp : GenMarkoff.General.Explicit.analyticCutoff ≤ p)
    [Fact p.Prime]
    (a : Coefficients (ZMod p))
    (hA1 : a.a1 ^ 2 ≠ 4) (hA2 : a.a2 ^ 2 ≠ 4)
    (hA3 : a.a3 ^ 2 ≠ 4) (hmoving : (a.a3, a.a1) ≠ (0, 0))
    (x : SolutionSurface a)
    (hx : IsCageReadyCanonicalFirstAxisPrimitiveSplit p a x)
    (hsquare :
      IsSquare (centeredNorm a.a2 a.a3 (traceAt a .first x.1))) :
    ∃ y : SolutionSurface a,
      SameVietaComponent x y ∧
        ∃ v : (ZMod p)ˣ,
          traceAt a .second y.1 = splitTorusTrace v ∧
            orderOf v = Nat.card (ZMod p)ˣ ∧
              OrderedTraceCandidateRegular a.a2 a.a3 a.a1
                  (traceAt a .second y.1) ∧
                incidenceCenteredNormObstruction
                    (directedCycleLeftCoefficients a)
                    (traceAt a .second y.1) ≠ 0 ∧
                  ¬ IsSquare
                    (centeredNorm a.a3 a.a1
                      (traceAt a .second y.1)) := by
  have hpFive : 5 ≤ p :=
    GenMarkoff.General.Explicit.five_le_analyticCutoff.trans hp
  have hexplicit :=
    GenMarkoff.General.Explicit.primitiveTrace_explicitInequality_one
      hp (coefficient := 984) (by norm_num)
  have hcard : Nat.card (ZMod p)ˣ = p - 1 := by
    rw [Nat.card_units, Nat.card_zmod]
  exact
    exists_axisTwo_of_orbitConnectingWitnessSelector
      p hpFive a hA1 hA2 hA3 hmoving x hx hsquare
        (fun t =>
          incidenceCenteredNormObstruction
            (directedCycleLeftCoefficients a) t ≠ 0)
        (by
          intro alpha beta gamma k omegaInv _ _ _ _
            homegaInvZero habsolute
          obtain
              ⟨v, w, hwTrace, hvOrder, hwRegular, hwObstruction⟩ :=
            exists_primitive_obstructionReady_orbitConnectingGoodThreeRootWitness_of_explicitInequality
              p hpFive (directedCycleLeftCoefficients a)
              alpha gamma k omegaInv a.a3 a.a1
              (by simpa [directedCycleLeftCoefficients] using hA2)
              (by simpa [directedCycleLeftCoefficients] using hA3)
              homegaInvZero habsolute
              (by rw [hcard]; simpa using hexplicit)
          exact
            ⟨v, w, hwTrace, hvOrder,
              by
                simpa [directedCycleLeftCoefficients] using hwRegular,
              hwObstruction⟩)

/-- Pointwise square prescribed-pair normalization on the second axis. -/
theorem cageReadyCanonicalFirstAxis_square_reaches_primitiveConnectingPairAxisTwo_of_analyticCutoff
    (p : ℕ) (hp : GenMarkoff.General.Explicit.analyticCutoff ≤ p)
    [Fact p.Prime]
    (a : Coefficients (ZMod p))
    (hA1 : a.a1 ^ 2 ≠ 4) (hA2 : a.a2 ^ 2 ≠ 4)
    (hA3 : a.a3 ^ 2 ≠ 4) (hmoving : (a.a3, a.a1) ≠ (0, 0))
    (eta : ZMod p)
    (hetaRegular : OrderedTraceCandidateRegular a.a2 a.a3 a.a1 eta)
    (hetaObstruction :
      incidenceCenteredNormObstruction
        (directedCycleLeftCoefficients a) eta ≠ 0)
    (x : SolutionSurface a)
    (hx : IsCageReadyCanonicalFirstAxisPrimitiveSplit p a x)
    (hsquare :
      IsSquare (centeredNorm a.a2 a.a3 (traceAt a .first x.1))) :
    ∃ y : SolutionSurface a,
      SameVietaComponent x y ∧
        ∃ v : (ZMod p)ˣ,
          traceAt a .second y.1 = splitTorusTrace v ∧
            orderOf v = Nat.card (ZMod p)ˣ ∧
              OrderedTraceCandidateRegular a.a2 a.a3 a.a1
                  (traceAt a .second y.1) ∧
                IsConnectingIncidencePair
                    (directedCycleLeftCoefficients a)
                    (traceAt a .second y.1) eta ∧
                  ¬ IsSquare
                    (centeredNorm a.a3 a.a1
                      (traceAt a .second y.1)) := by
  have hpFive : 5 ≤ p :=
    GenMarkoff.General.Explicit.five_le_analyticCutoff.trans hp
  have hexplicit :=
    GenMarkoff.General.Explicit.primitiveTrace_explicitInequality_one
      hp (coefficient := 1032) (by norm_num)
  have hcard : Nat.card (ZMod p)ˣ = p - 1 := by
    rw [Nat.card_units, Nat.card_zmod]
  exact
    exists_axisTwo_of_orbitConnectingWitnessSelector
      p hpFive a hA1 hA2 hA3 hmoving x hx hsquare
        (fun t =>
          IsConnectingIncidencePair
            (directedCycleLeftCoefficients a) t eta)
        (by
          intro alpha beta gamma k omegaInv _ _ _ _
            homegaInvZero habsolute
          obtain ⟨v, w, hwTrace, hvOrder, hwRegular, hwPair⟩ :=
            exists_primitive_connectingPair_orbitConnectingGoodThreeRootWitness_of_explicitInequality
              p hpFive (directedCycleLeftCoefficients a) eta
              alpha gamma k omegaInv a.a3 a.a1
              (by simpa [directedCycleLeftCoefficients] using hA2)
              (by simpa [directedCycleLeftCoefficients] using hA3)
              (by
                simpa [directedCycleLeftCoefficients] using
                  hetaRegular)
              hetaObstruction homegaInvZero habsolute
              (by rw [hcard]; simpa using hexplicit)
          exact
            ⟨v, w, hwTrace, hvOrder,
              by
                simpa [directedCycleLeftCoefficients] using hwRegular,
              hwPair⟩)

/-- Reasonable-cutoff square obstruction-ready normalization. -/
theorem cageReadyCanonicalFirstAxis_square_reaches_obstructionReadyPrimitiveConnectingAxisTwo_of_reasonableCutoff
    (p : ℕ)
    (hp : GenMarkoff.General.Explicit.reasonableAnalyticCutoff ≤ p)
    [Fact p.Prime]
    (a : Coefficients (ZMod p))
    (hA1 : a.a1 ^ 2 ≠ 4) (hA2 : a.a2 ^ 2 ≠ 4)
    (hA3 : a.a3 ^ 2 ≠ 4) (hmoving : (a.a3, a.a1) ≠ (0, 0))
    (x : SolutionSurface a)
    (hx : IsCageReadyCanonicalFirstAxisPrimitiveSplit p a x)
    (hsquare :
      IsSquare (centeredNorm a.a2 a.a3 (traceAt a .first x.1))) :
    ∃ y : SolutionSurface a,
      SameVietaComponent x y ∧
        ∃ v : (ZMod p)ˣ,
          traceAt a .second y.1 = splitTorusTrace v ∧
            orderOf v = Nat.card (ZMod p)ˣ ∧
              OrderedTraceCandidateRegular a.a2 a.a3 a.a1
                  (traceAt a .second y.1) ∧
                incidenceCenteredNormObstruction
                    (directedCycleLeftCoefficients a)
                    (traceAt a .second y.1) ≠ 0 ∧
                  ¬ IsSquare
                    (centeredNorm a.a3 a.a1
                      (traceAt a .second y.1)) := by
  have hpFive : 5 ≤ p :=
    GenMarkoff.General.Explicit.five_le_reasonableAnalyticCutoff.trans hp
  have hexplicit :=
    GenMarkoff.General.Explicit.reasonable_primitiveTrace_explicitInequality_one
      hp (coefficient := 984) (by norm_num)
  have hcard : Nat.card (ZMod p)ˣ = p - 1 := by
    rw [Nat.card_units, Nat.card_zmod]
  exact
    exists_axisTwo_of_orbitConnectingWitnessSelector
      p hpFive a hA1 hA2 hA3 hmoving x hx hsquare
        (fun t =>
          incidenceCenteredNormObstruction
            (directedCycleLeftCoefficients a) t ≠ 0)
        (by
          intro alpha beta gamma k omegaInv _ _ _ _
            homegaInvZero habsolute
          obtain
              ⟨v, w, hwTrace, hvOrder, hwRegular, hwObstruction⟩ :=
            exists_primitive_obstructionReady_orbitConnectingGoodThreeRootWitness_of_explicitInequality
              p hpFive (directedCycleLeftCoefficients a)
              alpha gamma k omegaInv a.a3 a.a1
              (by simpa [directedCycleLeftCoefficients] using hA2)
              (by simpa [directedCycleLeftCoefficients] using hA3)
              homegaInvZero habsolute
              (by rw [hcard]; simpa using hexplicit)
          exact
            ⟨v, w, hwTrace, hvOrder,
              by
                simpa [directedCycleLeftCoefficients] using hwRegular,
              hwObstruction⟩)

/-- Reasonable-cutoff square prescribed-pair normalization. -/
theorem cageReadyCanonicalFirstAxis_square_reaches_primitiveConnectingPairAxisTwo_of_reasonableCutoff
    (p : ℕ)
    (hp : GenMarkoff.General.Explicit.reasonableAnalyticCutoff ≤ p)
    [Fact p.Prime]
    (a : Coefficients (ZMod p))
    (hA1 : a.a1 ^ 2 ≠ 4) (hA2 : a.a2 ^ 2 ≠ 4)
    (hA3 : a.a3 ^ 2 ≠ 4) (hmoving : (a.a3, a.a1) ≠ (0, 0))
    (eta : ZMod p)
    (hetaRegular : OrderedTraceCandidateRegular a.a2 a.a3 a.a1 eta)
    (hetaObstruction :
      incidenceCenteredNormObstruction
        (directedCycleLeftCoefficients a) eta ≠ 0)
    (x : SolutionSurface a)
    (hx : IsCageReadyCanonicalFirstAxisPrimitiveSplit p a x)
    (hsquare :
      IsSquare (centeredNorm a.a2 a.a3 (traceAt a .first x.1))) :
    ∃ y : SolutionSurface a,
      SameVietaComponent x y ∧
        ∃ v : (ZMod p)ˣ,
          traceAt a .second y.1 = splitTorusTrace v ∧
            orderOf v = Nat.card (ZMod p)ˣ ∧
              OrderedTraceCandidateRegular a.a2 a.a3 a.a1
                  (traceAt a .second y.1) ∧
                IsConnectingIncidencePair
                    (directedCycleLeftCoefficients a)
                    (traceAt a .second y.1) eta ∧
                  ¬ IsSquare
                    (centeredNorm a.a3 a.a1
                      (traceAt a .second y.1)) := by
  have hpFive : 5 ≤ p :=
    GenMarkoff.General.Explicit.five_le_reasonableAnalyticCutoff.trans hp
  have hexplicit :=
    GenMarkoff.General.Explicit.reasonable_primitiveTrace_explicitInequality_one
      hp (coefficient := 1032) (by norm_num)
  have hcard : Nat.card (ZMod p)ˣ = p - 1 := by
    rw [Nat.card_units, Nat.card_zmod]
  exact
    exists_axisTwo_of_orbitConnectingWitnessSelector
      p hpFive a hA1 hA2 hA3 hmoving x hx hsquare
        (fun t =>
          IsConnectingIncidencePair
            (directedCycleLeftCoefficients a) t eta)
        (by
          intro alpha beta gamma k omegaInv _ _ _ _
            homegaInvZero habsolute
          obtain ⟨v, w, hwTrace, hvOrder, hwRegular, hwPair⟩ :=
            exists_primitive_connectingPair_orbitConnectingGoodThreeRootWitness_of_explicitInequality
              p hpFive (directedCycleLeftCoefficients a) eta
              alpha gamma k omegaInv a.a3 a.a1
              (by simpa [directedCycleLeftCoefficients] using hA2)
              (by simpa [directedCycleLeftCoefficients] using hA3)
              (by
                simpa [directedCycleLeftCoefficients] using
                  hetaRegular)
              hetaObstruction homegaInvZero habsolute
              (by rw [hcard]; simpa using hexplicit)
          exact
            ⟨v, w, hwTrace, hvOrder,
              by
                simpa [directedCycleLeftCoefficients] using hwRegular,
              hwPair⟩)

end

end GenMarkoff.General.Cage
