import GenMarkoff.General.Cage.ConnectingQuartic
import GenMarkoff.General.MiddleGame.ActualDiagonalization
import GenMarkoff.General.MiddleGame.ActualMoveWiring
import GenMarkoff.General.Assembly.VietaParityCollapse
import Mathlib.Algebra.Group.Subgroup.Even
import Mathlib.FieldTheory.Finite.Basic

/-!
# Full-Vieta connectivity of a primitive connecting fiber

On a regular split first-coordinate fiber, write the torus parameter as `h`
and let `P` be `centeredFiberProduct`.  The actual rotation sends
`h` to `q^2 h`, while the third Vieta involution sends `h` to `P / h`.
If `q` is primitive, `zpowers (q^2)` is exactly the square subgroup.
Consequently, if `P` is nonsquare, the reflection exchanges the two rotation
cosets and the group generated by the two adjacent Vieta involutions is
transitive on the whole fiber.

This file proves that statement directly in the fixed coefficient frame.  It
is the local “connecting fiber” theorem used by the new full-Vieta route.
-/

namespace GenMarkoff.General.Cage

open BGS.Markoff
open GenMarkoff.General.Assembly

universe u

noncomputable section

/-- A unit is a square exactly when its value in the ambient field is a
square. -/
theorem unit_isSquare_iff_isSquare_val
    {K : Type u} [Field K] (x : Kˣ) :
    IsSquare x ↔ IsSquare (x : K) := by
  constructor
  · rintro ⟨r, hr⟩
    refine ⟨(r : K), ?_⟩
    exact congrArg (fun z : Kˣ => (z : K)) hr
  · rintro ⟨r, hr⟩
    have hr0 : r ≠ 0 := by
      intro hrZero
      apply Units.ne_zero x
      calc
        (x : K) = r * r := hr
        _ = 0 := by simp [hrZero]
    let rUnit : Kˣ := Units.mk0 r hr0
    refine ⟨rUnit, ?_⟩
    apply Units.ext
    simpa [rUnit] using hr

/-- If `q` generates a commutative group, the subgroup generated by `q^2`
is exactly the subgroup of squares. -/
theorem zpowers_sq_eq_square_of_zpowers_eq_top
    {G : Type u} [CommGroup G] (q : G)
    (hq : Subgroup.zpowers q = ⊤) :
    Subgroup.zpowers (q ^ 2) = Subgroup.square G := by
  ext x
  constructor
  · intro hx
    obtain ⟨n, hn⟩ := Subgroup.mem_zpowers_iff.mp hx
    rw [Subgroup.mem_square]
    refine ⟨q ^ n, ?_⟩
    rw [← hn]
    simp only [pow_two, mul_zpow]
  · intro hx
    rw [Subgroup.mem_square] at hx
    obtain ⟨r, hr⟩ := hx
    have hrMem : r ∈ Subgroup.zpowers q := by
      rw [hq]
      exact Subgroup.mem_top r
    obtain ⟨n, hn⟩ := Subgroup.mem_zpowers_iff.mp hrMem
    apply Subgroup.mem_zpowers_iff.mpr
    refine ⟨n, ?_⟩
    rw [pow_two, mul_zpow, hn, hr]

/-- An element whose order is the cardinality of a finite group generates
that group. -/
theorem zpowers_eq_top_of_orderOf_eq_natCard
    {G : Type u} [Group G] [Finite G] (q : G)
    (hq : orderOf q = Nat.card G) :
    Subgroup.zpowers q = ⊤ := by
  exact
    (Subgroup.card_eq_iff_eq_top (Subgroup.zpowers q)).mp
      (by rw [Nat.card_zpowers, hq])

/-- In a finite field of odd characteristic, the quotient of two nonzero
nonsquares is a square. -/
theorem isSquare_div_of_not_isSquare_of_not_isSquare
    {K : Type u} [Field K] [Fintype K]
    (hchar : ringChar K ≠ 2) {x y : K}
    (hx0 : x ≠ 0) (hy0 : y ≠ 0)
    (hx : ¬ IsSquare x) (hy : ¬ IsSquare y) :
    IsSquare (x / y) := by
  have hxPow :
      x ^ (Fintype.card K / 2) = -1 := by
    rcases FiniteField.pow_dichotomy hchar hx0 with hxOne | hxNeg
    · exact False.elim (hx ((FiniteField.isSquare_iff hchar hx0).mpr hxOne))
    · exact hxNeg
  have hyPow :
      y ^ (Fintype.card K / 2) = -1 := by
    rcases FiniteField.pow_dichotomy hchar hy0 with hyOne | hyNeg
    · exact False.elim (hy ((FiniteField.isSquare_iff hchar hy0).mpr hyOne))
    · exact hyNeg
  apply (FiniteField.isSquare_iff hchar (div_ne_zero hx0 hy0)).mpr
  rw [div_pow, hxPow, hyPow]
  simp

/-- Full-Vieta connectivity is reflexive. -/
theorem sameVietaComponent_refl
    {R : Type u} [CommRing R] {a : Coefficients R}
    (x : SolutionSurface a) :
    SameVietaComponent x x :=
  ⟨1, one_smul _ _⟩

/-- Full-Vieta connectivity is transitive. -/
theorem sameVietaComponent_trans
    {R : Type u} [CommRing R] {a : Coefficients R}
    {x y z : SolutionSurface a}
    (hxy : SameVietaComponent x y)
    (hyz : SameVietaComponent y z) :
    SameVietaComponent x z := by
  obtain ⟨g, rfl⟩ := hxy
  obtain ⟨h, rfl⟩ := hyz
  exact ⟨h * g, mul_smul h g x⟩

/-- One third-Vieta reflection stays in the same full-Vieta component. -/
theorem sameVietaComponent_vieta3
    {R : Type u} [CommRing R] (a : Coefficients R)
    (x : SolutionSurface a) :
    SameVietaComponent x (vieta3SurfacePerm a x) := by
  let g : VietaGroup a :=
    ⟨vieta3SurfacePerm a, vieta3SurfacePerm_mem_VietaGroup a⟩
  exact ⟨g, rfl⟩

private theorem coe_iterate_rotation1SurfacePerm
    {R : Type u} [CommRing R] (a : Coefficients R)
    (x : SolutionSurface a) (n : ℕ) :
    ((((rotation1SurfacePerm a)^[n]) x :
      SolutionSurface a) : Point R) =
        ((rotation1 a)^[n]) x.1 := by
  induction n with
  | zero => rfl
  | succ n ih =>
      rw [Function.iterate_succ_apply', Function.iterate_succ_apply',
        coe_rotation1SurfacePerm, ih]

/-- A point equality produced by iterating the first rotation gives
full-Vieta connectivity of the corresponding surface points. -/
theorem sameVietaComponent_of_iterate_rotation1
    {R : Type u} [CommRing R] (a : Coefficients R)
    (x y : SolutionSurface a) (n : ℕ)
    (hxy : ((rotation1 a)^[n]) x.1 = y.1) :
    SameVietaComponent x y := by
  apply sameVietaComponent_of_sameRotationComponent
  obtain ⟨g, hg⟩ :=
    sameRotationComponent_iterate_rotationSurfacePermAt
      a .first x n
  refine ⟨g, hg.trans ?_⟩
  apply Subtype.ext
  simpa [rotationSurfacePermAt] using
    (coe_iterate_rotation1SurfacePerm a x n).trans hxy

/-- Parameter-coset dichotomy for a primitive split eigenvalue.  Either the
target parameter is in the current rotation coset, or it is in the rotation
coset obtained after the third-Vieta reflection. -/
theorem primitive_parameter_mem_rotation_or_reflected_rotation
    (p : ℕ) [Fact p.Prime] (hpTwo : p ≠ 2)
    (q P r s : (ZMod p)ˣ)
    (hq : orderOf q = Nat.card (ZMod p)ˣ)
    (hP : ¬ IsSquare (P : ZMod p)) :
    s * r⁻¹ ∈ Subgroup.zpowers (q ^ 2) ∨
      s * (P * r⁻¹)⁻¹ ∈ Subgroup.zpowers (q ^ 2) := by
  have hqTop : Subgroup.zpowers q = ⊤ :=
    zpowers_eq_top_of_orderOf_eq_natCard q hq
  have hsqSubgroup :
      Subgroup.zpowers (q ^ 2) = Subgroup.square (ZMod p)ˣ :=
    zpowers_sq_eq_square_of_zpowers_eq_top q hqTop
  let ratio : (ZMod p)ˣ := s * r⁻¹
  by_cases hratio : IsSquare (ratio : ZMod p)
  · left
    rw [hsqSubgroup, Subgroup.mem_square]
    exact (unit_isSquare_iff_isSquare_val ratio).mpr hratio
  · right
    have hchar : ringChar (ZMod p) ≠ 2 := by
      exact (ZMod.ringChar_zmod_n p).substr hpTwo
    have hsrNot : ¬ IsSquare ((s : ZMod p) * (r : ZMod p)) := by
      intro hsr
      apply hratio
      have hreorder :
          (r : ZMod p) ^ 2 * (ratio : ZMod p) =
            (s : ZMod p) * (r : ZMod p) := by
        simp only [ratio, Units.val_mul, Units.val_inv_eq_inv_val]
        field_simp [Units.ne_zero r]
      apply
        (isSquare_sq_mul_iff (r : ZMod p) (ratio : ZMod p)
          (Units.ne_zero r)).mp
      simpa only [hreorder] using hsr
    have hquotient :
        IsSquare
          (((s : ZMod p) * (r : ZMod p)) / (P : ZMod p)) :=
      isSquare_div_of_not_isSquare_of_not_isSquare
        hchar
        (mul_ne_zero (Units.ne_zero s) (Units.ne_zero r))
        (Units.ne_zero P) hsrNot hP
    rw [hsqSubgroup, Subgroup.mem_square]
    apply (unit_isSquare_iff_isSquare_val
      (s * (P * r⁻¹)⁻¹)).mpr
    convert hquotient using 1
    simp only [Units.val_mul, Units.val_inv_eq_inv_val]
    field_simp [Units.ne_zero r, Units.ne_zero P]

/-- A primitive first-axis split fiber with nonsquare centered product is a
single full-Vieta component.  The two displayed surface proofs merely package
the two parametrized points; no coordinate permutation is used. -/
theorem sameVietaComponent_firstAxis_fiberPoints_of_primitive_of_not_isSquare
    (p : ℕ) [Fact p.Prime] (hpTwo : p ≠ 2)
    (a : Coefficients (ZMod p)) (u t : ZMod p)
    (q r s : (ZMod p)ˣ)
    (hD : discriminant t ≠ 0)
    (heigen : t = splitTorusTrace q)
    (hcoordinate : t = orderedTrace a.multiplier a.a1 u)
    (hq : orderOf q = Nat.card (ZMod p)ˣ)
    (hP :
      ¬ IsSquare (centeredFiberProduct a.a2 a.a3 u t))
    (hx :
      IsSolution a (fiberPoint1 a u t (q : ZMod p) (r : ZMod p)))
    (hy :
      IsSolution a (fiberPoint1 a u t (q : ZMod p) (s : ZMod p))) :
    SameVietaComponent
      (⟨fiberPoint1 a u t (q : ZMod p) (r : ZMod p), hx⟩ :
        SolutionSurface a)
      (⟨fiberPoint1 a u t (q : ZMod p) (s : ZMod p), hy⟩ :
        SolutionSurface a) := by
  let P : ZMod p := centeredFiberProduct a.a2 a.a3 u t
  have hP0 : P ≠ 0 := by
    intro hzero
    apply hP
    rw [show centeredFiberProduct a.a2 a.a3 u t = P by rfl, hzero]
    exact IsSquare.zero
  let PUnit : (ZMod p)ˣ := Units.mk0 P hP0
  let x : SolutionSurface a :=
    ⟨fiberPoint1 a u t (q : ZMod p) (r : ZMod p), hx⟩
  let y : SolutionSurface a :=
    ⟨fiberPoint1 a u t (q : ZMod p) (s : ZMod p), hy⟩
  have hPUnit : ¬ IsSquare (PUnit : ZMod p) := by
    simpa [PUnit, P] using hP
  rcases
      primitive_parameter_mem_rotation_or_reflected_rotation
        p hpTwo q PUnit r s hq hPUnit with
    hsame | hreflected
  · let h : Subgroup.zpowers (q ^ 2) := ⟨s * r⁻¹, hsame⟩
    obtain ⟨n, hn⟩ :=
      GenMarkoff.General.MiddleGame.exists_iterate_fiberPoint1_eq_mul_zpowers_sq
        a u t q r hD heigen hcoordinate h
    apply sameVietaComponent_of_iterate_rotation1 a x y n
    simpa [x, y, h] using hn
  · have heigenField :
        t = (q : ZMod p) + (q : ZMod p)⁻¹ := by
      simpa only [splitTorusTrace, Units.val_inv_eq_inv_val] using heigen
    have hvieta :
        vieta3 a (fiberPoint1 a u t (q : ZMod p) (r : ZMod p)) =
          fiberPoint1 a u t (q : ZMod p)
            (centeredFiberProduct a.a2 a.a3 u t / (r : ZMod p)) :=
      vieta3_fiberPoint1 a u t (q : ZMod p) (r : ZMod p)
        hD (Units.ne_zero q) hP0 (Units.ne_zero r)
          heigenField hcoordinate
    have hzSolution :
        IsSolution a
          (fiberPoint1 a u t (q : ZMod p)
            (centeredFiberProduct a.a2 a.a3 u t / (r : ZMod p))) := by
      rw [← hvieta]
      exact (isSolution_vieta3 a _).mpr hx
    let z : SolutionSurface a :=
      ⟨fiberPoint1 a u t (q : ZMod p)
        (centeredFiberProduct a.a2 a.a3 u t / (r : ZMod p)),
        hzSolution⟩
    have hxz : SameVietaComponent x z := by
      have hmove := sameVietaComponent_vieta3 a x
      convert hmove using 1
      apply Subtype.ext
      simpa [x, z] using hvieta.symm
    let reflected : (ZMod p)ˣ := PUnit * r⁻¹
    let h : Subgroup.zpowers (q ^ 2) :=
      ⟨s * reflected⁻¹, by simpa [reflected] using hreflected⟩
    obtain ⟨n, hn⟩ :=
      GenMarkoff.General.MiddleGame.exists_iterate_fiberPoint1_eq_mul_zpowers_sq
        a u t q reflected hD heigen hcoordinate h
    have hzy : SameVietaComponent z y := by
      apply sameVietaComponent_of_iterate_rotation1 a z y n
      have hreflectedVal :
          (reflected : ZMod p) =
            centeredFiberProduct a.a2 a.a3 u t / (r : ZMod p) := by
        dsimp only [reflected]
        simp only [Units.val_mul, Units.val_inv_eq_inv_val]
        dsimp only [PUnit]
        change
          P * (r : ZMod p)⁻¹ =
            centeredFiberProduct a.a2 a.a3 u t / (r : ZMod p)
        rw [div_eq_mul_inv]
      simpa [z, y, h, hreflectedVal] using hn
    exact sameVietaComponent_trans hxz hzy

/-- Every two points on the same primitive first-coordinate fiber with
nonsquare centered norm lie in the same full-Vieta component as soon as the
trace is nonparabolic and the original fixed coordinate is nonzero.

Unlike the endgame-facing wrapper below, this local cage interface does not
require the four additional candidate-regular factors. -/
theorem
    sameVietaComponent_of_same_firstCoordinate_of_primitiveConnecting_basic
    (p : ℕ) [Fact p.Prime] (hpTwo : p ≠ 2)
    (a : Coefficients (ZMod p))
    (x y : SolutionSurface a)
    (hfirst : x.1.x1 = y.1.x1)
    (q : (ZMod p)ˣ)
    (heigen :
      traceAt a .first x.1 = splitTorusTrace q)
    (hq : orderOf q = Nat.card (ZMod p)ˣ)
    (hD :
      discriminant (traceAt a .first x.1) ≠ 0)
    (hcoordinateNonzero :
      traceAt a .first x.1 + a.a1 ≠ 0)
    (hconnecting :
      ¬ IsSquare
        (centeredNorm a.a2 a.a3 (traceAt a .first x.1))) :
    SameVietaComponent x y := by
  let u : ZMod p := x.1.x1
  let t : ZMod p := traceAt a .first x.1
  have hcoordinate :
      t = orderedTrace a.multiplier a.a1 u := by
    rfl
  have hD' : discriminant t ≠ 0 := by
    simpa [t] using hD
  have hu : u ≠ 0 := by
    intro huZero
    apply hcoordinateNonzero
    simp [u, huZero]
  have hP :
      ¬ IsSquare (centeredFiberProduct a.a2 a.a3 u t) := by
    intro hPsquare
    apply hconnecting
    exact
      (centeredFiberProduct_isSquare_iff_centeredNorm
        a.a2 a.a3 u t hu hD').mp hPsquare
  have hP0 : centeredFiberProduct a.a2 a.a3 u t ≠ 0 := by
    intro hzero
    apply hP
    rw [hzero]
    exact IsSquare.zero
  have hxConic :
      fiberConic a.a2 a.a3 u t x.1.x2 x.1.x3 = 0 := by
    have hxSurface := x.property
    rw [IsSolution, polynomial_fixed_first] at hxSurface
    change
      fiberConic a.a2 a.a3 x.1.x1
        (orderedTrace a.multiplier a.a1 x.1.x1)
        x.1.x2 x.1.x3 = 0
    exact hxSurface
  have hyConic :
      fiberConic a.a2 a.a3 u t y.1.x2 y.1.x3 = 0 := by
    have hySurface := y.property
    rw [IsSolution, polynomial_fixed_first] at hySurface
    change
      fiberConic a.a2 a.a3 x.1.x1
        (orderedTrace a.multiplier a.a1 x.1.x1)
        y.1.x2 y.1.x3 = 0
    rw [hfirst]
    exact hySurface
  obtain ⟨r, hrPair⟩ :=
    GenMarkoff.General.MiddleGame.exists_unit_fiberPair_eq
      a.a2 a.a3 u t q (x.1.x2, x.1.x3)
        hxConic heigen hD' hP0
  obtain ⟨s, hsPair⟩ :=
    GenMarkoff.General.MiddleGame.exists_unit_fiberPair_eq
      a.a2 a.a3 u t q (y.1.x2, y.1.x3)
        hyConic heigen hD' hP0
  have hrPoint :
      fiberPoint1 a u t (q : ZMod p) (r : ZMod p) = x.1 := by
    apply Point.ext
    · rfl
    · exact congrArg Prod.fst hrPair
    · exact congrArg Prod.snd hrPair
  have hsPoint :
      fiberPoint1 a u t (q : ZMod p) (s : ZMod p) = y.1 := by
    apply Point.ext
    · exact hfirst
    · exact congrArg Prod.fst hsPair
    · exact congrArg Prod.snd hsPair
  have hrSolution :
      IsSolution a
        (fiberPoint1 a u t (q : ZMod p) (r : ZMod p)) := by
    rw [hrPoint]
    exact x.property
  have hsSolution :
      IsSolution a
        (fiberPoint1 a u t (q : ZMod p) (s : ZMod p)) := by
    rw [hsPoint]
    exact y.property
  let xr : SolutionSurface a :=
    ⟨fiberPoint1 a u t (q : ZMod p) (r : ZMod p), hrSolution⟩
  let ys : SolutionSurface a :=
    ⟨fiberPoint1 a u t (q : ZMod p) (s : ZMod p), hsSolution⟩
  have hxr : xr = x := by
    apply Subtype.ext
    exact hrPoint
  have hys : ys = y := by
    apply Subtype.ext
    exact hsPoint
  have hconnected :
      SameVietaComponent xr ys :=
    sameVietaComponent_firstAxis_fiberPoints_of_primitive_of_not_isSquare
      p hpTwo a u t q r s hD' heigen hcoordinate hq hP
        hrSolution hsSolution
  rw [hxr, hys] at hconnected
  exact hconnected

/-- Every two points on the same regular primitive first-coordinate fiber
with nonsquare centered norm lie in the same full-Vieta component.  This is
the endgame-facing wrapper around the weaker local interface above. -/
theorem
    sameVietaComponent_of_same_firstCoordinate_of_primitiveConnecting
    (p : ℕ) [Fact p.Prime] (hpTwo : p ≠ 2)
    (a : Coefficients (ZMod p))
    (x y : SolutionSurface a)
    (hfirst : x.1.x1 = y.1.x1)
    (q : (ZMod p)ˣ)
    (heigen :
      traceAt a .first x.1 = splitTorusTrace q)
    (hq : orderOf q = Nat.card (ZMod p)ˣ)
    (hregular :
      OrderedTraceCandidateRegular a.a1 a.a2 a.a3
        (traceAt a .first x.1))
    (hconnecting :
      ¬ IsSquare
        (centeredNorm a.a2 a.a3 (traceAt a .first x.1))) :
    SameVietaComponent x y := by
  apply
    sameVietaComponent_of_same_firstCoordinate_of_primitiveConnecting_basic
      p hpTwo a x y hfirst q heigen hq
  · simpa [discriminant] using hregular.1
  · exact hregular.2.1
  · exact hconnecting

end

end GenMarkoff.General.Cage
