import GenMarkoff.General.Cage.ConnectingGeometricSquareClasses
import GenMarkoff.General.Cage.HyperellipticPlane

/-!
# Seven hyperelliptic-plane estimates for the unequal connecting cage

The three square roots used by the unequal connecting construction have
radicands

* the two incidence pullbacks;
* a nonzero scalar multiple of the full centered-norm pullback.

This file bounds the degrees of their seven nonempty products, turns the
geometric square-class calculation into absolute irreducibility of the seven
hyperelliptic planes, and packages the resulting affine Hasse--Weil errors.

The full centered-norm pullback is used here, including its forced polynomial
square in the two collision cases.  Consequently the Hasse--Weil adapter below
uses nonsquareness after extension to an algebraic closure, rather than a
squarefreeness hypothesis over the ground field.
-/

namespace GenMarkoff.General.Cage

open Polynomial

universe u v

noncomputable section

variable {K : Type u} [Field K]

/-- The unequal incidence pullback has degree at most `4d`. -/
theorem incidencePulledRadicand_natDegree_le
    (a : Coefficients K) (xi : K) (d : ℕ) :
    (incidencePulledRadicand a xi d).natDegree ≤ 4 * d := by
  unfold incidencePulledRadicand
  refine (natDegree_add_le _ _).trans (max_le ?_ ?_)
  · refine (natDegree_add_le _ _).trans (max_le ?_ ?_)
    · refine (natDegree_add_le _ _).trans (max_le ?_ ?_)
      · refine (natDegree_add_le _ _).trans (max_le ?_ ?_)
        · exact natDegree_C_mul_X_pow_le _ _
        · exact (natDegree_C_mul_X_pow_le _ _).trans (by omega)
      · exact (natDegree_C_mul_X_pow_le _ _).trans (by omega)
    · exact (natDegree_C_mul_X_pow_le _ _).trans (by omega)
  · exact (natDegree_C _).le.trans (Nat.zero_le _)

/-- The full centered-norm pullback has degree at most `4d`. -/
theorem centeredNormPulledRadicand_natDegree_le
    (B C0 : K) (d : ℕ) :
    (centeredNormPulledRadicand B C0 d).natDegree ≤ 4 * d := by
  unfold centeredNormPulledRadicand
  refine (natDegree_add_le _ _).trans (max_le ?_ ?_)
  · refine (natDegree_add_le _ _).trans (max_le ?_ ?_)
    · refine (natDegree_add_le _ _).trans (max_le ?_ ?_)
      · refine (natDegree_add_le _ _).trans (max_le ?_ ?_)
        · exact natDegree_X_pow_le _
        · exact (natDegree_C_mul_X_pow_le _ _).trans (by omega)
      · exact (natDegree_C_mul_X_pow_le _ _).trans (by omega)
    · exact (natDegree_C_mul_X_pow_le _ _).trans (by omega)
  · simp

/-- Multiplying the centered-norm pullback by a scalar does not increase
the `4d` degree bound. -/
theorem scaledCenteredNormPulledRadicand_natDegree_le
    (omegaInv B C0 : K) (d : ℕ) :
    (C omegaInv * centeredNormPulledRadicand B C0 d).natDegree ≤
      4 * d := by
  refine natDegree_mul_le.trans ?_
  have hcentered :=
    centeredNormPulledRadicand_natDegree_le B C0 d
  simpa using hcentered

/-- Degree bounds for the seven nonempty products generated by three
radicands of degree at most `D`. -/
def SevenRadicandProductNatDegreeBounds
    (f g h : K[X]) (D : ℕ) : Prop :=
  f.natDegree ≤ D ∧
    g.natDegree ≤ D ∧
    h.natDegree ≤ D ∧
    (f * g).natDegree ≤ 2 * D ∧
    (f * h).natDegree ≤ 2 * D ∧
    (g * h).natDegree ≤ 2 * D ∧
    (f * g * h).natDegree ≤ 3 * D

/-- The seven-product degree interface follows from the three individual
degree bounds. -/
theorem sevenRadicandProductNatDegreeBounds_of_le
    {f g h : K[X]} {D : ℕ}
    (hf : f.natDegree ≤ D)
    (hg : g.natDegree ≤ D)
    (hh : h.natDegree ≤ D) :
    SevenRadicandProductNatDegreeBounds f g h D := by
  have hfg : (f * g).natDegree ≤ 2 * D :=
    natDegree_mul_le.trans (by omega)
  have hfh : (f * h).natDegree ≤ 2 * D :=
    natDegree_mul_le.trans (by omega)
  have hgh : (g * h).natDegree ≤ 2 * D :=
    natDegree_mul_le.trans (by omega)
  have hfgh : (f * g * h).natDegree ≤ 3 * D :=
    natDegree_mul_le.trans (by omega)
  exact ⟨hf, hg, hh, hfg, hfh, hgh, hfgh⟩

/-- The two incidence radicands and a scalar multiple of the full
centered-norm radicand have the degree bounds
`4d,4d,4d,8d,8d,8d,12d`. -/
theorem connectingSevenScaledRadicandProducts_natDegree_le
    (a : Coefficients K) (xi eta omegaInv : K) (d : ℕ) :
    let f := incidencePulledRadicand a xi d
    let g := incidencePulledRadicand a eta d
    let h :=
      C omegaInv * centeredNormPulledRadicand a.a3 a.a1 d
    SevenRadicandProductNatDegreeBounds f g h (4 * d) := by
  dsimp only
  exact sevenRadicandProductNatDegreeBounds_of_le
    (incidencePulledRadicand_natDegree_le a xi d)
    (incidencePulledRadicand_natDegree_le a eta d)
    (scaledCenteredNormPulledRadicand_natDegree_le
      omegaInv a.a3 a.a1 d)

/-- The preceding degree interface, expanded with the literal bounds
`4d,4d,4d,8d,8d,8d,12d`. -/
theorem connectingSevenScaledRadicandProducts_explicit_natDegree_le
    (a : Coefficients K) (xi eta omegaInv : K) (d : ℕ) :
    let f := incidencePulledRadicand a xi d
    let g := incidencePulledRadicand a eta d
    let h :=
      C omegaInv * centeredNormPulledRadicand a.a3 a.a1 d
    f.natDegree ≤ 4 * d ∧
      g.natDegree ≤ 4 * d ∧
      h.natDegree ≤ 4 * d ∧
      (f * g).natDegree ≤ 8 * d ∧
      (f * h).natDegree ≤ 8 * d ∧
      (g * h).natDegree ≤ 8 * d ∧
      (f * g * h).natDegree ≤ 12 * d := by
  dsimp only
  have hbounds :=
    connectingSevenScaledRadicandProducts_natDegree_le
      a xi eta omegaInv d
  unfold SevenRadicandProductNatDegreeBounds at hbounds
  rcases hbounds with ⟨hf, hg, hh, hfg, hfh, hgh, hfgh⟩
  exact
    ⟨hf, hg, hh, hfg.trans (by omega), hfh.trans (by omega),
      hgh.trans (by omega), hfgh.trans (by omega)⟩

/-- The same seven degree bounds after applying an arbitrary coefficient
ring homomorphism.  In particular this records explicitly that mapping the
scalar-multiplied third radicand does not enlarge its degree. -/
theorem connectingSevenScaledRadicandProducts_map_natDegree_le
    {L : Type v} [Field L] (phi : K →+* L)
    (a : Coefficients K) (xi eta omegaInv : K) (d : ℕ) :
    let f := (incidencePulledRadicand a xi d).map phi
    let g := (incidencePulledRadicand a eta d).map phi
    let h :=
      (C omegaInv *
        centeredNormPulledRadicand a.a3 a.a1 d).map phi
    SevenRadicandProductNatDegreeBounds f g h (4 * d) := by
  dsimp only
  apply sevenRadicandProductNatDegreeBounds_of_le
  · exact Polynomial.natDegree_map_le.trans
      (incidencePulledRadicand_natDegree_le a xi d)
  · exact Polynomial.natDegree_map_le.trans
      (incidencePulledRadicand_natDegree_le a eta d)
  · exact Polynomial.natDegree_map_le.trans
      (scaledCenteredNormPulledRadicand_natDegree_le
        omegaInv a.a3 a.a1 d)

/-- The seven hyperelliptic planes attached to three radicands are
absolutely irreducible over the ground field. -/
def SevenHyperellipticPlanesAbsolutelyIrreducible
    (f g h : K[X]) : Prop :=
  let phi : K →+* AlgebraicClosure K :=
    algebraMap K (AlgebraicClosure K)
  Irreducible
      (MvPolynomial.map phi (hyperellipticPlanePolynomial f)) ∧
    Irreducible
      (MvPolynomial.map phi (hyperellipticPlanePolynomial g)) ∧
    Irreducible
      (MvPolynomial.map phi (hyperellipticPlanePolynomial h)) ∧
    Irreducible
      (MvPolynomial.map phi
        (hyperellipticPlanePolynomial (f * g))) ∧
    Irreducible
      (MvPolynomial.map phi
        (hyperellipticPlanePolynomial (f * h))) ∧
    Irreducible
      (MvPolynomial.map phi
        (hyperellipticPlanePolynomial (g * h))) ∧
    Irreducible
      (MvPolynomial.map phi
        (hyperellipticPlanePolynomial (f * g * h)))

/-- Nonsquareness of a polynomial in the concrete rational-function field
implies nonsquareness in Mathlib's abstract fraction ring. -/
theorem not_isSquare_fractionRing_of_not_isSquare_ratFunc
    {F : Type*} [Field F] {P : F[X]}
    (hnonsquare :
      ¬ IsSquare (algebraMap F[X] (RatFunc F) P)) :
    ¬ IsSquare (algebraMap F[X] (FractionRing F[X]) P) := by
  intro hsquare
  apply hnonsquare
  rcases hsquare with ⟨r, hr⟩
  refine ⟨RatFunc.ofFractionRing r, ?_⟩
  calc
    algebraMap F[X] (RatFunc F) P =
        RatFunc.ofFractionRing
          (algebraMap F[X] (FractionRing F[X]) P) :=
      (RatFunc.ofFractionRing_algebraMap P).symm
    _ = RatFunc.ofFractionRing (r * r) := congrArg _ hr
    _ = RatFunc.ofFractionRing r * RatFunc.ofFractionRing r :=
      RatFunc.ofFractionRing_mul r r

/-- The geometric seven-square-class theorem gives absolute irreducibility
of all seven hyperelliptic planes, including an arbitrary nonzero scalar on
the centered-norm radicand. -/
theorem connectingSevenScaledHyperellipticPlanes_absolutelyIrreducible
    (h2 : (2 : K) ≠ 0)
    {a : Coefficients K} {xi eta omegaInv : K}
    (hA1 : a.a1 ^ 2 ≠ 4)
    (hA2 : a.a2 ^ 2 ≠ 4)
    (hA3 : a.a3 ^ 2 ≠ 4)
    (hmoving : (a.a3, a.a1) ≠ (0, 0))
    (hxi :
      OrderedTraceCandidateRegular a.a1 a.a2 a.a3 xi)
    (heta :
      OrderedTraceCandidateRegular a.a1 a.a2 a.a3 eta)
    (hpair : IsConnectingIncidencePair a xi eta)
    {d : ℕ} (hd : 0 < d) (hdegree : (d : K) ≠ 0)
    (homegaInv : omegaInv ≠ 0) :
    let f := incidencePulledRadicand a xi d
    let g := incidencePulledRadicand a eta d
    let h :=
      C omegaInv * centeredNormPulledRadicand a.a3 a.a1 d
    SevenHyperellipticPlanesAbsolutelyIrreducible f g h := by
  dsimp only
  let phi : K →+* AlgebraicClosure K :=
    algebraMap K (AlgebraicClosure K)
  have homegaInvMap : phi omegaInv ≠ 0 :=
    (map_ne_zero_iff phi phi.injective).2 homegaInv
  obtain ⟨hf, hg, hh, hfg, hfh, hgh, hfgh⟩ :=
    connectingSevenOriginalRadicandProducts_scalarMultiples_not_isSquare_algebraicClosure
      h2 hA1 hA2 hA3 hmoving hxi heta hpair hd hdegree
      (cf := 1) (cg := 1) (ch := phi omegaInv)
      (cfg := 1) (cfh := phi omegaInv)
      (cgh := phi omegaInv) (cfgh := phi omegaInv)
      one_ne_zero one_ne_zero homegaInvMap one_ne_zero
      homegaInvMap homegaInvMap homegaInvMap
  unfold SevenHyperellipticPlanesAbsolutelyIrreducible
  dsimp only
  refine ⟨?_, ?_, ?_, ?_, ?_, ?_, ?_⟩
  · apply
      hyperellipticPlanePolynomial_absolutelyIrreducible_of_not_isSquare_map
    apply not_isSquare_fractionRing_of_not_isSquare_ratFunc
    simpa [map_mul, map_C, mul_assoc, mul_left_comm, mul_comm] using hf
  · apply
      hyperellipticPlanePolynomial_absolutelyIrreducible_of_not_isSquare_map
    apply not_isSquare_fractionRing_of_not_isSquare_ratFunc
    simpa [map_mul, map_C, mul_assoc, mul_left_comm, mul_comm] using hg
  · apply
      hyperellipticPlanePolynomial_absolutelyIrreducible_of_not_isSquare_map
    apply not_isSquare_fractionRing_of_not_isSquare_ratFunc
    simpa [map_mul, map_C, mul_assoc, mul_left_comm, mul_comm] using hh
  · apply
      hyperellipticPlanePolynomial_absolutelyIrreducible_of_not_isSquare_map
    apply not_isSquare_fractionRing_of_not_isSquare_ratFunc
    simpa [map_mul, map_C, mul_assoc, mul_left_comm, mul_comm] using hfg
  · apply
      hyperellipticPlanePolynomial_absolutelyIrreducible_of_not_isSquare_map
    apply not_isSquare_fractionRing_of_not_isSquare_ratFunc
    simpa [map_mul, map_C, mul_assoc, mul_left_comm, mul_comm] using hfh
  · apply
      hyperellipticPlanePolynomial_absolutelyIrreducible_of_not_isSquare_map
    apply not_isSquare_fractionRing_of_not_isSquare_ratFunc
    simpa [map_mul, map_C, mul_assoc, mul_left_comm, mul_comm] using hgh
  · apply
      hyperellipticPlanePolynomial_absolutelyIrreducible_of_not_isSquare_map
    apply not_isSquare_fractionRing_of_not_isSquare_ratFunc
    simpa [map_mul, map_C, mul_assoc, mul_left_comm, mul_comm] using hfgh

section FiniteFieldCount

variable [Fintype K] [DecidableEq K]

/-- The signed real error of a hyperelliptic square-root cover count from
the finite-field main term. -/
def squareRootCoverPointCountError (P : K[X]) : ℝ :=
  ((squareRootCoverPointCount
      (fun parameter : K => P.eval parameter) : ℤ) : ℝ) -
    (Fintype.card K : ℝ)

/-- The coefficient-eight affine Hasse--Weil error interface for a
hyperelliptic cover of supplied radicand degree `D`. -/
def SquareRootCoverPointCountErrorAtMost
    (P : K[X]) (D : ℕ) : Prop :=
  |squareRootCoverPointCountError P| ≤
    16 * Real.sqrt (Fintype.card K : ℝ) * D

/-- A geometrically irreducible hyperelliptic plane satisfies the
coefficient-eight affine Hasse--Weil estimate.  Unlike the squarefree
adapter in `HyperellipticPlane`, this statement also applies when the
radicand contains a visible polynomial square factor. -/
theorem squareRootCoverPointCount_error_le_of_absolutelyIrreducible
    {P : K[X]}
    (habsolute :
      Irreducible
        (MvPolynomial.map
          (algebraMap K (AlgebraicClosure K))
          (hyperellipticPlanePolynomial P)))
    {D : ℕ} (hD : 0 < D) (hdegree : P.natDegree ≤ D) :
    SquareRootCoverPointCountErrorAtMost P D := by
  have hbound :=
    BGS.HasseWeil.abs_affinePlaneCurveZeros_card_sub_card_le_eight_mul_bidegree
      K (hyperellipticPlanePolynomial P) 2 D
      (by norm_num) hD
      (hyperellipticPlanePolynomial_hasBidegreeAtMost P hdegree)
      habsolute
  have hcountReal :
      ((squareRootCoverPointCount
          (fun parameter : K => P.eval parameter) : ℤ) : ℝ) =
        ((BGS.External.affinePlaneCurveZeros K
          (hyperellipticPlanePolynomial P)).card : ℝ) := by
    have hcountInt :=
      (hyperellipticPlaneZeros_card_int_eq_squareRootCoverPointCount
        P).symm
    exact_mod_cast hcountInt
  unfold SquareRootCoverPointCountErrorAtMost
  unfold squareRootCoverPointCountError
  rw [hcountReal]
  calc
    |((BGS.External.affinePlaneCurveZeros K
          (hyperellipticPlanePolynomial P)).card : ℝ) -
        (Fintype.card K : ℝ)| ≤
        (8 : ℝ) * Real.sqrt (Fintype.card K : ℝ) *
          (((2 : ℕ) : ℝ)) * (D : ℝ) :=
      hbound
    _ = 16 * Real.sqrt (Fintype.card K : ℝ) * D := by
      ring

/-- A radicand that remains nonsquare after scalar extension satisfies the
same square-root-cover Hasse--Weil estimate. -/
theorem squareRootCoverPointCount_error_le_of_not_isSquare_map
    {P : K[X]}
    (hnonsquare :
      ¬ IsSquare
        (algebraMap
          (Polynomial (AlgebraicClosure K))
          (FractionRing (Polynomial (AlgebraicClosure K)))
          (P.map (algebraMap K (AlgebraicClosure K)))))
    {D : ℕ} (hD : 0 < D) (hdegree : P.natDegree ≤ D) :
    SquareRootCoverPointCountErrorAtMost P D :=
  squareRootCoverPointCount_error_le_of_absolutelyIrreducible
    (hyperellipticPlanePolynomial_absolutelyIrreducible_of_not_isSquare_map
      hnonsquare)
    hD hdegree

/-- Hasse--Weil error bounds for the seven nonempty products generated by
three radicands of degree at most `D`. -/
def SevenSquareRootCoverPointCountErrorsAtMost
    (f g h : K[X]) (D : ℕ) : Prop :=
  SquareRootCoverPointCountErrorAtMost f D ∧
    SquareRootCoverPointCountErrorAtMost g D ∧
    SquareRootCoverPointCountErrorAtMost h D ∧
    SquareRootCoverPointCountErrorAtMost (f * g) (2 * D) ∧
    SquareRootCoverPointCountErrorAtMost (f * h) (2 * D) ∧
    SquareRootCoverPointCountErrorAtMost (g * h) (2 * D) ∧
    SquareRootCoverPointCountErrorAtMost (f * g * h) (3 * D)

/-- Seven degree bounds and seven geometric irreducibility statements
produce the corresponding seven cover-count estimates. -/
theorem sevenSquareRootCoverPointCountErrorsAtMost_of_degreeBounds
    {f g h : K[X]} {D : ℕ} (hD : 0 < D)
    (hdegree :
      SevenRadicandProductNatDegreeBounds f g h D)
    (habsolute :
      SevenHyperellipticPlanesAbsolutelyIrreducible f g h) :
    SevenSquareRootCoverPointCountErrorsAtMost f g h D := by
  rcases hdegree with
    ⟨hfDegree, hgDegree, hhDegree, hfgDegree,
      hfhDegree, hghDegree, hfghDegree⟩
  unfold SevenHyperellipticPlanesAbsolutelyIrreducible at habsolute
  dsimp only at habsolute
  rcases habsolute with
    ⟨hfAbsolute, hgAbsolute, hhAbsolute, hfgAbsolute,
      hfhAbsolute, hghAbsolute, hfghAbsolute⟩
  exact
    ⟨squareRootCoverPointCount_error_le_of_absolutelyIrreducible
        hfAbsolute hD hfDegree,
      squareRootCoverPointCount_error_le_of_absolutelyIrreducible
        hgAbsolute hD hgDegree,
      squareRootCoverPointCount_error_le_of_absolutelyIrreducible
        hhAbsolute hD hhDegree,
      squareRootCoverPointCount_error_le_of_absolutelyIrreducible
        hfgAbsolute (by omega) hfgDegree,
      squareRootCoverPointCount_error_le_of_absolutelyIrreducible
        hfhAbsolute (by omega) hfhDegree,
      squareRootCoverPointCount_error_le_of_absolutelyIrreducible
        hghAbsolute (by omega) hghDegree,
      squareRootCoverPointCount_error_le_of_absolutelyIrreducible
        hfghAbsolute (by omega) hfghDegree⟩

/-- The unequal connecting radicands, with an arbitrary nonzero inverse
character scalar on the centered-norm radicand, satisfy all seven
square-root-cover Hasse--Weil estimates. -/
theorem connectingSevenScaledSquareRootCoverPointCount_errors_le
    (hchar : ringChar K ≠ 2)
    {a : Coefficients K} {xi eta omegaInv : K}
    (hA1 : a.a1 ^ 2 ≠ 4)
    (hA2 : a.a2 ^ 2 ≠ 4)
    (hA3 : a.a3 ^ 2 ≠ 4)
    (hmoving : (a.a3, a.a1) ≠ (0, 0))
    (hxi :
      OrderedTraceCandidateRegular a.a1 a.a2 a.a3 xi)
    (heta :
      OrderedTraceCandidateRegular a.a1 a.a2 a.a3 eta)
    (hpair : IsConnectingIncidencePair a xi eta)
    {d : ℕ} (hd : 0 < d) (hdegree : (d : K) ≠ 0)
    (homegaInv : omegaInv ≠ 0) :
    let f := incidencePulledRadicand a xi d
    let g := incidencePulledRadicand a eta d
    let h :=
      C omegaInv * centeredNormPulledRadicand a.a3 a.a1 d
    SevenSquareRootCoverPointCountErrorsAtMost f g h (4 * d) := by
  dsimp only
  apply sevenSquareRootCoverPointCountErrorsAtMost_of_degreeBounds
    (by omega)
  · exact connectingSevenScaledRadicandProducts_natDegree_le
      a xi eta omegaInv d
  · exact connectingSevenScaledHyperellipticPlanes_absolutelyIrreducible
      (Ring.two_ne_zero hchar) hA1 hA2 hA3 hmoving
      hxi heta hpair hd hdegree homegaInv

/-- The sum of the seven absolute cover-count errors is at most
`192 D sqrt(|K|)` when the three original radicands have degree at most
`D`. -/
theorem sevenSquareRootCoverPointCount_sum_abs_error_le
    {f g h : K[X]} {D : ℕ}
    (herrors :
      SevenSquareRootCoverPointCountErrorsAtMost f g h D) :
    |squareRootCoverPointCountError f| +
        |squareRootCoverPointCountError g| +
        |squareRootCoverPointCountError h| +
        |squareRootCoverPointCountError (f * g)| +
        |squareRootCoverPointCountError (f * h)| +
        |squareRootCoverPointCountError (g * h)| +
        |squareRootCoverPointCountError (f * g * h)| ≤
      192 * D * Real.sqrt (Fintype.card K : ℝ) := by
  unfold SevenSquareRootCoverPointCountErrorsAtMost at herrors
  unfold SquareRootCoverPointCountErrorAtMost at herrors
  rcases herrors with ⟨hf, hg, hh, hfg, hfh, hgh, hfgh⟩
  calc
    |squareRootCoverPointCountError f| +
          |squareRootCoverPointCountError g| +
          |squareRootCoverPointCountError h| +
          |squareRootCoverPointCountError (f * g)| +
          |squareRootCoverPointCountError (f * h)| +
          |squareRootCoverPointCountError (g * h)| +
          |squareRootCoverPointCountError (f * g * h)| ≤
          16 * Real.sqrt (Fintype.card K : ℝ) * D +
          16 * Real.sqrt (Fintype.card K : ℝ) * D +
          16 * Real.sqrt (Fintype.card K : ℝ) * D +
          16 * Real.sqrt (Fintype.card K : ℝ) *
            ((2 * D : ℕ) : ℝ) +
          16 * Real.sqrt (Fintype.card K : ℝ) *
            ((2 * D : ℕ) : ℝ) +
          16 * Real.sqrt (Fintype.card K : ℝ) *
            ((2 * D : ℕ) : ℝ) +
          16 * Real.sqrt (Fintype.card K : ℝ) *
            ((3 * D : ℕ) : ℝ) := by
      exact
        add_le_add
          (add_le_add
            (add_le_add
              (add_le_add
                (add_le_add
                  (add_le_add hf hg) hh)
                hfg)
              hfh)
            hgh)
          hfgh
    _ = 192 * D * Real.sqrt (Fintype.card K : ℝ) := by
      push_cast
      ring

/-- For the unequal connecting radicands, the seven absolute errors sum to
at most `768 d sqrt(|K|)`. -/
theorem connectingSevenScaledSquareRootCoverPointCount_sum_abs_error_le
    (hchar : ringChar K ≠ 2)
    {a : Coefficients K} {xi eta omegaInv : K}
    (hA1 : a.a1 ^ 2 ≠ 4)
    (hA2 : a.a2 ^ 2 ≠ 4)
    (hA3 : a.a3 ^ 2 ≠ 4)
    (hmoving : (a.a3, a.a1) ≠ (0, 0))
    (hxi :
      OrderedTraceCandidateRegular a.a1 a.a2 a.a3 xi)
    (heta :
      OrderedTraceCandidateRegular a.a1 a.a2 a.a3 eta)
    (hpair : IsConnectingIncidencePair a xi eta)
    {d : ℕ} (hd : 0 < d) (hdegree : (d : K) ≠ 0)
    (homegaInv : omegaInv ≠ 0) :
    let f := incidencePulledRadicand a xi d
    let g := incidencePulledRadicand a eta d
    let h :=
      C omegaInv * centeredNormPulledRadicand a.a3 a.a1 d
    |squareRootCoverPointCountError f| +
        |squareRootCoverPointCountError g| +
        |squareRootCoverPointCountError h| +
        |squareRootCoverPointCountError (f * g)| +
        |squareRootCoverPointCountError (f * h)| +
        |squareRootCoverPointCountError (g * h)| +
        |squareRootCoverPointCountError (f * g * h)| ≤
      768 * d * Real.sqrt (Fintype.card K : ℝ) := by
  dsimp only
  have herrors :=
    connectingSevenScaledSquareRootCoverPointCount_errors_le
      hchar hA1 hA2 hA3 hmoving hxi heta hpair
      hd hdegree homegaInv
  calc
    |squareRootCoverPointCountError
          (incidencePulledRadicand a xi d)| +
        |squareRootCoverPointCountError
          (incidencePulledRadicand a eta d)| +
        |squareRootCoverPointCountError
          (C omegaInv *
            centeredNormPulledRadicand a.a3 a.a1 d)| +
        |squareRootCoverPointCountError
          (incidencePulledRadicand a xi d *
            incidencePulledRadicand a eta d)| +
        |squareRootCoverPointCountError
          (incidencePulledRadicand a xi d *
            (C omegaInv *
              centeredNormPulledRadicand a.a3 a.a1 d))| +
        |squareRootCoverPointCountError
          (incidencePulledRadicand a eta d *
            (C omegaInv *
              centeredNormPulledRadicand a.a3 a.a1 d))| +
        |squareRootCoverPointCountError
          (incidencePulledRadicand a xi d *
            incidencePulledRadicand a eta d *
              (C omegaInv *
                centeredNormPulledRadicand a.a3 a.a1 d))| ≤
        192 * ((4 * d : ℕ) : ℝ) *
          Real.sqrt (Fintype.card K : ℝ) :=
      sevenSquareRootCoverPointCount_sum_abs_error_le herrors
    _ = 768 * d * Real.sqrt (Fintype.card K : ℝ) := by
      push_cast
      ring

end FiniteFieldCount

end

end GenMarkoff.General.Cage
