name = "docbuild"
version = "0.1.0"
reservoir = false
packagesDir = "../.lake/packages"

[[require]]
scope = "leanprover"
name = "doc-gen4"
git = "https://github.com/leanprover/doc-gen4.git"
rev = "v4.32.0"

[[require]]
name = "GenMarkoff"
path = "../"
