import GenMarkoff.Core.Statements

/-!
# Transferring orbit divisibility to the rotation subgroup

The generalized Martin theorem concerns the group generated by the three
individual Vieta involutions, whereas the rotation graph uses three products
of two Vieta involutions.  This file proves that the latter subgroup has at
most two orbits inside each Vieta orbit, and that the two possible rotation
orbits have the same cardinality.  Consequently divisibility by an odd prime
transfers from Vieta orbits to rotation orbits.
-/

namespace GenMarkoff

universe u

private abbrev SurfacePerm {R : Type u} [CommRing R] (a : Coefficients R) :=
  Equiv.Perm (SolutionSurface a)

@[simp]
private theorem vieta1SurfacePerm_mul_self {R : Type u} [CommRing R]
    (a : Coefficients R) :
    vieta1SurfacePerm a * vieta1SurfacePerm a = 1 := by
  apply Equiv.ext
  intro x
  apply Subtype.ext
  exact vieta1_involutive a x

@[simp]
private theorem vieta2SurfacePerm_mul_self {R : Type u} [CommRing R]
    (a : Coefficients R) :
    vieta2SurfacePerm a * vieta2SurfacePerm a = 1 := by
  apply Equiv.ext
  intro x
  apply Subtype.ext
  exact vieta2_involutive a x

@[simp]
private theorem vieta3SurfacePerm_mul_self {R : Type u} [CommRing R]
    (a : Coefficients R) :
    vieta3SurfacePerm a * vieta3SurfacePerm a = 1 := by
  apply Equiv.ext
  intro x
  apply Subtype.ext
  exact vieta3_involutive a x

@[simp]
private theorem vieta1SurfacePerm_inv {R : Type u} [CommRing R]
    (a : Coefficients R) :
    (vieta1SurfacePerm a)⁻¹ = vieta1SurfacePerm a := by
  exact inv_eq_of_mul_eq_one_right (vieta1SurfacePerm_mul_self a)

@[simp]
private theorem vieta2SurfacePerm_inv {R : Type u} [CommRing R]
    (a : Coefficients R) :
    (vieta2SurfacePerm a)⁻¹ = vieta2SurfacePerm a := by
  exact inv_eq_of_mul_eq_one_right (vieta2SurfacePerm_mul_self a)

@[simp]
private theorem vieta3SurfacePerm_inv {R : Type u} [CommRing R]
    (a : Coefficients R) :
    (vieta3SurfacePerm a)⁻¹ = vieta3SurfacePerm a := by
  exact inv_eq_of_mul_eq_one_right (vieta3SurfacePerm_mul_self a)

private theorem rotation1SurfacePerm_eq {R : Type u} [CommRing R]
    (a : Coefficients R) :
    rotation1SurfacePerm a = vieta3SurfacePerm a * vieta2SurfacePerm a := by
  rfl

private theorem rotation2SurfacePerm_eq {R : Type u} [CommRing R]
    (a : Coefficients R) :
    rotation2SurfacePerm a = vieta1SurfacePerm a * vieta3SurfacePerm a := by
  rfl

private theorem rotation3SurfacePerm_eq {R : Type u} [CommRing R]
    (a : Coefficients R) :
    rotation3SurfacePerm a = vieta2SurfacePerm a * vieta1SurfacePerm a := by
  rfl

theorem RotationGroup_le_VietaGroup {R : Type u} [CommRing R]
    (a : Coefficients R) :
    RotationGroup a ≤ VietaGroup a := by
  apply (Subgroup.closure_le (VietaGroup a)).2
  intro g hg
  simp only [rotationGenerators, Set.mem_insert_iff, Set.mem_singleton_iff] at hg
  rcases hg with rfl | rfl | rfl
  · rw [rotation1SurfacePerm_eq]
    exact (VietaGroup a).mul_mem
      (Subgroup.subset_closure (by simp [vietaGenerators]))
      (Subgroup.subset_closure (by simp [vietaGenerators]))
  · rw [rotation2SurfacePerm_eq]
    exact (VietaGroup a).mul_mem
      (Subgroup.subset_closure (by simp [vietaGenerators]))
      (Subgroup.subset_closure (by simp [vietaGenerators]))
  · rw [rotation3SurfacePerm_eq]
    exact (VietaGroup a).mul_mem
      (Subgroup.subset_closure (by simp [vietaGenerators]))
      (Subgroup.subset_closure (by simp [vietaGenerators]))

private theorem pair_mem_rotation_of_generators {R : Type u} [CommRing R]
    (a : Coefficients R) {g h : SurfacePerm a}
    (hg : g ∈ vietaGenerators a) (hh : h ∈ vietaGenerators a) :
    g * h ∈ RotationGroup a := by
  simp only [vietaGenerators, Set.mem_insert_iff, Set.mem_singleton_iff] at hg hh
  rcases hg with rfl | rfl | rfl <;> rcases hh with rfl | rfl | rfl
  · simp
  · have hmem := (RotationGroup a).inv_mem
      (Subgroup.subset_closure (by simp [rotationGenerators]) :
        rotation3SurfacePerm a ∈ RotationGroup a)
    simpa [rotation3SurfacePerm_eq] using hmem
  · rw [← rotation2SurfacePerm_eq]
    exact Subgroup.subset_closure (by simp [rotationGenerators])
  · rw [← rotation3SurfacePerm_eq]
    exact Subgroup.subset_closure (by simp [rotationGenerators])
  · simp
  · have hmem := (RotationGroup a).inv_mem
      (Subgroup.subset_closure (by simp [rotationGenerators]) :
        rotation1SurfacePerm a ∈ RotationGroup a)
    simpa [rotation1SurfacePerm_eq] using hmem
  · have hmem := (RotationGroup a).inv_mem
      (Subgroup.subset_closure (by simp [rotationGenerators]) :
        rotation2SurfacePerm a ∈ RotationGroup a)
    simpa [rotation2SurfacePerm_eq] using hmem
  · rw [← rotation1SurfacePerm_eq]
    exact Subgroup.subset_closure (by simp [rotationGenerators])
  · simp

private theorem generator_inv_eq_self {R : Type u} [CommRing R]
    (a : Coefficients R) {g : SurfacePerm a} (hg : g ∈ vietaGenerators a) :
    g⁻¹ = g := by
  simp only [vietaGenerators, Set.mem_insert_iff, Set.mem_singleton_iff] at hg
  rcases hg with rfl | rfl | rfl <;> simp

private theorem rotation_parity_step {R : Type u} [CommRing R]
    (a : Coefficients R) {g s : SurfacePerm a}
    (hs : s ∈ vietaGenerators a)
    (hg : g ∈ RotationGroup a ∨ g * vieta1SurfacePerm a ∈ RotationGroup a) :
    g * s ∈ RotationGroup a ∨
      (g * s) * vieta1SurfacePerm a ∈ RotationGroup a := by
  rcases hg with hg | hg
  · right
    rw [mul_assoc]
    exact (RotationGroup a).mul_mem hg
      (pair_mem_rotation_of_generators a hs (by simp [vietaGenerators]))
  · left
    have hpair : vieta1SurfacePerm a * s ∈ RotationGroup a :=
      pair_mem_rotation_of_generators a (by simp [vietaGenerators]) hs
    have hmul := (RotationGroup a).mul_mem hg hpair
    rw [mul_assoc, ← mul_assoc (vieta1SurfacePerm a) (vieta1SurfacePerm a) s,
      vieta1SurfacePerm_mul_self, one_mul] at hmul
    exact hmul

/-- Every Vieta-group element is either a rotation word or becomes one after
right multiplication by the first Vieta involution. -/
theorem mem_rotation_or_mul_vieta1_mem_rotation {R : Type u} [CommRing R]
    (a : Coefficients R) (g : VietaGroup a) :
    (g : SurfacePerm a) ∈ RotationGroup a ∨
      (g : SurfacePerm a) * vieta1SurfacePerm a ∈ RotationGroup a := by
  rcases g with ⟨g, hg⟩
  change g ∈ RotationGroup a ∨ g * vieta1SurfacePerm a ∈ RotationGroup a
  induction hg using Subgroup.closure_induction_right with
  | one => exact Or.inl (RotationGroup a).one_mem
  | mul_right x hx y hy ih =>
      exact rotation_parity_step a hy ih
  | mul_inv_cancel x hx y hy ih =>
      rw [generator_inv_eq_self a hy]
      exact rotation_parity_step a hy ih

private theorem vieta1_conjugates_rotationGroup {R : Type u} [CommRing R]
    (a : Coefficients R) {g : SurfacePerm a} (hg : g ∈ RotationGroup a) :
    vieta1SurfacePerm a * g * (vieta1SurfacePerm a)⁻¹ ∈ RotationGroup a := by
  induction hg using Subgroup.closure_induction with
  | mem g hg =>
      simp only [rotationGenerators, Set.mem_insert_iff, Set.mem_singleton_iff] at hg
      rcases hg with rfl | rfl | rfl
      · rw [rotation1SurfacePerm_eq]
        have hleft : vieta1SurfacePerm a * vieta3SurfacePerm a ∈ RotationGroup a :=
          pair_mem_rotation_of_generators a (by simp [vietaGenerators])
            (by simp [vietaGenerators])
        have hright : vieta2SurfacePerm a * (vieta1SurfacePerm a)⁻¹ ∈ RotationGroup a := by
          rw [vieta1SurfacePerm_inv]
          exact pair_mem_rotation_of_generators a (by simp [vietaGenerators])
            (by simp [vietaGenerators])
        simpa only [mul_assoc] using (RotationGroup a).mul_mem hleft hright
      · rw [rotation2SurfacePerm_eq]
        have hleft : vieta1SurfacePerm a * vieta1SurfacePerm a ∈ RotationGroup a :=
          pair_mem_rotation_of_generators a (by simp [vietaGenerators])
            (by simp [vietaGenerators])
        have hright : vieta3SurfacePerm a * (vieta1SurfacePerm a)⁻¹ ∈ RotationGroup a := by
          rw [vieta1SurfacePerm_inv]
          exact pair_mem_rotation_of_generators a (by simp [vietaGenerators])
            (by simp [vietaGenerators])
        simpa only [mul_assoc] using (RotationGroup a).mul_mem hleft hright
      · rw [rotation3SurfacePerm_eq]
        have hleft : vieta1SurfacePerm a * vieta2SurfacePerm a ∈ RotationGroup a :=
          pair_mem_rotation_of_generators a (by simp [vietaGenerators])
            (by simp [vietaGenerators])
        have hright : vieta1SurfacePerm a * (vieta1SurfacePerm a)⁻¹ ∈ RotationGroup a := by
          rw [vieta1SurfacePerm_inv]
          exact pair_mem_rotation_of_generators a (by simp [vietaGenerators])
            (by simp [vietaGenerators])
        simpa only [mul_assoc] using (RotationGroup a).mul_mem hleft hright
  | one => simp
  | mul x y hx hy ihx ihy =>
      rw [show vieta1SurfacePerm a * (x * y) * (vieta1SurfacePerm a)⁻¹ =
        (vieta1SurfacePerm a * x * (vieta1SurfacePerm a)⁻¹) *
          (vieta1SurfacePerm a * y * (vieta1SurfacePerm a)⁻¹) by group]
      exact (RotationGroup a).mul_mem ihx ihy
  | inv x hx ih =>
      rw [show vieta1SurfacePerm a * x⁻¹ * (vieta1SurfacePerm a)⁻¹ =
        (vieta1SurfacePerm a * x * (vieta1SurfacePerm a)⁻¹)⁻¹ by group]
      exact (RotationGroup a).inv_mem ih

@[simp]
private theorem vieta1InVietaGroup_inv {R : Type u} [CommRing R]
    (a : Coefficients R) :
    (vieta1InVietaGroup a)⁻¹ = vieta1InVietaGroup a := by
  apply Subtype.ext
  exact vieta1SurfacePerm_inv a

@[simp]
private theorem vieta1InVietaGroup_smul_self {R : Type u} [CommRing R]
    (a : Coefficients R) (x : PuncturedSolutionSurface a) :
    vieta1InVietaGroup a • (vieta1InVietaGroup a • x) = x := by
  simpa only [vieta1InVietaGroup_inv] using
    (inv_smul_smul (vieta1InVietaGroup a) x)

/-- A Vieta orbit is the union of the rotation orbit of `x` and the rotation
orbit of its first Vieta transform. -/
theorem puncturedVietaOrbit_eq_rotation_union {R : Type u} [CommRing R]
    (a : Coefficients R) (x : PuncturedSolutionSurface a) :
    puncturedVietaOrbit x =
      puncturedRotationOrbit x ∪
        puncturedRotationOrbit (vieta1InVietaGroup a • x) := by
  ext y
  constructor
  · rintro ⟨g, rfl⟩
    rcases mem_rotation_or_mul_vieta1_mem_rotation a g with hg | hg
    · left
      let h : RotationGroup a := ⟨g, hg⟩
      refine ⟨h, ?_⟩
      apply Subtype.ext
      rfl
    · right
      let h : RotationGroup a := ⟨(g : SurfacePerm a) * vieta1SurfacePerm a, hg⟩
      refine ⟨h, ?_⟩
      apply Subtype.ext
      change ((g : SurfacePerm a) * vieta1SurfacePerm a)
          (vieta1SurfacePerm a x.1) = (g : SurfacePerm a) x.1
      rw [← Equiv.Perm.mul_apply, mul_assoc, vieta1SurfacePerm_mul_self, mul_one]
  · rintro (hy | hy)
    · rcases hy with ⟨h, rfl⟩
      let g : VietaGroup a := ⟨h, RotationGroup_le_VietaGroup a h.2⟩
      refine ⟨g, ?_⟩
      apply Subtype.ext
      rfl
    · rcases hy with ⟨h, rfl⟩
      have hg : (h : SurfacePerm a) * vieta1SurfacePerm a ∈ VietaGroup a :=
        (VietaGroup a).mul_mem (RotationGroup_le_VietaGroup a h.2)
          (Subgroup.subset_closure (by simp [vietaGenerators]))
      let g : VietaGroup a := ⟨(h : SurfacePerm a) * vieta1SurfacePerm a, hg⟩
      refine ⟨g, ?_⟩
      apply Subtype.ext
      rfl

private theorem vieta1_smul_mem_rotationOrbit {R : Type u} [CommRing R]
    (a : Coefficients R) (x : PuncturedSolutionSurface a)
    {y : PuncturedSolutionSurface a} (hy : y ∈ puncturedRotationOrbit x) :
    vieta1InVietaGroup a • y ∈
      puncturedRotationOrbit (vieta1InVietaGroup a • x) := by
  rcases hy with ⟨h, rfl⟩
  let h' : RotationGroup a :=
    ⟨vieta1SurfacePerm a * (h : SurfacePerm a) * (vieta1SurfacePerm a)⁻¹,
      vieta1_conjugates_rotationGroup a h.2⟩
  refine ⟨h', ?_⟩
  apply Subtype.ext
  change (vieta1SurfacePerm a * (h : SurfacePerm a) * (vieta1SurfacePerm a)⁻¹)
      (vieta1SurfacePerm a x.1) =
    vieta1SurfacePerm a ((h : SurfacePerm a) x.1)
  rw [← Equiv.Perm.mul_apply, ← Equiv.Perm.mul_apply]
  congr 1
  group

private theorem vieta1_smul_mem_rotationOrbit_reverse {R : Type u} [CommRing R]
    (a : Coefficients R) (x : PuncturedSolutionSurface a)
    {y : PuncturedSolutionSurface a}
    (hy : y ∈ puncturedRotationOrbit (vieta1InVietaGroup a • x)) :
    vieta1InVietaGroup a • y ∈ puncturedRotationOrbit x := by
  have h := vieta1_smul_mem_rotationOrbit a (vieta1InVietaGroup a • x) hy
  simpa only [vieta1InVietaGroup_smul_self] using h

/-- Applying the first Vieta involution gives an equivalence between the two
possible rotation orbits inside a Vieta orbit. -/
noncomputable def rotationOrbitVieta1Equiv {R : Type u} [CommRing R]
    (a : Coefficients R) (x : PuncturedSolutionSurface a) :
    puncturedRotationOrbit x ≃
      puncturedRotationOrbit (vieta1InVietaGroup a • x) where
  toFun y := ⟨vieta1InVietaGroup a • y.1,
    vieta1_smul_mem_rotationOrbit a x y.2⟩
  invFun y := ⟨vieta1InVietaGroup a • y.1,
    vieta1_smul_mem_rotationOrbit_reverse a x y.2⟩
  left_inv y := Subtype.ext (vieta1InVietaGroup_smul_self a y.1)
  right_inv y := Subtype.ext (vieta1InVietaGroup_smul_self a y.1)

/-- The two possible rotation orbits inside a Vieta orbit have equal
cardinality. -/
theorem ncard_rotationOrbit_vieta1_eq {R : Type u} [CommRing R]
    (a : Coefficients R) (x : PuncturedSolutionSurface a) :
    (puncturedRotationOrbit (vieta1InVietaGroup a • x)).ncard =
      (puncturedRotationOrbit x).ncard := by
  exact (Set.ncard_congr' (rotationOrbitVieta1Equiv a x)).symm

/-- For a prime at least five, divisibility of one Vieta orbit implies
divisibility of the rotation orbit through the same point. -/
theorem prime_dvd_puncturedRotationOrbit_ncard_of_vieta
    (p : ℕ) (hp : p.Prime) (hpFive : 5 ≤ p)
    {R : Type u} [CommRing R] [Fintype R]
    (a : Coefficients R) (x : PuncturedSolutionSurface a)
    (hdiv : p ∣ (puncturedVietaOrbit x).ncard) :
    p ∣ (puncturedRotationOrbit x).ncard := by
  classical
  rw [puncturedVietaOrbit_eq_rotation_union a x] at hdiv
  rcases MulAction.orbit.eq_or_disjoint
      (G := RotationGroup a) x (vieta1InVietaGroup a • x) with heq | hdisjoint
  · change puncturedRotationOrbit x =
      puncturedRotationOrbit (vieta1InVietaGroup a • x) at heq
    rw [heq, Set.union_self] at hdiv
    exact heq.symm ▸ hdiv
  · change Disjoint (puncturedRotationOrbit x)
      (puncturedRotationOrbit (vieta1InVietaGroup a • x)) at hdisjoint
    rw [Set.ncard_union_eq hdisjoint, ncard_rotationOrbit_vieta1_eq a x] at hdiv
    rw [← two_mul] at hdiv
    have hpNotDvdTwo : ¬p ∣ 2 := by
      intro hpTwo
      have hpLeTwo : p ≤ 2 := Nat.le_of_dvd (by omega) hpTwo
      omega
    exact (hp.dvd_mul.mp hdiv).resolve_left hpNotDvdTwo

/-- Generalized Martin divisibility for the Vieta group transfers to the
rotation group used by the generalized Markoff graph. -/
theorem rotationOrbitDivisibility_of_vietaOrbitDivisibility
    (p : ℕ) (hp : p.Prime) (hpFive : 5 ≤ p) (a : Coefficients (ZMod p)) :
    VietaOrbitDivisibility p hp a → RotationOrbitDivisibility p hp a := by
  letI : Fact p.Prime := ⟨hp⟩
  change
    (∀ x : PuncturedSolutionSurface a, p ∣ (puncturedVietaOrbit x).ncard) →
      ∀ x : PuncturedSolutionSurface a, p ∣ (puncturedRotationOrbit x).ncard
  intro hVieta x
  exact prime_dvd_puncturedRotationOrbit_ncard_of_vieta p hp hpFive a x (hVieta x)

end GenMarkoff
