import BGS.Markoff.Core.ConicParametrization
import BGS.Markoff.MiddleGame.CorvajaZannierStep
import BGS.Markoff.TraceCurve.Geometry

/-!
# Wiring the middle-game trace escape to Markoff moves

The orbit of a split fiber point with parameter `s` is parametrized by the coset
`s * Subgroup.zpowers w`.  Its second coordinate is therefore a *scaled* twisted trace, not
the unscaled subgroup trace used in `MiddleGameCorvajaZannierStep`.  The first two theorems make
this discrepancy explicit.

For the distinguished parameter `s = 1`, the scaling disappears.  The final theorem wires the
existing Corvaja--Zannier escape theorem all the way to a point in the same rotation orbit whose
second coordinate has strictly larger rotation order.  Its remaining `htraceCoverage` hypothesis
states the separate split/nonsplit classification interface that must be constructed for the
chosen family of right subgroups.
-/

namespace BGS.Markoff

variable {E : Type*} [Field E]

/-- The exact second-coordinate formula on a translated split rotation orbit.  The factor `s`
and the replacement of `splitFiberProduct w` by `splitFiberProduct w / s^2` are indispensable. -/
theorem splitFiberOrbit_secondCoordinate_eq_scaledTwistedTrace
    (w s h : Eˣ) :
    (splitFiberPoint w (s * h)).u2 =
      (s : E) * twistedUnitTrace
        (splitFiberProduct w / (s : E) ^ 2) h := by
  simp only [splitFiberPoint, twistedUnitTrace]
  change (s : E) * h +
      splitFiberProduct w * (((s * h)⁻¹ : Eˣ) : E) =
    (s : E) *
      ((h : E) + (splitFiberProduct w / (s : E) ^ 2) * ((h⁻¹ : Eˣ) : E))
  simp only [Units.val_mul, Units.val_inv_eq_inv_val]
  field_simp [Units.ne_zero s, Units.ne_zero h]

/-- Source-faithful weighted form of the orbit-coordinate identity.  Here
`alpha = s`, `beta = splitFiberProduct w / s`, and hence `alpha * beta` is the invariant
`splitFiberProduct w`.  This is the correct subgroup equation for an arbitrary starting point;
it avoids incorrectly replacing a coset by a subgroup. -/
theorem splitFiberOrbit_secondCoordinate_eq_weightedSplitTorusTrace
    (w s h : Eˣ) :
    (splitFiberPoint w (s * h)).u2 =
      weightedSplitTorusTrace (s : E)
        (splitFiberProduct w * ((s⁻¹ : Eˣ) : E)) h := by
  rw [splitFiberOrbit_secondCoordinate_eq_scaledTwistedTrace]
  simp only [twistedUnitTrace, weightedSplitTorusTrace, Units.val_inv_eq_inv_val]
  field_simp [Units.ne_zero s]

/-- The product of the two weights in the preceding identity is exactly the fiber invariant.
Thus the paper's nondegeneracy condition is `alpha * beta != 1`. -/
theorem splitFiberOrbit_weights_mul (w s : Eˣ) :
    (s : E) * (splitFiberProduct w * ((s⁻¹ : Eˣ) : E)) = splitFiberProduct w := by
  simp only [Units.val_inv_eq_inv_val]
  field_simp [Units.ne_zero s]

/-- Every translated parameter `s * h` with `h` in the cyclic subgroup generated by `w` is an
actual forward iterate of the normalized Markoff rotation through `splitFiberPoint w s`. -/
theorem exists_iterate_splitFiberPoint_eq_mul_zpowers
    [Finite E] (w s : Eˣ) (h : Subgroup.zpowers w) :
    ∃ n : ℕ,
      (normalizedRotate1^[n]) (splitFiberPoint w s) =
        splitFiberPoint w (s * (h : Eˣ)) := by
  have hhPowers : (h : Eˣ) ∈ Submonoid.powers w :=
    mem_powers_iff_mem_zpowers.mpr h.property
  obtain ⟨n, hn⟩ := (Submonoid.mem_powers_iff (h : Eˣ) w).mp hhPowers
  refine ⟨n, ?_⟩
  rw [iterate_normalizedRotate1_splitFiberPoint]
  congr 1
  exact congrArg (fun u : Eˣ ↦ s * u) hn

/-- At the base parameter `1`, the orbit-coordinate formula is exactly the unscaled trace
equation used by the Corvaja--Zannier counting module. -/
theorem splitFiberBaseOrbit_secondCoordinate_eq_twistedUnitTrace
    (w : Eˣ) (h : Subgroup.zpowers w) :
    (splitFiberPoint w (h : Eˣ)).u2 =
      twistedUnitTrace (splitFiberProduct w) (h : Eˣ) := by
  simpa using splitFiberOrbit_secondCoordinate_eq_scaledTwistedTrace w 1 (h : Eˣ)

section NonsplitFiber

variable (p : ℕ) [Fact p.Prime]

/-- The nonsplit conic parametrization has the same translated-coset obstruction after scalar
extension to the quadratic field.  This is the exact formula that an eventual coset form of the
Corvaja--Zannier estimate must consume. -/
theorem algebraMap_quadraticNormFiberOrbit_secondCoordinate_eq_scaledTwistedTrace
    (t : ZMod p) (ht : t ^ 2 ≠ 4) (ht0 : t ≠ 0)
    (w : quadraticNormOneTorus p) (htrace : quadraticNormOneTrace p w = t)
    (s : ↑(quadraticConicNormFiber p t ht ht0))
    (h : quadraticNormOneTorus p) :
    algebraMap (ZMod p) (quadraticFiniteField p)
        (quadraticNormFiberPoint p t ht ht0 w
          (quadraticNormFiberMulNormOne p
            (quadraticFiberProductUnit p t ht ht0) s h)).u2 =
      (s.1 : quadraticFiniteField p) *
        twistedUnitTrace
          (splitFiberProduct (w : (quadraticFiniteField p)ˣ) /
            (s.1 : quadraticFiniteField p) ^ 2)
          (h : (quadraticFiniteField p)ˣ) := by
  have hpoint := algebraMap_quadraticNormFiberPoint p t ht ht0 w htrace
    (quadraticNormFiberMulNormOne p (quadraticFiberProductUnit p t ht ht0) s h)
  have hcoordinate := congrArg NormalizedPoint.u2 hpoint
  change algebraMap (ZMod p) (quadraticFiniteField p)
      (quadraticNormFiberPoint p t ht ht0 w
        (quadraticNormFiberMulNormOne p
          (quadraticFiberProductUnit p t ht ht0) s h)).u2 =
    (splitFiberPoint (w : (quadraticFiniteField p)ˣ)
      (s.1 * (h : (quadraticFiniteField p)ˣ))).u2 at hcoordinate
  rw [hcoordinate]
  exact splitFiberOrbit_secondCoordinate_eq_scaledTwistedTrace
    (w : (quadraticFiniteField p)ˣ) s.1 (h : (quadraticFiniteField p)ˣ)

end NonsplitFiber

section FiniteSplitField

variable [Fintype E]

/-- The Corvaja--Zannier escape, specialized to the cyclic subgroup generated by the current
split eigenvalue, produces an actual Markoff rotation iterate whose second-coordinate order is
strictly larger.

`htraceCoverage` is not the deep Corvaja--Zannier bound.  It is the still-missing concrete
classification assertion that every trace of order at most the current order is represented in
the chosen indexed right subgroup.  Keeping it explicit prevents the split and norm-one torus
cases from being conflated. -/
theorem exists_splitFiberBaseOrbitPoint_with_larger_secondRotationOrder
    (p : ℕ) (w : Eˣ)
    (rightSubgroup : ℕ → Subgroup Eˣ)
    (hrightOrder :
      ∀ d ∈ middleGameCandidateOrders p (Nat.card (Subgroup.zpowers w)),
        Nat.card (rightSubgroup d) = d)
    (hCZ : splitFiberProduct w ≠ 1 →
      ∀ d ∈ middleGameCandidateOrders p (Nat.card (Subgroup.zpowers w)),
        ((traceEquationSolutions (splitFiberProduct w) (Subgroup.zpowers w)
          (rightSubgroup d)).card : ℝ) ≤
          corvajaZannierTraceUpperBound p (Nat.card (Subgroup.zpowers w))
            (Nat.card (rightSubgroup d)))
    (hsigma : splitFiberProduct w ≠ 1)
    (hcurrentOrder : 0 < Nat.card (Subgroup.zpowers w))
    (hcube :
      (corvajaZannierCorollaryTwoSafeCoefficient *
        ((p - 1).divisors.card + (p + 1).divisors.card)) ^ 3 <
        Nat.card (Subgroup.zpowers w))
    (hlinear :
      corvajaZannierCorollaryTwoSafeCoefficient *
        ((p - 1).divisors.card + (p + 1).divisors.card) *
          Nat.card (Subgroup.zpowers w) < p)
    (htraceCoverage :
      ∀ t : E, rotationOrder t ≤ Nat.card (Subgroup.zpowers w) →
        ∃ d ∈ middleGameCandidateOrders p (Nat.card (Subgroup.zpowers w)),
          ∃ h₂ : rightSubgroup d, t = twistedUnitTrace 1 h₂) :
    ∃ h : Subgroup.zpowers w,
      Nat.card (Subgroup.zpowers w) <
          rotationOrder (splitFiberPoint w (h : Eˣ)).u2 ∧
        ∃ n : ℕ,
          (normalizedRotate1^[n]) (splitFiberPoint w 1) =
            splitFiberPoint w (h : Eˣ) := by
  obtain ⟨h, hEscapes⟩ :=
    exists_left_element_escaping_of_corvajaZannierEstimate_and_sizeBounds
      p (splitFiberProduct w) (Subgroup.zpowers w) rightSubgroup
      hrightOrder hCZ hsigma hcurrentOrder hcube hlinear
  refine ⟨h, ?_, ?_⟩
  · apply lt_of_not_ge
    intro hsmall
    obtain ⟨d, hd, h₂, htrace⟩ :=
      htraceCoverage (splitFiberPoint w (h : Eˣ)).u2 hsmall
    exact hEscapes d hd h₂ <| by
      rw [← htrace]
      exact (splitFiberBaseOrbit_secondCoordinate_eq_twistedUnitTrace w h).symm
  · simpa using exists_iterate_splitFiberPoint_eq_mul_zpowers w 1 h

end FiniteSplitField

end BGS.Markoff
