import BGS.CorvajaZannier.DedekindLocalDerivationExtension
import BGS.CorvajaZannier.DedekindPlaceOrder
import Mathlib.RingTheory.Discriminant
import Mathlib.Data.Finsupp.Order

/-!
# The different divisor and the primitive-element derivative

For a finite separable extension represented by an integral primitive element,
the different ideal divides the principal ideal generated by the derivative of
the integral minimal polynomial. This file packages that fact at four levels:

* effective finitely supported divisors of nonzero Dedekind ideals;
* coefficientwise and arbitrary nonnegative weighted bounds for the different;
* the corresponding local finite-place order inequality; and
* the field norm identity relating the derivative to the power-basis
  discriminant.

Thus all ramified finite-place contributions represented by the different are
controlled by one principal divisor. No canonical-divisor or genus estimate is
assumed here.
-/

open scoped nonZeroDivisors
open IsDedekindDomain Polynomial

namespace BGS.CorvajaZannier

noncomputable section

attribute [local instance] FractionRing.liftAlgebra
  FractionRing.isScalarTower_liftAlgebra

section IdealDivisor

variable {R : Type*} [CommRing R] [IsDedekindDomain R]

/-- The effective divisor associated to a nonzero integral ideal of a Dedekind domain. -/
def idealMultiplicityDivisor (I : Ideal R) (hI : I ≠ ⊥) :
    HeightOneSpectrum R →₀ Nat :=
  let h := Ideal.finite_factors hI
  Finsupp.mk h.toFinset (fun v => multiplicity v.asIdeal I) (fun v => by
    rw [h.mem_toFinset, Set.mem_setOf_eq]
    simpa [Nat.pos_iff_ne_zero] using
      (dvd_iff_multiplicity_pos (a := v.asIdeal) (b := I)).symm)

@[simp]
theorem idealMultiplicityDivisor_apply (I : Ideal R) (hI : I ≠ ⊥)
    (v : HeightOneSpectrum R) :
    idealMultiplicityDivisor I hI v = multiplicity v.asIdeal I := by
  simp [idealMultiplicityDivisor]

theorem idealMultiplicityDivisor_mono
    {I J : Ideal R} (hI : I ≠ ⊥) (hJ : J ≠ ⊥) (h : J <= I) :
    idealMultiplicityDivisor I hI <= idealMultiplicityDivisor J hJ := by
  intro v
  simp only [idealMultiplicityDivisor_apply]
  exact v.multiplicity_le_of_ideal_ge h hJ

theorem idealMultiplicityDivisor_weightedSum_mono
    {I J : Ideal R} (hI : I ≠ ⊥) (hJ : J ≠ ⊥) (h : J <= I)
    (weight : HeightOneSpectrum R -> Nat) :
    (idealMultiplicityDivisor I hI).sum (fun v e => e * weight v) <=
      (idealMultiplicityDivisor J hJ).sum (fun v e => e * weight v) := by
  classical
  apply Finsupp.sum_le_sum_index (idealMultiplicityDivisor_mono hI hJ h)
  · intro v _ a b hab
    exact Nat.mul_le_mul_right (weight v) hab
  · simp

end IdealDivisor

section DifferentDivisor

variable (A B : Type*) [CommRing A] [CommRing B]
  [IsDomain A] [IsDedekindDomain B] [Algebra A B]
  [Module.IsTorsionFree A B]

/-- The effective different divisor of a finite separable Dedekind extension. -/
def differentMultiplicityDivisor (hDifferent : differentIdeal A B ≠ ⊥) :
    HeightOneSpectrum B →₀ Nat :=
  idealMultiplicityDivisor (differentIdeal A B) hDifferent

@[simp]
theorem differentMultiplicityDivisor_apply
    (hDifferent : differentIdeal A B ≠ ⊥) (v : HeightOneSpectrum B) :
    differentMultiplicityDivisor A B hDifferent v =
      multiplicity v.asIdeal (differentIdeal A B) := by
  simp [differentMultiplicityDivisor]

end DifferentDivisor

section PrimitiveDifferent

variable {A K L B : Type*}
  [CommRing A] [Field K] [CommRing B] [Field L]
  [Algebra A K] [Algebra B L] [Algebra A B] [Algebra K L] [Algebra A L]
  [IsScalarTower A K L] [IsScalarTower A B L]
  [IsDomain A] [IsFractionRing A K] [FiniteDimensional K L]
  [Algebra.IsSeparable K L] [IsIntegralClosure B A L]
  [IsIntegrallyClosed A] [IsDedekindDomain B]
  [Module.IsTorsionFree A B]

include K L in
omit [FiniteDimensional K L] [Module.IsTorsionFree A B] in
/-- In a separable function-field extension, the integral minimal-polynomial
derivative of every integral element is nonzero. -/
theorem minpolyDerivative_ne_zero (x : B) :
    aeval x (derivative (minpoly A x)) ≠ 0 := by
  have hne :
      aeval (algebraMap B L x)
          (derivative (minpoly K (algebraMap B L x))) ≠ 0 :=
    (Algebra.IsSeparable.isSeparable _ _).aeval_derivative_ne_zero
      (minpoly.aeval K (algebraMap B L x))
  have hmap : algebraMap B L (aeval x (derivative (minpoly A x))) ≠ 0 := by
    rwa [minpoly.isIntegrallyClosed_eq_field_fractions K L
      (IsIntegralClosure.isIntegral A L x), derivative_map,
      aeval_map_algebraMap, aeval_algebraMap_apply] at hne
  exact fun hzero => hmap (by simp [hzero])

include K L in
omit [FiniteDimensional K L] [Module.IsTorsionFree A B] in
theorem minpolyDerivative_span_ne_bot (x : B) :
    Ideal.span {aeval x (derivative (minpoly A x))} ≠ ⊥ := by
  rw [ne_eq, Ideal.span_singleton_eq_bot]
  exact minpolyDerivative_ne_zero (A := A) (K := K) (L := L) x

/-- A separable primitive element supplies a nonzero element of the different,
so the different ideal itself is nonzero. -/
theorem differentIdeal_ne_bot_of_primitiveElement
    (x : B) (hx : Algebra.adjoin K {algebraMap B L x} = ⊤) :
    differentIdeal A B ≠ ⊥ := by
  intro hDifferent
  have hmem := aeval_derivative_mem_differentIdeal A K L x hx
  rw [hDifferent, Ideal.mem_bot] at hmem
  exact minpolyDerivative_ne_zero (A := A) (K := K) (L := L) x hmem

/-- The different divides the principal ideal generated by the derivative of a
primitive element's integral minimal polynomial. -/
theorem differentIdeal_dvd_minpolyDerivativeSpan
    (x : B) (hx : Algebra.adjoin K {algebraMap B L x} = ⊤) :
    differentIdeal A B ∣
      Ideal.span {aeval x (derivative (minpoly A x))} := by
  rw [Ideal.dvd_iff_le, Ideal.span_singleton_le_iff_mem]
  exact aeval_derivative_mem_differentIdeal A K L x hx

/-- At every finite prime, the different exponent is bounded by the order of
the primitive element's minimal-polynomial derivative. -/
theorem differentIdeal_multiplicity_le_minpolyDerivativeSpan
    (x : B) (hx : Algebra.adjoin K {algebraMap B L x} = ⊤)
    (v : HeightOneSpectrum B) :
    multiplicity v.asIdeal (differentIdeal A B) <=
      multiplicity v.asIdeal
        (Ideal.span {aeval x (derivative (minpoly A x))}) := by
  apply v.multiplicity_le_of_ideal_ge
  · exact Ideal.dvd_iff_le.mp (differentIdeal_dvd_minpolyDerivativeSpan x hx)
  · exact minpolyDerivative_span_ne_bot (A := A) (K := K) (L := L) x

theorem differentPrime_dvd_minpolyDerivativeSpan
    (x : B) (hx : Algebra.adjoin K {algebraMap B L x} = ⊤)
    (v : HeightOneSpectrum B)
    (hv : v.asIdeal ∣ differentIdeal A B) :
    v.asIdeal ∣ Ideal.span {aeval x (derivative (minpoly A x))} :=
  hv.trans (differentIdeal_dvd_minpolyDerivativeSpan x hx)

end PrimitiveDifferent

section DifferentFinsuppBound

variable {A K L B : Type*}
  [CommRing A] [Field K] [CommRing B] [Field L]
  [Algebra A K] [Algebra B L] [Algebra A B] [Algebra K L] [Algebra A L]
  [IsScalarTower A K L] [IsScalarTower A B L]
  [IsDomain A] [IsIntegrallyClosed A] [IsDedekindDomain B]
  [IsFractionRing A K] [FiniteDimensional K L]
  [Algebra.IsSeparable K L] [IsIntegralClosure B A L]
  [Module.IsTorsionFree A B]

theorem differentMultiplicityDivisor_le_minpolyDerivativeDivisor
    (x : B) (hx : Algebra.adjoin K {algebraMap B L x} = ⊤) :
    differentMultiplicityDivisor A B
        (differentIdeal_ne_bot_of_primitiveElement
          (A := A) (K := K) (L := L) (B := B) x hx) <=
      idealMultiplicityDivisor
        (Ideal.span {aeval x (derivative (minpoly A x))})
        (minpolyDerivative_span_ne_bot
          (A := A) (K := K) (L := L) (B := B) x) := by
  intro v
  simp only [differentMultiplicityDivisor_apply,
    idealMultiplicityDivisor_apply]
  exact differentIdeal_multiplicity_le_minpolyDerivativeSpan
    (A := A) (K := K) (L := L) (B := B) x hx v

theorem differentMultiplicityWeightedSum_le_minpolyDerivative
    (x : B) (hx : Algebra.adjoin K {algebraMap B L x} = ⊤)
    (weight : HeightOneSpectrum B -> Nat) :
    (differentMultiplicityDivisor A B
      (differentIdeal_ne_bot_of_primitiveElement
        (A := A) (K := K) (L := L) (B := B) x hx)).sum
        (fun v e => e * weight v) <=
      (idealMultiplicityDivisor
        (Ideal.span {aeval x (derivative (minpoly A x))})
        (minpolyDerivative_span_ne_bot
          (A := A) (K := K) (L := L) (B := B) x)).sum
          (fun v e => e * weight v) := by
  classical
  apply Finsupp.sum_le_sum_index
    (differentMultiplicityDivisor_le_minpolyDerivativeDivisor
      (A := A) (K := K) (L := L) (B := B) x hx)
  · intro v _ a b hab
    exact Nat.mul_le_mul_right (weight v) hab
  · simp

theorem finite_differentPrimes_of_primitiveElement
    (x : B) (hx : Algebra.adjoin K {algebraMap B L x} = ⊤) :
    {v : HeightOneSpectrum B |
      v.asIdeal ∣ differentIdeal A B}.Finite := by
  apply Set.Finite.subset
    (Ideal.finite_factors (minpolyDerivative_span_ne_bot
      (A := A) (K := K) (L := L) (B := B) x))
  intro v hv
  exact differentPrime_dvd_minpolyDerivativeSpan
    (A := A) (K := K) (L := L) (B := B) x hx v hv

end DifferentFinsuppBound

section LocalOrder

variable {R F : Type*} [CommRing R] [IsDedekindDomain R]
  [Field F] [Algebra R F] [IsFractionRing R F]

theorem finitePlaceOrder_algebraMap_eq_multiplicity
    (v : HeightOneSpectrum R) (a : R) (ha : a ≠ 0) :
    finitePlaceOrder v (algebraMap R F a) =
      (multiplicity v.asIdeal (Ideal.span {a}) : Int) := by
  have hmap : algebraMap R F a ≠ 0 := by
    intro hzero
    apply ha
    apply IsFractionRing.injective R F
    simpa using hzero
  have hvaluation :=
    valuation_eq_exp_neg_finitePlaceOrder v (algebraMap R F a) hmap
  rw [HeightOneSpectrum.valuation_of_algebraMap,
    v.intValuation_eq_exp_neg_multiplicity ha] at hvaluation
  exact (neg_injective (WithZero.exp_injective hvaluation)).symm

end LocalOrder

section PrimitiveLocalOrder

variable {A K L B : Type*}
  [CommRing A] [Field K] [CommRing B] [Field L]
  [Algebra A K] [Algebra A B] [Algebra B L]
  [Algebra K L] [Algebra A L]
  [IsScalarTower A K L]
  [IsScalarTower A B L]
  [IsDomain A] [IsFractionRing A K]
  [IsFractionRing B L] [FiniteDimensional K L]
  [Algebra.IsSeparable K L]
  [IsIntegralClosure B A L]
  [IsIntegrallyClosed A] [IsDedekindDomain B]
  [Module.IsTorsionFree A B]

theorem differentIdeal_multiplicity_le_finitePlaceOrder_minpolyDerivative
    (x : B)
    (hx : Algebra.adjoin K
      {algebraMap B L x} = ⊤)
    (v : HeightOneSpectrum B) :
    (multiplicity v.asIdeal (differentIdeal A B) : Int) <=
      finitePlaceOrder v
        (algebraMap B L
          (aeval x (derivative (minpoly A x)))) := by
  rw [finitePlaceOrder_algebraMap_eq_multiplicity _ _
    (minpolyDerivative_ne_zero (A := A) (K := K) (L := L) x)]
  exact_mod_cast differentIdeal_multiplicity_le_minpolyDerivativeSpan x hx v

end PrimitiveLocalOrder

section NormDiscriminant

variable {A K L B : Type*}
  [CommRing A] [Field K] [CommRing B] [Field L]
  [Algebra A K] [Algebra B L] [Algebra A B] [Algebra K L] [Algebra A L]
  [IsScalarTower A K L] [IsScalarTower A B L]
  [IsDomain A] [IsFractionRing A K] [FiniteDimensional K L]
  [Algebra.IsSeparable K L] [IsIntegralClosure B A L]
  [IsIntegrallyClosed A] [IsDedekindDomain B]

/-- The field norm of the integral minimal-polynomial derivative is the
power-basis discriminant, up to the standard sign. -/
theorem discr_powerBasisOfPrimitiveElement_eq_norm_minpolyDerivative
    (x : B) (hx : Algebra.adjoin K {algebraMap B L x} = ⊤) :
    let pb : PowerBasis K L :=
      PowerBasis.ofAdjoinEqTop' (Algebra.IsIntegral.isIntegral _) hx
    Algebra.discr K pb.basis =
      (-1) ^ (Module.finrank K L * (Module.finrank K L - 1) / 2) *
        Algebra.norm K
          (algebraMap B L (aeval x (derivative (minpoly A x)))) := by
  dsimp only
  let pb : PowerBasis K L :=
    PowerBasis.ofAdjoinEqTop' (Algebra.IsIntegral.isIntegral _) hx
  rw [Algebra.discr_powerBasis_eq_norm K pb]
  congr 2
  simp only [pb, PowerBasis.ofAdjoinEqTop'_gen]
  rw [minpoly.isIntegrallyClosed_eq_field_fractions K L
    (IsIntegralClosure.isIntegral A L x), derivative_map,
    aeval_map_algebraMap, aeval_algebraMap_apply]

end NormDiscriminant

end

end BGS.CorvajaZannier
