import BGS.CorvajaZannier.PlaneCurveFunctionField
import Mathlib.FieldTheory.Separable
import Mathlib.FieldTheory.SeparableDegree
import Mathlib.RingTheory.Polynomial.GaussLemma
import Mathlib.RingTheory.AlgebraicIndependent.Adjoin

/-!
# Separability of a plane-curve coordinate extension

For an irreducible plane equation whose partial derivative in the second coordinate is nonzero,
this file proves that the function field is a finite separable extension of the field generated by
the first coordinate. The proof passes through the iterated-polynomial presentation and Gauss's
lemma.
-/

namespace BGS.CorvajaZannier

noncomputable section

variable {K : Type*} [Field K]

private theorem derivative_optionEquivLeft
    {σ : Type*} (p : MvPolynomial (Option σ) K) :
    (MvPolynomial.optionEquivLeft K σ p).derivative =
      MvPolynomial.optionEquivLeft K σ (MvPolynomial.pderiv none p) := by
  classical
  induction p using MvPolynomial.induction_on with
  | C a => simp
  | add p q hp hq => simp [hp, hq]
  | mul_X p i hp =>
      cases i <;> simp_all [MvPolynomial.pderiv_X, mul_comm]

/-- The iterated-polynomial presentation of an irreducible bivariate polynomial is irreducible. -/
theorem polynomialInSecondCoordinate_irreducible
    {f : MvPolynomial (Fin 2) K} (hf : Irreducible f) :
    Irreducible (polynomialInSecondCoordinate f) := by
  let e := Equiv.optionSubtypeNe (1 : Fin 2)
  have hrename : Irreducible (MvPolynomial.rename e.symm f) := by
    change Irreducible ((MvPolynomial.renameEquiv K e.symm) f)
    exact hf.map (MvPolynomial.renameEquiv K e.symm).toMulEquiv
  exact hrename.map (MvPolynomial.optionEquivLeft K {i : Fin 2 // i ≠ 1}).toMulEquiv

/-- Ordinary differentiation of the iterated-polynomial presentation agrees with taking the
partial derivative in the second affine coordinate. -/
theorem derivative_polynomialInSecondCoordinate
    (f : MvPolynomial (Fin 2) K) :
    (polynomialInSecondCoordinate f).derivative =
      polynomialInSecondCoordinate (MvPolynomial.pderiv 1 f) := by
  let e := Equiv.optionSubtypeNe (1 : Fin 2)
  rw [polynomialInSecondCoordinate, polynomialInSecondCoordinate,
    derivative_optionEquivLeft]
  congr 1
  simpa [e] using MvPolynomial.pderiv_rename e.symm.injective (1 : Fin 2) f

/-- A nonzero second-coordinate partial derivative remains nonzero after rewriting the equation
as a polynomial in the second coordinate over the first-coordinate polynomial ring. -/
theorem derivative_polynomialInSecondCoordinate_ne_zero
    {f : MvPolynomial (Fin 2) K} (hderiv : MvPolynomial.pderiv 1 f ≠ 0) :
    (polynomialInSecondCoordinate f).derivative ≠ 0 := by
  rw [derivative_polynomialInSecondCoordinate]
  exact polynomialInSecondCoordinate_ne_zero hderiv

/-- The fraction field of the polynomial coefficient ring in the remaining affine coordinate is
the intermediate field generated by the first coordinate function. -/
def firstCoordinateFractionEquiv
    (f : MvPolynomial (Fin 2) K) [IsDomain (PlaneCurveCoordinateRing f)]
    (htrans : Transcendental K (planeCurveFunction f 0)) :
    FractionRing (MvPolynomial {i : Fin 2 // i ≠ 1} K) ≃ₐ[K]
      FirstCoordinateSubfield f := by
  let remaining := {i : Fin 2 // i ≠ 1}
  have remaining_value_zero (i : remaining) : i.1 = 0 := by omega
  letI : Subsingleton remaining :=
    ⟨fun i j => Subtype.ext ((remaining_value_zero i).trans (remaining_value_zero j).symm)⟩
  let i0 : remaining := ⟨0, by decide⟩
  have hIndependent : AlgebraicIndependent K
      (fun _ : remaining => planeCurveFunction f 0) := by
    rw [algebraicIndependent_singleton_iff i0]
    exact htrans
  have hrange : Set.range (fun _ : remaining => planeCurveFunction f 0) =
      ({planeCurveFunction f 0} : Set (PlaneCurveFunctionField f)) := by
    ext z
    constructor
    · rintro ⟨i, rfl⟩
      simp
    · intro hz
      rw [Set.mem_singleton_iff] at hz
      subst z
      exact ⟨i0, rfl⟩
  have hfield :
      IntermediateField.adjoin K
          (Set.range (fun _ : remaining => planeCurveFunction f 0)) =
        FirstCoordinateSubfield f := by
    rw [hrange]
  exact hIndependent.aevalEquivField.trans (IntermediateField.equivOfEq hfield)

set_option maxHeartbeats 800000 in
/-- The fraction-field equivalence extends the coefficient evaluation homomorphism. -/
@[simp]
theorem firstCoordinateFractionEquiv_algebraMap
    (f : MvPolynomial (Fin 2) K) [IsDomain (PlaneCurveCoordinateRing f)]
    (htrans : Transcendental K (planeCurveFunction f 0))
    (p : MvPolynomial {i : Fin 2 // i ≠ 1} K) :
    firstCoordinateFractionEquiv f htrans
        (algebraMap (MvPolynomial {i : Fin 2 // i ≠ 1} K)
          (FractionRing (MvPolynomial {i : Fin 2 // i ≠ 1} K)) p) =
      firstCoordinateCoefficientEval f p := by
  apply Subtype.ext
  · simp [firstCoordinateFractionEquiv, firstCoordinateCoefficientEval,
      firstCoordinateInSubfield]
    simpa [MvPolynomial.aeval_def, firstCoordinateInSubfield] using
      (MvPolynomial.hom_eval₂ p
        (algebraMap K (FirstCoordinateSubfield f))
        (FirstCoordinateSubfield f).val.toRingHom
        (fun _ => firstCoordinateInSubfield f)).symm

/-- An irreducible plane equation with nonzero second partial derivative stays irreducible after
passing to the field generated by the first coordinate and viewing it as a polynomial in the
second coordinate. -/
theorem polynomialOverFirstCoordinate_irreducible
    {f : MvPolynomial (Fin 2) K} (hf : Irreducible f)
    (hderiv : MvPolynomial.pderiv 1 f ≠ 0) :
    letI := planeCurveCoordinateRing_isDomain hf
    Irreducible (polynomialOverFirstCoordinate f) := by
  letI : IsDomain (PlaneCurveCoordinateRing f) := planeCurveCoordinateRing_isDomain hf
  let R := MvPolynomial {i : Fin 2 // i ≠ 1} K
  let F := FractionRing R
  let p := polynomialInSecondCoordinate f
  have hsecond : 0 < MvPolynomial.degreeOf 1 f :=
    degreeOf_second_pos_of_pderiv_ne_zero hderiv
  have htrans : Transcendental K (planeCurveFunction f 0) :=
    firstCoordinate_transcendental hf hsecond
  have hpIrreducible : Irreducible p := polynomialInSecondCoordinate_irreducible hf
  have hpDerivative : p.derivative ≠ 0 :=
    derivative_polynomialInSecondCoordinate_ne_zero hderiv
  have hpDegree : p.natDegree ≠ 0 := by
    intro hdegree
    exact hpDerivative (Polynomial.derivative_of_natDegree_zero hdegree)
  have hpPrimitive : p.IsPrimitive := hpIrreducible.isPrimitive hpDegree
  have hFractionIrreducible :
      Irreducible (p.map (algebraMap R F)) :=
    (hpPrimitive.irreducible_iff_irreducible_map_fraction_map (K := F)).mp hpIrreducible
  let e := firstCoordinateFractionEquiv f htrans
  have hMappedIrreducible :
      Irreducible ((p.map (algebraMap R F)).map e.toRingHom) :=
    hFractionIrreducible.map (Polynomial.mapEquiv e.toRingEquiv).toMulEquiv
  have hmap : e.toRingHom.comp (algebraMap R F) = firstCoordinateCoefficientEval f := by
    apply DFunLike.ext _ _
    intro q
    exact firstCoordinateFractionEquiv_algebraMap f htrans q
  rw [polynomialOverFirstCoordinate_eq_map_polynomialInSecondCoordinate]
  simpa only [Polynomial.map_map, hmap] using hMappedIrreducible

/-- The ordinary derivative of the specialized plane equation is nonzero. -/
theorem derivative_polynomialOverFirstCoordinate_ne_zero
    {f : MvPolynomial (Fin 2) K} (hf : Irreducible f)
    (hderiv : MvPolynomial.pderiv 1 f ≠ 0) :
    letI := planeCurveCoordinateRing_isDomain hf
    (polynomialOverFirstCoordinate f).derivative ≠ 0 := by
  letI : IsDomain (PlaneCurveCoordinateRing f) := planeCurveCoordinateRing_isDomain hf
  rw [polynomialOverFirstCoordinate_eq_map_polynomialInSecondCoordinate,
    Polynomial.derivative_map]
  exact (Polynomial.map_ne_zero_iff
    (firstCoordinateCoefficientEval_injective hf
      (degreeOf_second_pos_of_pderiv_ne_zero hderiv))).mpr
        (derivative_polynomialInSecondCoordinate_ne_zero hderiv)

/-- The specialized defining polynomial over the first-coordinate field is separable. -/
theorem polynomialOverFirstCoordinate_separable
    {f : MvPolynomial (Fin 2) K} (hf : Irreducible f)
    (hderiv : MvPolynomial.pderiv 1 f ≠ 0) :
    letI := planeCurveCoordinateRing_isDomain hf
    (polynomialOverFirstCoordinate f).Separable := by
  letI : IsDomain (PlaneCurveCoordinateRing f) := planeCurveCoordinateRing_isDomain hf
  exact (Polynomial.separable_iff_derivative_ne_zero
    (polynomialOverFirstCoordinate_irreducible hf hderiv)).mpr
      (derivative_polynomialOverFirstCoordinate_ne_zero hf hderiv)

/-- The second coordinate function is separable over the field generated by the first
coordinate. -/
theorem secondCoordinate_isSeparable_over_first
    {f : MvPolynomial (Fin 2) K} (hf : Irreducible f)
    (hderiv : MvPolynomial.pderiv 1 f ≠ 0) :
    letI := planeCurveCoordinateRing_isDomain hf
    IsSeparable (FirstCoordinateSubfield f) (planeCurveFunction f 1) := by
  letI : IsDomain (PlaneCurveCoordinateRing f) := planeCurveCoordinateRing_isDomain hf
  have hroot : Polynomial.aeval (planeCurveFunction f 1)
      (polynomialOverFirstCoordinate f) = 0 := by
    simpa [Polynomial.aeval_def] using eval₂_polynomialOverFirstCoordinate_eq_zero f
  exact (polynomialOverFirstCoordinate_separable hf hderiv).of_dvd
    (minpoly.dvd (FirstCoordinateSubfield f) (planeCurveFunction f 1) hroot)

/-- The plane-curve function field is a finite separable extension of the field generated by its
first coordinate. -/
theorem finiteSeparable_over_firstCoordinate_of_irreducible
    {f : MvPolynomial (Fin 2) K} (hf : Irreducible f)
    (hderiv : MvPolynomial.pderiv 1 f ≠ 0) :
    letI := planeCurveCoordinateRing_isDomain hf
    FiniteDimensional (FirstCoordinateSubfield f) (PlaneCurveFunctionField f) ∧
      Algebra.IsSeparable (FirstCoordinateSubfield f) (PlaneCurveFunctionField f) := by
  letI : IsDomain (PlaneCurveCoordinateRing f) := planeCurveCoordinateRing_isDomain hf
  constructor
  · exact finiteDimensional_over_firstCoordinate_of_irreducible hf hderiv
  · have hAdjoin : Algebra.IsSeparable (FirstCoordinateSubfield f)
        (IntermediateField.adjoin (FirstCoordinateSubfield f)
          {planeCurveFunction f 1}) :=
      (IntermediateField.isSeparable_adjoin_simple_iff_isSeparable
      (FirstCoordinateSubfield f) (PlaneCurveFunctionField f)).mpr
        (secondCoordinate_isSeparable_over_first hf hderiv)
    have hTop : Algebra.IsSeparable (FirstCoordinateSubfield f)
        (⊤ : IntermediateField (FirstCoordinateSubfield f)
          (PlaneCurveFunctionField f)) := by
      rw [← adjoin_secondCoordinate_over_first_eq_top f]
      exact hAdjoin
    exact (IntermediateField.isSeparable_top
      (F := FirstCoordinateSubfield f) (E := PlaneCurveFunctionField f)).mp hTop

/-- Specialization at the transcendental first coordinate preserves the second-coordinate
degree. -/
theorem natDegree_polynomialOverFirstCoordinate_eq_degreeOf_second
    {f : MvPolynomial (Fin 2) K} (hf : Irreducible f)
    (hderiv : MvPolynomial.pderiv 1 f ≠ 0) :
    letI := planeCurveCoordinateRing_isDomain hf
    (polynomialOverFirstCoordinate f).natDegree = MvPolynomial.degreeOf 1 f := by
  letI : IsDomain (PlaneCurveCoordinateRing f) := planeCurveCoordinateRing_isDomain hf
  rw [polynomialOverFirstCoordinate_eq_map_polynomialInSecondCoordinate,
    Polynomial.natDegree_map_eq_of_injective
      (firstCoordinateCoefficientEval_injective hf
        (degreeOf_second_pos_of_pderiv_ne_zero hderiv))]
  exact (MvPolynomial.degreeOf_eq_natDegree (1 : Fin 2) f).symm

/-- The minimal polynomial of the second coordinate has the full second-coordinate degree of the
irreducible plane equation. -/
theorem natDegree_minpoly_secondCoordinate_eq_degreeOf_second
    {f : MvPolynomial (Fin 2) K} (hf : Irreducible f)
    (hderiv : MvPolynomial.pderiv 1 f ≠ 0) :
    letI := planeCurveCoordinateRing_isDomain hf
    (minpoly (FirstCoordinateSubfield f) (planeCurveFunction f 1)).natDegree =
      MvPolynomial.degreeOf 1 f := by
  letI : IsDomain (PlaneCurveCoordinateRing f) := planeCurveCoordinateRing_isDomain hf
  let p := polynomialOverFirstCoordinate f
  have hpIrreducible : Irreducible p :=
    polynomialOverFirstCoordinate_irreducible hf hderiv
  have hroot : Polynomial.aeval (planeCurveFunction f 1) p = 0 := by
    simpa [p, Polynomial.aeval_def] using eval₂_polynomialOverFirstCoordinate_eq_zero f
  have heq := minpoly.eq_of_irreducible hpIrreducible hroot
  calc
    (minpoly (FirstCoordinateSubfield f) (planeCurveFunction f 1)).natDegree =
        (p * Polynomial.C p.leadingCoeff⁻¹).natDegree := by rw [heq]
    _ = p.natDegree := Polynomial.natDegree_mul_C
      (inv_ne_zero (Polynomial.leadingCoeff_ne_zero.mpr hpIrreducible.ne_zero))
    _ = MvPolynomial.degreeOf 1 f :=
      natDegree_polynomialOverFirstCoordinate_eq_degreeOf_second hf hderiv

/-- The extension degree over the first-coordinate field is exactly the degree of the defining
equation in the second coordinate. -/
theorem finrank_over_firstCoordinate_eq_degreeOf_second_of_irreducible
    {f : MvPolynomial (Fin 2) K} (hf : Irreducible f)
    (hderiv : MvPolynomial.pderiv 1 f ≠ 0) :
    letI := planeCurveCoordinateRing_isDomain hf
    Module.finrank (FirstCoordinateSubfield f) (PlaneCurveFunctionField f) =
      MvPolynomial.degreeOf 1 f := by
  letI : IsDomain (PlaneCurveCoordinateRing f) := planeCurveCoordinateRing_isDomain hf
  letI : FiniteDimensional (FirstCoordinateSubfield f) (PlaneCurveFunctionField f) :=
    finiteDimensional_over_firstCoordinate_of_irreducible hf hderiv
  have halg := secondCoordinate_isAlgebraic_over_first f
    (polynomialOverFirstCoordinate_ne_zero_of_irreducible hf
      (degreeOf_second_pos_of_pderiv_ne_zero hderiv))
  calc
    Module.finrank (FirstCoordinateSubfield f) (PlaneCurveFunctionField f) =
        Module.finrank (FirstCoordinateSubfield f)
          (⊤ : IntermediateField (FirstCoordinateSubfield f)
            (PlaneCurveFunctionField f)) := by rw [IntermediateField.finrank_top']
    _ = Module.finrank (FirstCoordinateSubfield f)
          (IntermediateField.adjoin (FirstCoordinateSubfield f)
            {planeCurveFunction f 1}) := by
      rw [adjoin_secondCoordinate_over_first_eq_top f]
    _ = (minpoly (FirstCoordinateSubfield f) (planeCurveFunction f 1)).natDegree :=
      IntermediateField.adjoin.finrank halg.isIntegral
    _ = MvPolynomial.degreeOf 1 f :=
      natDegree_minpoly_secondCoordinate_eq_degreeOf_second hf hderiv

/-! ## The coordinate-swapped extension -/

/-- Embed a univariate polynomial in the second affine coordinate. -/
def polynomialInSecondCoordinateOnly (P : Polynomial K) : MvPolynomial (Fin 2) K :=
  P.sum fun n c => MvPolynomial.C c * MvPolynomial.X 1 ^ n

theorem eval₂_polynomialInSecondCoordinateOnly
    {S : Type*} [CommSemiring S] (P : Polynomial K) (phi : K →+* S) (x y : S) :
    MvPolynomial.eval₂ phi ![x, y] (polynomialInSecondCoordinateOnly P) =
      P.eval₂ phi y := by
  classical
  simp [polynomialInSecondCoordinateOnly, Polynomial.sum_def, Polynomial.eval₂_eq_sum]

theorem polynomialInSecondCoordinateOnly_ne_zero {P : Polynomial K} (hP : P ≠ 0) :
    polynomialInSecondCoordinateOnly P ≠ 0 := by
  intro hzero
  have heval := eval₂_polynomialInSecondCoordinateOnly P Polynomial.C
    (0 : Polynomial K) Polynomial.X
  rw [hzero, MvPolynomial.eval₂_zero] at heval
  apply hP
  simpa using heval.symm

private theorem degreeOf_finset_sum_le_for_second
    {R ι : Type*} [CommSemiring R]
    (coordinate : Fin 2) (terms : ι → MvPolynomial (Fin 2) R)
    (indices : Finset ι) (bound : ℕ)
    (hterms : ∀ i ∈ indices, MvPolynomial.degreeOf coordinate (terms i) ≤ bound) :
    MvPolynomial.degreeOf coordinate (∑ i ∈ indices, terms i) ≤ bound := by
  classical
  induction indices using Finset.induction_on with
  | empty => simp
  | @insert i indices hi ih =>
      rw [Finset.sum_insert hi]
      exact (MvPolynomial.degreeOf_add_le _ _ _).trans
        (max_le (hterms i (Finset.mem_insert_self i indices))
          (ih fun j hj => hterms j (Finset.mem_insert_of_mem hj)))

theorem polynomialInSecondCoordinateOnly_degreeOf_first_le (P : Polynomial K) :
    MvPolynomial.degreeOf (0 : Fin 2) (polynomialInSecondCoordinateOnly P) ≤ 0 := by
  classical
  rw [polynomialInSecondCoordinateOnly, Polynomial.sum_def]
  apply degreeOf_finset_sum_le_for_second (0 : Fin 2) _ P.support 0
  intro n _hn
  calc
    MvPolynomial.degreeOf (0 : Fin 2)
        (MvPolynomial.C (P.coeff n) * MvPolynomial.X 1 ^ n) ≤
        MvPolynomial.degreeOf (0 : Fin 2) (MvPolynomial.C (P.coeff n)) +
          MvPolynomial.degreeOf (0 : Fin 2) (MvPolynomial.X 1 ^ n) :=
      MvPolynomial.degreeOf_mul_le _ _ _
    _ ≤ 0 := by
      have hpow : MvPolynomial.degreeOf (0 : Fin 2)
          (MvPolynomial.X 1 ^ n : MvPolynomial (Fin 2) K) ≤ 0 := by
        calc
          _ ≤ n * MvPolynomial.degreeOf (0 : Fin 2) (MvPolynomial.X 1) :=
            MvPolynomial.degreeOf_pow_le _ _ _
          _ = 0 := by rw [MvPolynomial.degreeOf_X]; norm_num
      rw [MvPolynomial.degreeOf_C]
      simpa using hpow

/-- Positive degree in the first coordinate makes the second coordinate function
transcendental. -/
theorem secondCoordinate_transcendental
    {f : MvPolynomial (Fin 2) K} (hf : Irreducible f)
    (hfirst : 0 < MvPolynomial.degreeOf 0 f) :
    letI := planeCurveCoordinateRing_isDomain hf
    Transcendental K (planeCurveFunction f 1) := by
  letI : IsDomain (PlaneCurveCoordinateRing f) := planeCurveCoordinateRing_isDomain hf
  rw [transcendental_iff]
  intro P hPzero
  by_contra hP
  have hembedded : polynomialInSecondCoordinateOnly P ≠ 0 :=
    polynomialInSecondCoordinateOnly_ne_zero hP
  have hquotient : planeCurveQuotientMap f (polynomialInSecondCoordinateOnly P) = 0 := by
    apply IsFractionRing.injective (PlaneCurveCoordinateRing f) (PlaneCurveFunctionField f)
    rw [map_zero]
    change
      ((algebraMap (PlaneCurveCoordinateRing f) (PlaneCurveFunctionField f)).comp
        (planeCurveQuotientMap f)) (polynomialInSecondCoordinateOnly P) = 0
    rw [← eval₂_planeCurveFunction f]
    have hcoordinates : planeCurveFunction f =
        ![planeCurveFunction f 0, planeCurveFunction f 1] := by
      funext i
      fin_cases i <;> rfl
    rw [hcoordinates]
    change MvPolynomial.eval₂ (algebraMap K (PlaneCurveFunctionField f))
      ![planeCurveFunction f 0, planeCurveFunction f 1]
        (polynomialInSecondCoordinateOnly P) = 0
    rw [eval₂_polynomialInSecondCoordinateOnly]
    simpa [Polynomial.aeval_def] using hPzero
  have hdvd : f ∣ polynomialInSecondCoordinateOnly P :=
    Ideal.mem_span_singleton.mp (Ideal.Quotient.eq_zero_iff_mem.mp hquotient)
  obtain ⟨g, hg⟩ := hdvd
  have hgzero : g ≠ 0 := by
    intro hzero
    apply hembedded
    rw [hg, hzero, mul_zero]
  have hdegree : MvPolynomial.degreeOf 0 f ≤
      MvPolynomial.degreeOf 0 (polynomialInSecondCoordinateOnly P) := by
    rw [hg, MvPolynomial.degreeOf_mul_eq hf.ne_zero hgzero]
    exact Nat.le_add_right _ _
  have hzeroDegree := polynomialInSecondCoordinateOnly_degreeOf_first_le P
  omega

/-- The intermediate field generated by the second coordinate function. -/
abbrev SecondCoordinateSubfield
    (f : MvPolynomial (Fin 2) K) [IsDomain (PlaneCurveCoordinateRing f)] :=
  IntermediateField.adjoin K ({planeCurveFunction f 1} : Set (PlaneCurveFunctionField f))

def secondCoordinateInSubfield
    (f : MvPolynomial (Fin 2) K) [IsDomain (PlaneCurveCoordinateRing f)] :
    SecondCoordinateSubfield f :=
  ⟨planeCurveFunction f 1,
    IntermediateField.mem_adjoin_simple_self K (planeCurveFunction f 1)⟩

/-- Regard the plane equation as a polynomial in the first coordinate, with coefficients in the
field generated by the second coordinate. -/
def polynomialOverSecondCoordinate
    (f : MvPolynomial (Fin 2) K) [IsDomain (PlaneCurveCoordinateRing f)] :
    Polynomial (SecondCoordinateSubfield f) :=
  MvPolynomial.eval₂ (algebraMap K (Polynomial (SecondCoordinateSubfield f)))
    ![Polynomial.X, Polynomial.C (secondCoordinateInSubfield f)] f

/-- Iterated-polynomial presentation with the original first coordinate as outer variable. -/
def polynomialInFirstVariablePresentation (f : MvPolynomial (Fin 2) K) :
    Polynomial (MvPolynomial {i : Fin 2 // i ≠ 0} K) :=
  MvPolynomial.optionEquivLeft K {i : Fin 2 // i ≠ 0}
    (MvPolynomial.rename (Equiv.optionSubtypeNe (0 : Fin 2)).symm f)

theorem polynomialInFirstVariablePresentation_ne_zero
    {f : MvPolynomial (Fin 2) K} (hf : f ≠ 0) :
    polynomialInFirstVariablePresentation f ≠ 0 := by
  intro hzero
  apply hf
  apply MvPolynomial.rename_injective
    (Equiv.optionSubtypeNe (0 : Fin 2)).symm
    (Equiv.optionSubtypeNe (0 : Fin 2)).symm.injective
  apply (MvPolynomial.optionEquivLeft K {i : Fin 2 // i ≠ 0}).injective
  simpa [polynomialInFirstVariablePresentation] using hzero

def secondCoordinateCoefficientEval
    (f : MvPolynomial (Fin 2) K) [IsDomain (PlaneCurveCoordinateRing f)] :
    MvPolynomial {i : Fin 2 // i ≠ 0} K →+* SecondCoordinateSubfield f :=
  MvPolynomial.eval₂Hom (algebraMap K (SecondCoordinateSubfield f))
    (fun _ => secondCoordinateInSubfield f)

theorem secondCoordinateCoefficientEval_injective
    {f : MvPolynomial (Fin 2) K} (hf : Irreducible f)
    (hfirst : 0 < MvPolynomial.degreeOf 0 f) :
    letI := planeCurveCoordinateRing_isDomain hf
    Function.Injective (secondCoordinateCoefficientEval f) := by
  letI : IsDomain (PlaneCurveCoordinateRing f) := planeCurveCoordinateRing_isDomain hf
  let remaining := {i : Fin 2 // i ≠ 0}
  have remaining_value_one (i : remaining) : i.1 = 1 := by omega
  letI : Subsingleton remaining :=
    ⟨fun i j => Subtype.ext ((remaining_value_one i).trans (remaining_value_one j).symm)⟩
  let i1 : remaining := ⟨1, by decide⟩
  have hIndependent : AlgebraicIndependent K
      (fun _ : remaining => planeCurveFunction f 1) := by
    rw [algebraicIndependent_singleton_iff i1]
    exact secondCoordinate_transcendental hf hfirst
  let composed : MvPolynomial remaining K →+* PlaneCurveFunctionField f :=
    (algebraMap (SecondCoordinateSubfield f) (PlaneCurveFunctionField f)).comp
      (secondCoordinateCoefficientEval f)
  let evaluated : MvPolynomial remaining K →+* PlaneCurveFunctionField f :=
    MvPolynomial.eval₂Hom (algebraMap K (PlaneCurveFunctionField f))
      (fun _ => planeCurveFunction f 1)
  have hhom : composed = evaluated := by
    apply MvPolynomial.ringHom_ext
    · intro c
      simp [composed, evaluated, secondCoordinateCoefficientEval]
    · intro i
      simp [composed, evaluated, secondCoordinateCoefficientEval,
        secondCoordinateInSubfield]
  intro a b hab
  apply (algebraicIndependent_iff_injective_aeval.mp hIndependent)
  change evaluated a = evaluated b
  rw [← hhom]
  exact congrArg (algebraMap (SecondCoordinateSubfield f) (PlaneCurveFunctionField f)) hab

theorem polynomialOverSecondCoordinate_eq_map_polynomialInFirstVariablePresentation
    (f : MvPolynomial (Fin 2) K) [IsDomain (PlaneCurveCoordinateRing f)] :
    polynomialOverSecondCoordinate f =
      (polynomialInFirstVariablePresentation f).map (secondCoordinateCoefficientEval f) := by
  let lhs : MvPolynomial (Fin 2) K →+* Polynomial (SecondCoordinateSubfield f) :=
    MvPolynomial.eval₂Hom (algebraMap K (Polynomial (SecondCoordinateSubfield f)))
      ![Polynomial.X, Polynomial.C (secondCoordinateInSubfield f)]
  let rhs : MvPolynomial (Fin 2) K →+* Polynomial (SecondCoordinateSubfield f) :=
    (Polynomial.mapRingHom (secondCoordinateCoefficientEval f)).comp
      ((MvPolynomial.optionEquivLeft K {i : Fin 2 // i ≠ 0}).toRingEquiv.toRingHom.comp
        (MvPolynomial.rename (Equiv.optionSubtypeNe (0 : Fin 2)).symm).toRingHom)
  change lhs f = rhs f
  congr 1
  apply MvPolynomial.ringHom_ext
  · intro c
    simp [lhs, rhs, secondCoordinateCoefficientEval]
  · intro i
    fin_cases i <;>
      simp [lhs, rhs, secondCoordinateCoefficientEval, secondCoordinateInSubfield]

theorem polynomialInFirstVariablePresentation_irreducible
    {f : MvPolynomial (Fin 2) K} (hf : Irreducible f) :
    Irreducible (polynomialInFirstVariablePresentation f) := by
  let e := Equiv.optionSubtypeNe (0 : Fin 2)
  have hrename : Irreducible (MvPolynomial.rename e.symm f) := by
    change Irreducible ((MvPolynomial.renameEquiv K e.symm) f)
    exact hf.map (MvPolynomial.renameEquiv K e.symm).toMulEquiv
  exact hrename.map (MvPolynomial.optionEquivLeft K {i : Fin 2 // i ≠ 0}).toMulEquiv

theorem derivative_polynomialInFirstVariablePresentation
    (f : MvPolynomial (Fin 2) K) :
    (polynomialInFirstVariablePresentation f).derivative =
      polynomialInFirstVariablePresentation (MvPolynomial.pderiv 0 f) := by
  let e := Equiv.optionSubtypeNe (0 : Fin 2)
  rw [polynomialInFirstVariablePresentation, polynomialInFirstVariablePresentation,
    derivative_optionEquivLeft]
  congr 1
  simpa [e] using MvPolynomial.pderiv_rename e.symm.injective (0 : Fin 2) f

theorem derivative_polynomialInFirstVariablePresentation_ne_zero
    {f : MvPolynomial (Fin 2) K} (hderiv : MvPolynomial.pderiv 0 f ≠ 0) :
    (polynomialInFirstVariablePresentation f).derivative ≠ 0 := by
  rw [derivative_polynomialInFirstVariablePresentation]
  exact polynomialInFirstVariablePresentation_ne_zero hderiv

theorem degreeOf_first_pos_of_pderiv_ne_zero
    {f : MvPolynomial (Fin 2) K} (hderiv : MvPolynomial.pderiv 0 f ≠ 0) :
    0 < MvPolynomial.degreeOf 0 f := by
  apply Nat.pos_of_ne_zero
  apply MvPolynomial.mem_vars_iff_degreeOf_ne_zero.mp
  by_contra hmem
  exact hderiv (MvPolynomial.pderiv_eq_zero_of_notMem_vars hmem)

theorem polynomialOverSecondCoordinate_ne_zero_of_irreducible
    {f : MvPolynomial (Fin 2) K} (hf : Irreducible f)
    (hfirst : 0 < MvPolynomial.degreeOf 0 f) :
    letI := planeCurveCoordinateRing_isDomain hf
    polynomialOverSecondCoordinate f ≠ 0 := by
  letI : IsDomain (PlaneCurveCoordinateRing f) := planeCurveCoordinateRing_isDomain hf
  rw [polynomialOverSecondCoordinate_eq_map_polynomialInFirstVariablePresentation]
  exact (Polynomial.map_ne_zero_iff
      (secondCoordinateCoefficientEval_injective hf hfirst)).mpr
    (polynomialInFirstVariablePresentation_ne_zero hf.ne_zero)

theorem natDegree_polynomialOverSecondCoordinate_le_degreeOf_first
    (f : MvPolynomial (Fin 2) K) [IsDomain (PlaneCurveCoordinateRing f)] :
    (polynomialOverSecondCoordinate f).natDegree ≤ MvPolynomial.degreeOf 0 f := by
  rw [polynomialOverSecondCoordinate_eq_map_polynomialInFirstVariablePresentation]
  calc
    ((polynomialInFirstVariablePresentation f).map
        (secondCoordinateCoefficientEval f)).natDegree ≤
        (polynomialInFirstVariablePresentation f).natDegree := Polynomial.natDegree_map_le
    _ = MvPolynomial.degreeOf 0 f :=
      (MvPolynomial.degreeOf_eq_natDegree (0 : Fin 2) f).symm

theorem eval₂_polynomialOverSecondCoordinate_eq_zero
    (f : MvPolynomial (Fin 2) K) [IsDomain (PlaneCurveCoordinateRing f)] :
    Polynomial.eval₂
        (algebraMap (SecondCoordinateSubfield f) (PlaneCurveFunctionField f))
        (planeCurveFunction f 0) (polynomialOverSecondCoordinate f) = 0 := by
  let lhs : MvPolynomial (Fin 2) K →+* PlaneCurveFunctionField f :=
    (Polynomial.eval₂RingHom
      (algebraMap (SecondCoordinateSubfield f) (PlaneCurveFunctionField f))
      (planeCurveFunction f 0)).comp
        (MvPolynomial.eval₂Hom
          (algebraMap K (Polynomial (SecondCoordinateSubfield f)))
          ![Polynomial.X, Polynomial.C (secondCoordinateInSubfield f)])
  let rhs : MvPolynomial (Fin 2) K →+* PlaneCurveFunctionField f :=
    MvPolynomial.eval₂Hom (algebraMap K (PlaneCurveFunctionField f))
      (planeCurveFunction f)
  have hhom : lhs = rhs := by
    apply MvPolynomial.ringHom_ext
    · intro c
      simp [lhs, rhs]
    · intro i
      fin_cases i <;>
        simp [lhs, rhs, secondCoordinateInSubfield]
  change lhs f = 0
  rw [hhom]
  exact eval₂_planeCurveFunction_eq_zero f

theorem firstCoordinate_isAlgebraic_over_second
    (f : MvPolynomial (Fin 2) K) [IsDomain (PlaneCurveCoordinateRing f)]
    (hpoly : polynomialOverSecondCoordinate f ≠ 0) :
    IsAlgebraic (SecondCoordinateSubfield f) (planeCurveFunction f 0) := by
  refine ⟨polynomialOverSecondCoordinate f, hpoly, ?_⟩
  simpa [Polynomial.aeval_def] using eval₂_polynomialOverSecondCoordinate_eq_zero f

theorem adjoin_firstCoordinate_over_second_eq_top
    (f : MvPolynomial (Fin 2) K) [IsDomain (PlaneCurveCoordinateRing f)] :
    IntermediateField.adjoin (SecondCoordinateSubfield f) {planeCurveFunction f 0} = ⊤ := by
  have hpair :
      IntermediateField.adjoin K
          ({planeCurveFunction f 1, planeCurveFunction f 0} :
            Set (PlaneCurveFunctionField f)) = ⊤ := by
    have horiginal :
        IntermediateField.adjoin K
            ({planeCurveFunction f 0, planeCurveFunction f 1} :
              Set (PlaneCurveFunctionField f)) = ⊤ := by
      rw [← range_planeCurveFunction f]
      exact adjoin_planeCurveFunctions_eq_top
    simpa [Set.pair_comm] using horiginal
  apply IntermediateField.restrictScalars_injective K
  rw [IntermediateField.restrictScalars_top]
  change
    (IntermediateField.adjoin
        (IntermediateField.adjoin K {planeCurveFunction f 1})
        {planeCurveFunction f 0}).restrictScalars K = ⊤
  rw [IntermediateField.adjoin_adjoin_left]
  simpa only [Set.singleton_union] using hpair

theorem finiteDimensional_over_secondCoordinate
    (f : MvPolynomial (Fin 2) K) [IsDomain (PlaneCurveCoordinateRing f)]
    (hpoly : polynomialOverSecondCoordinate f ≠ 0) :
    FiniteDimensional (SecondCoordinateSubfield f) (PlaneCurveFunctionField f) := by
  have halg := firstCoordinate_isAlgebraic_over_second f hpoly
  letI : FiniteDimensional (SecondCoordinateSubfield f)
      (IntermediateField.adjoin (SecondCoordinateSubfield f) {planeCurveFunction f 0}) :=
    IntermediateField.adjoin.finiteDimensional halg.isIntegral
  letI : FiniteDimensional (SecondCoordinateSubfield f)
      (⊤ : IntermediateField (SecondCoordinateSubfield f) (PlaneCurveFunctionField f)) := by
    rw [← adjoin_firstCoordinate_over_second_eq_top f]
    infer_instance
  exact IntermediateField.topEquiv.toLinearEquiv.finiteDimensional

/-- The fraction field of the coefficient polynomial ring in the second affine coordinate is the
field generated by that coordinate function. -/
def secondCoordinateFractionEquiv
    (f : MvPolynomial (Fin 2) K) [IsDomain (PlaneCurveCoordinateRing f)]
    (htrans : Transcendental K (planeCurveFunction f 1)) :
    FractionRing (MvPolynomial {i : Fin 2 // i ≠ 0} K) ≃ₐ[K]
      SecondCoordinateSubfield f := by
  let remaining := {i : Fin 2 // i ≠ 0}
  have remaining_value_one (i : remaining) : i.1 = 1 := by omega
  letI : Subsingleton remaining :=
    ⟨fun i j => Subtype.ext ((remaining_value_one i).trans (remaining_value_one j).symm)⟩
  let i1 : remaining := ⟨1, by decide⟩
  have hIndependent : AlgebraicIndependent K
      (fun _ : remaining => planeCurveFunction f 1) := by
    rw [algebraicIndependent_singleton_iff i1]
    exact htrans
  have hrange : Set.range (fun _ : remaining => planeCurveFunction f 1) =
      ({planeCurveFunction f 1} : Set (PlaneCurveFunctionField f)) := by
    ext z
    constructor
    · rintro ⟨i, rfl⟩
      simp
    · intro hz
      rw [Set.mem_singleton_iff] at hz
      subst z
      exact ⟨i1, rfl⟩
  have hfield :
      IntermediateField.adjoin K
          (Set.range (fun _ : remaining => planeCurveFunction f 1)) =
        SecondCoordinateSubfield f := by
    rw [hrange]
  exact hIndependent.aevalEquivField.trans (IntermediateField.equivOfEq hfield)

set_option maxHeartbeats 800000 in
/-- The second-coordinate fraction-field equivalence extends coefficient evaluation. -/
@[simp]
theorem secondCoordinateFractionEquiv_algebraMap
    (f : MvPolynomial (Fin 2) K) [IsDomain (PlaneCurveCoordinateRing f)]
    (htrans : Transcendental K (planeCurveFunction f 1))
    (p : MvPolynomial {i : Fin 2 // i ≠ 0} K) :
    secondCoordinateFractionEquiv f htrans
        (algebraMap (MvPolynomial {i : Fin 2 // i ≠ 0} K)
          (FractionRing (MvPolynomial {i : Fin 2 // i ≠ 0} K)) p) =
      secondCoordinateCoefficientEval f p := by
  apply Subtype.ext
  · simp [secondCoordinateFractionEquiv, secondCoordinateCoefficientEval,
      secondCoordinateInSubfield]
    simpa [MvPolynomial.aeval_def, secondCoordinateInSubfield] using
      (MvPolynomial.hom_eval₂ p
        (algebraMap K (SecondCoordinateSubfield f))
        (SecondCoordinateSubfield f).val.toRingHom
        (fun _ => secondCoordinateInSubfield f)).symm

/-- The plane equation remains irreducible over the field generated by the second coordinate when
viewed as a polynomial in the first coordinate. -/
theorem polynomialOverSecondCoordinate_irreducible
    {f : MvPolynomial (Fin 2) K} (hf : Irreducible f)
    (hderiv : MvPolynomial.pderiv 0 f ≠ 0) :
    letI := planeCurveCoordinateRing_isDomain hf
    Irreducible (polynomialOverSecondCoordinate f) := by
  letI : IsDomain (PlaneCurveCoordinateRing f) := planeCurveCoordinateRing_isDomain hf
  let R := MvPolynomial {i : Fin 2 // i ≠ 0} K
  let F := FractionRing R
  let p := polynomialInFirstVariablePresentation f
  have hfirst : 0 < MvPolynomial.degreeOf 0 f :=
    degreeOf_first_pos_of_pderiv_ne_zero hderiv
  have htrans : Transcendental K (planeCurveFunction f 1) :=
    secondCoordinate_transcendental hf hfirst
  have hpIrreducible : Irreducible p := polynomialInFirstVariablePresentation_irreducible hf
  have hpDerivative : p.derivative ≠ 0 :=
    derivative_polynomialInFirstVariablePresentation_ne_zero hderiv
  have hpDegree : p.natDegree ≠ 0 := by
    intro hdegree
    exact hpDerivative (Polynomial.derivative_of_natDegree_zero hdegree)
  have hpPrimitive : p.IsPrimitive := hpIrreducible.isPrimitive hpDegree
  have hFractionIrreducible : Irreducible (p.map (algebraMap R F)) :=
    (hpPrimitive.irreducible_iff_irreducible_map_fraction_map (K := F)).mp hpIrreducible
  let e := secondCoordinateFractionEquiv f htrans
  have hMappedIrreducible :
      Irreducible ((p.map (algebraMap R F)).map e.toRingHom) :=
    hFractionIrreducible.map (Polynomial.mapEquiv e.toRingEquiv).toMulEquiv
  have hmap : e.toRingHom.comp (algebraMap R F) = secondCoordinateCoefficientEval f := by
    apply DFunLike.ext _ _
    intro q
    exact secondCoordinateFractionEquiv_algebraMap f htrans q
  rw [polynomialOverSecondCoordinate_eq_map_polynomialInFirstVariablePresentation]
  simpa only [Polynomial.map_map, hmap] using hMappedIrreducible

theorem derivative_polynomialOverSecondCoordinate_ne_zero
    {f : MvPolynomial (Fin 2) K} (hf : Irreducible f)
    (hderiv : MvPolynomial.pderiv 0 f ≠ 0) :
    letI := planeCurveCoordinateRing_isDomain hf
    (polynomialOverSecondCoordinate f).derivative ≠ 0 := by
  letI : IsDomain (PlaneCurveCoordinateRing f) := planeCurveCoordinateRing_isDomain hf
  rw [polynomialOverSecondCoordinate_eq_map_polynomialInFirstVariablePresentation,
    Polynomial.derivative_map]
  exact (Polynomial.map_ne_zero_iff
    (secondCoordinateCoefficientEval_injective hf
      (degreeOf_first_pos_of_pderiv_ne_zero hderiv))).mpr
        (derivative_polynomialInFirstVariablePresentation_ne_zero hderiv)

theorem polynomialOverSecondCoordinate_separable
    {f : MvPolynomial (Fin 2) K} (hf : Irreducible f)
    (hderiv : MvPolynomial.pderiv 0 f ≠ 0) :
    letI := planeCurveCoordinateRing_isDomain hf
    (polynomialOverSecondCoordinate f).Separable := by
  letI : IsDomain (PlaneCurveCoordinateRing f) := planeCurveCoordinateRing_isDomain hf
  exact (Polynomial.separable_iff_derivative_ne_zero
    (polynomialOverSecondCoordinate_irreducible hf hderiv)).mpr
      (derivative_polynomialOverSecondCoordinate_ne_zero hf hderiv)

/-- The first coordinate is separable over the field generated by the second coordinate. -/
theorem firstCoordinate_isSeparable_over_second
    {f : MvPolynomial (Fin 2) K} (hf : Irreducible f)
    (hderiv : MvPolynomial.pderiv 0 f ≠ 0) :
    letI := planeCurveCoordinateRing_isDomain hf
    IsSeparable (SecondCoordinateSubfield f) (planeCurveFunction f 0) := by
  letI : IsDomain (PlaneCurveCoordinateRing f) := planeCurveCoordinateRing_isDomain hf
  have hroot : Polynomial.aeval (planeCurveFunction f 0)
      (polynomialOverSecondCoordinate f) = 0 := by
    simpa [Polynomial.aeval_def] using eval₂_polynomialOverSecondCoordinate_eq_zero f
  exact (polynomialOverSecondCoordinate_separable hf hderiv).of_dvd
    (minpoly.dvd (SecondCoordinateSubfield f) (planeCurveFunction f 0) hroot)

/-- The plane-curve function field is finite and separable over the field generated by its second
coordinate. -/
theorem finiteSeparable_over_secondCoordinate_of_irreducible
    {f : MvPolynomial (Fin 2) K} (hf : Irreducible f)
    (hderiv : MvPolynomial.pderiv 0 f ≠ 0) :
    letI := planeCurveCoordinateRing_isDomain hf
    FiniteDimensional (SecondCoordinateSubfield f) (PlaneCurveFunctionField f) ∧
      Algebra.IsSeparable (SecondCoordinateSubfield f) (PlaneCurveFunctionField f) := by
  letI : IsDomain (PlaneCurveCoordinateRing f) := planeCurveCoordinateRing_isDomain hf
  have hpoly : polynomialOverSecondCoordinate f ≠ 0 :=
    polynomialOverSecondCoordinate_ne_zero_of_irreducible hf
      (degreeOf_first_pos_of_pderiv_ne_zero hderiv)
  constructor
  · exact finiteDimensional_over_secondCoordinate f hpoly
  · have hAdjoin : Algebra.IsSeparable (SecondCoordinateSubfield f)
        (IntermediateField.adjoin (SecondCoordinateSubfield f)
          {planeCurveFunction f 0}) :=
      (IntermediateField.isSeparable_adjoin_simple_iff_isSeparable
        (SecondCoordinateSubfield f) (PlaneCurveFunctionField f)).mpr
          (firstCoordinate_isSeparable_over_second hf hderiv)
    have hTop : Algebra.IsSeparable (SecondCoordinateSubfield f)
        (⊤ : IntermediateField (SecondCoordinateSubfield f)
          (PlaneCurveFunctionField f)) := by
      rw [← adjoin_firstCoordinate_over_second_eq_top f]
      exact hAdjoin
    exact (IntermediateField.isSeparable_top
      (F := SecondCoordinateSubfield f) (E := PlaneCurveFunctionField f)).mp hTop

theorem natDegree_polynomialOverSecondCoordinate_eq_degreeOf_first
    {f : MvPolynomial (Fin 2) K} (hf : Irreducible f)
    (hderiv : MvPolynomial.pderiv 0 f ≠ 0) :
    letI := planeCurveCoordinateRing_isDomain hf
    (polynomialOverSecondCoordinate f).natDegree = MvPolynomial.degreeOf 0 f := by
  letI : IsDomain (PlaneCurveCoordinateRing f) := planeCurveCoordinateRing_isDomain hf
  rw [polynomialOverSecondCoordinate_eq_map_polynomialInFirstVariablePresentation,
    Polynomial.natDegree_map_eq_of_injective
      (secondCoordinateCoefficientEval_injective hf
        (degreeOf_first_pos_of_pderiv_ne_zero hderiv))]
  exact (MvPolynomial.degreeOf_eq_natDegree (0 : Fin 2) f).symm

theorem natDegree_minpoly_firstCoordinate_eq_degreeOf_first
    {f : MvPolynomial (Fin 2) K} (hf : Irreducible f)
    (hderiv : MvPolynomial.pderiv 0 f ≠ 0) :
    letI := planeCurveCoordinateRing_isDomain hf
    (minpoly (SecondCoordinateSubfield f) (planeCurveFunction f 0)).natDegree =
      MvPolynomial.degreeOf 0 f := by
  letI : IsDomain (PlaneCurveCoordinateRing f) := planeCurveCoordinateRing_isDomain hf
  let p := polynomialOverSecondCoordinate f
  have hpIrreducible : Irreducible p := polynomialOverSecondCoordinate_irreducible hf hderiv
  have hroot : Polynomial.aeval (planeCurveFunction f 0) p = 0 := by
    simpa [p, Polynomial.aeval_def] using eval₂_polynomialOverSecondCoordinate_eq_zero f
  have heq := minpoly.eq_of_irreducible hpIrreducible hroot
  calc
    (minpoly (SecondCoordinateSubfield f) (planeCurveFunction f 0)).natDegree =
        (p * Polynomial.C p.leadingCoeff⁻¹).natDegree := by rw [heq]
    _ = p.natDegree := Polynomial.natDegree_mul_C
      (inv_ne_zero (Polynomial.leadingCoeff_ne_zero.mpr hpIrreducible.ne_zero))
    _ = MvPolynomial.degreeOf 0 f :=
      natDegree_polynomialOverSecondCoordinate_eq_degreeOf_first hf hderiv

/-- The extension degree over the second-coordinate field is the first-coordinate degree of the
plane equation. -/
theorem finrank_over_secondCoordinate_eq_degreeOf_first_of_irreducible
    {f : MvPolynomial (Fin 2) K} (hf : Irreducible f)
    (hderiv : MvPolynomial.pderiv 0 f ≠ 0) :
    letI := planeCurveCoordinateRing_isDomain hf
    Module.finrank (SecondCoordinateSubfield f) (PlaneCurveFunctionField f) =
      MvPolynomial.degreeOf 0 f := by
  letI : IsDomain (PlaneCurveCoordinateRing f) := planeCurveCoordinateRing_isDomain hf
  have hpoly : polynomialOverSecondCoordinate f ≠ 0 :=
    polynomialOverSecondCoordinate_ne_zero_of_irreducible hf
      (degreeOf_first_pos_of_pderiv_ne_zero hderiv)
  letI : FiniteDimensional (SecondCoordinateSubfield f) (PlaneCurveFunctionField f) :=
    finiteDimensional_over_secondCoordinate f hpoly
  have halg := firstCoordinate_isAlgebraic_over_second f hpoly
  calc
    Module.finrank (SecondCoordinateSubfield f) (PlaneCurveFunctionField f) =
        Module.finrank (SecondCoordinateSubfield f)
          (⊤ : IntermediateField (SecondCoordinateSubfield f)
            (PlaneCurveFunctionField f)) := by rw [IntermediateField.finrank_top']
    _ = Module.finrank (SecondCoordinateSubfield f)
          (IntermediateField.adjoin (SecondCoordinateSubfield f)
            {planeCurveFunction f 0}) := by
      rw [adjoin_firstCoordinate_over_second_eq_top f]
    _ = (minpoly (SecondCoordinateSubfield f) (planeCurveFunction f 0)).natDegree :=
      IntermediateField.adjoin.finrank halg.isIntegral
    _ = MvPolynomial.degreeOf 0 f :=
      natDegree_minpoly_firstCoordinate_eq_degreeOf_first hf hderiv

end

end BGS.CorvajaZannier
