import BGS.CorvajaZannier.PlaneCurveDiagonalStabilizer
import BGS.CorvajaZannier.PoweredImageIndex
import Mathlib.FieldTheory.Galois.Basic
import Mathlib.FieldTheory.KummerExtension
import Mathlib.RingTheory.RootsOfUnity.AlgebraicallyClosed
import Mathlib.Tactic

/-!
# The source-to-powered-image index over algebraically closed constants

When the power exponents are nonzero in the constant field, the source
function field is a Galois extension of the field generated by the two powered
coordinates.  Its automorphisms act diagonally on the two coordinates.  The
resulting pair of roots of unity lies in the support-character stabilizer, so
a rank-two support determinant bounds the extension degree.
-/

namespace BGS.CorvajaZannier
noncomputable section

private def autUnitRatio {B L : Type*} [Field B] [Field L] [Algebra B L]
    (σ : L ≃ₐ[B] L) (x : L) (hx : x ≠ 0) : Lˣ :=
  Units.mk0 (σ x / x) (div_ne_zero ((map_ne_zero σ).2 hx) hx)

private theorem autUnitRatio_pow_eq_one
    {B L : Type*} [Field B] [Field L] [Algebra B L]
    (σ : L ≃ₐ[B] L) (x : L) (hx : x ≠ 0) (d : ℕ)
    (hfix : σ (x ^ d) = x ^ d) :
    autUnitRatio σ x hx ^ d = 1 := by
  apply Units.ext
  change (σ x / x) ^ d = 1
  rw [div_pow, ← map_pow, hfix, div_self (pow_ne_zero d hx)]

private def descendedRootUnit
    {F L : Type*} [Field F] [Field L] [Algebra F L]
    {d : ℕ} [NeZero d]
    (hμ : (primitiveRoots d F).Nonempty)
    (u : Lˣ) (hu : u ^ d = 1) : Fˣ :=
  ((rootsOfUnityEquivOfPrimitiveRoots (algebraMap F L).injective hμ).symm
    (⟨u, hu⟩ : rootsOfUnity d L)).1

private theorem algebraMap_descendedRootUnit
    {F L : Type*} [Field F] [Field L] [Algebra F L]
    {d : ℕ} [NeZero d]
    (hμ : (primitiveRoots d F).Nonempty)
    (u : Lˣ) (hu : u ^ d = 1) :
    algebraMap F L (descendedRootUnit hμ u hu : F) = (u : L) := by
  exact rootsOfUnityEquivOfPrimitiveRoots_symm_apply
    (algebraMap F L).injective hμ (⟨u, hu⟩ : rootsOfUnity d L)

set_option maxHeartbeats 800000 in
theorem poweredCoordinateImageField_adjoin_coordinates_eq_top_and_ne_zero
    {F : Type*} [Field F] {f : MvPolynomial (Fin 2) F}
    (hf : Irreducible f)
    (hpartialFirst : MvPolynomial.pderiv 0 f ≠ 0)
    (hpartialSecond : MvPolynomial.pderiv 1 f ≠ 0)
    (m n : ℕ) :
    letI := planeCurveCoordinateRing_isDomain hf
    let L := PlaneCurveFunctionField f
    let B := PoweredCoordinateImageField f m n
    IntermediateField.adjoin B
        ({planeCurveFunction f 0, planeCurveFunction f 1} : Set L) = ⊤ ∧
      planeCurveFunction f 0 ≠ 0 ∧ planeCurveFunction f 1 ≠ 0 := by
  letI : IsDomain (PlaneCurveCoordinateRing f) :=
    planeCurveCoordinateRing_isDomain hf
  let L := PlaneCurveFunctionField f
  let B := PoweredCoordinateImageField f m n
  have hxtrans : Transcendental F (planeCurveFunction f 0) :=
    firstCoordinate_transcendental hf
      (degreeOf_second_pos_of_pderiv_ne_zero hpartialSecond)
  have hytrans : Transcendental F (planeCurveFunction f 1) :=
    secondCoordinate_transcendental hf
      (degreeOf_first_pos_of_pderiv_ne_zero hpartialFirst)
  have hx0 : planeCurveFunction f 0 ≠ 0 := by
    intro hx
    apply hxtrans
    rw [hx]
    exact isAlgebraic_zero
  have hy0 : planeCurveFunction f 1 ≠ 0 := by
    intro hy
    apply hytrans
    rw [hy]
    exact isAlgebraic_zero
  refine ⟨?_, hx0, hy0⟩
  apply IntermediateField.restrictScalars_injective F
  rw [IntermediateField.restrictScalars_top]
  rw [IntermediateField.restrictScalars_adjoin_eq_sup]
  have hxy : IntermediateField.adjoin F
      ({planeCurveFunction f 0, planeCurveFunction f 1} : Set L) = ⊤ := by
    rw [← range_planeCurveFunction f]
    exact adjoin_planeCurveFunctions_eq_top
  rw [hxy]
  exact sup_eq_right.mpr le_top

set_option maxHeartbeats 800000 in
set_option synthInstance.maxHeartbeats 200000 in
theorem finiteDimensional_poweredCoordinateImageField
    {F : Type*} [Field F] {f : MvPolynomial (Fin 2) F}
    (hf : Irreducible f)
    (hpartialSecond : MvPolynomial.pderiv 1 f ≠ 0)
    (m n : ℕ) (hm : 0 < m) :
    letI := planeCurveCoordinateRing_isDomain hf
    FiniteDimensional (PoweredCoordinateImageField f m n)
      (PlaneCurveFunctionField f) := by
  letI : IsDomain (PlaneCurveCoordinateRing f) :=
    planeCurveCoordinateRing_isDomain hf
  let L := PlaneCurveFunctionField f
  let E0 := FirstPoweredCoordinateSubfield f m
  let B := PoweredCoordinateImageField f m n
  letI : FiniteDimensional E0 L :=
    finiteDimensional_over_firstPoweredCoordinate hf hpartialSecond m hm
  have hE0B : E0 ≤ B := by
    apply IntermediateField.adjoin.mono F
    intro z hz
    simp only [Set.mem_singleton_iff] at hz
    simp only [Set.mem_insert_iff, Set.mem_singleton_iff]
    exact Or.inl hz
  letI : Algebra E0 B :=
    (IntermediateField.inclusion hE0B).toRingHom.toAlgebra
  letI : IsScalarTower E0 B L := by
    apply IsScalarTower.of_algebraMap_eq'
    ext z
    rfl
  exact Module.Finite.of_restrictScalars_finite E0 B L

theorem firstCoordinate_isSeparable_over_poweredCoordinateImageField
    {F : Type*} [Field F] {f : MvPolynomial (Fin 2) F}
    (hf : Irreducible f)
    (hpartialSecond : MvPolynomial.pderiv 1 f ≠ 0)
    (m n : ℕ) (hmF : (m : F) ≠ 0) :
    letI := planeCurveCoordinateRing_isDomain hf
    IsSeparable (PoweredCoordinateImageField f m n)
      (planeCurveFunction f 0) := by
  letI : IsDomain (PlaneCurveCoordinateRing f) :=
    planeCurveCoordinateRing_isDomain hf
  let L := PlaneCurveFunctionField f
  let B := PoweredCoordinateImageField f m n
  let x : L := planeCurveFunction f 0
  have hxtrans : Transcendental F x :=
    firstCoordinate_transcendental hf
      (degreeOf_second_pos_of_pderiv_ne_zero hpartialSecond)
  have hx0 : x ≠ 0 := by
    intro hx
    apply hxtrans
    rw [hx]
    exact isAlgebraic_zero
  let bx : B := ⟨x ^ m, by
    apply IntermediateField.subset_adjoin F
    simp [x]⟩
  let P : Polynomial B := Polynomial.X ^ m - Polynomial.C bx
  have hP : Polynomial.aeval x P = 0 := by
    simp only [P, map_sub, map_pow, Polynomial.aeval_X, Polynomial.aeval_C]
    change x ^ m - (algebraMap B L) bx = 0
    rw [IntermediateField.algebraMap_apply]
    simp [bx]
  have hdvd : minpoly B x ∣ P := minpoly.dvd B x hP
  have hmB : (m : B) ≠ 0 := by
    intro h
    apply hmF
    apply (algebraMap F B).injective
    simpa using h
  have hbx0 : bx ≠ 0 := by
    intro h
    apply pow_ne_zero m hx0
    exact congrArg Subtype.val h
  exact Polynomial.Separable.of_dvd
    (Polynomial.separable_X_pow_sub_C bx hmB hbx0)
    hdvd

theorem firstCoordinate_minpoly_splits_over_poweredCoordinateImageField
    {F : Type*} [Field F] [IsAlgClosed F]
    {f : MvPolynomial (Fin 2) F}
    (hf : Irreducible f)
    (m n : ℕ) (hm : 0 < m) (hmF : (m : F) ≠ 0) :
    letI := planeCurveCoordinateRing_isDomain hf
    (Polynomial.map
      (algebraMap (PoweredCoordinateImageField f m n)
        (PlaneCurveFunctionField f))
      (minpoly (PoweredCoordinateImageField f m n)
        (planeCurveFunction f 0))).Splits := by
  letI : IsDomain (PlaneCurveCoordinateRing f) :=
    planeCurveCoordinateRing_isDomain hf
  let L := PlaneCurveFunctionField f
  let B := PoweredCoordinateImageField f m n
  let x : L := planeCurveFunction f 0
  let bx : B := ⟨x ^ m, by
    apply IntermediateField.subset_adjoin F
    simp [x]⟩
  let P : Polynomial B := Polynomial.X ^ m - Polynomial.C bx
  have hP : Polynomial.aeval x P = 0 := by
    simp only [P, map_sub, map_pow, Polynomial.aeval_X, Polynomial.aeval_C]
    change x ^ m - (algebraMap B L) bx = 0
    rw [IntermediateField.algebraMap_apply]
    simp [bx]
  have hdvd : minpoly B x ∣ P := minpoly.dvd B x hP
  letI : NeZero m := ⟨Nat.ne_of_gt hm⟩
  letI : NeZero (m : F) := ⟨hmF⟩
  obtain ⟨ζ, hζ⟩ := HasEnoughRootsOfUnity.exists_primitiveRoot F m
  have hζL : IsPrimitiveRoot (algebraMap F L ζ) m :=
    hζ.map_of_injective (algebraMap F L).injective
  have hsplits : (Polynomial.X ^ m - Polynomial.C (x ^ m)).Splits :=
    X_pow_sub_C_splits_of_isPrimitiveRoot hζL rfl
  apply Polynomial.Splits.of_dvd hsplits
    (Polynomial.X_pow_sub_C_ne_zero hm (x ^ m))
  have hmap := Polynomial.map_dvd (algebraMap B L) hdvd
  have hbx : (algebraMap B L) bx = x ^ m := by
    rw [IntermediateField.algebraMap_apply]
  rw [show P = Polynomial.X ^ m - Polynomial.C bx from rfl,
    Polynomial.map_sub, Polynomial.map_pow, Polynomial.map_X,
    Polynomial.map_C, hbx] at hmap
  exact hmap

theorem secondCoordinate_isSeparable_over_poweredCoordinateImageField
    {F : Type*} [Field F] {f : MvPolynomial (Fin 2) F}
    (hf : Irreducible f)
    (hpartialFirst : MvPolynomial.pderiv 0 f ≠ 0)
    (m n : ℕ) (hnF : (n : F) ≠ 0) :
    letI := planeCurveCoordinateRing_isDomain hf
    IsSeparable (PoweredCoordinateImageField f m n)
      (planeCurveFunction f 1) := by
  letI : IsDomain (PlaneCurveCoordinateRing f) :=
    planeCurveCoordinateRing_isDomain hf
  let L := PlaneCurveFunctionField f
  let B := PoweredCoordinateImageField f m n
  let y : L := planeCurveFunction f 1
  have hytrans : Transcendental F y :=
    secondCoordinate_transcendental hf
      (degreeOf_first_pos_of_pderiv_ne_zero hpartialFirst)
  have hy0 : y ≠ 0 := by
    intro hy
    apply hytrans
    rw [hy]
    exact isAlgebraic_zero
  let by' : B := ⟨y ^ n, by
    apply IntermediateField.subset_adjoin F
    simp [y]⟩
  let P : Polynomial B := Polynomial.X ^ n - Polynomial.C by'
  have hP : Polynomial.aeval y P = 0 := by
    simp only [P, map_sub, map_pow, Polynomial.aeval_X, Polynomial.aeval_C]
    change y ^ n - (algebraMap B L) by' = 0
    rw [IntermediateField.algebraMap_apply]
    simp [by']
  have hdvd : minpoly B y ∣ P := minpoly.dvd B y hP
  have hnB : (n : B) ≠ 0 := by
    intro h
    apply hnF
    apply (algebraMap F B).injective
    simpa using h
  have hby0 : by' ≠ 0 := by
    intro h
    apply pow_ne_zero n hy0
    exact congrArg Subtype.val h
  exact Polynomial.Separable.of_dvd
    (Polynomial.separable_X_pow_sub_C by' hnB hby0)
    hdvd

theorem secondCoordinate_minpoly_splits_over_poweredCoordinateImageField
    {F : Type*} [Field F] [IsAlgClosed F]
    {f : MvPolynomial (Fin 2) F}
    (hf : Irreducible f)
    (m n : ℕ) (hn : 0 < n) (hnF : (n : F) ≠ 0) :
    letI := planeCurveCoordinateRing_isDomain hf
    (Polynomial.map
      (algebraMap (PoweredCoordinateImageField f m n)
        (PlaneCurveFunctionField f))
      (minpoly (PoweredCoordinateImageField f m n)
        (planeCurveFunction f 1))).Splits := by
  letI : IsDomain (PlaneCurveCoordinateRing f) :=
    planeCurveCoordinateRing_isDomain hf
  let L := PlaneCurveFunctionField f
  let B := PoweredCoordinateImageField f m n
  let y : L := planeCurveFunction f 1
  let by' : B := ⟨y ^ n, by
    apply IntermediateField.subset_adjoin F
    simp [y]⟩
  let P : Polynomial B := Polynomial.X ^ n - Polynomial.C by'
  have hP : Polynomial.aeval y P = 0 := by
    simp only [P, map_sub, map_pow, Polynomial.aeval_X, Polynomial.aeval_C]
    change y ^ n - (algebraMap B L) by' = 0
    rw [IntermediateField.algebraMap_apply]
    simp [by']
  have hdvd : minpoly B y ∣ P := minpoly.dvd B y hP
  letI : NeZero n := ⟨Nat.ne_of_gt hn⟩
  letI : NeZero (n : F) := ⟨hnF⟩
  obtain ⟨η, hη⟩ := HasEnoughRootsOfUnity.exists_primitiveRoot F n
  have hηL : IsPrimitiveRoot (algebraMap F L η) n :=
    hη.map_of_injective (algebraMap F L).injective
  have hsplits : (Polynomial.X ^ n - Polynomial.C (y ^ n)).Splits :=
    X_pow_sub_C_splits_of_isPrimitiveRoot hηL rfl
  apply Polynomial.Splits.of_dvd hsplits
    (Polynomial.X_pow_sub_C_ne_zero hn (y ^ n))
  have hmap := Polynomial.map_dvd (algebraMap B L) hdvd
  have hby : (algebraMap B L) by' = y ^ n := by
    rw [IntermediateField.algebraMap_apply]
  rw [show P = Polynomial.X ^ n - Polynomial.C by' from rfl,
    Polynomial.map_sub, Polynomial.map_pow, Polynomial.map_X,
    Polynomial.map_C, hby] at hmap
  exact hmap

set_option maxHeartbeats 800000 in
set_option synthInstance.maxHeartbeats 200000 in
theorem isGalois_over_poweredCoordinateImageField
    {F : Type*} [Field F] [IsAlgClosed F]
    {f : MvPolynomial (Fin 2) F}
    (hf : Irreducible f)
    (hpartialFirst : MvPolynomial.pderiv 0 f ≠ 0)
    (hpartialSecond : MvPolynomial.pderiv 1 f ≠ 0)
    (m n : ℕ) (hm : 0 < m) (hn : 0 < n)
    (hmF : (m : F) ≠ 0) (hnF : (n : F) ≠ 0) :
    letI := planeCurveCoordinateRing_isDomain hf
    IsGalois (PoweredCoordinateImageField f m n)
      (PlaneCurveFunctionField f) := by
  letI : IsDomain (PlaneCurveCoordinateRing f) :=
    planeCurveCoordinateRing_isDomain hf
  let L := PlaneCurveFunctionField f
  let B := PoweredCoordinateImageField f m n
  let E0 := FirstPoweredCoordinateSubfield f m
  letI : FiniteDimensional E0 L :=
    finiteDimensional_over_firstPoweredCoordinate hf hpartialSecond m hm
  have hE0B : E0 ≤ B := by
    apply IntermediateField.adjoin.mono F
    intro z hz
    simp only [Set.mem_singleton_iff] at hz
    simp only [Set.mem_insert_iff, Set.mem_singleton_iff]
    exact Or.inl hz
  letI : Algebra E0 B :=
    (IntermediateField.inclusion hE0B).toRingHom.toAlgebra
  letI : IsScalarTower E0 B L := by
    apply IsScalarTower.of_algebraMap_eq'
    ext z
    rfl
  letI : FiniteDimensional B L :=
    Module.Finite.of_restrictScalars_finite E0 B L
  let x : L := planeCurveFunction f 0
  let y : L := planeCurveFunction f 1
  have hbasic := poweredCoordinateImageField_adjoin_coordinates_eq_top_and_ne_zero hf hpartialFirst
    hpartialSecond m n
  have hgen : IntermediateField.adjoin B ({x, y} : Set L) = ⊤ := hbasic.1
  have hxsep : IsSeparable B x :=
    firstCoordinate_isSeparable_over_poweredCoordinateImageField hf hpartialSecond m n hmF
  have hysep : IsSeparable B y :=
    secondCoordinate_isSeparable_over_poweredCoordinateImageField hf hpartialFirst m n hnF
  letI : Algebra.IsSeparable B L := ⟨fun z => by
    letI : Algebra.IsSeparable B (IntermediateField.adjoin B ({x, y} : Set L)) :=
      IntermediateField.isSeparable_adjoin_pair_of_isSeparable B L hxsep hysep
    have hz : z ∈ IntermediateField.adjoin B ({x, y} : Set L) := by
      rw [hgen]
      exact Set.mem_univ z
    exact IntermediateField.isSeparable_of_mem_isSeparable B L hz⟩
  have hxsplits :
      (Polynomial.map (algebraMap B L) (minpoly B x)).Splits :=
    firstCoordinate_minpoly_splits_over_poweredCoordinateImageField hf m n hm hmF
  have hysplits :
      (Polynomial.map (algebraMap B L) (minpoly B y)).Splits :=
    secondCoordinate_minpoly_splits_over_poweredCoordinateImageField hf m n hn hnF
  letI : Normal B L := normal_iff.mpr fun z => by
    refine ⟨Algebra.IsIntegral.isIntegral z, ?_⟩
    have hz : z ∈ IntermediateField.adjoin B ({x, y} : Set L) := by
      rw [hgen]
      exact Set.mem_univ z
    apply IntermediateField.splits_of_mem_adjoin B L _ hz
    intro q hq
    simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hq
    rcases hq with rfl | rfl
    · exact ⟨IsSeparable.isIntegral hxsep, hxsplits⟩
    · exact ⟨IsSeparable.isIntegral hysep, hysplits⟩
  exact IsGalois.mk

set_option maxHeartbeats 800000 in
set_option synthInstance.maxHeartbeats 200000 in
theorem exists_support_stabilizer_scaling_of_poweredImage_aut
    {F : Type*} [Field F] [IsAlgClosed F]
    {f : MvPolynomial (Fin 2) F}
    (hf : Irreducible f)
    (hpartialFirst : MvPolynomial.pderiv 0 f ≠ 0)
    (hpartialSecond : MvPolynomial.pderiv 1 f ≠ 0)
    (m n : ℕ) (hm : 0 < m) (hn : 0 < n)
    (hmF : (m : F) ≠ 0) (hnF : (n : F) ≠ 0)
    (σ :
      letI := planeCurveCoordinateRing_isDomain hf
      (PlaneCurveFunctionField f) ≃ₐ[PoweredCoordinateImageField f m n]
        (PlaneCurveFunctionField f)) :
    letI := planeCurveCoordinateRing_isDomain hf
    ∃ z : Fˣ × Fˣ,
      algebraMap F (PlaneCurveFunctionField f) z.1 * planeCurveFunction f 0 =
          σ (planeCurveFunction f 0) ∧
      algebraMap F (PlaneCurveFunctionField f) z.2 * planeCurveFunction f 1 =
          σ (planeCurveFunction f 1) ∧
      (∀ r ∈ f.support, ∀ s ∈ f.support,
        z.1 ^ ((s 0 : ℤ) - (r 0 : ℤ)) *
          z.2 ^ ((s 1 : ℤ) - (r 1 : ℤ)) = 1) := by
  letI : IsDomain (PlaneCurveCoordinateRing f) :=
    planeCurveCoordinateRing_isDomain hf
  let L := PlaneCurveFunctionField f
  let B := PoweredCoordinateImageField f m n
  let x : L := planeCurveFunction f 0
  let y : L := planeCurveFunction f 1
  have hbasic := poweredCoordinateImageField_adjoin_coordinates_eq_top_and_ne_zero hf hpartialFirst
    hpartialSecond m n
  have hx0 : x ≠ 0 := hbasic.2.1
  have hy0 : y ≠ 0 := hbasic.2.2
  let bx : B := ⟨x ^ m, by
    apply IntermediateField.subset_adjoin F
    simp [x]⟩
  let by' : B := ⟨y ^ n, by
    apply IntermediateField.subset_adjoin F
    simp [y]⟩
  have hbx : (algebraMap B L) bx = x ^ m := by
    rw [IntermediateField.algebraMap_apply]
  have hby : (algebraMap B L) by' = y ^ n := by
    rw [IntermediateField.algebraMap_apply]
  have hfixx : σ (x ^ m) = x ^ m := by
    rw [← hbx, σ.commutes]
  have hfixy : σ (y ^ n) = y ^ n := by
    rw [← hby, σ.commutes]
  have hux : autUnitRatio σ x hx0 ^ m = 1 :=
    autUnitRatio_pow_eq_one σ x hx0 m hfixx
  have huy : autUnitRatio σ y hy0 ^ n = 1 :=
    autUnitRatio_pow_eq_one σ y hy0 n hfixy
  letI : NeZero m := ⟨Nat.ne_of_gt hm⟩
  letI : NeZero n := ⟨Nat.ne_of_gt hn⟩
  letI : NeZero (m : F) := ⟨hmF⟩
  letI : NeZero (n : F) := ⟨hnF⟩
  obtain ⟨ζ, hζ⟩ := HasEnoughRootsOfUnity.exists_primitiveRoot F m
  obtain ⟨η, hη⟩ := HasEnoughRootsOfUnity.exists_primitiveRoot F n
  have hμm : (primitiveRoots m F).Nonempty :=
    ⟨ζ, (mem_primitiveRoots hm).2 hζ⟩
  have hμn : (primitiveRoots n F).Nonempty :=
    ⟨η, (mem_primitiveRoots hn).2 hη⟩
  let zx : Fˣ := descendedRootUnit hμm (autUnitRatio σ x hx0) hux
  let zy : Fˣ := descendedRootUnit hμn (autUnitRatio σ y hy0) huy
  have hzxMap : algebraMap F L (zx : F) = (autUnitRatio σ x hx0 : L) :=
    algebraMap_descendedRootUnit hμm (autUnitRatio σ x hx0) hux
  have hzyMap : algebraMap F L (zy : F) = (autUnitRatio σ y hy0 : L) :=
    algebraMap_descendedRootUnit hμn (autUnitRatio σ y hy0) huy
  have hzx : algebraMap F L zx * x = σ x := by
    rw [hzxMap]
    exact div_mul_cancel₀ (σ x) hx0
  have hzy : algebraMap F L zy * y = σ y := by
    rw [hzyMap]
    exact div_mul_cancel₀ (σ y) hy0
  refine ⟨(zx, zy), hzx, hzy, ?_⟩
  apply planeCurveSupportCharacterStabilizer_of_diagonalScale_eval_zero hf
  have hxyfun : planeCurveFunction f = ![x, y] := by
    funext i
    fin_cases i <;> rfl
  rw [hxyfun]
  rw [eval₂_diagonalScale]
  have hcoeff : σ.toRingHom.comp (algebraMap F L) = algebraMap F L := by
    ext c
    rw [RingHom.comp_apply, IsScalarTower.algebraMap_apply F B L]
    change σ ((algebraMap B L) ((algebraMap F B) c)) =
      (algebraMap B L) ((algebraMap F B) c)
    exact σ.commutes ((algebraMap F B) c)
  have hmap := MvPolynomial.map_eval₂Hom (algebraMap F L)
    (planeCurveFunction f) σ.toRingHom f
  rw [hcoeff] at hmap
  have hgeneric := eval₂_planeCurveFunction_eq_zero f
  have hzero : MvPolynomial.eval₂ (algebraMap F L)
      (fun i => σ (planeCurveFunction f i)) f = 0 := by
    change (MvPolynomial.eval₂Hom (algebraMap F L)
      (fun i => σ.toRingHom (planeCurveFunction f i))) f = 0
    change (MvPolynomial.eval₂Hom (algebraMap F L)
      (planeCurveFunction f)) f = 0 at hgeneric
    rw [← hmap, hgeneric, map_zero]
  have hcoords : ![algebraMap F L zx * x, algebraMap F L zy * y] =
      fun i => σ (planeCurveFunction f i) := by
    funext i
    fin_cases i <;> simp [x, y, hzx, hzy]
  rw [hcoords]
  exact hzero

set_option maxHeartbeats 800000 in
set_option synthInstance.maxHeartbeats 200000 in
theorem finrank_poweredCoordinateImageField_le_twice_bidegree_isAlgClosed
    {F : Type*} [Field F] [IsAlgClosed F]
    {f : MvPolynomial (Fin 2) F}
    (hf : Irreducible f)
    (hpartialFirst : MvPolynomial.pderiv 0 f ≠ 0)
    (hpartialSecond : MvPolynomial.pderiv 1 f ≠ 0)
    (hrank : PlaneCurveSupportHasRankTwo f)
    (m n : ℕ) (hm : 0 < m) (hn : 0 < n)
    (hmF : (m : F) ≠ 0) (hnF : (n : F) ≠ 0) :
    letI := planeCurveCoordinateRing_isDomain hf
    Module.finrank (PoweredCoordinateImageField f m n)
        (PlaneCurveFunctionField f) ≤
      2 * MvPolynomial.degreeOf 0 f * MvPolynomial.degreeOf 1 f := by
  letI : IsDomain (PlaneCurveCoordinateRing f) :=
    planeCurveCoordinateRing_isDomain hf
  let L := PlaneCurveFunctionField f
  let B := PoweredCoordinateImageField f m n
  let x : L := planeCurveFunction f 0
  let y : L := planeCurveFunction f 1
  letI : FiniteDimensional B L :=
    finiteDimensional_poweredCoordinateImageField hf hpartialSecond m n hm
  letI : IsGalois B L :=
    isGalois_over_poweredCoordinateImageField hf hpartialFirst hpartialSecond m n hm hn hmF hnF
  have hbasic := poweredCoordinateImageField_adjoin_coordinates_eq_top_and_ne_zero hf hpartialFirst
    hpartialSecond m n
  have hgen : IntermediateField.adjoin B ({x, y} : Set L) = ⊤ := hbasic.1
  have hgenAlg : Algebra.adjoin B ({x, y} : Set L) = ⊤ := by
    rw [← IntermediateField.adjoin_toSubalgebra]
    rw [hgen]
    rfl
  have hrank' := hrank
  obtain ⟨r₀, s₀, t₀, hr₀, hs₀, ht₀, hdet₀⟩ := hrank'
  let a : ℤ := (s₀ 0 : ℤ) - (r₀ 0 : ℤ)
  let b : ℤ := (s₀ 1 : ℤ) - (r₀ 1 : ℤ)
  let c : ℤ := (t₀ 0 : ℤ) - (r₀ 0 : ℤ)
  let d : ℤ := (t₀ 1 : ℤ) - (r₀ 1 : ℤ)
  have hdet' : a * d - b * c ≠ 0 := by
    simpa [a, b, c, d, planeCurveSupportDifferenceDet] using hdet₀
  letI : Finite (torusCharacterKernel F a b c d) :=
    finite_torusCharacterKernel_of_det_ne_zero a b c d hdet'
  let supportToKernel : planeCurveSupportCharacterStabilizer F f →
      torusCharacterKernel F a b c d := fun z =>
    ⟨z.1, z.2 r₀ hr₀ s₀ hs₀, z.2 r₀ hr₀ t₀ ht₀⟩
  have supportToKernel_injective : Function.Injective supportToKernel := by
    intro z w hzw
    apply Subtype.ext
    exact congrArg (fun u : torusCharacterKernel F a b c d => u.1) hzw
  letI : Finite (planeCurveSupportCharacterStabilizer F f) :=
    Finite.of_injective supportToKernel supportToKernel_injective
  have hscale (σ : L ≃ₐ[B] L) :=
    exists_support_stabilizer_scaling_of_poweredImage_aut hf hpartialFirst hpartialSecond
      m n hm hn hmF hnF σ
  let scalePair : (L ≃ₐ[B] L) → Fˣ × Fˣ := fun σ =>
    Classical.choose (hscale σ)
  have scalePair_spec (σ : L ≃ₐ[B] L) :
      algebraMap F L (scalePair σ).1 * x = σ x ∧
      algebraMap F L (scalePair σ).2 * y = σ y ∧
      ∀ r ∈ f.support, ∀ s ∈ f.support,
        (scalePair σ).1 ^ ((s 0 : ℤ) - (r 0 : ℤ)) *
          (scalePair σ).2 ^ ((s 1 : ℤ) - (r 1 : ℤ)) = 1 :=
    Classical.choose_spec (hscale σ)
  let e : (L ≃ₐ[B] L) → planeCurveSupportCharacterStabilizer F f :=
    fun σ => ⟨scalePair σ, (scalePair_spec σ).2.2⟩
  have he : Function.Injective e := by
    intro σ τ hστ
    have hpairs : scalePair σ = scalePair τ :=
      congrArg Subtype.val hστ
    have hx : σ x = τ x := by
      rw [← (scalePair_spec σ).1, ← (scalePair_spec τ).1, hpairs]
    have hy : σ y = τ y := by
      rw [← (scalePair_spec σ).2.1, ← (scalePair_spec τ).2.1, hpairs]
    apply AlgEquiv.ext
    have hhom : σ.toAlgHom = τ.toAlgHom := by
      apply AlgHom.ext_of_adjoin_eq_top hgenAlg
      intro q hq
      simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hq
      rcases hq with rfl | rfl
      · exact hx
      · exact hy
    exact fun z => DFunLike.congr_fun hhom z
  calc
    Module.finrank B L = Nat.card (L ≃ₐ[B] L) :=
      (IsGalois.card_aut_eq_finrank B L).symm
    _ ≤ Nat.card (planeCurveSupportCharacterStabilizer F f) :=
      Nat.card_le_card_of_injective e he
    _ ≤ 2 * MvPolynomial.degreeOf 0 f * MvPolynomial.degreeOf 1 f :=
      natCard_planeCurveSupportCharacterStabilizer_le_twice_bidegree hrank

/-- The same algebraically closed bound in the first-coordinate presentation
used by the Corvaja--Zannier endpoint. -/
theorem finrank_poweredImageOverFirst_le_twice_bidegree_isAlgClosed
    {F : Type*} [Field F] [IsAlgClosed F]
    {f : MvPolynomial (Fin 2) F}
    (hf : Irreducible f)
    (hpartialFirst : MvPolynomial.pderiv 0 f ≠ 0)
    (hpartialSecond : MvPolynomial.pderiv 1 f ≠ 0)
    (hrank : PlaneCurveSupportHasRankTwo f)
    (m n : ℕ) (hm : 0 < m) (hn : 0 < n)
    (hmF : (m : F) ≠ 0) (hnF : (n : F) ≠ 0) :
    letI := planeCurveCoordinateRing_isDomain hf
    Module.finrank (PoweredImageOverFirst f m n)
        (PlaneCurveFunctionField f) ≤
      2 * MvPolynomial.degreeOf 0 f * MvPolynomial.degreeOf 1 f := by
  letI : IsDomain (PlaneCurveCoordinateRing f) :=
    planeCurveCoordinateRing_isDomain hf
  rw [finrank_poweredImageOverFirst_eq_imageField]
  exact finrank_poweredCoordinateImageField_le_twice_bidegree_isAlgClosed
    hf hpartialFirst hpartialSecond hrank m n hm hn hmF hnF

end
end BGS.CorvajaZannier
