import BGS.CorvajaZannier.PoweredCoordinates
import Mathlib.Algebra.Polynomial.RingDivision

/-!
# An explicit relation between powered plane-curve coordinates

Let `F = L^p`, `u = x^m`, and `v = y^n`.  When `n` is prime to `p`, the
element `v` is a primitive element of `L / F`.  Its power basis therefore
writes `u` as a unique polynomial `P(v)` of degree less than `p`.  This file
constructs that polynomial and the linear elimination relation

`G(U,V) = U - P(V)`.

The relation is irreducible over `F[V]`, has exact bidegree
`(1, degree P)`, satisfies the coefficient-degree bound used by the
Corvaja--Zannier resultant argument, and vanishes at `(u,v)`.  The final
theorem feeds these facts into Proposition 1 without leaving an unspecified
relation polynomial as a hypothesis.
-/

namespace BGS.CorvajaZannier

noncomputable section

variable {F L : Type*} [Field F] [Field L] [Algebra F L]

/-- The unique bounded-degree coordinate polynomial of `u` in a chosen power
basis generated by `v`. -/
noncomputable def powerBasisCoordinatePolynomial
    (pb : PowerBasis F L) (u : L) : Polynomial F :=
  Classical.choose (pb.exists_eq_aeval u)

theorem powerBasisCoordinatePolynomial_natDegree_lt
    (pb : PowerBasis F L) (u : L) :
    (powerBasisCoordinatePolynomial pb u).natDegree < pb.dim :=
  (Classical.choose_spec (pb.exists_eq_aeval u)).1

theorem powerBasisCoordinatePolynomial_aeval
    (pb : PowerBasis F L) (u : L) :
    u = Polynomial.aeval pb.gen (powerBasisCoordinatePolynomial pb u) :=
  (Classical.choose_spec (pb.exists_eq_aeval u)).2

theorem powerBasisCoordinatePolynomial_natDegree_pos_of_not_mem_range
    (pb : PowerBasis F L) (u : L)
    (hu : u ∉ Set.range (algebraMap F L)) :
    0 < (powerBasisCoordinatePolynomial pb u).natDegree := by
  apply Nat.pos_of_ne_zero
  intro hdegree
  have hconstant := Polynomial.eq_C_of_natDegree_eq_zero hdegree
  apply hu
  refine ⟨(powerBasisCoordinatePolynomial pb u).coeff 0, ?_⟩
  calc
    algebraMap F L ((powerBasisCoordinatePolynomial pb u).coeff 0) =
        Polynomial.aeval pb.gen
          (Polynomial.C ((powerBasisCoordinatePolynomial pb u).coeff 0)) := by simp
    _ = Polynomial.aeval pb.gen (powerBasisCoordinatePolynomial pb u) := by
      exact congrArg (Polynomial.aeval pb.gen) hconstant.symm
    _ = u := (powerBasisCoordinatePolynomial_aeval pb u).symm

/-- The linear elimination relation `U - P(V)`. -/
def powerBasisEliminationRelation (pb : PowerBasis F L) (u : L) :
    Polynomial (Polynomial F) :=
  Polynomial.X - Polynomial.C (powerBasisCoordinatePolynomial pb u)

theorem powerBasisEliminationRelation_irreducible
    (pb : PowerBasis F L) (u : L) :
    Irreducible (powerBasisEliminationRelation pb u) := by
  exact Polynomial.irreducible_X_sub_C _

theorem powerBasisEliminationRelation_natDegree
    (pb : PowerBasis F L) (u : L) :
    (powerBasisEliminationRelation pb u).natDegree = 1 := by
  exact Polynomial.natDegree_X_sub_C _

theorem transpose_powerBasisEliminationRelation
    (pb : PowerBasis F L) (u : L) :
    transposeBivariate (powerBasisEliminationRelation pb u) =
      Polynomial.C Polynomial.X -
        (powerBasisCoordinatePolynomial pb u).map Polynomial.C := by
  simp [powerBasisEliminationRelation, transposeBivariate]

theorem transpose_powerBasisEliminationRelation_natDegree
    (pb : PowerBasis F L) (u : L) :
    (transposeBivariate (powerBasisEliminationRelation pb u)).natDegree =
      (powerBasisCoordinatePolynomial pb u).natDegree := by
  rw [transpose_powerBasisEliminationRelation]
  let P := powerBasisCoordinatePolynomial pb u
  have hmap : (P.map Polynomial.C).natDegree = P.natDegree := by
    rw [Polynomial.natDegree_map_eq_of_injective Polynomial.C_injective]
  by_cases hP : P.natDegree = 0
  · change (Polynomial.C Polynomial.X - P.map Polynomial.C).natDegree = P.natDegree
    rw [hP]
    apply Nat.eq_zero_of_le_zero
    exact (Polynomial.natDegree_sub_le _ _).trans (by simp [hP, hmap])
  · have hlt : (Polynomial.C Polynomial.X : Polynomial (Polynomial F)).natDegree <
        (P.map Polynomial.C).natDegree := by
      rw [hmap]
      simpa using Nat.pos_of_ne_zero hP
    rw [Polynomial.natDegree_sub_eq_right_of_natDegree_lt hlt, hmap]

theorem powerBasisEliminationRelation_coeff_natDegree_le
    (pb : PowerBasis F L) (u : L) (i : ℕ) :
    ((powerBasisEliminationRelation pb u).coeff i).natDegree ≤
      (powerBasisCoordinatePolynomial pb u).natDegree := by
  by_cases hi : i = 0
  · subst i
    simp [powerBasisEliminationRelation]
  · rw [powerBasisEliminationRelation, Polynomial.coeff_sub,
      Polynomial.coeff_C_of_ne_zero hi]
    by_cases hi1 : i = 1
    · subst i
      simp
    · rw [Polynomial.coeff_X_of_ne_one hi1]
      simp

theorem evalBivariate_powerBasisEliminationRelation
    (pb : PowerBasis F L) (u : L) :
    evalBivariate pb.gen u (powerBasisEliminationRelation pb u) = 0 := by
  rw [powerBasisEliminationRelation]
  unfold evalBivariate
  rw [Polynomial.eval₂_sub, Polynomial.eval₂_X, Polynomial.eval₂_C]
  change u - Polynomial.aeval pb.gen (powerBasisCoordinatePolynomial pb u) = 0
  rw [← powerBasisCoordinatePolynomial_aeval pb u, sub_self]

/-- The canonical Frobenius power basis generated by the powered second
coordinate of an irreducible plane curve. -/
noncomputable def secondPoweredCoordinateFrobeniusPowerBasis
    {K : Type*} [Field K] [PerfectField K]
    {p : ℕ} [Fact p.Prime] [CharP K p]
    {f : MvPolynomial (Fin 2) K} (hf : Irreducible f)
    (hpartialFirst : MvPolynomial.pderiv 0 f ≠ 0)
    (n : ℕ) (hn : ¬ p ∣ n) :
    letI := planeCurveCoordinateRing_isDomain hf
    letI : CharP (PlaneCurveFunctionField f) p :=
      charP_of_injective_algebraMap
        (algebraMap K (PlaneCurveFunctionField f)).injective p
    PowerBasis (frobeniusSubfield (PlaneCurveFunctionField f) p)
      (PlaneCurveFunctionField f) := by
  letI : IsDomain (PlaneCurveCoordinateRing f) :=
    planeCurveCoordinateRing_isDomain hf
  let L := PlaneCurveFunctionField f
  letI : CharP L p := charP_of_injective_algebraMap
    (algebraMap K L).injective p
  let F := frobeniusSubfield L p
  letI : IsPurelyInseparable F L :=
    frobeniusSubfield_isPurelyInseparable p
  let v : L := (planeCurveFunction f 1) ^ n
  have hvTop : IntermediateField.adjoin F {v} = ⊤ := by
    simpa [F, L, v] using
      (adjoin_frobeniusSubfield_secondCoordinatePow_eq_top
        hf hpartialFirst n hn)
  have hvIntegral : IsIntegral F v :=
    IsPurelyInseparable.isIntegral' F v
  let pb : PowerBasis F L := PowerBasis.ofAdjoinEqTop hvIntegral
    (Algebra.adjoin_eq_top_of_primitive_element
      hvIntegral.isAlgebraic hvTop)
  simpa [F, L] using pb

theorem secondPoweredCoordinateFrobeniusPowerBasis_gen
    {K : Type*} [Field K] [PerfectField K]
    {p : ℕ} [Fact p.Prime] [CharP K p]
    {f : MvPolynomial (Fin 2) K} (hf : Irreducible f)
    (hpartialFirst : MvPolynomial.pderiv 0 f ≠ 0)
    (n : ℕ) (hn : ¬ p ∣ n) :
    letI := planeCurveCoordinateRing_isDomain hf
    letI : CharP (PlaneCurveFunctionField f) p :=
      charP_of_injective_algebraMap
        (algebraMap K (PlaneCurveFunctionField f)).injective p
    (secondPoweredCoordinateFrobeniusPowerBasis hf hpartialFirst n hn).gen =
      (planeCurveFunction f 1) ^ n := by
  simp [secondPoweredCoordinateFrobeniusPowerBasis]

theorem secondPoweredCoordinateFrobeniusPowerBasis_dim
    {K : Type*} [Field K] [PerfectField K]
    {p : ℕ} [Fact p.Prime] [CharP K p]
    {f : MvPolynomial (Fin 2) K} (hf : Irreducible f)
    (hpartialFirst : MvPolynomial.pderiv 0 f ≠ 0)
    (n : ℕ) (hn : ¬ p ∣ n) :
    letI := planeCurveCoordinateRing_isDomain hf
    letI : CharP (PlaneCurveFunctionField f) p :=
      charP_of_injective_algebraMap
        (algebraMap K (PlaneCurveFunctionField f)).injective p
    (secondPoweredCoordinateFrobeniusPowerBasis hf hpartialFirst n hn).dim = p := by
  letI : IsDomain (PlaneCurveCoordinateRing f) :=
    planeCurveCoordinateRing_isDomain hf
  let L := PlaneCurveFunctionField f
  letI : CharP L p := charP_of_injective_algebraMap
    (algebraMap K L).injective p
  rw [secondPoweredCoordinateFrobeniusPowerBasis,
    PowerBasis.ofAdjoinEqTop_dim]
  exact minpoly_secondCoordinatePow_natDegree_eq_char
    hf hpartialFirst n hn

/-- The bounded polynomial in `y^n` representing `x^m` over the Frobenius
subfield. -/
noncomputable def poweredCoordinateExpansionPolynomial
    {K : Type*} [Field K] [PerfectField K]
    {p : ℕ} [Fact p.Prime] [CharP K p]
    {f : MvPolynomial (Fin 2) K} (hf : Irreducible f)
    (hpartialFirst : MvPolynomial.pderiv 0 f ≠ 0)
    (m n : ℕ) (hn : ¬ p ∣ n) :
    letI := planeCurveCoordinateRing_isDomain hf
    letI : CharP (PlaneCurveFunctionField f) p :=
      charP_of_injective_algebraMap
        (algebraMap K (PlaneCurveFunctionField f)).injective p
    Polynomial (frobeniusSubfield (PlaneCurveFunctionField f) p) := by
  letI : IsDomain (PlaneCurveCoordinateRing f) :=
    planeCurveCoordinateRing_isDomain hf
  letI : CharP (PlaneCurveFunctionField f) p :=
    charP_of_injective_algebraMap
      (algebraMap K (PlaneCurveFunctionField f)).injective p
  exact powerBasisCoordinatePolynomial
    (secondPoweredCoordinateFrobeniusPowerBasis hf hpartialFirst n hn)
    ((planeCurveFunction f 0) ^ m)

theorem poweredCoordinateExpansionPolynomial_natDegree_lt_char
    {K : Type*} [Field K] [PerfectField K]
    {p : ℕ} [Fact p.Prime] [CharP K p]
    {f : MvPolynomial (Fin 2) K} (hf : Irreducible f)
    (hpartialFirst : MvPolynomial.pderiv 0 f ≠ 0)
    (m n : ℕ) (hn : ¬ p ∣ n) :
    letI := planeCurveCoordinateRing_isDomain hf
    letI : CharP (PlaneCurveFunctionField f) p :=
      charP_of_injective_algebraMap
        (algebraMap K (PlaneCurveFunctionField f)).injective p
    (poweredCoordinateExpansionPolynomial hf hpartialFirst m n hn).natDegree < p := by
  letI : IsDomain (PlaneCurveCoordinateRing f) :=
    planeCurveCoordinateRing_isDomain hf
  letI : CharP (PlaneCurveFunctionField f) p :=
    charP_of_injective_algebraMap
      (algebraMap K (PlaneCurveFunctionField f)).injective p
  calc
    (poweredCoordinateExpansionPolynomial hf hpartialFirst m n hn).natDegree <
        (secondPoweredCoordinateFrobeniusPowerBasis hf hpartialFirst n hn).dim := by
      exact powerBasisCoordinatePolynomial_natDegree_lt _ _
    _ = p := secondPoweredCoordinateFrobeniusPowerBasis_dim
      hf hpartialFirst n hn

theorem poweredCoordinateExpansionPolynomial_aeval
    {K : Type*} [Field K] [PerfectField K]
    {p : ℕ} [Fact p.Prime] [CharP K p]
    {f : MvPolynomial (Fin 2) K} (hf : Irreducible f)
    (hpartialFirst : MvPolynomial.pderiv 0 f ≠ 0)
    (m n : ℕ) (hn : ¬ p ∣ n) :
    letI := planeCurveCoordinateRing_isDomain hf
    letI : CharP (PlaneCurveFunctionField f) p :=
      charP_of_injective_algebraMap
        (algebraMap K (PlaneCurveFunctionField f)).injective p
    (planeCurveFunction f 0) ^ m =
      Polynomial.aeval ((planeCurveFunction f 1) ^ n)
        (poweredCoordinateExpansionPolynomial hf hpartialFirst m n hn) := by
  letI : IsDomain (PlaneCurveCoordinateRing f) :=
    planeCurveCoordinateRing_isDomain hf
  letI : CharP (PlaneCurveFunctionField f) p :=
    charP_of_injective_algebraMap
      (algebraMap K (PlaneCurveFunctionField f)).injective p
  rw [← secondPoweredCoordinateFrobeniusPowerBasis_gen
    hf hpartialFirst n hn]
  exact powerBasisCoordinatePolynomial_aeval _ _

/-- The explicit bivariate elimination relation
`U - P_{m,n}(V)` between `x^m` and `y^n`. -/
noncomputable def poweredCoordinateEliminationRelation
    {K : Type*} [Field K] [PerfectField K]
    {p : ℕ} [Fact p.Prime] [CharP K p]
    {f : MvPolynomial (Fin 2) K} (hf : Irreducible f)
    (hpartialFirst : MvPolynomial.pderiv 0 f ≠ 0)
    (m n : ℕ) (hn : ¬ p ∣ n) :
    letI := planeCurveCoordinateRing_isDomain hf
    letI : CharP (PlaneCurveFunctionField f) p :=
      charP_of_injective_algebraMap
        (algebraMap K (PlaneCurveFunctionField f)).injective p
    Polynomial (Polynomial
      (frobeniusSubfield (PlaneCurveFunctionField f) p)) := by
  letI : IsDomain (PlaneCurveCoordinateRing f) :=
    planeCurveCoordinateRing_isDomain hf
  letI : CharP (PlaneCurveFunctionField f) p :=
    charP_of_injective_algebraMap
      (algebraMap K (PlaneCurveFunctionField f)).injective p
  exact powerBasisEliminationRelation
    (secondPoweredCoordinateFrobeniusPowerBasis hf hpartialFirst n hn)
    ((planeCurveFunction f 0) ^ m)

theorem poweredCoordinateEliminationRelation_irreducible
    {K : Type*} [Field K] [PerfectField K]
    {p : ℕ} [Fact p.Prime] [CharP K p]
    {f : MvPolynomial (Fin 2) K} (hf : Irreducible f)
    (hpartialFirst : MvPolynomial.pderiv 0 f ≠ 0)
    (m n : ℕ) (hn : ¬ p ∣ n) :
    letI := planeCurveCoordinateRing_isDomain hf
    letI : CharP (PlaneCurveFunctionField f) p :=
      charP_of_injective_algebraMap
        (algebraMap K (PlaneCurveFunctionField f)).injective p
    Irreducible
      (poweredCoordinateEliminationRelation hf hpartialFirst m n hn) := by
  letI : IsDomain (PlaneCurveCoordinateRing f) :=
    planeCurveCoordinateRing_isDomain hf
  letI : CharP (PlaneCurveFunctionField f) p :=
    charP_of_injective_algebraMap
      (algebraMap K (PlaneCurveFunctionField f)).injective p
  exact powerBasisEliminationRelation_irreducible _ _

theorem poweredCoordinateEliminationRelation_natDegree
    {K : Type*} [Field K] [PerfectField K]
    {p : ℕ} [Fact p.Prime] [CharP K p]
    {f : MvPolynomial (Fin 2) K} (hf : Irreducible f)
    (hpartialFirst : MvPolynomial.pderiv 0 f ≠ 0)
    (m n : ℕ) (hn : ¬ p ∣ n) :
    letI := planeCurveCoordinateRing_isDomain hf
    letI : CharP (PlaneCurveFunctionField f) p :=
      charP_of_injective_algebraMap
        (algebraMap K (PlaneCurveFunctionField f)).injective p
    (poweredCoordinateEliminationRelation hf hpartialFirst m n hn).natDegree = 1 := by
  letI : IsDomain (PlaneCurveCoordinateRing f) :=
    planeCurveCoordinateRing_isDomain hf
  letI : CharP (PlaneCurveFunctionField f) p :=
    charP_of_injective_algebraMap
      (algebraMap K (PlaneCurveFunctionField f)).injective p
  exact powerBasisEliminationRelation_natDegree _ _

theorem transpose_poweredCoordinateEliminationRelation_natDegree
    {K : Type*} [Field K] [PerfectField K]
    {p : ℕ} [Fact p.Prime] [CharP K p]
    {f : MvPolynomial (Fin 2) K} (hf : Irreducible f)
    (hpartialFirst : MvPolynomial.pderiv 0 f ≠ 0)
    (m n : ℕ) (hn : ¬ p ∣ n) :
    letI := planeCurveCoordinateRing_isDomain hf
    letI : CharP (PlaneCurveFunctionField f) p :=
      charP_of_injective_algebraMap
        (algebraMap K (PlaneCurveFunctionField f)).injective p
    (transposeBivariate
      (poweredCoordinateEliminationRelation hf hpartialFirst m n hn)).natDegree =
        (poweredCoordinateExpansionPolynomial hf hpartialFirst m n hn).natDegree := by
  letI : IsDomain (PlaneCurveCoordinateRing f) :=
    planeCurveCoordinateRing_isDomain hf
  letI : CharP (PlaneCurveFunctionField f) p :=
    charP_of_injective_algebraMap
      (algebraMap K (PlaneCurveFunctionField f)).injective p
  exact transpose_powerBasisEliminationRelation_natDegree _ _

theorem poweredCoordinateEliminationRelation_coeff_natDegree_le
    {K : Type*} [Field K] [PerfectField K]
    {p : ℕ} [Fact p.Prime] [CharP K p]
    {f : MvPolynomial (Fin 2) K} (hf : Irreducible f)
    (hpartialFirst : MvPolynomial.pderiv 0 f ≠ 0)
    (m n : ℕ) (hn : ¬ p ∣ n) (i : ℕ) :
    letI := planeCurveCoordinateRing_isDomain hf
    letI : CharP (PlaneCurveFunctionField f) p :=
      charP_of_injective_algebraMap
        (algebraMap K (PlaneCurveFunctionField f)).injective p
    ((poweredCoordinateEliminationRelation hf hpartialFirst m n hn).coeff i).natDegree ≤
      (poweredCoordinateExpansionPolynomial hf hpartialFirst m n hn).natDegree := by
  letI : IsDomain (PlaneCurveCoordinateRing f) :=
    planeCurveCoordinateRing_isDomain hf
  letI : CharP (PlaneCurveFunctionField f) p :=
    charP_of_injective_algebraMap
      (algebraMap K (PlaneCurveFunctionField f)).injective p
  exact powerBasisEliminationRelation_coeff_natDegree_le _ _ i

theorem evalBivariate_poweredCoordinateEliminationRelation
    {K : Type*} [Field K] [PerfectField K]
    {p : ℕ} [Fact p.Prime] [CharP K p]
    {f : MvPolynomial (Fin 2) K} (hf : Irreducible f)
    (hpartialFirst : MvPolynomial.pderiv 0 f ≠ 0)
    (m n : ℕ) (hn : ¬ p ∣ n) :
    letI := planeCurveCoordinateRing_isDomain hf
    letI : CharP (PlaneCurveFunctionField f) p :=
      charP_of_injective_algebraMap
        (algebraMap K (PlaneCurveFunctionField f)).injective p
    evalBivariate ((planeCurveFunction f 1) ^ n)
      ((planeCurveFunction f 0) ^ m)
      (poweredCoordinateEliminationRelation hf hpartialFirst m n hn) = 0 := by
  letI : IsDomain (PlaneCurveCoordinateRing f) :=
    planeCurveCoordinateRing_isDomain hf
  letI : CharP (PlaneCurveFunctionField f) p :=
    charP_of_injective_algebraMap
      (algebraMap K (PlaneCurveFunctionField f)).injective p
  rw [← secondPoweredCoordinateFrobeniusPowerBasis_gen
    hf hpartialFirst n hn]
  exact evalBivariate_powerBasisEliminationRelation _ _

/-- If both powered coordinates are separating, the second bidegree of the
linear elimination relation is positive as well as strictly below `p`. -/
theorem poweredCoordinateExpansionPolynomial_natDegree_pos
    {K : Type*} [Field K] [PerfectField K]
    {p : ℕ} [Fact p.Prime] [CharP K p]
    {f : MvPolynomial (Fin 2) K} (hf : Irreducible f)
    (hpartialFirst : MvPolynomial.pderiv 0 f ≠ 0)
    (hpartialSecond : MvPolynomial.pderiv 1 f ≠ 0)
    (m n : ℕ) (hm : ¬ p ∣ m) (hn : ¬ p ∣ n) :
    letI := planeCurveCoordinateRing_isDomain hf
    letI : CharP (PlaneCurveFunctionField f) p :=
      charP_of_injective_algebraMap
        (algebraMap K (PlaneCurveFunctionField f)).injective p
    0 < (poweredCoordinateExpansionPolynomial
      hf hpartialFirst m n hn).natDegree := by
  letI : IsDomain (PlaneCurveCoordinateRing f) :=
    planeCurveCoordinateRing_isDomain hf
  let L := PlaneCurveFunctionField f
  letI : CharP L p := charP_of_injective_algebraMap
    (algebraMap K L).injective p
  let F := frobeniusSubfield L p
  let x : L := planeCurveFunction f 0
  have hsep := (finiteSeparable_over_firstCoordinate_of_irreducible
    hf hpartialSecond).2
  letI : Algebra.IsSeparable (FirstCoordinateSubfield f) L := hsep
  letI : Algebra.IsSeparable (IntermediateField.adjoin F {x}) L :=
    isSeparable_over_frobeniusAdjoin_of_isSeparable_over_constantAdjoin
      (K := K) (L := L) (p := p) x
  have hxTrans : Transcendental K x := firstCoordinate_transcendental hf
    (degreeOf_second_pos_of_pderiv_ne_zero hpartialSecond)
  have hx0 : x ≠ 0 := by
    intro hx
    apply hxTrans
    rw [hx]
    exact isAlgebraic_zero
  have hxNot : x ∉ F := firstCoordinate_not_mem_frobeniusSubfield
    hf hpartialSecond
  have hxmNot : x ^ m ∉ F := frobeniusPower_not_mem
    x hx0 hxNot m hm
  have hxmRange : x ^ m ∉ Set.range (algebraMap F L) := by
    rintro ⟨c, hc⟩
    apply hxmNot
    rw [← hc]
    exact c.property
  exact powerBasisCoordinatePolynomial_natDegree_pos_of_not_mem_range
    (secondPoweredCoordinateFrobeniusPowerBasis hf hpartialFirst n hn)
    (x ^ m) hxmRange

set_option maxHeartbeats 800000 in
/-- Proposition 1 for powered plane coordinates with the defining relation
constructed internally.  The only remaining numerical hypotheses refer to
the actual second degree of the canonical elimination polynomial. -/
theorem poweredCoordinates_auxiliaryFamily_linearIndependent_of_elimination
    {K : Type*} [Field K] [PerfectField K]
    {p : ℕ} [Fact p.Prime] [CharP K p]
    {f : MvPolynomial (Fin 2) K} (hf : Irreducible f)
    (hpartialFirst : MvPolynomial.pderiv 0 f ≠ 0)
    (m n : ℕ) (hn : ¬ p ∣ n) (h k : ℕ)
    (hh : 0 < h) (hk : 0 < k)
    (hsize : h +
      (poweredCoordinateExpansionPolynomial hf hpartialFirst m n hn).natDegree * k < p)
    (hdegree : h <
      (poweredCoordinateExpansionPolynomial hf hpartialFirst m n hn).natDegree) :
    letI := planeCurveCoordinateRing_isDomain hf
    letI : CharP (PlaneCurveFunctionField f) p :=
      charP_of_injective_algebraMap
        (algebraMap K (PlaneCurveFunctionField f)).injective p
    LinearIndependent
      (frobeniusSubfield (PlaneCurveFunctionField f) p)
      (auxiliaryFamily ((planeCurveFunction f 0) ^ m)
        ((planeCurveFunction f 1) ^ n) h k) := by
  letI : IsDomain (PlaneCurveCoordinateRing f) :=
    planeCurveCoordinateRing_isDomain hf
  letI : CharP (PlaneCurveFunctionField f) p :=
    charP_of_injective_algebraMap
      (algebraMap K (PlaneCurveFunctionField f)).injective p
  exact poweredCoordinates_auxiliaryFamily_linearIndependent_of_relation
    hf hpartialFirst m n hn
    (poweredCoordinateEliminationRelation hf hpartialFirst m n hn)
    1
    (poweredCoordinateExpansionPolynomial hf hpartialFirst m n hn).natDegree
    h k Nat.zero_lt_one hh hk
    (poweredCoordinateEliminationRelation_irreducible
      hf hpartialFirst m n hn)
    (poweredCoordinateEliminationRelation_natDegree
      hf hpartialFirst m n hn)
    (transpose_poweredCoordinateEliminationRelation_natDegree
      hf hpartialFirst m n hn)
    (poweredCoordinateEliminationRelation_coeff_natDegree_le
      hf hpartialFirst m n hn)
    (evalBivariate_poweredCoordinateEliminationRelation
      hf hpartialFirst m n hn)
    (by simpa using hsize)
    (by
      intro hdegrees
      exact (Nat.not_le_of_lt hdegree) hdegrees.2)

end

end BGS.CorvajaZannier
