import BGS.CorvajaZannier.FrobeniusSubfield
import BGS.CorvajaZannier.PlaneCurveSeparability
import Mathlib.FieldTheory.PurelyInseparable.PerfectClosure

/-!
# Separating coordinates are not Frobenius powers

For an irreducible plane curve in characteristic `p`, a nonzero partial
derivative makes the function field separable over the field generated by the
opposite coordinate.  This file uses that separability to prove that the
generating coordinate cannot be a `p`-th power in the curve function field.

The last step is made explicit in the one-variable rational function field:
if `(a / b) ^ p = X`, then `a ^ p = X * b ^ p`, whose degrees would satisfy
`p * degree(a) = 1 + p * degree(b)`.
-/

namespace BGS.CorvajaZannier

noncomputable section

/-- A polynomial variable is not a nontrivial power in the fraction field of
a multivariate polynomial ring. -/
theorem mvPolynomial_variable_not_pow_in_fractionRing
    {K σ : Type*} [Field K] (i : σ) (p : ℕ) (hp : 1 < p) :
    ¬ ∃ z : FractionRing (MvPolynomial σ K),
      z ^ p = algebraMap (MvPolynomial σ K)
        (FractionRing (MvPolynomial σ K)) (MvPolynomial.X i) := by
  rintro ⟨z, hz⟩
  let R := MvPolynomial σ K
  let F := FractionRing R
  obtain ⟨a, b, hb, hab⟩ := IsFractionRing.div_surjective R z
  have hb0 : b ≠ 0 := nonZeroDivisors.ne_zero hb
  have hmapb0 : algebraMap R F b ≠ 0 := by
    simpa using (IsFractionRing.injective R F).ne hb0
  have hfield :
      algebraMap R F (a ^ p) = algebraMap R F (MvPolynomial.X i * b ^ p) := by
    rw [map_mul, map_pow, map_pow, ← hz, ← hab, div_pow]
    rw [div_mul_cancel₀ _ (pow_ne_zero p hmapb0)]
  have hpoly : a ^ p = MvPolynomial.X i * b ^ p :=
    IsFractionRing.injective R F hfield
  have ha0 : a ≠ 0 := by
    intro ha
    rw [ha, zero_pow (Nat.ne_zero_of_lt hp), zero_eq_mul] at hpoly
    exact pow_ne_zero p hb0 (hpoly.resolve_left (MvPolynomial.X_ne_zero i))
  have hdegree := congrArg (MvPolynomial.degreeOf i) hpoly
  rw [MvPolynomial.degreeOf_pow_eq i a p ha0,
    MvPolynomial.degreeOf_mul_eq (MvPolynomial.X_ne_zero i) (pow_ne_zero p hb0),
    MvPolynomial.degreeOf_X_self,
    MvPolynomial.degreeOf_pow_eq i b p hb0] at hdegree
  have hmod := congrArg (fun n : ℕ => n % p) hdegree
  simp [Nat.add_mod, Nat.mod_eq_of_lt hp] at hmod

/-- The first coordinate has no nontrivial power root in the field it
generates over the constant field. -/
theorem firstCoordinateInSubfield_not_pow
    {K : Type*} [Field K] {f : MvPolynomial (Fin 2) K}
    (hf : Irreducible f) (hsecond : 0 < MvPolynomial.degreeOf 1 f)
    (p : ℕ) (hp : 1 < p) :
    letI := planeCurveCoordinateRing_isDomain hf
    ¬ ∃ z : FirstCoordinateSubfield f,
      z ^ p = firstCoordinateInSubfield f := by
  letI : IsDomain (PlaneCurveCoordinateRing f) :=
    planeCurveCoordinateRing_isDomain hf
  let remaining := {i : Fin 2 // i ≠ 1}
  let i0 : remaining := ⟨0, by decide⟩
  have htrans : Transcendental K (planeCurveFunction f 0) :=
    firstCoordinate_transcendental hf hsecond
  let e := firstCoordinateFractionEquiv f htrans
  rintro ⟨z, hz⟩
  apply mvPolynomial_variable_not_pow_in_fractionRing
    (K := K) (σ := remaining) i0 p hp
  refine ⟨e.symm z, ?_⟩
  apply e.injective
  rw [map_pow, e.apply_symm_apply, hz,
    firstCoordinateFractionEquiv_algebraMap]
  apply Subtype.ext
  simp [firstCoordinateCoefficientEval, firstCoordinateInSubfield, i0]

/-- The second coordinate has no nontrivial power root in the field it
generates over the constant field. -/
theorem secondCoordinateInSubfield_not_pow
    {K : Type*} [Field K] {f : MvPolynomial (Fin 2) K}
    (hf : Irreducible f) (hfirst : 0 < MvPolynomial.degreeOf 0 f)
    (p : ℕ) (hp : 1 < p) :
    letI := planeCurveCoordinateRing_isDomain hf
    ¬ ∃ z : SecondCoordinateSubfield f,
      z ^ p = secondCoordinateInSubfield f := by
  letI : IsDomain (PlaneCurveCoordinateRing f) :=
    planeCurveCoordinateRing_isDomain hf
  let remaining := {i : Fin 2 // i ≠ 0}
  let i1 : remaining := ⟨1, by decide⟩
  have htrans : Transcendental K (planeCurveFunction f 1) :=
    secondCoordinate_transcendental hf hfirst
  let e := secondCoordinateFractionEquiv f htrans
  rintro ⟨z, hz⟩
  apply mvPolynomial_variable_not_pow_in_fractionRing
    (K := K) (σ := remaining) i1 p hp
  refine ⟨e.symm z, ?_⟩
  apply e.injective
  rw [map_pow, e.apply_symm_apply, hz,
    secondCoordinateFractionEquiv_algebraMap]
  apply Subtype.ext
  simp [secondCoordinateCoefficientEval, secondCoordinateInSubfield, i1]

/-- A first coordinate that is separating (equivalently here, the other
partial derivative is nonzero) is not a `p`-th power in the plane-curve
function field. -/
theorem firstCoordinate_not_mem_frobeniusSubfield
    {K : Type*} [Field K] {p : ℕ} [Fact p.Prime] [CharP K p]
    {f : MvPolynomial (Fin 2) K} (hf : Irreducible f)
    (hpartialSecond : MvPolynomial.pderiv 1 f ≠ 0) :
    letI := planeCurveCoordinateRing_isDomain hf
    letI : CharP (PlaneCurveFunctionField f) p :=
      charP_of_injective_algebraMap
        (algebraMap K (PlaneCurveFunctionField f)).injective p
    planeCurveFunction f 0 ∉
      frobeniusSubfield (PlaneCurveFunctionField f) p := by
  letI : IsDomain (PlaneCurveCoordinateRing f) :=
    planeCurveCoordinateRing_isDomain hf
  let L := PlaneCurveFunctionField f
  letI : CharP L p := charP_of_injective_algebraMap
    (algebraMap K L).injective p
  let F := FirstCoordinateSubfield f
  have hseparable :=
    (finiteSeparable_over_firstCoordinate_of_irreducible hf hpartialSecond).2
  letI : Algebra.IsSeparable F L := hseparable
  intro hx
  rcases hx with ⟨y, hy⟩
  have hypow : y ^ p = planeCurveFunction f 0 := by
    simpa [frobenius_def] using hy
  let E : IntermediateField F L := IntermediateField.adjoin F {y}
  letI : IsPurelyInseparable F E :=
    (IntermediateField.isPurelyInseparable_adjoin_simple_iff_pow_mem F L p).2 (by
      refine ⟨1, ?_⟩
      rw [pow_one]
      refine ⟨firstCoordinateInSubfield f, ?_⟩
      change planeCurveFunction f 0 = y ^ p
      exact hypow.symm)
  letI : Algebra.IsSeparable F E :=
    (IntermediateField.isSeparable_adjoin_simple_iff_isSeparable F L).2
      (Algebra.IsSeparable.isSeparable F y)
  have hE : E = ⊥ :=
    IntermediateField.eq_bot_of_isPurelyInseparable_of_isSeparable E
  have hyE : y ∈ E := IntermediateField.mem_adjoin_simple_self F y
  rw [hE] at hyE
  rw [IntermediateField.mem_bot] at hyE
  rcases hyE with ⟨z, hz⟩
  apply firstCoordinateInSubfield_not_pow hf
    (degreeOf_second_pos_of_pderiv_ne_zero hpartialSecond) p
    (Fact.out : p.Prime).one_lt
  refine ⟨z, ?_⟩
  apply Subtype.ext
  change (z : L) ^ p = planeCurveFunction f 0
  have hz' : (z : L) = y := by simpa [L] using hz
  rw [hz']
  exact hypow

/-- A second coordinate that is separating (equivalently here, the other
partial derivative is nonzero) is not a `p`-th power in the plane-curve
function field. -/
theorem secondCoordinate_not_mem_frobeniusSubfield
    {K : Type*} [Field K] {p : ℕ} [Fact p.Prime] [CharP K p]
    {f : MvPolynomial (Fin 2) K} (hf : Irreducible f)
    (hpartialFirst : MvPolynomial.pderiv 0 f ≠ 0) :
    letI := planeCurveCoordinateRing_isDomain hf
    letI : CharP (PlaneCurveFunctionField f) p :=
      charP_of_injective_algebraMap
        (algebraMap K (PlaneCurveFunctionField f)).injective p
    planeCurveFunction f 1 ∉
      frobeniusSubfield (PlaneCurveFunctionField f) p := by
  letI : IsDomain (PlaneCurveCoordinateRing f) :=
    planeCurveCoordinateRing_isDomain hf
  let L := PlaneCurveFunctionField f
  letI : CharP L p := charP_of_injective_algebraMap
    (algebraMap K L).injective p
  let F := SecondCoordinateSubfield f
  have hseparable :=
    (finiteSeparable_over_secondCoordinate_of_irreducible hf hpartialFirst).2
  letI : Algebra.IsSeparable F L := hseparable
  intro hx
  rcases hx with ⟨y, hy⟩
  have hypow : y ^ p = planeCurveFunction f 1 := by
    simpa [frobenius_def] using hy
  let E : IntermediateField F L := IntermediateField.adjoin F {y}
  letI : IsPurelyInseparable F E :=
    (IntermediateField.isPurelyInseparable_adjoin_simple_iff_pow_mem F L p).2 (by
      refine ⟨1, ?_⟩
      rw [pow_one]
      refine ⟨secondCoordinateInSubfield f, ?_⟩
      change planeCurveFunction f 1 = y ^ p
      exact hypow.symm)
  letI : Algebra.IsSeparable F E :=
    (IntermediateField.isSeparable_adjoin_simple_iff_isSeparable F L).2
      (Algebra.IsSeparable.isSeparable F y)
  have hE : E = ⊥ :=
    IntermediateField.eq_bot_of_isPurelyInseparable_of_isSeparable E
  have hyE : y ∈ E := IntermediateField.mem_adjoin_simple_self F y
  rw [hE] at hyE
  rw [IntermediateField.mem_bot] at hyE
  rcases hyE with ⟨z, hz⟩
  apply secondCoordinateInSubfield_not_pow hf
    (degreeOf_first_pos_of_pderiv_ne_zero hpartialFirst) p
    (Fact.out : p.Prime).one_lt
  refine ⟨z, ?_⟩
  apply Subtype.ext
  change (z : L) ^ p = planeCurveFunction f 1
  have hz' : (z : L) = y := by simpa [L] using hz
  rw [hz']
  exact hypow

end

end BGS.CorvajaZannier
