import BGS.CorvajaZannier.PoweredImageCurve
import Mathlib.RingTheory.Polynomial.Eisenstein.Basic
import Mathlib.Tactic

/-!
# Exact degree of a transcendental power map

For a transcendental element `z`, the extension `K(z)/K(z^m)` has exact
degree `m`.  The key polynomial is Eisenstein at the rational parameter.
-/

namespace BGS.CorvajaZannier

noncomputable section

open scoped Polynomial
open Polynomial

private theorem polynomial_X_pow_sub_C_X_irreducible
    {K : Type*} [Field K] (m : ℕ) (hm : 0 < m) :
    Irreducible
      (Polynomial.X ^ m - Polynomial.C (Polynomial.X : Polynomial K) :
        Polynomial (Polynomial K)) := by
  let R := Polynomial K
  let q : Polynomial R :=
    Polynomial.X ^ m - Polynomial.C (Polynomial.X : R)
  let P : Ideal R := Ideal.span {(Polynomial.X : R)}
  have hX : Irreducible (Polynomial.X : R) := Polynomial.irreducible_X
  have hP : P.IsPrime :=
    (Ideal.span_singleton_prime Polynomial.X_ne_zero).mpr hX.prime
  have hqMonic : q.Monic :=
    Polynomial.monic_X_pow_sub_C (Polynomial.X : R) hm.ne'
  have hqDegree : q.natDegree = m := by
    simpa only [q] using
      (Polynomial.natDegree_X_pow_sub_C
        (R := R) (n := m) (r := (Polynomial.X : R)))
  have hqEisenstein : q.IsEisensteinAt P := by
    refine {
      leading := ?_
      mem := ?_
      notMem := ?_ }
    · rw [hqMonic.leadingCoeff, Ideal.mem_span_singleton]
      exact hX.not_dvd_one
    · intro i hi
      rw [hqDegree] at hi
      by_cases hi0 : i = 0
      · subst i
        have hq0 : q.coeff 0 = -(Polynomial.X : R) := by
          simp [q, Ne.symm hm.ne']
        rw [hq0]
        exact P.neg_mem (Ideal.subset_span (Set.mem_singleton _))
      · have him : i ≠ m := ne_of_lt hi
        simp only [q, Polynomial.coeff_sub, Polynomial.coeff_X_pow,
          Polynomial.coeff_C, if_neg him, if_neg hi0, sub_zero]
        exact P.zero_mem
    · have hcoeff : q.coeff 0 = -(Polynomial.X : R) := by
        simp [q, Ne.symm hm.ne']
      rw [hcoeff, Ideal.span_singleton_pow,
        Ideal.mem_span_singleton]
      intro hdvd
      have hle := Polynomial.natDegree_le_of_dvd hdvd
        (neg_ne_zero.mpr Polynomial.X_ne_zero)
      rw [Polynomial.natDegree_pow, Polynomial.natDegree_X] at hle
      norm_num at hle
  exact hqEisenstein.irreducible hP hqMonic.isPrimitive
    (by rw [hqDegree]; exact hm)

/-- A transcendental element has minimal polynomial of degree `m` over the
field generated by its `m`-th power. -/
theorem minpoly_natDegree_over_adjoin_pow_eq
    {K L : Type*} [Field K] [Field L] [Algebra K L]
    (z : L) (hz : Transcendental K z) (m : ℕ) (hm : 0 < m) :
    (minpoly (IntermediateField.adjoin K {z ^ m}) z).natDegree = m := by
  let E0 := IntermediateField.adjoin K {z ^ m}
  let c : E0 :=
    ⟨z ^ m, IntermediateField.subset_adjoin K {z ^ m}
      (Set.mem_singleton (z ^ m))⟩
  let q : Polynomial E0 := Polynomial.X ^ m - Polynomial.C c
  have hzmTrans : Transcendental K (z ^ m) := hz.pow hm
  let e : RatFunc K ≃ₐ[K] E0 :=
    RatFunc.algEquivOfTranscendental (z ^ m) hzmTrans
  have hec : e RatFunc.X = c := by
    apply Subtype.ext
    simpa only [e, c] using
      (RatFunc.algEquivOfTranscendental_X
        (f := z ^ m) (h := hzmTrans))
  have hecinv : e.symm c = RatFunc.X := by
    rw [← hec, e.symm_apply_apply]
  have hqMap : (Polynomial.mapEquiv e.symm.toRingEquiv) q =
      (Polynomial.X ^ m - Polynomial.C RatFunc.X :
        Polynomial (RatFunc K)) := by
    simp [Polynomial.mapEquiv_apply, q, hecinv]
  let q0 : Polynomial (Polynomial K) :=
    Polynomial.X ^ m - Polynomial.C (Polynomial.X : Polynomial K)
  have hq0 : Irreducible q0 := by
    exact polynomial_X_pow_sub_C_X_irreducible m hm
  have hq0Monic : q0.Monic :=
    Polynomial.monic_X_pow_sub_C (Polynomial.X : Polynomial K) hm.ne'
  have hqRat : Irreducible
      (q0.map (algebraMap (Polynomial K) (RatFunc K))) :=
    hq0Monic.isPrimitive.irreducible_iff_irreducible_map_fraction_map.mp hq0
  have hqMapIrred : Irreducible
      ((Polynomial.mapEquiv e.symm.toRingEquiv) q) := by
    rw [hqMap]
    simpa [q0] using hqRat
  have hqIrred : Irreducible q := by
    apply Irreducible.of_map
      (f := Polynomial.mapEquiv e.symm.toRingEquiv)
    exact hqMapIrred
  have hqMonic : q.Monic :=
    Polynomial.monic_X_pow_sub_C c hm.ne'
  have hqRoot : Polynomial.aeval z q = 0 := by
    simp [q, c]
  have hminpoly : minpoly E0 z = q :=
    (minpoly.eq_of_irreducible_of_monic hqIrred hqRoot hqMonic).symm
  rw [hminpoly]
  simp [q]

/-- The simple extension generated by a transcendental element over the
field generated by its power has exact degree `m`. -/
theorem finrank_adjoin_over_adjoin_pow_eq
    {K L : Type*} [Field K] [Field L] [Algebra K L]
    (z : L) (hz : Transcendental K z) (m : ℕ) (hm : 0 < m) :
    Module.finrank (IntermediateField.adjoin K {z ^ m})
      (IntermediateField.adjoin
        (IntermediateField.adjoin K {z ^ m}) {z}) = m := by
  let E0 := IntermediateField.adjoin K {z ^ m}
  let c : E0 :=
    ⟨z ^ m, IntermediateField.subset_adjoin K {z ^ m}
      (Set.mem_singleton (z ^ m))⟩
  let q : Polynomial E0 := Polynomial.X ^ m - Polynomial.C c
  have hqMonic : q.Monic :=
    Polynomial.monic_X_pow_sub_C c hm.ne'
  have hqRoot : Polynomial.aeval z q = 0 := by simp [q, c]
  have hzIntegral : IsIntegral E0 z := ⟨q, hqMonic, hqRoot⟩
  rw [IntermediateField.adjoin.finrank hzIntegral,
    minpoly_natDegree_over_adjoin_pow_eq z hz m hm]

set_option maxHeartbeats 800000 in
set_option synthInstance.maxHeartbeats 200000 in
/-- Passing from `K(z)` to `K(z^m)` multiplies the degree of any finite top
extension by exactly `m`. -/
theorem finrank_over_adjoin_pow_eq_mul
    {K L : Type*} [Field K] [Field L] [Algebra K L]
    (z : L) (hz : Transcendental K z) (m : ℕ) (hm : 0 < m)
    [FiniteDimensional (IntermediateField.adjoin K {z}) L] :
    Module.finrank (IntermediateField.adjoin K {z ^ m}) L =
      m * Module.finrank (IntermediateField.adjoin K {z}) L := by
  let E0 := IntermediateField.adjoin K {z ^ m}
  let A := IntermediateField.adjoin E0 {z}
  let AK : IntermediateField K L := A.restrictScalars K
  have hAK : AK = IntermediateField.adjoin K {z} :=
    restrictScalars_adjoin_over_adjoin_pow_eq_adjoin z m
  let c : E0 :=
    ⟨z ^ m, IntermediateField.subset_adjoin K {z ^ m}
      (Set.mem_singleton (z ^ m))⟩
  let q : Polynomial E0 := Polynomial.X ^ m - Polynomial.C c
  have hqMonic : q.Monic :=
    Polynomial.monic_X_pow_sub_C c hm.ne'
  have hqRoot : Polynomial.aeval z q = 0 := by simp [q, c]
  have hzIntegral : IsIntegral E0 z := ⟨q, hqMonic, hqRoot⟩
  letI : FiniteDimensional E0 A :=
    IntermediateField.adjoin.finiteDimensional hzIntegral
  letI : FiniteDimensional A L := by
    change FiniteDimensional AK L
    rw [hAK]
    infer_instance
  calc
    Module.finrank E0 L = Module.finrank E0 A * Module.finrank A L := by
      rw [Module.finrank_mul_finrank]
    _ = m * Module.finrank A L := by
      rw [finrank_adjoin_over_adjoin_pow_eq z hz m hm]
    _ = m * Module.finrank (IntermediateField.adjoin K {z}) L := by
      congr 1
      change Module.finrank AK L = _
      rw [hAK]

set_option maxHeartbeats 800000 in
set_option synthInstance.maxHeartbeats 200000 in
/-- Exact source degree over the powered first coordinate. -/
theorem finrank_over_firstPoweredCoordinate_eq
    {K : Type*} [Field K] {f : MvPolynomial (Fin 2) K}
    (hf : Irreducible f) (hpartialSecond : MvPolynomial.pderiv 1 f ≠ 0)
    (m : ℕ) (hm : 0 < m) :
    letI := planeCurveCoordinateRing_isDomain hf
    Module.finrank (FirstPoweredCoordinateSubfield f m)
        (PlaneCurveFunctionField f) =
      m * MvPolynomial.degreeOf 1 f := by
  letI : IsDomain (PlaneCurveCoordinateRing f) :=
    planeCurveCoordinateRing_isDomain hf
  let x := planeCurveFunction f 0
  have hx : Transcendental K x :=
    firstCoordinate_transcendental hf
      (degreeOf_second_pos_of_pderiv_ne_zero hpartialSecond)
  letI : FiniteDimensional (FirstCoordinateSubfield f)
      (PlaneCurveFunctionField f) :=
    finiteDimensional_over_firstCoordinate_of_irreducible hf hpartialSecond
  rw [finrank_over_adjoin_pow_eq_mul x hx m hm,
    finrank_over_firstCoordinate_eq_degreeOf_second_of_irreducible
      hf hpartialSecond]

set_option maxHeartbeats 800000 in
set_option synthInstance.maxHeartbeats 200000 in
/-- Exact source degree over the powered second coordinate. -/
theorem finrank_over_secondPoweredCoordinate_eq
    {K : Type*} [Field K] {f : MvPolynomial (Fin 2) K}
    (hf : Irreducible f) (hpartialFirst : MvPolynomial.pderiv 0 f ≠ 0)
    (n : ℕ) (hn : 0 < n) :
    letI := planeCurveCoordinateRing_isDomain hf
    Module.finrank (SecondPoweredCoordinateSubfield f n)
        (PlaneCurveFunctionField f) =
      n * MvPolynomial.degreeOf 0 f := by
  letI : IsDomain (PlaneCurveCoordinateRing f) :=
    planeCurveCoordinateRing_isDomain hf
  let y := planeCurveFunction f 1
  have hy : Transcendental K y :=
    secondCoordinate_transcendental hf
      (degreeOf_first_pos_of_pderiv_ne_zero hpartialFirst)
  letI : FiniteDimensional (SecondCoordinateSubfield f)
      (PlaneCurveFunctionField f) :=
    (finiteSeparable_over_secondCoordinate_of_irreducible
      hf hpartialFirst).1
  rw [finrank_over_adjoin_pow_eq_mul y hy n hn,
    finrank_over_secondCoordinate_eq_degreeOf_first_of_irreducible
      hf hpartialFirst]

end

end BGS.CorvajaZannier
