import BGS.NumberTheory.RankinCanonicalProfile
import BGS.NumberTheory.RankinJointEnvelopeCoverage
import Mathlib.Analysis.SpecialFunctions.Pow.NthRootLemmas
import Mathlib.Algebra.Order.Floor.Div
import Mathlib.NumberTheory.PrimeCounting
import Mathlib.Data.List.Indexes

/-!
# Positional Rankin profiles

The globally sorted odd support has a canonical position.  We attach the
`i`-th generated cap to the `i`-th support prime, rather than selecting a cap
from the prime value.  After side erasure the resulting profile is determined
only by the two-adic exponents and the list of odd exponents.

Caps are generated by integer arithmetic.  For a denominator `D` and prime
floor `q`, the numerator is one more than the integral twelfth root of
`ceil(D^12 / q)`.  The extra one makes the required twelfth-power inequality
immediate and keeps the checker independent of floating-point arithmetic.
-/

namespace BGS.NumberTheory

/-- Executable numerator for a rational upper approximation to
`floor ^ (-1/12)`. -/
def rankinCapNumerator (precision floor : ℕ) : ℕ :=
  Nat.nthRoot 12
      (precision ^ 12 ⌈/⌉ floor) + 1

def rationalPrimeWeightCapForFloor
    (precision floor : ℕ) : RationalPrimeWeightCap where
  lowerPrime := floor
  numerator := rankinCapNumerator precision floor
  denominator := precision

theorem rationalPrimeWeightCapForFloor_valid
    {precision floor : ℕ} (hprecision : 0 < precision)
    (hfloor : 0 < floor) :
    (rationalPrimeWeightCapForFloor precision floor).Valid := by
  refine ⟨hfloor, ?_, hprecision, ?_⟩
  · simp [rationalPrimeWeightCapForFloor, rankinCapNumerator]
  · have hceil :
        precision ^ 12 ≤ floor * (precision ^ 12 ⌈/⌉ floor) := by
      simpa [nsmul_eq_mul] using
        (le_smul_ceilDiv (α := ℕ) (β := ℕ)
          hfloor :
          precision ^ 12 ≤ floor • (precision ^ 12 ⌈/⌉ floor))
    have hroot :
        (precision ^ 12 ⌈/⌉ floor) ≤
          rankinCapNumerator precision floor ^ 12 := by
      exact (Nat.lt_pow_nthRoot_add_one (by norm_num : 12 ≠ 0)
        (precision ^ 12 ⌈/⌉ floor)).le
    exact hceil.trans (Nat.mul_le_mul_left _ hroot)

/-- The odd factor in position `index`, with side already erased. -/
def positionalRankinOddFactor
    (oddCapAt : ℕ → RationalPrimeWeightCap)
    (index exponent : ℕ) : RankinOddFactor where
  side := .minus
  exponent := exponent
  weightCap := oddCapAt index

/-- The finite-search representative determined by an exponent skeleton. -/
def positionalRankinSkeletonProfile
    (twoCap : RationalPrimeWeightCap)
    (oddCapAt : ℕ → RationalPrimeWeightCap)
    (minusTwoExponent plusTwoExponent : ℕ)
    (oddExponents : List ℕ) (rootCap : ℕ) : RankinNeighborProfile where
  minusTwoExponent := minusTwoExponent
  plusTwoExponent := plusTwoExponent
  twoWeightCap := twoCap
  oddFactors := oddExponents.mapIdx
    (fun index exponent =>
      positionalRankinOddFactor oddCapAt index exponent)
  rootCap := rootCap

/-- Position-dependent cap assignment on the actual sorted support. -/
def positionalOddCap
    (p : ℕ) (oddCapAt : ℕ → RationalPrimeWeightCap)
    (prime : ℕ) : RationalPrimeWeightCap :=
  oddCapAt ((jointOddPrimeList p).idxOf prime)

/-- Canonical actual profile using the same cap ladder as the skeleton
representatives. -/
def positionalCanonicalRankinNeighborProfile
    (p : ℕ) (twoCap : RationalPrimeWeightCap)
    (oddCapAt : ℕ → RationalPrimeWeightCap)
    (rootCap : ℕ) : RankinNeighborProfile :=
  canonicalRankinNeighborProfile p
    twoCap (positionalOddCap p oddCapAt) rootCap

/-- The odd exponent skeleton of the actual neighboring factorization. -/
def actualOddExponentSkeleton (p : ℕ) : List ℕ :=
  (jointOddPrimeList p).map (actualNeighborExponent p)

private theorem mapIdx_eq_map_idxOf
    {α β : Type*} [BEq α] [LawfulBEq α]
    (values : List α) (hnodup : values.Nodup)
    (f : ℕ → α → β) :
    values.mapIdx f =
      values.map (fun value => f (values.idxOf value) value) := by
  rw [List.mapIdx_eq_ofFn]
  apply List.ext_getElem
  · simp
  · intro index hleft hright
    simp only [List.getElem_ofFn, List.getElem_map]
    congr 1
    simpa using
      (List.get_idxOf hnodup ⟨index, by simpa using hleft⟩).symm

private theorem mapIdx_map
    {α β γ : Type*} (values : List α) (g : α → β)
    (f : ℕ → β → γ) :
    (values.map g).mapIdx f =
      values.mapIdx (fun index value => f index (g value)) := by
  rw [List.mapIdx_eq_ofFn, List.mapIdx_eq_ofFn]
  apply List.ext_getElem
  · simp
  · intro index hleft hright
    simp only [List.getElem_ofFn]
    rw [List.get_eq_getElem, List.getElem_map, List.get_eq_getElem]

/-- Side erasure turns the positional canonical profile into exactly the
finite-search exponent skeleton. -/
theorem eraseSides_positionalCanonicalRankinNeighborProfile
    (p : ℕ) (twoCap : RationalPrimeWeightCap)
    (oddCapAt : ℕ → RationalPrimeWeightCap) (rootCap : ℕ) :
    (positionalCanonicalRankinNeighborProfile
        p twoCap oddCapAt rootCap).eraseSides =
      positionalRankinSkeletonProfile twoCap oddCapAt
        ((p - 1).factorization 2) ((p + 1).factorization 2)
        (actualOddExponentSkeleton p) rootCap := by
  simp only [positionalCanonicalRankinNeighborProfile,
    canonicalRankinNeighborProfile, RankinNeighborProfile.eraseSides,
    positionalRankinSkeletonProfile]
  congr 1
  rw [actualOddExponentSkeleton, List.map_map]
  rw [mapIdx_map]
  rw [mapIdx_eq_map_idxOf (jointOddPrimeList p)
    (Finset.sort_nodup (jointOddPrimeSupport p) (· ≤ ·))]
  simp [positionalRankinOddFactor, canonicalRankinOddFactor,
    RankinNeighborProfile.eraseOddFactorSide, positionalOddCap]

end BGS.NumberTheory
