import BGS.Markoff.Assembly.Unconditional
import GenMarkoff.General.Assembly.VietaRotationEquivalence

/-!
# The classical all-zero coefficient bridge

For the integral coefficient triple `(0,0,0)`, the generalized surface is
the classical Markoff surface

`x₁² + x₂² + x₃² - 3 * x₁ * x₂ * x₃ = 0`.

The BGS group `Gamma` is larger than the fixed-coefficient `VietaGroup`: it
also contains coordinate swaps.  We therefore do not transport a `Gamma`
element directly into `VietaGroup`.

Instead, inside the BGS surface permutation group we form the subgroup
generated by the three Vieta involutions alone.  Coordinate swaps conjugate
this subgroup to itself, and both swaps fix `(1,1,1)`.  Consequently the
full `Gamma` orbit of `(1,1,1)` is already its Vieta-only orbit.  BGS
transitivity then gives Vieta-only transitivity, which is transported through
an explicit equivalence of the two punctured surfaces.
-/

namespace GenMarkoff.General.Assembly

universe u

open scoped Pointwise

/-- The all-zero coefficient triple over an arbitrary ring. -/
def classicalZeroCoefficients
    (R : Type u) [Zero R] : Coefficients R :=
  ⟨0, 0, 0⟩

@[simp]
theorem classicalZeroCoefficients_a1
    (R : Type u) [Zero R] :
    (classicalZeroCoefficients R).a1 = 0 :=
  rfl

@[simp]
theorem classicalZeroCoefficients_a2
    (R : Type u) [Zero R] :
    (classicalZeroCoefficients R).a2 = 0 :=
  rfl

@[simp]
theorem classicalZeroCoefficients_a3
    (R : Type u) [Zero R] :
    (classicalZeroCoefficients R).a3 = 0 :=
  rfl

@[simp]
theorem modCoefficients_classicalZeroCoefficients (p : ℕ) :
    modCoefficients (classicalZeroCoefficients ℤ) p =
      classicalZeroCoefficients (ZMod p) := by
  ext <;> simp [modCoefficients, classicalZeroCoefficients,
    Coefficients.intCast]

/-- Coordinatewise identification of generalized points with BGS points. -/
def classicalPointEquiv
    (R : Type u) : Point R ≃ BGS.Markoff.Point R where
  toFun x := ⟨x.x1, x.x2, x.x3⟩
  invFun x := ⟨x.x1, x.x2, x.x3⟩
  left_inv x := by ext <;> rfl
  right_inv x := by ext <;> rfl

@[simp]
theorem classicalPointEquiv_x1
    {R : Type u} (x : Point R) :
    (classicalPointEquiv R x).x1 = x.x1 :=
  rfl

@[simp]
theorem classicalPointEquiv_x2
    {R : Type u} (x : Point R) :
    (classicalPointEquiv R x).x2 = x.x2 :=
  rfl

@[simp]
theorem classicalPointEquiv_x3
    {R : Type u} (x : Point R) :
    (classicalPointEquiv R x).x3 = x.x3 :=
  rfl

@[simp]
theorem classicalPointEquiv_origin
    {R : Type u} [Zero R] :
    classicalPointEquiv R (origin : Point R) =
      (BGS.Markoff.origin : BGS.Markoff.Point R) := by
  rfl

/-- The two defining polynomials agree for the all-zero coefficient
triple. -/
theorem polynomial_classicalZero_eq_markoffPolynomial
    {R : Type u} [CommRing R] (x : Point R) :
    polynomial (classicalZeroCoefficients R) x =
      BGS.Markoff.markoffPolynomial (classicalPointEquiv R x) := by
  simp [polynomial, classicalZeroCoefficients,
    Coefficients.multiplier, BGS.Markoff.markoffPolynomial]

/-- Explicit equivalence between the generalized all-zero surface and the
BGS Markoff surface. -/
def classicalSurfaceEquiv
    (R : Type u) [CommRing R] :
    SolutionSurface (classicalZeroCoefficients R) ≃
      BGS.Markoff.MarkoffSurface R where
  toFun x :=
    ⟨classicalPointEquiv R x.1, by
      rw [BGS.Markoff.IsMarkoff]
      rw [← polynomial_classicalZero_eq_markoffPolynomial]
      exact x.2⟩
  invFun x :=
    ⟨(classicalPointEquiv R).symm x.1, by
      rw [IsSolution]
      rw [polynomial_classicalZero_eq_markoffPolynomial]
      exact x.2⟩
  left_inv x := by
    apply Subtype.ext
    exact (classicalPointEquiv R).left_inv x.1
  right_inv x := by
    apply Subtype.ext
    exact (classicalPointEquiv R).right_inv x.1

@[simp]
theorem classicalSurfaceEquiv_surfaceOrigin
    {R : Type u} [CommRing R] :
    classicalSurfaceEquiv R
        (surfaceOrigin (classicalZeroCoefficients R)) =
      BGS.Markoff.surfaceOrigin R := by
  apply Subtype.ext
  rfl

/-- Explicit equivalence of the punctured surfaces. -/
def classicalPuncturedSurfaceEquiv
    (R : Type u) [CommRing R] :
    PuncturedSolutionSurface (classicalZeroCoefficients R) ≃
      BGS.Markoff.PuncturedMarkoffSurface R where
  toFun x :=
    ⟨classicalSurfaceEquiv R x.1, by
      intro h
      apply x.2
      apply (classicalSurfaceEquiv R).injective
      simpa using h⟩
  invFun x :=
    ⟨(classicalSurfaceEquiv R).symm x.1, by
      intro h
      apply x.2
      have h' := congrArg (classicalSurfaceEquiv R) h
      simpa using h'⟩
  left_inv x := by
    apply Subtype.ext
    exact (classicalSurfaceEquiv R).left_inv x.1
  right_inv x := by
    apply Subtype.ext
    exact (classicalSurfaceEquiv R).right_inv x.1

section BgsVietaOnly

variable (R : Type u) [CommRing R]

private abbrev BgsSurfacePerm :=
  Equiv.Perm (BGS.Markoff.MarkoffSurface R)

/-- The three BGS Vieta involutions, without coordinate swaps. -/
def classicalBgsVietaGenerators : Set (BgsSurfacePerm R) :=
  {BGS.Markoff.vieta1SurfacePerm R,
    BGS.Markoff.vieta2SurfacePerm R,
    BGS.Markoff.vieta3SurfacePerm R}

/-- The Vieta-only subgroup of the BGS surface permutation group. -/
def ClassicalBgsVietaGroup : Subgroup (BgsSurfacePerm R) :=
  Subgroup.closure (classicalBgsVietaGenerators R)

theorem bgs_vieta1_mem_ClassicalBgsVietaGroup :
    BGS.Markoff.vieta1SurfacePerm R ∈
      ClassicalBgsVietaGroup R :=
  Subgroup.subset_closure (by simp [classicalBgsVietaGenerators])

theorem bgs_vieta2_mem_ClassicalBgsVietaGroup :
    BGS.Markoff.vieta2SurfacePerm R ∈
      ClassicalBgsVietaGroup R :=
  Subgroup.subset_closure (by simp [classicalBgsVietaGenerators])

theorem bgs_vieta3_mem_ClassicalBgsVietaGroup :
    BGS.Markoff.vieta3SurfacePerm R ∈
      ClassicalBgsVietaGroup R :=
  Subgroup.subset_closure (by simp [classicalBgsVietaGenerators])

private theorem bgs_swap12SurfacePerm_inv :
    (BGS.Markoff.swap12SurfacePerm R)⁻¹ =
      BGS.Markoff.swap12SurfacePerm R := by
  apply Equiv.ext
  intro x
  apply Subtype.ext
  rfl

private theorem bgs_swap23SurfacePerm_inv :
    (BGS.Markoff.swap23SurfacePerm R)⁻¹ =
      BGS.Markoff.swap23SurfacePerm R := by
  apply Equiv.ext
  intro x
  apply Subtype.ext
  rfl

private theorem bgs_swap12_conjugates_vieta1 :
    BGS.Markoff.swap12SurfacePerm R *
          BGS.Markoff.vieta1SurfacePerm R *
          (BGS.Markoff.swap12SurfacePerm R)⁻¹ =
        BGS.Markoff.vieta2SurfacePerm R := by
  apply Equiv.ext
  intro x
  apply Subtype.ext
  change
    BGS.Markoff.swap12
        (BGS.Markoff.vieta1 (BGS.Markoff.swap12 x.1)) =
      BGS.Markoff.vieta2 x.1
  rfl

private theorem bgs_swap12_conjugates_vieta2 :
    BGS.Markoff.swap12SurfacePerm R *
          BGS.Markoff.vieta2SurfacePerm R *
          (BGS.Markoff.swap12SurfacePerm R)⁻¹ =
        BGS.Markoff.vieta1SurfacePerm R := by
  apply Equiv.ext
  intro x
  apply Subtype.ext
  change
    BGS.Markoff.swap12
        (BGS.Markoff.vieta2 (BGS.Markoff.swap12 x.1)) =
      BGS.Markoff.vieta1 x.1
  rfl

private theorem bgs_swap12_conjugates_vieta3 :
    BGS.Markoff.swap12SurfacePerm R *
          BGS.Markoff.vieta3SurfacePerm R *
          (BGS.Markoff.swap12SurfacePerm R)⁻¹ =
        BGS.Markoff.vieta3SurfacePerm R := by
  apply Equiv.ext
  intro x
  apply Subtype.ext
  change
    BGS.Markoff.swap12
        (BGS.Markoff.vieta3 (BGS.Markoff.swap12 x.1)) =
      BGS.Markoff.vieta3 x.1
  ext <;> simp [BGS.Markoff.swap12, BGS.Markoff.vieta3] <;> ring

private theorem bgs_swap23_conjugates_vieta1 :
    BGS.Markoff.swap23SurfacePerm R *
          BGS.Markoff.vieta1SurfacePerm R *
          (BGS.Markoff.swap23SurfacePerm R)⁻¹ =
        BGS.Markoff.vieta1SurfacePerm R := by
  apply Equiv.ext
  intro x
  apply Subtype.ext
  change
    BGS.Markoff.swap23
        (BGS.Markoff.vieta1 (BGS.Markoff.swap23 x.1)) =
      BGS.Markoff.vieta1 x.1
  ext <;> simp [BGS.Markoff.swap23, BGS.Markoff.vieta1] <;> ring

private theorem bgs_swap23_conjugates_vieta2 :
    BGS.Markoff.swap23SurfacePerm R *
          BGS.Markoff.vieta2SurfacePerm R *
          (BGS.Markoff.swap23SurfacePerm R)⁻¹ =
        BGS.Markoff.vieta3SurfacePerm R := by
  apply Equiv.ext
  intro x
  apply Subtype.ext
  change
    BGS.Markoff.swap23
        (BGS.Markoff.vieta2 (BGS.Markoff.swap23 x.1)) =
      BGS.Markoff.vieta3 x.1
  rfl

private theorem bgs_swap23_conjugates_vieta3 :
    BGS.Markoff.swap23SurfacePerm R *
          BGS.Markoff.vieta3SurfacePerm R *
          (BGS.Markoff.swap23SurfacePerm R)⁻¹ =
        BGS.Markoff.vieta2SurfacePerm R := by
  apply Equiv.ext
  intro x
  apply Subtype.ext
  change
    BGS.Markoff.swap23
        (BGS.Markoff.vieta3 (BGS.Markoff.swap23 x.1)) =
      BGS.Markoff.vieta2 x.1
  rfl

private theorem conjugate_mem_classicalBgsVietaGroup
    (s : BgsSurfacePerm R)
    (hgenerator :
      ∀ g ∈ classicalBgsVietaGenerators R,
        s * g * s⁻¹ ∈ ClassicalBgsVietaGroup R)
    {g : BgsSurfacePerm R}
    (hg : g ∈ ClassicalBgsVietaGroup R) :
    s * g * s⁻¹ ∈ ClassicalBgsVietaGroup R := by
  induction hg using Subgroup.closure_induction with
  | mem g hg => exact hgenerator g hg
  | one => simp
  | mul g h _ _ hg' hh' =>
      rw [show
        s * (g * h) * s⁻¹ =
          (s * g * s⁻¹) * (s * h * s⁻¹) by group]
      exact (ClassicalBgsVietaGroup R).mul_mem hg' hh'
  | inv g _ hg' =>
      rw [show
        s * g⁻¹ * s⁻¹ = (s * g * s⁻¹)⁻¹ by group]
      exact (ClassicalBgsVietaGroup R).inv_mem hg'

private theorem bgs_swap12_conjugate_mem
    {g : BgsSurfacePerm R}
    (hg : g ∈ ClassicalBgsVietaGroup R) :
    BGS.Markoff.swap12SurfacePerm R * g *
          (BGS.Markoff.swap12SurfacePerm R)⁻¹ ∈
        ClassicalBgsVietaGroup R := by
  apply conjugate_mem_classicalBgsVietaGroup R
  intro q hq
  simp only [classicalBgsVietaGenerators, Set.mem_insert_iff,
    Set.mem_singleton_iff] at hq
  rcases hq with rfl | rfl | rfl
  · rw [bgs_swap12_conjugates_vieta1]
    exact bgs_vieta2_mem_ClassicalBgsVietaGroup R
  · rw [bgs_swap12_conjugates_vieta2]
    exact bgs_vieta1_mem_ClassicalBgsVietaGroup R
  · rw [bgs_swap12_conjugates_vieta3]
    exact bgs_vieta3_mem_ClassicalBgsVietaGroup R
  exact hg

private theorem bgs_swap23_conjugate_mem
    {g : BgsSurfacePerm R}
    (hg : g ∈ ClassicalBgsVietaGroup R) :
    BGS.Markoff.swap23SurfacePerm R * g *
          (BGS.Markoff.swap23SurfacePerm R)⁻¹ ∈
        ClassicalBgsVietaGroup R := by
  apply conjugate_mem_classicalBgsVietaGroup R
  intro q hq
  simp only [classicalBgsVietaGenerators, Set.mem_insert_iff,
    Set.mem_singleton_iff] at hq
  rcases hq with rfl | rfl | rfl
  · rw [bgs_swap23_conjugates_vieta1]
    exact bgs_vieta1_mem_ClassicalBgsVietaGroup R
  · rw [bgs_swap23_conjugates_vieta2]
    exact bgs_vieta3_mem_ClassicalBgsVietaGroup R
  · rw [bgs_swap23_conjugates_vieta3]
    exact bgs_vieta2_mem_ClassicalBgsVietaGroup R
  exact hg

/-- The symmetric Markoff point `(1,1,1)`. -/
def classicalBgsSurfaceUnit :
    BGS.Markoff.MarkoffSurface R :=
  ⟨⟨1, 1, 1⟩, by
    simp [BGS.Markoff.IsMarkoff, BGS.Markoff.markoffPolynomial]
    ring⟩

@[simp]
theorem bgs_swap12SurfacePerm_surfaceUnit :
    BGS.Markoff.swap12SurfacePerm R
        (classicalBgsSurfaceUnit R) =
      classicalBgsSurfaceUnit R := by
  apply Subtype.ext
  rfl

@[simp]
theorem bgs_swap23SurfacePerm_surfaceUnit :
    BGS.Markoff.swap23SurfacePerm R
        (classicalBgsSurfaceUnit R) =
      classicalBgsSurfaceUnit R := by
  apply Subtype.ext
  rfl

/-- The orbit of `(1,1,1)` under the three BGS Vieta involutions alone. -/
def classicalBgsVietaOrbit :
    Set (BGS.Markoff.MarkoffSurface R) :=
  MulAction.orbit (ClassicalBgsVietaGroup R)
    (classicalBgsSurfaceUnit R)

private theorem classicalBgsVietaGroup_le_orbitStabilizer :
    ClassicalBgsVietaGroup R ≤
      MulAction.stabilizer (BgsSurfacePerm R)
        (classicalBgsVietaOrbit R) := by
  intro g hg
  rw [MulAction.mem_stabilizer_iff,
    ← Subgroup.coe_mk (ClassicalBgsVietaGroup R) g hg,
    ← (ClassicalBgsVietaGroup R).toSubmonoid.smul_def]
  exact MulAction.smul_orbit
    (⟨g, hg⟩ : ClassicalBgsVietaGroup R)
    (classicalBgsSurfaceUnit R)

private theorem swap_mem_classicalBgsVietaOrbit_stabilizer
    (s : BgsSurfacePerm R)
    (hsInv : s⁻¹ = s)
    (hsUnit : s (classicalBgsSurfaceUnit R) =
      classicalBgsSurfaceUnit R)
    (hconjugate :
      ∀ {g : BgsSurfacePerm R},
        g ∈ ClassicalBgsVietaGroup R →
          s * g * s⁻¹ ∈ ClassicalBgsVietaGroup R) :
    s ∈ MulAction.stabilizer (BgsSurfacePerm R)
      (classicalBgsVietaOrbit R) := by
  have hmaps :
      ∀ x ∈ classicalBgsVietaOrbit R,
        s x ∈ classicalBgsVietaOrbit R := by
    intro x hx
    rcases hx with ⟨g, rfl⟩
    refine ⟨⟨s * g * s⁻¹, hconjugate g.2⟩, ?_⟩
    change s ((g : BgsSurfacePerm R)
        (s⁻¹ (classicalBgsSurfaceUnit R))) =
      s ((g : BgsSurfacePerm R) (classicalBgsSurfaceUnit R))
    rw [hsInv, hsUnit]
  rw [MulAction.mem_stabilizer_iff]
  apply Set.Subset.antisymm
  · rintro y ⟨x, hx, rfl⟩
    exact hmaps x hx
  · intro y hy
    refine ⟨s y, hmaps y hy, ?_⟩
    change s (s y) = y
    calc
      s (s y) = s (s⁻¹ y) := by
        congr 1
        exact (congrArg (fun e : BgsSurfacePerm R => e y) hsInv).symm
      _ = y := s.apply_symm_apply y

private theorem bgs_swap12_mem_classicalBgsVietaOrbit_stabilizer :
    BGS.Markoff.swap12SurfacePerm R ∈
      MulAction.stabilizer (BgsSurfacePerm R)
        (classicalBgsVietaOrbit R) := by
  apply swap_mem_classicalBgsVietaOrbit_stabilizer R
  · exact bgs_swap12SurfacePerm_inv R
  · exact bgs_swap12SurfacePerm_surfaceUnit R
  · exact fun hg => bgs_swap12_conjugate_mem R hg

private theorem bgs_swap23_mem_classicalBgsVietaOrbit_stabilizer :
    BGS.Markoff.swap23SurfacePerm R ∈
      MulAction.stabilizer (BgsSurfacePerm R)
        (classicalBgsVietaOrbit R) := by
  apply swap_mem_classicalBgsVietaOrbit_stabilizer R
  · exact bgs_swap23SurfacePerm_inv R
  · exact bgs_swap23SurfacePerm_surfaceUnit R
  · exact fun hg => bgs_swap23_conjugate_mem R hg

/-- Every BGS `Gamma` element preserves the Vieta-only orbit of the
swap-fixed point `(1,1,1)`. -/
theorem bgs_Gamma_le_classicalBgsVietaOrbit_stabilizer :
    BGS.Markoff.Gamma R ≤
      MulAction.stabilizer (BgsSurfacePerm R)
        (classicalBgsVietaOrbit R) := by
  apply (Subgroup.closure_le _).2
  intro g hg
  simp only [BGS.Markoff.gammaGenerators, Set.mem_insert_iff,
    Set.mem_singleton_iff] at hg
  rcases hg with rfl | rfl | rfl | rfl | rfl
  · exact classicalBgsVietaGroup_le_orbitStabilizer R
      (bgs_vieta1_mem_ClassicalBgsVietaGroup R)
  · exact classicalBgsVietaGroup_le_orbitStabilizer R
      (bgs_vieta2_mem_ClassicalBgsVietaGroup R)
  · exact classicalBgsVietaGroup_le_orbitStabilizer R
      (bgs_vieta3_mem_ClassicalBgsVietaGroup R)
  · exact bgs_swap12_mem_classicalBgsVietaOrbit_stabilizer R
  · exact bgs_swap23_mem_classicalBgsVietaOrbit_stabilizer R

/-- Hence the image of `(1,1,1)` under any full BGS word already belongs to
its Vieta-only orbit. -/
theorem bgs_Gamma_smul_surfaceUnit_mem_classicalBgsVietaOrbit
    (g : BGS.Markoff.Gamma R) :
    g • classicalBgsSurfaceUnit R ∈
      classicalBgsVietaOrbit R := by
  have hstabilizes :
      (g : BgsSurfacePerm R) • classicalBgsVietaOrbit R =
        classicalBgsVietaOrbit R :=
    MulAction.mem_stabilizer_iff.mp
      (bgs_Gamma_le_classicalBgsVietaOrbit_stabilizer R g.2)
  have hunit :
      classicalBgsSurfaceUnit R ∈ classicalBgsVietaOrbit R :=
    MulAction.mem_orbit_self (classicalBgsSurfaceUnit R)
  have himage :
      (g : BgsSurfacePerm R) • classicalBgsSurfaceUnit R ∈
        (g : BgsSurfacePerm R) • classicalBgsVietaOrbit R :=
    ⟨classicalBgsSurfaceUnit R, hunit, rfl⟩
  rwa [hstabilizes] at himage

variable [Nontrivial R]

/-- The same symmetric base point on the punctured BGS surface. -/
def classicalBgsPuncturedUnit :
    BGS.Markoff.PuncturedMarkoffSurface R :=
  ⟨classicalBgsSurfaceUnit R, by
    intro h
    have hfirst := congrArg
      (fun x : BGS.Markoff.MarkoffSurface R => x.1.x1) h
    exact one_ne_zero hfirst⟩

/-- Full BGS transitivity implies transitivity of the subgroup generated by
the three Vieta involutions alone. -/
theorem classicalBgsVieta_transitive_of_Gamma_transitive
    (hGamma :
      ∀ x y : BGS.Markoff.PuncturedMarkoffSurface R,
        ∃ g : BGS.Markoff.Gamma R, g • x = y) :
    ∀ x y : BGS.Markoff.PuncturedMarkoffSurface R,
      ∃ g : ClassicalBgsVietaGroup R, g • x.1 = y.1 := by
  intro x y
  obtain ⟨gx, hgx⟩ :=
    hGamma (classicalBgsPuncturedUnit R) x
  obtain ⟨gy, hgy⟩ :=
    hGamma (classicalBgsPuncturedUnit R) y
  have hxmem : x.1 ∈ classicalBgsVietaOrbit R := by
    have hmem :=
      bgs_Gamma_smul_surfaceUnit_mem_classicalBgsVietaOrbit R gx
    have hgxSurface :
        gx • classicalBgsSurfaceUnit R = x.1 :=
      congrArg Subtype.val hgx
    rwa [hgxSurface] at hmem
  have hymem : y.1 ∈ classicalBgsVietaOrbit R := by
    have hmem :=
      bgs_Gamma_smul_surfaceUnit_mem_classicalBgsVietaOrbit R gy
    have hgySurface :
        gy • classicalBgsSurfaceUnit R = y.1 :=
      congrArg Subtype.val hgy
    rwa [hgySurface] at hmem
  rcases hxmem with ⟨hx, hhx⟩
  rcases hymem with ⟨hy, hhy⟩
  refine ⟨hy * hx⁻¹, ?_⟩
  calc
    (hy * hx⁻¹) • x.1 = hy • (hx⁻¹ • x.1) := mul_smul _ _ _
    _ = hy • classicalBgsSurfaceUnit R := by
      rw [← hhx, inv_smul_smul]
    _ = y.1 := hhy

end BgsVietaOnly

section Transport

variable (R : Type u) [CommRing R]

/-- The first generalized Vieta move corresponds exactly to the first BGS
Vieta move under the surface equivalence. -/
theorem classicalSurfaceEquiv_vieta1
    (x : SolutionSurface (classicalZeroCoefficients R)) :
    classicalSurfaceEquiv R
        (vieta1SurfacePerm (classicalZeroCoefficients R) x) =
      BGS.Markoff.vieta1SurfacePerm R
        (classicalSurfaceEquiv R x) := by
  apply Subtype.ext
  change classicalPointEquiv R
      (vieta1 (classicalZeroCoefficients R) x.1) =
    BGS.Markoff.vieta1 (classicalPointEquiv R x.1)
  ext <;>
    simp [classicalPointEquiv, vieta1, classicalZeroCoefficients,
      Coefficients.multiplier, BGS.Markoff.vieta1] <;>
    ring

/-- The second generalized Vieta move corresponds exactly to the second BGS
Vieta move. -/
theorem classicalSurfaceEquiv_vieta2
    (x : SolutionSurface (classicalZeroCoefficients R)) :
    classicalSurfaceEquiv R
        (vieta2SurfacePerm (classicalZeroCoefficients R) x) =
      BGS.Markoff.vieta2SurfacePerm R
        (classicalSurfaceEquiv R x) := by
  apply Subtype.ext
  change classicalPointEquiv R
      (vieta2 (classicalZeroCoefficients R) x.1) =
    BGS.Markoff.vieta2 (classicalPointEquiv R x.1)
  ext <;>
    simp [classicalPointEquiv, vieta2, classicalZeroCoefficients,
      Coefficients.multiplier, BGS.Markoff.vieta2] <;>
    ring

/-- The third generalized Vieta move corresponds exactly to the third BGS
Vieta move. -/
theorem classicalSurfaceEquiv_vieta3
    (x : SolutionSurface (classicalZeroCoefficients R)) :
    classicalSurfaceEquiv R
        (vieta3SurfacePerm (classicalZeroCoefficients R) x) =
      BGS.Markoff.vieta3SurfacePerm R
        (classicalSurfaceEquiv R x) := by
  apply Subtype.ext
  change classicalPointEquiv R
      (vieta3 (classicalZeroCoefficients R) x.1) =
    BGS.Markoff.vieta3 (classicalPointEquiv R x.1)
  ext <;>
    simp [classicalPointEquiv, vieta3, classicalZeroCoefficients,
      Coefficients.multiplier, BGS.Markoff.vieta3] <;>
    ring

/-- Every BGS Vieta-only word has a generalized Vieta word with the same
action under the explicit surface equivalence. -/
theorem exists_VietaGroup_lift_of_ClassicalBgsVietaGroup
    (h : ClassicalBgsVietaGroup R) :
    ∃ g : VietaGroup (classicalZeroCoefficients R),
      ∀ x : SolutionSurface (classicalZeroCoefficients R),
        classicalSurfaceEquiv R (g • x) =
          h • classicalSurfaceEquiv R x := by
  let motive :
      ∀ q : Equiv.Perm (BGS.Markoff.MarkoffSurface R),
        q ∈ Subgroup.closure (classicalBgsVietaGenerators R) → Prop :=
    fun q hq =>
      ∃ g : VietaGroup (classicalZeroCoefficients R),
        ∀ x : SolutionSurface (classicalZeroCoefficients R),
          classicalSurfaceEquiv R (g • x) =
            (⟨q, hq⟩ : ClassicalBgsVietaGroup R) •
              classicalSurfaceEquiv R x
  rcases h with ⟨h, hh⟩
  apply Subgroup.closure_induction (p := motive)
  · intro q hq
    simp only [classicalBgsVietaGenerators, Set.mem_insert_iff,
      Set.mem_singleton_iff] at hq
    rcases hq with rfl | rfl | rfl
    · refine ⟨vieta1InVietaGroup (classicalZeroCoefficients R), ?_⟩
      exact classicalSurfaceEquiv_vieta1 R
    · refine ⟨vieta2InVietaGroup (classicalZeroCoefficients R), ?_⟩
      exact classicalSurfaceEquiv_vieta2 R
    · refine ⟨vieta3InVietaGroup (classicalZeroCoefficients R), ?_⟩
      exact classicalSurfaceEquiv_vieta3 R
  · refine ⟨1, ?_⟩
    intro x
    change classicalSurfaceEquiv R
        ((1 : VietaGroup (classicalZeroCoefficients R)) • x) =
      (1 : ClassicalBgsVietaGroup R) • classicalSurfaceEquiv R x
    simp
  · intro q r hq hr hqLift hrLift
    obtain ⟨qR, hqR⟩ := hqLift
    obtain ⟨rR, hrR⟩ := hrLift
    refine ⟨qR * rR, ?_⟩
    intro x
    change classicalSurfaceEquiv R ((qR * rR) • x) =
      ((⟨q, hq⟩ : ClassicalBgsVietaGroup R) *
        (⟨r, hr⟩ : ClassicalBgsVietaGroup R)) •
          classicalSurfaceEquiv R x
    rw [mul_smul, mul_smul, hqR, hrR]
  · intro q hq hqLift
    obtain ⟨qR, hqR⟩ := hqLift
    refine ⟨qR⁻¹, ?_⟩
    intro x
    change classicalSurfaceEquiv R (qR⁻¹ • x) =
      (⟨q, hq⟩ : ClassicalBgsVietaGroup R)⁻¹ •
        classicalSurfaceEquiv R x
    have h := congrArg
      (fun y =>
        (⟨q, hq⟩ : ClassicalBgsVietaGroup R)⁻¹ • y)
      (hqR (qR⁻¹ • x))
    simpa [mul_smul] using h.symm

end Transport

/-- At every prime at which BGS strong approximation holds, the generalized
all-zero surface is transitive under the three Vieta moves alone. -/
theorem classicalZero_vietaStrongApproximationAt_of_BGS
    (p : ℕ) (hp : p.Prime)
    (hBgs : BGS.Markoff.StrongApproximationAt p) :
    VietaStrongApproximationAt
      (classicalZeroCoefficients ℤ) p hp := by
  letI : Fact p.Prime := ⟨hp⟩
  letI : Fact (1 < p) := ⟨hp.one_lt⟩
  letI : Nontrivial (ZMod p) := ZMod.nontrivial p
  rw [VietaStrongApproximationAt]
  rw [modCoefficients_classicalZeroCoefficients p]
  intro x y
  let xBgs : BGS.Markoff.PuncturedMarkoffSurface (ZMod p) :=
    classicalPuncturedSurfaceEquiv (ZMod p) x
  let yBgs : BGS.Markoff.PuncturedMarkoffSurface (ZMod p) :=
    classicalPuncturedSurfaceEquiv (ZMod p) y
  have hGamma : BGS.Markoff.PuncturedMarkoffTransitiveAt p hp :=
    (BGS.Markoff.puncturedMarkoffTransitiveAt_iff_strongApproximationAt
      p hp).2 hBgs
  change
    (∀ x y : BGS.Markoff.PuncturedMarkoffSurface (ZMod p),
      ∃ g : BGS.Markoff.Gamma (ZMod p), g • x = y) at hGamma
  have hVietaTransitive :
      ∀ u v : BGS.Markoff.PuncturedMarkoffSurface (ZMod p),
        ∃ h : ClassicalBgsVietaGroup (ZMod p),
          h • u.1 = v.1 :=
    classicalBgsVieta_transitive_of_Gamma_transitive
      (R := ZMod p) hGamma
  have hvieta := hVietaTransitive xBgs yBgs
  rcases hvieta with ⟨h, hh⟩
  have hlift :=
    exists_VietaGroup_lift_of_ClassicalBgsVietaGroup (ZMod p) h
  rcases hlift with ⟨g, hg⟩
  refine ⟨g, ?_⟩
  apply Subtype.ext
  apply (classicalSurfaceEquiv (ZMod p)).injective
  calc
    classicalSurfaceEquiv (ZMod p) (g • x.1) =
        h • classicalSurfaceEquiv (ZMod p) x.1 := hg x.1
    _ = classicalSurfaceEquiv (ZMod p) y.1 := hh

/-- The classical all-zero coefficient triple satisfies eventual Vieta
strong approximation. -/
theorem classicalZero_eventuallyVietaStrongApproximation :
    EventuallyVietaStrongApproximation
      (classicalZeroCoefficients ℤ) := by
  obtain ⟨threshold, hBgs⟩ :=
    BGS.Markoff.eventually_strongApproximationAt
  refine ⟨threshold, ?_⟩
  intro p hp hpLarge
  exact classicalZero_vietaStrongApproximationAt_of_BGS
    p hp (hBgs p hp hpLarge)

/-- The all-zero integral coefficient triple is integrally nondegenerate. -/
theorem classicalZero_integrallyNondegenerate :
    IntegrallyNondegenerate (classicalZeroCoefficients ℤ) := by
  norm_num [IntegrallyNondegenerate, classicalZeroCoefficients,
    Coefficients.multiplier]

/-- By the already-proved eventual Vieta/rotation equivalence, the all-zero
triple also satisfies eventual rotation strong approximation. -/
theorem classicalZero_eventuallyRotationStrongApproximation :
    EventuallyRotationStrongApproximation
      (classicalZeroCoefficients ℤ) :=
  (IntegrallyNondegenerate.eventuallyRotationStrongApproximation_iff_eventuallyVietaStrongApproximation
    classicalZero_integrallyNondegenerate).mpr
      classicalZero_eventuallyVietaStrongApproximation

end GenMarkoff.General.Assembly
