import GenMarkoff.Assembly.RotationDivisibility
import GenMarkoff.General.Axis

/-!
# Collapsing Vieta parity at an odd fixed point

The rotation group is the even-word subgroup of the full Vieta group.  The
public theorem `mem_rotation_or_mul_vieta1_mem_rotation` gives the two parity
classes, represented by `1` and the first Vieta involution.  Consequently the
two classes collapse on the component of a point whenever its first Vieta
image already lies in the same rotation component.

The older divisibility module proves the parity decomposition for punctured
orbits, but the conjugation and involution lemmas used internally there are
private.  This file reuses its public parity theorem and reproduces only the
minimal surface-level involution calculation needed to expose a component
interface.  The coefficient triple remains fixed throughout.

Fixed points of any one of the three Vieta involutions suffice.  For a
`vieta2` fixed point, `rotation3` carries the first Vieta image back to the
point; for a `vieta3` fixed point, `rotation2` carries the point to its first
Vieta image.

There is a genuinely new arithmetic obstruction to obtaining such a fixed
point from every split `q ^ 2`-orbit in the unequal-coefficient setting.  On
the first-axis parametrization, put
`P = centeredFiberProduct a.a2 a.a3 u t`.  Away from `q ^ 2 = 1`, the
candidate-regular regime has `P ≠ 0`, and the centered formulas give

* `vieta3 : h ↦ P / h`;
* `vieta2 : h ↦ P / (q ^ 2 * h)`.

Both involutions send the actual rotation coset
`h * zpowers (q ^ 2)` to `(P / h) * zpowers (q ^ 2)`.  Hence that coset is
reflection-stable exactly when `P / h ^ 2 ∈ zpowers (q ^ 2)`.  If the
membership exponent is even, the coset contains a `vieta3` fixed point; if it
is odd, it contains a `vieta2` fixed point.  In particular, when `q` is
primitive, `zpowers (q ^ 2)` is the square subgroup and the criterion is
equivalent to `P` being a square.  For nonprimitive `q`, squareness of `P`
alone is insufficient.

Pointwise, `vieta3` fixes `h` exactly when `h ^ 2 = P`, while `vieta2` fixes
it exactly when `(q * h) ^ 2 = P`.  Splitness of the eigenvalue only says
that `discriminant t` is a square and does not force `P` to be a square for
unequal coefficients.  For example, over `ZMod 5`, the data
`a = (1, 0, 4)`, `q = 2`, `t = 0`, and `u = 2` give multiplier `3`,
discriminant `1`, and `P = 3`, a nonsquare.  Hence no unconditional
adjacent-Vieta-fixed-point theorem for every primitive split `q ^ 2`-orbit is
stated here.
-/

namespace GenMarkoff.General.Assembly

universe u

private abbrev SurfacePerm
    {R : Type u} [CommRing R] (a : Coefficients R) :=
  Equiv.Perm (SolutionSurface a)

/-- Connectivity under the full group generated by the individual Vieta
involutions. -/
def SameVietaComponent
    {R : Type u} [CommRing R] {a : Coefficients R}
    (x y : SolutionSurface a) : Prop :=
  ∃ g : VietaGroup a, g • x = y

/-- The full Vieta orbit of a solution-surface point. -/
def surfaceVietaOrbit
    {R : Type u} [CommRing R] {a : Coefficients R}
    (x : SolutionSurface a) : Set (SolutionSurface a) :=
  MulAction.orbit (VietaGroup a) x

/-- The rotation orbit of a solution-surface point. -/
def surfaceRotationOrbit
    {R : Type u} [CommRing R] {a : Coefficients R}
    (x : SolutionSurface a) : Set (SolutionSurface a) :=
  MulAction.orbit (RotationGroup a) x

/-- If the odd representative `vieta1 x` is already rotation-reachable from
`x`, then every full Vieta move from `x` is a rotation move. -/
theorem
    sameRotationComponent_of_sameVietaComponent_of_vieta1_reachable
    {R : Type u} [CommRing R] {a : Coefficients R}
    {x y : SolutionSurface a}
    (hodd :
      SameRotationComponent x (vieta1SurfacePerm a x))
    (hxy : SameVietaComponent x y) :
    SameRotationComponent x y := by
  obtain ⟨r, hr⟩ := hodd
  obtain ⟨g, hgx⟩ := hxy
  have hr' :
      (r : SurfacePerm a) x = vieta1SurfacePerm a x := by
    simpa only [Subgroup.smul_def, Equiv.Perm.smul_def] using hr
  have hgx' : (g : SurfacePerm a) x = y := by
    simpa only [Subgroup.smul_def, Equiv.Perm.smul_def] using hgx
  rcases mem_rotation_or_mul_vieta1_mem_rotation a g with hg | hg
  · let h : RotationGroup a := ⟨g, hg⟩
    exact
      ⟨h, by
        simpa only [Subgroup.smul_def, Equiv.Perm.smul_def] using hgx'⟩
  · let h : RotationGroup a :=
      ⟨(g : SurfacePerm a) * vieta1SurfacePerm a, hg⟩
    let k : RotationGroup a := h * r
    refine ⟨k, ?_⟩
    simp only [Subgroup.smul_def, Equiv.Perm.smul_def]
    change
      (((g : SurfacePerm a) * vieta1SurfacePerm a) *
          (r : SurfacePerm a)) x = y
    rw [Equiv.Perm.mul_apply, Equiv.Perm.mul_apply, hr']
    have hvv :
        vieta1SurfacePerm a (vieta1SurfacePerm a x) = x := by
      apply Subtype.ext
      exact vieta1_involutive a x.1
    rw [hvv, hgx']

/-- Rotation connectivity always implies Vieta connectivity because the
rotation group is a subgroup of the Vieta group. -/
theorem sameVietaComponent_of_sameRotationComponent
    {R : Type u} [CommRing R] {a : Coefficients R}
    {x y : SolutionSurface a}
    (hxy : SameRotationComponent x y) :
    SameVietaComponent x y := by
  obtain ⟨r, hr⟩ := hxy
  let g : VietaGroup a :=
    ⟨r, RotationGroup_le_VietaGroup a r.2⟩
  exact
    ⟨g, by
      simpa only [Subgroup.smul_def, Equiv.Perm.smul_def] using hr⟩

/-- Component equality once the odd parity representative is
rotation-reachable. -/
theorem
    sameVietaComponent_iff_sameRotationComponent_of_vieta1_reachable
    {R : Type u} [CommRing R] {a : Coefficients R}
    {x y : SolutionSurface a}
    (hodd :
      SameRotationComponent x (vieta1SurfacePerm a x)) :
    SameVietaComponent x y ↔ SameRotationComponent x y :=
  ⟨sameRotationComponent_of_sameVietaComponent_of_vieta1_reachable hodd,
    sameVietaComponent_of_sameRotationComponent⟩

/-- Full Vieta connectivity is symmetric. -/
theorem sameVietaComponent_symm
    {R : Type u} [CommRing R] {a : Coefficients R}
    {x y : SolutionSurface a}
    (hxy : SameVietaComponent x y) :
    SameVietaComponent y x := by
  obtain ⟨g, rfl⟩ := hxy
  exact ⟨g⁻¹, inv_smul_smul g x⟩

/-- Equality of full Vieta and rotation orbits once the odd parity
representative is rotation-reachable. -/
theorem surfaceVietaOrbit_eq_surfaceRotationOrbit_of_vieta1_reachable
    {R : Type u} [CommRing R] {a : Coefficients R}
    {x : SolutionSurface a}
    (hodd :
      SameRotationComponent x (vieta1SurfacePerm a x)) :
    surfaceVietaOrbit x = surfaceRotationOrbit x := by
  ext y
  change SameVietaComponent x y ↔ SameRotationComponent x y
  exact
    sameVietaComponent_iff_sameRotationComponent_of_vieta1_reachable hodd

/-- A first-Vieta fixed point makes the odd parity representative trivial. -/
theorem vieta1_reachable_of_vieta1_fixed
    {R : Type u} [CommRing R] {a : Coefficients R}
    {x : SolutionSurface a}
    (hfix : vieta1SurfacePerm a x = x) :
    SameRotationComponent x (vieta1SurfacePerm a x) := by
  rw [hfix]
  exact sameRotationComponent_refl x

/-- At a second-Vieta fixed point, `rotation3 = vieta2 * vieta1` carries the
first-Vieta image back to the point.  This is the new adjacent-generator
observation needed when the fixed odd generator is not the chosen parity
representative. -/
theorem vieta1_reachable_of_vieta2_fixed
    {R : Type u} [CommRing R] {a : Coefficients R}
    {x : SolutionSurface a}
    (hfix : vieta2SurfacePerm a x = x) :
    SameRotationComponent x (vieta1SurfacePerm a x) := by
  apply sameRotationComponent_symm
  let r : RotationGroup a :=
    ⟨rotation3SurfacePerm a,
      rotation3SurfacePerm_mem_RotationGroup a⟩
  refine ⟨r, ?_⟩
  simp only [Subgroup.smul_def, Equiv.Perm.smul_def]
  apply Subtype.ext
  change vieta2 a (vieta1 a (vieta1 a x.1)) = x.1
  rw [vieta1_involutive]
  exact congrArg Subtype.val hfix

/-- At a third-Vieta fixed point, `rotation2 = vieta1 * vieta3` carries the
point to its first-Vieta image. -/
theorem vieta1_reachable_of_vieta3_fixed
    {R : Type u} [CommRing R] {a : Coefficients R}
    {x : SolutionSurface a}
    (hfix : vieta3SurfacePerm a x = x) :
    SameRotationComponent x (vieta1SurfacePerm a x) := by
  have hfix' : vieta3 a x.1 = x.1 :=
    congrArg Subtype.val hfix
  let r : RotationGroup a :=
    ⟨rotation2SurfacePerm a,
      rotation2SurfacePerm_mem_RotationGroup a⟩
  refine ⟨r, ?_⟩
  simp only [Subgroup.smul_def, Equiv.Perm.smul_def]
  apply Subtype.ext
  change vieta1 a (vieta3 a x.1) = vieta1 a x.1
  rw [hfix']

/-- At a first-Vieta fixed point, full Vieta and rotation connectivity
coincide. -/
theorem sameVietaComponent_iff_sameRotationComponent_of_vieta1_fixed
    {R : Type u} [CommRing R] {a : Coefficients R}
    {x y : SolutionSurface a}
    (hfix : vieta1SurfacePerm a x = x) :
    SameVietaComponent x y ↔ SameRotationComponent x y :=
  sameVietaComponent_iff_sameRotationComponent_of_vieta1_reachable
    (vieta1_reachable_of_vieta1_fixed hfix)

/-- At a second-Vieta fixed point, full Vieta and rotation connectivity
coincide. -/
theorem sameVietaComponent_iff_sameRotationComponent_of_vieta2_fixed
    {R : Type u} [CommRing R] {a : Coefficients R}
    {x y : SolutionSurface a}
    (hfix : vieta2SurfacePerm a x = x) :
    SameVietaComponent x y ↔ SameRotationComponent x y :=
  sameVietaComponent_iff_sameRotationComponent_of_vieta1_reachable
    (vieta1_reachable_of_vieta2_fixed hfix)

/-- At a third-Vieta fixed point, full Vieta and rotation connectivity
coincide. -/
theorem sameVietaComponent_iff_sameRotationComponent_of_vieta3_fixed
    {R : Type u} [CommRing R] {a : Coefficients R}
    {x y : SolutionSurface a}
    (hfix : vieta3SurfacePerm a x = x) :
    SameVietaComponent x y ↔ SameRotationComponent x y :=
  sameVietaComponent_iff_sameRotationComponent_of_vieta1_reachable
    (vieta1_reachable_of_vieta3_fixed hfix)

/-- A full-Vieta path ending at a first-Vieta fixed point is already a
rotation path. -/
theorem sameRotationComponent_of_sameVietaComponent_to_vieta1_fixed
    {R : Type u} [CommRing R] {a : Coefficients R}
    {x y : SolutionSurface a}
    (hfix : vieta1SurfacePerm a x = x)
    (hyx : SameVietaComponent y x) :
    SameRotationComponent y x := by
  apply sameRotationComponent_symm
  exact
    (sameVietaComponent_iff_sameRotationComponent_of_vieta1_fixed hfix).mp
      (sameVietaComponent_symm hyx)

/-- A full-Vieta path ending at a second-Vieta fixed point is already a
rotation path. -/
theorem sameRotationComponent_of_sameVietaComponent_to_vieta2_fixed
    {R : Type u} [CommRing R] {a : Coefficients R}
    {x y : SolutionSurface a}
    (hfix : vieta2SurfacePerm a x = x)
    (hyx : SameVietaComponent y x) :
    SameRotationComponent y x := by
  apply sameRotationComponent_symm
  exact
    (sameVietaComponent_iff_sameRotationComponent_of_vieta2_fixed hfix).mp
      (sameVietaComponent_symm hyx)

/-- A full-Vieta path ending at a third-Vieta fixed point is already a
rotation path. -/
theorem sameRotationComponent_of_sameVietaComponent_to_vieta3_fixed
    {R : Type u} [CommRing R] {a : Coefficients R}
    {x y : SolutionSurface a}
    (hfix : vieta3SurfacePerm a x = x)
    (hyx : SameVietaComponent y x) :
    SameRotationComponent y x := by
  apply sameRotationComponent_symm
  exact
    (sameVietaComponent_iff_sameRotationComponent_of_vieta3_fixed hfix).mp
      (sameVietaComponent_symm hyx)

/-- At a first-Vieta fixed point, the full Vieta orbit equals the rotation
orbit. -/
theorem surfaceVietaOrbit_eq_surfaceRotationOrbit_of_vieta1_fixed
    {R : Type u} [CommRing R] {a : Coefficients R}
    {x : SolutionSurface a}
    (hfix : vieta1SurfacePerm a x = x) :
    surfaceVietaOrbit x = surfaceRotationOrbit x :=
  surfaceVietaOrbit_eq_surfaceRotationOrbit_of_vieta1_reachable
    (vieta1_reachable_of_vieta1_fixed hfix)

/-- At a second-Vieta fixed point, the full Vieta orbit equals the rotation
orbit. -/
theorem surfaceVietaOrbit_eq_surfaceRotationOrbit_of_vieta2_fixed
    {R : Type u} [CommRing R] {a : Coefficients R}
    {x : SolutionSurface a}
    (hfix : vieta2SurfacePerm a x = x) :
    surfaceVietaOrbit x = surfaceRotationOrbit x :=
  surfaceVietaOrbit_eq_surfaceRotationOrbit_of_vieta1_reachable
    (vieta1_reachable_of_vieta2_fixed hfix)

/-- At a third-Vieta fixed point, the full Vieta orbit equals the rotation
orbit. -/
theorem surfaceVietaOrbit_eq_surfaceRotationOrbit_of_vieta3_fixed
    {R : Type u} [CommRing R] {a : Coefficients R}
    {x : SolutionSurface a}
    (hfix : vieta3SurfacePerm a x = x) :
    surfaceVietaOrbit x = surfaceRotationOrbit x :=
  surfaceVietaOrbit_eq_surfaceRotationOrbit_of_vieta1_reachable
    (vieta1_reachable_of_vieta3_fixed hfix)

end GenMarkoff.General.Assembly
