import BGS.Markoff.Incidence.Fibers
import Mathlib.FieldTheory.KummerPolynomial
import Mathlib.RingTheory.TensorProduct.MvPolynomial
import Mathlib.RingTheory.TensorProduct.Quotient

/-!
# Geometric integrality of the incidence auxiliary coordinate ring

This module proves the missing coordinate-ring algebra by an explicit base change and rank-four
biquadratic normal form.  Every declaration is proved; there are no placeholder axioms.
-/

namespace BGS.Markoff

open MvPolynomial
open scoped TensorProduct

noncomputable section

universe u v

variable (K : Type u) [Field K]
variable (L : Type v) [Field L] [Algebra K L]

/-- The explicit two-equation ideal after extending coefficients from `K` to `L`. -/
def incidenceAuxBaseChangeIdeal (a b : K) : Ideal (MvPolynomial (Fin 3) L) :=
  Ideal.span
    {MvPolynomial.map (algebraMap K L) (incidenceAuxPolynomial1 a),
      MvPolynomial.map (algebraMap K L) (incidenceAuxPolynomial2 b)}

lemma incidenceAuxBaseChangeIdeal_eq_map (a b : K) :
    incidenceAuxBaseChangeIdeal K L a b =
      (incidenceAuxIdeal a b).map
        (MvPolynomial.map (σ := Fin 3) (algebraMap K L)) := by
  simp only [incidenceAuxBaseChangeIdeal, incidenceAuxIdeal, Ideal.map_span,
    Set.image_insert_eq, Set.image_singleton]

lemma incidenceAuxBaseChangeIdeal_eq_incidenceAuxIdeal (a b : K) :
    incidenceAuxBaseChangeIdeal K L a b =
      incidenceAuxIdeal (algebraMap K L a) (algebraMap K L b) := by
  simp [incidenceAuxBaseChangeIdeal, incidenceAuxIdeal, incidenceAuxPolynomial1,
    incidenceAuxPolynomial2, map_sub, map_mul, map_pow, map_ofNat]

lemma algebraTensorAlgEquiv_comp_includeRight :
    (MvPolynomial.algebraTensorAlgEquiv (σ := Fin 3) K L).toRingHom.comp
        (Algebra.TensorProduct.includeRight (R := K) (A := L)).toRingHom =
      MvPolynomial.map (σ := Fin 3) (algebraMap K L) := by
  apply MvPolynomial.ringHom_ext
  · intro r
    simp [RingHom.comp_apply]
  · intro i
    simp [RingHom.comp_apply]

/-- Base change commutes with the explicit presentation of the incidence auxiliary curve. -/
noncomputable def incidenceAuxCoordinateRingBaseChangeEquiv (a b : K) :
    L ⊗[K] IncidenceAuxCoordinateRing K a b ≃ₐ[L]
      MvPolynomial (Fin 3) L ⧸ incidenceAuxBaseChangeIdeal K L a b :=
  (Algebra.TensorProduct.tensorQuotientEquiv
      (R := K) L (MvPolynomial (Fin 3) K) L (incidenceAuxIdeal a b)).trans
    (Ideal.quotientEquivAlg
      ((incidenceAuxIdeal a b).map
        (Algebra.TensorProduct.includeRight (R := K) (A := L)).toRingHom)
      (incidenceAuxBaseChangeIdeal K L a b)
      (MvPolynomial.algebraTensorAlgEquiv (σ := Fin 3) K L)
      (by
        rw [incidenceAuxBaseChangeIdeal_eq_map]
        rw [Ideal.map_map]
        congr 1
        exact (algebraTensorAlgEquiv_comp_includeRight K L).symm))

/-- Base change identifies the original coordinate ring with the same two equations over the
larger coefficient field. -/
noncomputable def incidenceAuxCoordinateRingBaseChangeExplicitEquiv (a b : K) :
    L ⊗[K] IncidenceAuxCoordinateRing K a b ≃ₐ[L]
      IncidenceAuxCoordinateRing L (algebraMap K L a) (algebraMap K L b) :=
  (incidenceAuxCoordinateRingBaseChangeEquiv K L a b).trans
    (Ideal.quotientEquivAlgOfEq L
      (incidenceAuxBaseChangeIdeal_eq_incidenceAuxIdeal K L a b))

/-- The monic quadratic used to adjoin a square root of an element. -/
def adjoinSquarePolynomial {R : Type*} [CommRing R] (f : R) : Polynomial R :=
  Polynomial.X ^ 2 - Polynomial.C f

lemma adjoinSquarePolynomial_monic {R : Type*} [CommRing R] (f : R) :
    (adjoinSquarePolynomial f).Monic := by
  exact Polynomial.monic_X_pow_sub_C f (by norm_num)

lemma adjoinSquarePolynomial_natDegree {R : Type*} [Nontrivial R] [CommRing R] (f : R) :
    (adjoinSquarePolynomial f).natDegree = 2 := by
  simp [adjoinSquarePolynomial]

lemma adjoinSquareRoot_sq {R : Type*} [CommRing R] (f : R) :
    (AdjoinRoot.root (adjoinSquarePolynomial f)) ^ 2 =
      algebraMap R (AdjoinRoot (adjoinSquarePolynomial f)) f := by
  have h := AdjoinRoot.eval₂_root (adjoinSquarePolynomial f)
  rw [adjoinSquarePolynomial, Polynomial.eval₂_sub, Polynomial.eval₂_pow,
    Polynomial.eval₂_X, Polynomial.eval₂_C, sub_eq_zero] at h
  exact h

lemma adjoinSquarePolynomial_irreducible_of_not_isSquare
    {F : Type*} [Field F] {f : F} (hf : ¬ IsSquare f) :
    Irreducible (adjoinSquarePolynomial f) := by
  apply X_pow_sub_C_irreducible_of_prime Nat.prime_two
  intro z hz
  apply hf
  exact ⟨z, by simpa [pow_two] using hz.symm⟩

/-- In a quadratic extension generated by `sqrt f`, a base-field element `g` can become a
square only if `g` or `f * g` was already a square. -/
lemma not_isSquare_algebraMap_adjoinSquare_of_independent
    {F : Type*} [Field F] (h2 : (2 : F) ≠ 0) {f g : F}
    (hf : ¬ IsSquare f) (hg : ¬ IsSquare g) (hfg : ¬ IsSquare (f * g)) :
    ¬ IsSquare
      (algebraMap F (AdjoinRoot (adjoinSquarePolynomial f)) g) := by
  let q : Polynomial F := adjoinSquarePolynomial f
  have hqIrreducible : Irreducible q :=
    adjoinSquarePolynomial_irreducible_of_not_isSquare hf
  letI : Fact (Irreducible q) := ⟨hqIrreducible⟩
  change ¬ IsSquare (algebraMap F (AdjoinRoot q) g)
  have hqMonic : q.Monic := by simpa [q] using adjoinSquarePolynomial_monic f
  have hqNatDegree : q.natDegree = 2 := by
    simpa [q] using adjoinSquarePolynomial_natDegree f
  let b : Module.Basis (Fin 2) F (AdjoinRoot q) :=
    (AdjoinRoot.powerBasis' hqMonic).basis.reindex (finCongr hqNatDegree)
  rintro ⟨z, hzSquare⟩
  let x : F := b.repr z 0
  let y : F := b.repr z 1
  have hb0 : b 0 = 1 := by
    simp [b, PowerBasis.coe_basis]
  have hb1 : b 1 = AdjoinRoot.root q := by
    simp [b, PowerBasis.coe_basis]
  have hz : z = algebraMap F (AdjoinRoot q) x +
      algebraMap F (AdjoinRoot q) y * AdjoinRoot.root q := by
    have hsum := b.sum_repr z
    rw [Fin.sum_univ_two] at hsum
    simpa [hb0, hb1, x, y, Algebra.smul_def] using hsum.symm
  have hroot : (AdjoinRoot.root q) ^ 2 = algebraMap F (AdjoinRoot q) f := by
    simpa [q] using adjoinSquareRoot_sq f
  have hexpand :
      algebraMap F (AdjoinRoot q) g =
        algebraMap F (AdjoinRoot q) (x * x + y * y * f) +
          algebraMap F (AdjoinRoot q) (2 * x * y) * AdjoinRoot.root q := by
    rw [hzSquare, hz]
    calc
      (algebraMap F (AdjoinRoot q) x +
          algebraMap F (AdjoinRoot q) y * AdjoinRoot.root q) *
          (algebraMap F (AdjoinRoot q) x +
            algebraMap F (AdjoinRoot q) y * AdjoinRoot.root q) =
        algebraMap F (AdjoinRoot q) x * algebraMap F (AdjoinRoot q) x +
          2 * algebraMap F (AdjoinRoot q) x * algebraMap F (AdjoinRoot q) y *
            AdjoinRoot.root q +
          algebraMap F (AdjoinRoot q) y * algebraMap F (AdjoinRoot q) y *
            (AdjoinRoot.root q) ^ 2 := by ring
      _ = _ := by
        rw [hroot]
        simp only [map_add, map_mul, map_ofNat]
        ring
  have hbasisExpression :
      g • b 0 = (x * x + y * y * f) • b 0 + (2 * x * y) • b 1 := by
    simpa [hb0, hb1, Algebra.smul_def] using hexpand
  have hconstant := congrArg (b.coord 0) hbasisExpression
  have hlinear := congrArg (b.coord 1) hbasisExpression
  have hgExpression : g = x * x + y * y * f := by
    simpa using hconstant
  have hxy : x * y = 0 := by
    have htwoXY : (2 : F) * (x * y) = 0 := by
      simpa [mul_assoc] using hlinear.symm
    exact (mul_eq_zero.mp htwoXY).resolve_left h2
  rcases mul_eq_zero.mp hxy with hx | hy
  · apply hfg
    refine ⟨y * f, ?_⟩
    rw [hgExpression, hx]
    ring
  · apply hg
    refine ⟨x, ?_⟩
    rw [hgExpression, hy]
    ring

/-- Extend coefficients in a quadratic `AdjoinRoot` presentation. -/
def adjoinSquareMap {R S : Type*} [CommRing R] [CommRing S]
    (φ : R →+* S) (f : R) :
    AdjoinRoot (adjoinSquarePolynomial f) →+*
      AdjoinRoot (adjoinSquarePolynomial (φ f)) :=
  AdjoinRoot.map φ (adjoinSquarePolynomial f) (adjoinSquarePolynomial (φ f))
    (by simp [adjoinSquarePolynomial])

/-- Extending coefficients in a monic quadratic presentation preserves injectivity. -/
lemma adjoinSquareMap_injective {R S : Type*} [CommRing R] [CommRing S]
    [Nontrivial R] [Nontrivial S] (φ : R →+* S) (hφ : Function.Injective φ) (f : R) :
    Function.Injective (adjoinSquareMap φ f) := by
  let qR : Polynomial R := adjoinSquarePolynomial f
  let qS : Polynomial S := adjoinSquarePolynomial (φ f)
  have hqRMonic : qR.Monic := by simpa [qR] using adjoinSquarePolynomial_monic f
  have hqSMonic : qS.Monic := by simpa [qS] using adjoinSquarePolynomial_monic (φ f)
  have hqRNatDegree : qR.natDegree = 2 := by
    simpa [qR] using adjoinSquarePolynomial_natDegree f
  have hqSNatDegree : qS.natDegree = 2 := by
    simpa [qS] using adjoinSquarePolynomial_natDegree (φ f)
  let bR : Module.Basis (Fin 2) R (AdjoinRoot qR) :=
    (AdjoinRoot.powerBasis' hqRMonic).basis.reindex (finCongr hqRNatDegree)
  let bS : Module.Basis (Fin 2) S (AdjoinRoot qS) :=
    (AdjoinRoot.powerBasis' hqSMonic).basis.reindex (finCongr hqSNatDegree)
  have hbR0 : bR 0 = 1 := by simp [bR, PowerBasis.coe_basis]
  have hbR1 : bR 1 = AdjoinRoot.root qR := by simp [bR, PowerBasis.coe_basis]
  have hbS0 : bS 0 = 1 := by simp [bS, PowerBasis.coe_basis]
  have hbS1 : bS 1 = AdjoinRoot.root qS := by simp [bS, PowerBasis.coe_basis]
  rw [injective_iff_map_eq_zero]
  intro z hzMap
  let x : R := bR.repr z 0
  let y : R := bR.repr z 1
  have hz : z = algebraMap R (AdjoinRoot qR) x +
      algebraMap R (AdjoinRoot qR) y * AdjoinRoot.root qR := by
    have hsum := bR.sum_repr z
    rw [Fin.sum_univ_two] at hsum
    simpa [hbR0, hbR1, x, y, Algebra.smul_def] using hsum.symm
  have htarget :
      algebraMap S (AdjoinRoot qS) (φ x) +
          algebraMap S (AdjoinRoot qS) (φ y) * AdjoinRoot.root qS = 0 := by
    rw [hz] at hzMap
    simpa [adjoinSquareMap, qR, qS] using hzMap
  have hbasisTarget : φ x • bS 0 + φ y • bS 1 = 0 := by
    simpa [hbS0, hbS1, Algebra.smul_def] using htarget
  have hxMap := congrArg (bS.coord 0) hbasisTarget
  have hyMap := congrArg (bS.coord 1) hbasisTarget
  have hx : x = 0 := hφ (by simpa using hxMap)
  have hy : y = 0 := hφ (by simpa using hyMap)
  rw [hz, hx, hy]
  simp

/-- Adjoin the first branch square root over the polynomial ring in the `y`-coordinate. -/
abbrev IncidenceFirstQuadraticRing (a : L) :=
  AdjoinRoot (adjoinSquarePolynomial (incidenceBranchPolynomial a))

noncomputable local instance incidenceFirstQuadraticRing_nontrivial (a : L) :
    Nontrivial (IncidenceFirstQuadraticRing L a) :=
  AdjoinRoot.nontrivial _ (by
    rw [Polynomial.degree_eq_natDegree (adjoinSquarePolynomial_monic _).ne_zero,
      adjoinSquarePolynomial_natDegree]
    norm_num)

/-- Over the first quadratic cover, adjoin the second branch square root. -/
def incidenceSecondQuadraticPolynomial (a b : L) :
    Polynomial (IncidenceFirstQuadraticRing L a) :=
  adjoinSquarePolynomial
    (algebraMap (Polynomial L) (IncidenceFirstQuadraticRing L a)
      (incidenceBranchPolynomial b))

/-- The iterated quadratic algebra with generators satisfying the two incidence equations. -/
abbrev IncidenceBiquadraticRing (a b : L) :=
  AdjoinRoot (incidenceSecondQuadraticPolynomial L a b)

/-- The first quadratic extension after passing from `L[y]` to its rational function field. -/
abbrev IncidenceFirstQuadraticRatFuncRing (a : L) :=
  AdjoinRoot
    (adjoinSquarePolynomial
      (algebraMap (Polynomial L) (RatFunc L) (incidenceBranchPolynomial a)))

noncomputable local instance incidenceFirstQuadraticRatFuncRing_nontrivial (a : L) :
    Nontrivial (IncidenceFirstQuadraticRatFuncRing L a) :=
  AdjoinRoot.nontrivial _ (by
    rw [Polynomial.degree_eq_natDegree (adjoinSquarePolynomial_monic _).ne_zero,
      adjoinSquarePolynomial_natDegree]
    norm_num)

/-- Extend the first quadratic cover from `L[y]` to `L(y)`. -/
def incidenceFirstQuadraticToRatFunc (a : L) :
    IncidenceFirstQuadraticRing L a →+* IncidenceFirstQuadraticRatFuncRing L a :=
  adjoinSquareMap (algebraMap (Polynomial L) (RatFunc L))
    (incidenceBranchPolynomial a)

lemma incidenceFirstQuadraticToRatFunc_algebraMap (a : L) (r : Polynomial L) :
    incidenceFirstQuadraticToRatFunc L a
        (algebraMap (Polynomial L) (IncidenceFirstQuadraticRing L a) r) =
      algebraMap (RatFunc L) (IncidenceFirstQuadraticRatFuncRing L a)
        (algebraMap (Polynomial L) (RatFunc L) r) := by
  simp [incidenceFirstQuadraticToRatFunc, adjoinSquareMap]

/-- The second quadratic polynomial over the first rational-function-field extension. -/
def incidenceSecondQuadraticRatFuncPolynomial (a b : L) :
    Polynomial (IncidenceFirstQuadraticRatFuncRing L a) :=
  adjoinSquarePolynomial
    (incidenceFirstQuadraticToRatFunc L a
      (algebraMap (Polynomial L) (IncidenceFirstQuadraticRing L a)
        (incidenceBranchPolynomial b)))

/-- The biquadratic field presentation over `L(y)`.  Field instances are installed below from
the two irreducibility proofs. -/
abbrev IncidenceBiquadraticRatFuncRing (a b : L) :=
  AdjoinRoot (incidenceSecondQuadraticRatFuncPolynomial L a b)

/-- Extend both successive quadratic presentations from `L[y]` to `L(y)`. -/
def incidenceBiquadraticToRatFunc (a b : L) :
    IncidenceBiquadraticRing L a b →+* IncidenceBiquadraticRatFuncRing L a b :=
  adjoinSquareMap (incidenceFirstQuadraticToRatFunc L a)
    (algebraMap (Polynomial L) (IncidenceFirstQuadraticRing L a)
      (incidenceBranchPolynomial b))

lemma incidenceFirstQuadraticToRatFunc_injective (a : L) :
    Function.Injective (incidenceFirstQuadraticToRatFunc L a) := by
  exact adjoinSquareMap_injective _
    (FaithfulSMul.algebraMap_injective (Polynomial L) (RatFunc L)) _

lemma incidenceBiquadraticToRatFunc_injective (a b : L) :
    Function.Injective (incidenceBiquadraticToRatFunc L a b) := by
  exact adjoinSquareMap_injective _ (incidenceFirstQuadraticToRatFunc_injective L a) _

/-- The rational-function-field biquadratic presentation is a domain when the three square
classes supplied by the branch-polynomial calculation are nontrivial. -/
theorem incidenceBiquadraticRatFuncRing_isDomain
    (h2 : (2 : L) ≠ 0) {a b : L}
    (ha : a ≠ 0) (hb : b ≠ 0)
    (hA : 9 * a ^ 2 - 4 ≠ 0) (hB : 9 * b ^ 2 - 4 ≠ 0)
    (hab : a ^ 2 ≠ b ^ 2) :
    IsDomain (IncidenceBiquadraticRatFuncRing L a b) := by
  obtain ⟨hf, hg, hfg⟩ :=
    incidenceBranchSquareClasses_independent_ratFunc h2 ha hb hA hB hab
  have h2RatFunc : (2 : RatFunc L) ≠ 0 := by
    intro hzero
    apply h2
    apply FaithfulSMul.algebraMap_injective L (RatFunc L)
    simpa only [map_ofNat, map_zero] using hzero
  letI : Fact
      (Irreducible
        (adjoinSquarePolynomial
          (algebraMap (Polynomial L) (RatFunc L) (incidenceBranchPolynomial a)))) :=
    ⟨adjoinSquarePolynomial_irreducible_of_not_isSquare hf⟩
  have hsecondNotSquare :
      ¬ IsSquare
        (incidenceFirstQuadraticToRatFunc L a
          (algebraMap (Polynomial L) (IncidenceFirstQuadraticRing L a)
            (incidenceBranchPolynomial b))) := by
    rw [incidenceFirstQuadraticToRatFunc_algebraMap]
    apply not_isSquare_algebraMap_adjoinSquare_of_independent h2RatFunc hf hg
    simpa only [map_mul] using hfg
  letI : Fact (Irreducible (incidenceSecondQuadraticRatFuncPolynomial L a b)) :=
    ⟨adjoinSquarePolynomial_irreducible_of_not_isSquare hsecondNotSquare⟩
  letI : Field (IncidenceBiquadraticRatFuncRing L a b) := AdjoinRoot.instField
  infer_instance

/-- The rank-four algebra over `L[y]` is a domain because it injects into the preceding
biquadratic field presentation. -/
theorem incidenceBiquadraticRing_isDomain
    (h2 : (2 : L) ≠ 0) {a b : L}
    (ha : a ≠ 0) (hb : b ≠ 0)
    (hA : 9 * a ^ 2 - 4 ≠ 0) (hB : 9 * b ^ 2 - 4 ≠ 0)
    (hab : a ^ 2 ≠ b ^ 2) :
    IsDomain (IncidenceBiquadraticRing L a b) := by
  letI : IsDomain (IncidenceBiquadraticRatFuncRing L a b) :=
    incidenceBiquadraticRatFuncRing_isDomain L h2 ha hb hA hB hab
  exact (incidenceBiquadraticToRatFunc_injective L a b).isDomain
    (incidenceBiquadraticToRatFunc L a b)

lemma incidenceSecondQuadraticPolynomial_monic (a b : L) :
    (incidenceSecondQuadraticPolynomial L a b).Monic := by
  exact adjoinSquarePolynomial_monic _

lemma incidenceSecondQuadraticPolynomial_natDegree (a b : L) :
    (incidenceSecondQuadraticPolynomial L a b).natDegree = 2 := by
  exact adjoinSquarePolynomial_natDegree _

/-- The canonical product basis of the two successive monic quadratic extensions. -/
noncomputable def incidenceBiquadraticTowerBasis (a b : L) :
    Module.Basis
      (Fin (adjoinSquarePolynomial (incidenceBranchPolynomial a)).natDegree ×
        Fin (incidenceSecondQuadraticPolynomial L a b).natDegree)
      (Polynomial L) (IncidenceBiquadraticRing L a b) :=
  (AdjoinRoot.powerBasis' (adjoinSquarePolynomial_monic
      (incidenceBranchPolynomial a))).basis.smulTower
    (AdjoinRoot.powerBasis' (incidenceSecondQuadraticPolynomial_monic L a b)).basis

/-- The unreduced two-equation algebra has the expected rank four over `L[y]`. -/
theorem incidenceBiquadraticRing_finrank (a b : L) :
    Module.finrank (Polynomial L) (IncidenceBiquadraticRing L a b) = 4 := by
  rw [Module.finrank_eq_card_basis (incidenceBiquadraticTowerBasis L a b)]
  simp [adjoinSquarePolynomial_natDegree, incidenceSecondQuadraticPolynomial_natDegree]

lemma incidenceFirstQuadraticRoot_sq (a : L) :
    (AdjoinRoot.root
        (adjoinSquarePolynomial (incidenceBranchPolynomial a))) ^ 2 =
      algebraMap (Polynomial L) (IncidenceFirstQuadraticRing L a)
        (incidenceBranchPolynomial a) := by
  exact adjoinSquareRoot_sq _

lemma incidenceSecondQuadraticRoot_sq (a b : L) :
    (AdjoinRoot.root (incidenceSecondQuadraticPolynomial L a b)) ^ 2 =
      algebraMap (IncidenceFirstQuadraticRing L a) (IncidenceBiquadraticRing L a b)
        (algebraMap (Polynomial L) (IncidenceFirstQuadraticRing L a)
          (incidenceBranchPolynomial b)) := by
  exact adjoinSquareRoot_sq _

/-- The `y`-coordinate in the iterated quadratic presentation. -/
def incidenceBiquadraticY (a b : L) : IncidenceBiquadraticRing L a b :=
  algebraMap (Polynomial L) (IncidenceBiquadraticRing L a b) Polynomial.X

/-- The first square-root coordinate in the iterated quadratic presentation. -/
def incidenceBiquadraticLambda (a b : L) : IncidenceBiquadraticRing L a b :=
  algebraMap (IncidenceFirstQuadraticRing L a) (IncidenceBiquadraticRing L a b)
    (AdjoinRoot.root (adjoinSquarePolynomial (incidenceBranchPolynomial a)))

/-- The second square-root coordinate in the iterated quadratic presentation. -/
def incidenceBiquadraticMu (a b : L) : IncidenceBiquadraticRing L a b :=
  AdjoinRoot.root (incidenceSecondQuadraticPolynomial L a b)

/-- Evaluate the three-variable incidence presentation in the iterated quadratic algebra. -/
def incidenceAuxAevalToBiquadratic (a b : L) :
    MvPolynomial (Fin 3) L →ₐ[L] IncidenceBiquadraticRing L a b :=
  MvPolynomial.aeval ![incidenceBiquadraticY L a b,
    incidenceBiquadraticLambda L a b, incidenceBiquadraticMu L a b]

lemma incidenceAuxAevalToBiquadratic_polynomial1 (a b : L) :
    incidenceAuxAevalToBiquadratic L a b (incidenceAuxPolynomial1 a) = 0 := by
  simp only [incidenceAuxAevalToBiquadratic, incidenceAuxPolynomial1, map_sub, map_mul,
    map_pow, MvPolynomial.aeval_C, MvPolynomial.aeval_X]
  change
    ((algebraMap L (IncidenceBiquadraticRing L a b)) 9 *
          (algebraMap L (IncidenceBiquadraticRing L a b)) a ^ 2 -
        (algebraMap L (IncidenceBiquadraticRing L a b)) 4) *
        (incidenceBiquadraticY L a b) ^ 2 -
      (incidenceBiquadraticLambda L a b) ^ 2 -
      (algebraMap L (IncidenceBiquadraticRing L a b)) 4 *
        (algebraMap L (IncidenceBiquadraticRing L a b)) a ^ 2 = 0
  rw [show (incidenceBiquadraticLambda L a b) ^ 2 =
      algebraMap (Polynomial L) (IncidenceBiquadraticRing L a b)
        (incidenceBranchPolynomial a) by
    simp only [incidenceBiquadraticLambda]
    rw [← map_pow, incidenceFirstQuadraticRoot_sq]
    exact IsScalarTower.algebraMap_apply (Polynomial L)
      (IncidenceFirstQuadraticRing L a) (IncidenceBiquadraticRing L a b) _]
  simp only [incidenceBiquadraticY, incidenceBranchPolynomial]
  simp [map_sub, map_mul, map_pow,
    IsScalarTower.algebraMap_apply L (Polynomial L) (IncidenceBiquadraticRing L a b)]

lemma incidenceAuxAevalToBiquadratic_polynomial2 (a b : L) :
    incidenceAuxAevalToBiquadratic L a b (incidenceAuxPolynomial2 b) = 0 := by
  simp only [incidenceAuxAevalToBiquadratic, incidenceAuxPolynomial2, map_sub, map_mul,
    map_pow, MvPolynomial.aeval_C, MvPolynomial.aeval_X]
  change
    ((algebraMap L (IncidenceBiquadraticRing L a b)) 9 *
          (algebraMap L (IncidenceBiquadraticRing L a b)) b ^ 2 -
        (algebraMap L (IncidenceBiquadraticRing L a b)) 4) *
        (incidenceBiquadraticY L a b) ^ 2 -
      (incidenceBiquadraticMu L a b) ^ 2 -
      (algebraMap L (IncidenceBiquadraticRing L a b)) 4 *
        (algebraMap L (IncidenceBiquadraticRing L a b)) b ^ 2 = 0
  rw [show (incidenceBiquadraticMu L a b) ^ 2 =
      algebraMap (Polynomial L) (IncidenceBiquadraticRing L a b)
        (incidenceBranchPolynomial b) by
    simp only [incidenceBiquadraticMu]
    rw [incidenceSecondQuadraticRoot_sq]
    exact IsScalarTower.algebraMap_apply (Polynomial L)
      (IncidenceFirstQuadraticRing L a) (IncidenceBiquadraticRing L a b) _]
  simp only [incidenceBiquadraticY, incidenceBranchPolynomial]
  simp [map_sub, map_mul, map_pow,
    IsScalarTower.algebraMap_apply L (Polynomial L) (IncidenceBiquadraticRing L a b)]

lemma incidenceAuxIdeal_le_aevalToBiquadratic_ker (a b : L) :
    incidenceAuxIdeal a b ≤
      RingHom.ker (incidenceAuxAevalToBiquadratic L a b).toRingHom := by
  rw [incidenceAuxIdeal, Ideal.span_le]
  rintro p (rfl | hp)
  · exact incidenceAuxAevalToBiquadratic_polynomial1 L a b
  · rw [Set.mem_singleton_iff.mp hp]
    exact incidenceAuxAevalToBiquadratic_polynomial2 L a b

/-- The canonical map from the explicit coordinate-ring quotient to the iterated quadratic
normal form. -/
def incidenceAuxCoordinateRingToBiquadratic (a b : L) :
    IncidenceAuxCoordinateRing L a b →ₐ[L] IncidenceBiquadraticRing L a b :=
  Ideal.Quotient.liftₐ (incidenceAuxIdeal a b)
    (incidenceAuxAevalToBiquadratic L a b)
    (fun _p hp => incidenceAuxIdeal_le_aevalToBiquadratic_ker L a b hp)

lemma incidenceBiquadraticY_mem_aeval_range (a b : L) :
    incidenceBiquadraticY L a b ∈ (incidenceAuxAevalToBiquadratic L a b).range := by
  refine ⟨MvPolynomial.X 0, ?_⟩
  simp [incidenceAuxAevalToBiquadratic]

lemma incidenceBiquadraticLambda_mem_aeval_range (a b : L) :
    incidenceBiquadraticLambda L a b ∈
      (incidenceAuxAevalToBiquadratic L a b).range := by
  refine ⟨MvPolynomial.X 1, ?_⟩
  simp [incidenceAuxAevalToBiquadratic]

lemma incidenceBiquadraticMu_mem_aeval_range (a b : L) :
    incidenceBiquadraticMu L a b ∈ (incidenceAuxAevalToBiquadratic L a b).range := by
  refine ⟨MvPolynomial.X 2, ?_⟩
  simp [incidenceAuxAevalToBiquadratic]

lemma polynomialAlgebraMap_mem_incidenceAevalRange (a b : L) (r : Polynomial L) :
    algebraMap (Polynomial L) (IncidenceBiquadraticRing L a b) r ∈
      (incidenceAuxAevalToBiquadratic L a b).range := by
  induction r using Polynomial.induction_on' with
  | add p q hp hq =>
      rw [map_add]
      exact Subalgebra.add_mem _ hp hq
  | monomial n c =>
      have hy := incidenceBiquadraticY_mem_aeval_range L a b
      have hc := (incidenceAuxAevalToBiquadratic L a b).range.algebraMap_mem c
      rw [← Polynomial.C_mul_X_pow_eq_monomial, map_mul, map_pow]
      simpa [incidenceBiquadraticY,
        IsScalarTower.algebraMap_apply L (Polynomial L) (IncidenceBiquadraticRing L a b)]
        using Subalgebra.mul_mem _ hc (Subalgebra.pow_mem _ hy n)

lemma firstQuadraticAlgebraMap_mem_incidenceAevalRange (a b : L)
    (s : IncidenceFirstQuadraticRing L a) :
    algebraMap (IncidenceFirstQuadraticRing L a) (IncidenceBiquadraticRing L a b) s ∈
      (incidenceAuxAevalToBiquadratic L a b).range := by
  induction s using AdjoinRoot.induction_on with
  | ih p =>
      induction p using Polynomial.induction_on' with
      | add p q hp hq =>
          simpa only [map_add] using Subalgebra.add_mem _ hp hq
      | monomial n r =>
          have hr := polynomialAlgebraMap_mem_incidenceAevalRange L a b r
          have hlambda := incidenceBiquadraticLambda_mem_aeval_range L a b
          have heq :
              algebraMap (IncidenceFirstQuadraticRing L a)
                  (IncidenceBiquadraticRing L a b)
                  (AdjoinRoot.mk
                    (adjoinSquarePolynomial (incidenceBranchPolynomial a))
                    (Polynomial.monomial n r)) =
                algebraMap (Polynomial L) (IncidenceBiquadraticRing L a b) r *
                  (incidenceBiquadraticLambda L a b) ^ n := by
            rw [← AdjoinRoot.aeval_eq, ← Polynomial.C_mul_X_pow_eq_monomial]
            simp [incidenceBiquadraticLambda,
              IsScalarTower.algebraMap_apply (Polynomial L)
                (IncidenceFirstQuadraticRing L a) (IncidenceBiquadraticRing L a b)]
          rw [heq]
          exact Subalgebra.mul_mem _ hr (Subalgebra.pow_mem _ hlambda n)

lemma incidenceAuxAevalToBiquadratic_surjective (a b : L) :
    Function.Surjective (incidenceAuxAevalToBiquadratic L a b) := by
  rw [← AlgHom.range_eq_top]
  apply Algebra.eq_top_iff.mpr
  intro t
  induction t using AdjoinRoot.induction_on with
  | ih p =>
      induction p using Polynomial.induction_on' with
      | add p q hp hq =>
          simpa only [map_add] using Subalgebra.add_mem _ hp hq
      | monomial n s =>
          have hs := firstQuadraticAlgebraMap_mem_incidenceAevalRange L a b s
          have hmu := incidenceBiquadraticMu_mem_aeval_range L a b
          have heq :
              AdjoinRoot.mk (incidenceSecondQuadraticPolynomial L a b)
                  (Polynomial.monomial n s) =
                algebraMap (IncidenceFirstQuadraticRing L a)
                    (IncidenceBiquadraticRing L a b) s *
                  (incidenceBiquadraticMu L a b) ^ n := by
            rw [← AdjoinRoot.aeval_eq, ← Polynomial.C_mul_X_pow_eq_monomial]
            simp [incidenceBiquadraticMu]
          rw [heq]
          exact Subalgebra.mul_mem _ hs (Subalgebra.pow_mem _ hmu n)

lemma incidenceAuxCoordinateRingToBiquadratic_surjective (a b : L) :
    Function.Surjective (incidenceAuxCoordinateRingToBiquadratic L a b) := by
  intro t
  obtain ⟨p, rfl⟩ := incidenceAuxAevalToBiquadratic_surjective L a b t
  exact ⟨Ideal.Quotient.mk (incidenceAuxIdeal a b) p, rfl⟩

/-- The class of one of the three coordinate variables in the auxiliary coordinate ring. -/
def incidenceAuxCoordinateClass (a b : L) (i : Fin 3) :
    IncidenceAuxCoordinateRing L a b :=
  Ideal.Quotient.mk (incidenceAuxIdeal a b) (MvPolynomial.X i)

/-- The polynomial algebra in `y` maps to the auxiliary coordinate ring by sending `X` to the
class of the `y`-coordinate. -/
def incidenceAuxPolynomialAlgebraMap (a b : L) :
    Polynomial L →ₐ[L] IncidenceAuxCoordinateRing L a b :=
  Polynomial.aeval (incidenceAuxCoordinateClass L a b 0)

lemma incidenceAuxPolynomial1_class_eq_zero (a b : L) :
    Ideal.Quotient.mk (incidenceAuxIdeal a b) (incidenceAuxPolynomial1 a) = 0 := by
  rw [Ideal.Quotient.eq_zero_iff_mem]
  exact Ideal.subset_span (by simp)

lemma incidenceAuxPolynomial2_class_eq_zero (a b : L) :
    Ideal.Quotient.mk (incidenceAuxIdeal a b) (incidenceAuxPolynomial2 b) = 0 := by
  rw [Ideal.Quotient.eq_zero_iff_mem]
  exact Ideal.subset_span (by simp)

lemma incidenceAuxLambdaClass_sq (a b : L) :
    (incidenceAuxCoordinateClass L a b 1) ^ 2 =
      incidenceAuxPolynomialAlgebraMap L a b (incidenceBranchPolynomial a) := by
  have h := incidenceAuxPolynomial1_class_eq_zero L a b
  simp only [incidenceAuxPolynomial1, map_sub, map_mul, map_pow] at h
  simp only [incidenceAuxPolynomialAlgebraMap, incidenceBranchPolynomial,
    map_sub, map_mul, map_pow, Polynomial.aeval_C, Polynomial.aeval_X]
  change
    (incidenceAuxCoordinateClass L a b 1) ^ 2 =
      ((algebraMap L (IncidenceAuxCoordinateRing L a b)) 9 *
          (algebraMap L (IncidenceAuxCoordinateRing L a b)) a ^ 2 -
        (algebraMap L (IncidenceAuxCoordinateRing L a b)) 4) *
        (incidenceAuxCoordinateClass L a b 0) ^ 2 -
      (algebraMap L (IncidenceAuxCoordinateRing L a b)) 4 *
        (algebraMap L (IncidenceAuxCoordinateRing L a b)) a ^ 2
  change
    ((algebraMap L (IncidenceAuxCoordinateRing L a b)) 9 *
          (algebraMap L (IncidenceAuxCoordinateRing L a b)) a ^ 2 -
        (algebraMap L (IncidenceAuxCoordinateRing L a b)) 4) *
          (incidenceAuxCoordinateClass L a b 0) ^ 2 -
        (incidenceAuxCoordinateClass L a b 1) ^ 2 -
      (algebraMap L (IncidenceAuxCoordinateRing L a b)) 4 *
        (algebraMap L (IncidenceAuxCoordinateRing L a b)) a ^ 2 = 0 at h
  linear_combination -h

lemma incidenceAuxMuClass_sq (a b : L) :
    (incidenceAuxCoordinateClass L a b 2) ^ 2 =
      incidenceAuxPolynomialAlgebraMap L a b (incidenceBranchPolynomial b) := by
  have h := incidenceAuxPolynomial2_class_eq_zero L a b
  simp only [incidenceAuxPolynomial2, map_sub, map_mul, map_pow] at h
  simp only [incidenceAuxPolynomialAlgebraMap, incidenceBranchPolynomial,
    map_sub, map_mul, map_pow, Polynomial.aeval_C, Polynomial.aeval_X]
  change
    (incidenceAuxCoordinateClass L a b 2) ^ 2 =
      ((algebraMap L (IncidenceAuxCoordinateRing L a b)) 9 *
          (algebraMap L (IncidenceAuxCoordinateRing L a b)) b ^ 2 -
        (algebraMap L (IncidenceAuxCoordinateRing L a b)) 4) *
        (incidenceAuxCoordinateClass L a b 0) ^ 2 -
      (algebraMap L (IncidenceAuxCoordinateRing L a b)) 4 *
        (algebraMap L (IncidenceAuxCoordinateRing L a b)) b ^ 2
  change
    ((algebraMap L (IncidenceAuxCoordinateRing L a b)) 9 *
          (algebraMap L (IncidenceAuxCoordinateRing L a b)) b ^ 2 -
        (algebraMap L (IncidenceAuxCoordinateRing L a b)) 4) *
          (incidenceAuxCoordinateClass L a b 0) ^ 2 -
        (incidenceAuxCoordinateClass L a b 2) ^ 2 -
      (algebraMap L (IncidenceAuxCoordinateRing L a b)) 4 *
        (algebraMap L (IncidenceAuxCoordinateRing L a b)) b ^ 2 = 0 at h
  linear_combination -h

/-- Map the first quadratic extension back to the explicit coordinate ring. -/
def incidenceFirstQuadraticToAuxCoordinateRing (a b : L) :
    IncidenceFirstQuadraticRing L a →ₐ[L] IncidenceAuxCoordinateRing L a b :=
  AdjoinRoot.liftAlgHom
    (adjoinSquarePolynomial (incidenceBranchPolynomial a))
    (incidenceAuxPolynomialAlgebraMap L a b)
    (incidenceAuxCoordinateClass L a b 1)
    (by
      simp [adjoinSquarePolynomial, incidenceAuxLambdaClass_sq])

/-- Map the iterated quadratic normal form back to the explicit coordinate ring. -/
def incidenceBiquadraticToAuxCoordinateRing (a b : L) :
    IncidenceBiquadraticRing L a b →ₐ[L] IncidenceAuxCoordinateRing L a b :=
  AdjoinRoot.liftAlgHom
    (incidenceSecondQuadraticPolynomial L a b)
    (incidenceFirstQuadraticToAuxCoordinateRing L a b)
    (incidenceAuxCoordinateClass L a b 2)
    (by
      simp only [incidenceSecondQuadraticPolynomial, adjoinSquarePolynomial,
        Polynomial.eval₂_sub, Polynomial.eval₂_pow, Polynomial.eval₂_X,
        Polynomial.eval₂_C]
      rw [incidenceAuxMuClass_sq]
      change
        incidenceAuxPolynomialAlgebraMap L a b (incidenceBranchPolynomial b) -
          incidenceFirstQuadraticToAuxCoordinateRing L a b
            (AdjoinRoot.of
              (adjoinSquarePolynomial (incidenceBranchPolynomial a))
              (incidenceBranchPolynomial b)) = 0
      rw [incidenceFirstQuadraticToAuxCoordinateRing, AdjoinRoot.liftAlgHom_of]
      exact sub_self _)

@[simp]
lemma incidenceAuxCoordinateRingToBiquadratic_coordinateClass (a b : L) (i : Fin 3) :
    incidenceAuxCoordinateRingToBiquadratic L a b
        (incidenceAuxCoordinateClass L a b i) =
      ![incidenceBiquadraticY L a b, incidenceBiquadraticLambda L a b,
        incidenceBiquadraticMu L a b] i := by
  simp [incidenceAuxCoordinateRingToBiquadratic, incidenceAuxCoordinateClass,
    incidenceAuxAevalToBiquadratic]

@[simp]
lemma incidenceBiquadraticToAuxCoordinateRing_y (a b : L) :
    incidenceBiquadraticToAuxCoordinateRing L a b (incidenceBiquadraticY L a b) =
      incidenceAuxCoordinateClass L a b 0 := by
  rw [incidenceBiquadraticY,
    IsScalarTower.algebraMap_apply (Polynomial L) (IncidenceFirstQuadraticRing L a)
      (IncidenceBiquadraticRing L a b)]
  simp [incidenceBiquadraticToAuxCoordinateRing,
    incidenceFirstQuadraticToAuxCoordinateRing, incidenceAuxPolynomialAlgebraMap]

@[simp]
lemma incidenceBiquadraticToAuxCoordinateRing_lambda (a b : L) :
    incidenceBiquadraticToAuxCoordinateRing L a b
        (incidenceBiquadraticLambda L a b) =
      incidenceAuxCoordinateClass L a b 1 := by
  simp [incidenceBiquadraticToAuxCoordinateRing, incidenceBiquadraticLambda,
    incidenceFirstQuadraticToAuxCoordinateRing]

@[simp]
lemma incidenceBiquadraticToAuxCoordinateRing_mu (a b : L) :
    incidenceBiquadraticToAuxCoordinateRing L a b (incidenceBiquadraticMu L a b) =
      incidenceAuxCoordinateClass L a b 2 := by
  simp [incidenceBiquadraticToAuxCoordinateRing, incidenceBiquadraticMu]

lemma incidenceBiquadraticToAux_comp_auxToBiquadratic (a b : L) :
    (incidenceBiquadraticToAuxCoordinateRing L a b).comp
        (incidenceAuxCoordinateRingToBiquadratic L a b) =
      AlgHom.id L (IncidenceAuxCoordinateRing L a b) := by
  apply Ideal.Quotient.algHom_ext L
  apply MvPolynomial.algHom_ext
  intro i
  fin_cases i
  · change incidenceBiquadraticToAuxCoordinateRing L a b
      (incidenceAuxCoordinateRingToBiquadratic L a b
        (incidenceAuxCoordinateClass L a b 0)) = incidenceAuxCoordinateClass L a b 0
    rw [incidenceAuxCoordinateRingToBiquadratic_coordinateClass]
    exact incidenceBiquadraticToAuxCoordinateRing_y L a b
  · change incidenceBiquadraticToAuxCoordinateRing L a b
      (incidenceAuxCoordinateRingToBiquadratic L a b
        (incidenceAuxCoordinateClass L a b 1)) = incidenceAuxCoordinateClass L a b 1
    rw [incidenceAuxCoordinateRingToBiquadratic_coordinateClass]
    exact incidenceBiquadraticToAuxCoordinateRing_lambda L a b
  · change incidenceBiquadraticToAuxCoordinateRing L a b
      (incidenceAuxCoordinateRingToBiquadratic L a b
        (incidenceAuxCoordinateClass L a b 2)) = incidenceAuxCoordinateClass L a b 2
    rw [incidenceAuxCoordinateRingToBiquadratic_coordinateClass]
    exact incidenceBiquadraticToAuxCoordinateRing_mu L a b

lemma incidenceAuxToBiquadratic_comp_biquadraticToAux (a b : L) :
    (incidenceAuxCoordinateRingToBiquadratic L a b).comp
        (incidenceBiquadraticToAuxCoordinateRing L a b) =
      AlgHom.id L (IncidenceBiquadraticRing L a b) := by
  apply AdjoinRoot.algHom_ext'
  · apply AdjoinRoot.algHom_ext'
    · apply Polynomial.algHom_ext
      change incidenceAuxCoordinateRingToBiquadratic L a b
        (incidenceBiquadraticToAuxCoordinateRing L a b
          (algebraMap (IncidenceFirstQuadraticRing L a)
            (IncidenceBiquadraticRing L a b)
            (algebraMap (Polynomial L) (IncidenceFirstQuadraticRing L a) Polynomial.X))) = _
      rw [show algebraMap (IncidenceFirstQuadraticRing L a)
          (IncidenceBiquadraticRing L a b)
          (algebraMap (Polynomial L) (IncidenceFirstQuadraticRing L a) Polynomial.X) =
          incidenceBiquadraticY L a b by
        exact (IsScalarTower.algebraMap_apply (Polynomial L)
          (IncidenceFirstQuadraticRing L a) (IncidenceBiquadraticRing L a b) _).symm]
      rw [incidenceBiquadraticToAuxCoordinateRing_y]
      rw [incidenceAuxCoordinateRingToBiquadratic_coordinateClass]
      exact IsScalarTower.algebraMap_apply (Polynomial L)
        (IncidenceFirstQuadraticRing L a) (IncidenceBiquadraticRing L a b) _
    · change incidenceAuxCoordinateRingToBiquadratic L a b
        (incidenceBiquadraticToAuxCoordinateRing L a b
          (incidenceBiquadraticLambda L a b)) = incidenceBiquadraticLambda L a b
      rw [incidenceBiquadraticToAuxCoordinateRing_lambda]
      rw [incidenceAuxCoordinateRingToBiquadratic_coordinateClass]
      simp
  · change incidenceAuxCoordinateRingToBiquadratic L a b
      (incidenceBiquadraticToAuxCoordinateRing L a b
        (incidenceBiquadraticMu L a b)) = incidenceBiquadraticMu L a b
    rw [incidenceBiquadraticToAuxCoordinateRing_mu]
    rw [incidenceAuxCoordinateRingToBiquadratic_coordinateClass]
    simp

/-- The two-equation coordinate quotient is exactly the rank-four iterated quadratic algebra. -/
noncomputable def incidenceAuxCoordinateRingEquivBiquadratic (a b : L) :
    IncidenceAuxCoordinateRing L a b ≃ₐ[L] IncidenceBiquadraticRing L a b :=
  AlgEquiv.ofAlgHom
    (incidenceAuxCoordinateRingToBiquadratic L a b)
    (incidenceBiquadraticToAuxCoordinateRing L a b)
    (incidenceAuxToBiquadratic_comp_biquadraticToAux L a b)
    (incidenceBiquadraticToAux_comp_auxToBiquadratic L a b)

/-- The explicit two-equation coordinate quotient is a domain under the off-diagonal
nondegeneracy hypotheses. -/
theorem incidenceAuxCoordinateRing_isDomain
    (h2 : (2 : L) ≠ 0) {a b : L}
    (ha : a ≠ 0) (hb : b ≠ 0)
    (hA : 9 * a ^ 2 - 4 ≠ 0) (hB : 9 * b ^ 2 - 4 ≠ 0)
    (hab : a ^ 2 ≠ b ^ 2) :
    IsDomain (IncidenceAuxCoordinateRing L a b) := by
  letI : IsDomain (IncidenceBiquadraticRing L a b) :=
    incidenceBiquadraticRing_isDomain L h2 ha hb hA hB hab
  exact (incidenceAuxCoordinateRingEquivBiquadratic L a b).injective.isDomain
    (incidenceAuxCoordinateRingEquivBiquadratic L a b).toRingEquiv.toRingHom

/-- The actual geometric-integrality statement follows after explicit scalar extension to the
algebraic closure; no irreducibility assertion is hidden in a structure field. -/
theorem incidenceAuxGeometricallyIntegral_of_nondegenerate
    {K : Type*} [Field K] (h2 : (2 : K) ≠ 0) {a b : K}
    (ha : a ≠ 0) (hb : b ≠ 0)
    (hA : 9 * a ^ 2 - 4 ≠ 0) (hB : 9 * b ^ 2 - 4 ≠ 0)
    (hab : a ^ 2 ≠ b ^ 2) :
    IncidenceAuxGeometricallyIntegral a b := by
  let L := AlgebraicClosure K
  have hmapNeZero {x : K} (hx : x ≠ 0) : algebraMap K L x ≠ 0 := by
    intro hzero
    apply hx
    apply FaithfulSMul.algebraMap_injective K L
    simpa only [map_zero] using hzero
  have h2L : (2 : L) ≠ 0 := by
    simpa only [map_ofNat] using hmapNeZero h2
  have haL : algebraMap K L a ≠ 0 := hmapNeZero ha
  have hbL : algebraMap K L b ≠ 0 := hmapNeZero hb
  have hAL : 9 * (algebraMap K L a) ^ 2 - 4 ≠ 0 := by
    simpa only [map_sub, map_mul, map_pow, map_ofNat] using hmapNeZero hA
  have hBL : 9 * (algebraMap K L b) ^ 2 - 4 ≠ 0 := by
    simpa only [map_sub, map_mul, map_pow, map_ofNat] using hmapNeZero hB
  have habL : (algebraMap K L a) ^ 2 ≠ (algebraMap K L b) ^ 2 := by
    intro heq
    apply hab
    apply FaithfulSMul.algebraMap_injective K L
    simpa only [map_pow] using heq
  letI : IsDomain
      (IncidenceAuxCoordinateRing L (algebraMap K L a) (algebraMap K L b)) :=
    incidenceAuxCoordinateRing_isDomain L h2L haL hbL hAL hBL habL
  exact (incidenceAuxCoordinateRingBaseChangeExplicitEquiv K L a b).injective.isDomain
    (incidenceAuxCoordinateRingBaseChangeExplicitEquiv K L a b).toRingEquiv.toRingHom

/-- Specialization to the paper's admissible off-diagonal coordinates.  The threshold `3` only
excludes characteristic two; no large-prime estimate is used in this geometric step. -/
theorem incidenceAux_offDiagonal_geometricallyIntegral :
    ∃ p0 : ℕ, ∀ (p : ℕ) (hp : p.Prime), p0 ≤ p →
      IncidenceAuxOffDiagonalGeometryAt p hp := by
  refine ⟨3, ?_⟩
  intro p hp hpLarge
  letI : Fact p.Prime := ⟨hp⟩
  intro a b ha hb hab
  apply incidenceAuxGeometricallyIntegral_of_nondegenerate
  · exact two_ne_zero_zmod (by omega)
  · exact ha.1
  · exact hb.1
  · intro hzero
    apply ha.2
    calc
      (3 * a) ^ 2 = 9 * a ^ 2 := by ring
      _ = 4 := sub_eq_zero.mp hzero
  · intro hzero
    apply hb.2
    calc
      (3 * b) ^ 2 = 9 * b ^ 2 := by ring
      _ = 4 := sub_eq_zero.mp hzero
  · exact hab

end

end BGS.Markoff
