import BGS.Markoff.Endgame.PrimitiveTraceCount
import BGS.Markoff.MiddleGame.DivisorRange
import Mathlib.NumberTheory.ArithmeticFunction.Moebius

/-!
# Möbius inclusion--exclusion for primitive endgame traces

This file formalizes published equations (35)--(36).  For a fixed left power-map image and a
finite cyclic right group, it partitions trace coincidences by the exact order of the right-hand
element, applies Möbius inversion, and identifies the cumulative order-divisibility count with the
corresponding right power-map image.
-/

namespace BGS.Markoff

open scoped ArithmeticFunction.Moebius BigOperators
open Filter

noncomputable section

variable {G H T : Type*} [CommGroup G] [CommGroup H]

/-- In a finite cyclic group, the image of the `d`-th power map is the kernel of the
`(card / d)`-th power map whenever `d` divides the group order. -/
theorem powMonoidHom_range_eq_ker_complementaryExponent
    [Finite H] [IsCyclic H] (d : ℕ) (hdvd : d ∣ Nat.card H) :
    (powMonoidHom d : H →* H).range =
      (powMonoidHom (Nat.card H / d) : H →* H).ker := by
  letI := Fintype.ofFinite H
  apply Subgroup.eq_of_le_of_card_ge
  · rintro y ⟨x, rfl⟩
    change (x ^ d) ^ (Nat.card H / d) = 1
    rw [← pow_mul, Nat.mul_div_cancel' hdvd, Nat.card_eq_fintype_card, pow_card_eq_one]
  · rw [IsCyclic.card_powMonoidHom_ker, IsCyclic.card_powMonoidHom_range]
    rw [Nat.gcd_eq_right (Nat.div_dvd_of_dvd hdvd)]
    rw [Nat.gcd_eq_right hdvd]

/-- In a finite cyclic group, the image of the complementary power map is exactly the cyclic
subgroup generated by the element whose order defines that complementary exponent.  This is
the bridge between the endgame count, which is naturally stated on a power-map image, and the
rotation orbit, which is naturally stated as `Subgroup.zpowers w`. -/
theorem powMonoidHom_range_eq_zpowers_of_complementaryOrder
    {K : Type*} [CommGroup K] [Finite K] [IsCyclic K] (w : K) :
    (powMonoidHom (Nat.card K / orderOf w) : K →* K).range =
      Subgroup.zpowers w := by
  let n := Nat.card K
  let m := orderOf w
  let e := n / m
  have hn : 0 < n := Nat.card_pos
  have hm : 0 < m := orderOf_pos w
  have hmDvd : m ∣ n := orderOf_dvd_natCard w
  have hmLe : m ≤ n := Nat.le_of_dvd hn hmDvd
  have he : 0 < e := Nat.div_pos hmLe hm
  have heDvd : e ∣ n := Nat.div_dvd_of_dvd hmDvd
  have hComplement : n / e = m := by
    apply (Nat.div_eq_iff_eq_mul_right he heDvd).2
    exact (Nat.div_mul_cancel hmDvd).symm
  symm
  apply Subgroup.eq_of_le_of_card_ge
  · rw [Subgroup.zpowers_le]
    rw [powMonoidHom_range_eq_ker_complementaryExponent (H := K) e heDvd]
    change w ^ (n / e) = 1
    rw [hComplement]
    exact pow_orderOf_eq_one w
  · rw [Nat.card_zpowers, IsCyclic.card_powMonoidHom_range]
    change n / n.gcd e ≤ m
    rw [Nat.gcd_eq_right_iff_dvd.mpr heDvd, hComplement]

/-- All trace coincidences with the left coordinate restricted to one power-map image. -/
noncomputable def traceRelationPairs
    [Finite G] [Finite H]
    (leftTrace : G → T) (rightTrace : H → T) (leftExponent : ℕ) :
    Finset ((powMonoidHom leftExponent : G →* G).range × H) := by
  classical
  letI := Fintype.ofFinite G
  letI := Fintype.ofFinite H
  exact Finset.univ.filter fun z => leftTrace z.1 = rightTrace z.2

/-- Trace coincidences whose right coordinate has one exact multiplicative order. -/
noncomputable def traceExactOrderSolutions
    [Finite G] [Finite H]
    (leftTrace : G → T) (rightTrace : H → T) (leftExponent order : ℕ) :
    Finset ((powMonoidHom leftExponent : G →* G).range × H) := by
  classical
  exact (traceRelationPairs leftTrace rightTrace leftExponent).filter fun z =>
    orderOf z.2 = order

/-- Trace coincidences whose right coordinate is killed by one power. -/
noncomputable def tracePowerKernelSolutions
    [Finite G] [Finite H]
    (leftTrace : G → T) (rightTrace : H → T) (leftExponent exponent : ℕ) :
    Finset ((powMonoidHom leftExponent : G →* G).range × H) := by
  classical
  exact (traceRelationPairs leftTrace rightTrace leftExponent).filter fun z =>
    z.2 ^ exponent = 1

@[simp]
theorem mem_traceExactOrderSolutions_iff
    [Finite G] [Finite H]
    (leftTrace : G → T) (rightTrace : H → T) (leftExponent order : ℕ)
    (z : (powMonoidHom leftExponent : G →* G).range × H) :
    z ∈ traceExactOrderSolutions leftTrace rightTrace leftExponent order ↔
      leftTrace z.1 = rightTrace z.2 ∧ orderOf z.2 = order := by
  classical
  simp [traceExactOrderSolutions, traceRelationPairs]

@[simp]
theorem mem_tracePowerKernelSolutions_iff
    [Finite G] [Finite H]
    (leftTrace : G → T) (rightTrace : H → T) (leftExponent exponent : ℕ)
    (z : (powMonoidHom leftExponent : G →* G).range × H) :
    z ∈ tracePowerKernelSolutions leftTrace rightTrace leftExponent exponent ↔
      leftTrace z.1 = rightTrace z.2 ∧ z.2 ^ exponent = 1 := by
  classical
  simp [tracePowerKernelSolutions, traceRelationPairs]

/-- Exact-order classes partition the trace coincidences killed by the `m`-th power map. -/
theorem sum_traceExactOrderSolutions_card_eq_tracePowerKernelSolutions_card
    [Finite G] [Finite H]
    (leftTrace : G → T) (rightTrace : H → T) (leftExponent m : ℕ) (hm : 0 < m) :
    ∑ order ∈ m.divisors,
        (traceExactOrderSolutions leftTrace rightTrace leftExponent order).card =
      (tracePowerKernelSolutions leftTrace rightTrace leftExponent m).card := by
  classical
  simp only [traceExactOrderSolutions]
  rw [Finset.sum_card_fiberwise_eq_card_filter]
  apply congrArg Finset.card
  ext z
  simp [tracePowerKernelSolutions, Nat.mem_divisors, hm.ne',
    orderOf_dvd_iff_pow_eq_one]

/-- Möbius inversion recovers the exact-order trace count from the power-kernel counts. -/
theorem moebius_sum_tracePowerKernelSolutions_card_eq_traceExactOrderSolutions_card
    [Finite G] [Finite H]
    (leftTrace : G → T) (rightTrace : H → T) (leftExponent n : ℕ) (hn : 0 < n) :
    ∑ x ∈ n.divisorsAntidiagonal,
        (μ x.fst : ℤ) *
          (tracePowerKernelSolutions leftTrace rightTrace leftExponent x.snd).card =
      (traceExactOrderSolutions leftTrace rightTrace leftExponent n).card := by
  have hinversion :=
    (ArithmeticFunction.sum_eq_iff_sum_mul_moebius_eq
      (R := ℤ)
      (f := fun order =>
        ((traceExactOrderSolutions leftTrace rightTrace leftExponent order).card : ℤ))
      (g := fun exponent =>
        ((tracePowerKernelSolutions leftTrace rightTrace leftExponent exponent).card : ℤ))).mp
      (fun m hm => by
        exact_mod_cast
          sum_traceExactOrderSolutions_card_eq_tracePowerKernelSolutions_card
            leftTrace rightTrace leftExponent m hm)
  exact hinversion n hn

/-- A right power-range solution is a right power-kernel solution whenever the two subgroups are
identified. -/
def powerTraceRangeSolutionsEquivTracePowerKernelSolutions
    [Finite G] [Finite H]
    (leftTrace : G → T) (rightTrace : H → T) (leftExponent rightExponent kernelExponent : ℕ)
    (hsubgroup :
      (powMonoidHom rightExponent : H →* H).range =
        (powMonoidHom kernelExponent : H →* H).ker) :
    powerTraceRangeSolutions leftTrace rightTrace leftExponent rightExponent ≃
      ↥(tracePowerKernelSolutions leftTrace rightTrace leftExponent kernelExponent) where
  toFun z := ⟨(z.1.1, z.1.2.1), by
    rw [mem_tracePowerKernelSolutions_iff]
    refine ⟨z.2, ?_⟩
    have hzker : z.1.2.1 ∈ (powMonoidHom kernelExponent : H →* H).ker := by
      rw [← hsubgroup]
      exact z.1.2.2
    exact hzker⟩
  invFun z := ⟨(z.1.1, ⟨z.1.2, by
    rw [hsubgroup]
    exact (mem_tracePowerKernelSolutions_iff
      leftTrace rightTrace leftExponent kernelExponent z.1).mp z.2 |>.2⟩),
    (mem_tracePowerKernelSolutions_iff
      leftTrace rightTrace leftExponent kernelExponent z.1).mp z.2 |>.1⟩
  left_inv z := by rfl
  right_inv z := by rfl

/-- Cardinal form of `powerTraceRangeSolutionsEquivTracePowerKernelSolutions`. -/
theorem natCard_powerTraceRangeSolutions_eq_tracePowerKernelSolutions_card
    [Finite G] [Finite H]
    (leftTrace : G → T) (rightTrace : H → T) (leftExponent rightExponent kernelExponent : ℕ)
    (hsubgroup :
      (powMonoidHom rightExponent : H →* H).range =
        (powMonoidHom kernelExponent : H →* H).ker) :
    Nat.card (powerTraceRangeSolutions leftTrace rightTrace leftExponent rightExponent) =
      (tracePowerKernelSolutions leftTrace rightTrace leftExponent kernelExponent).card := by
  calc
    Nat.card (powerTraceRangeSolutions leftTrace rightTrace leftExponent rightExponent) =
        Nat.card ↥(tracePowerKernelSolutions leftTrace rightTrace
          leftExponent kernelExponent) :=
      Nat.card_congr
        (powerTraceRangeSolutionsEquivTracePowerKernelSolutions
          leftTrace rightTrace leftExponent rightExponent kernelExponent hsubgroup)
    _ = (tracePowerKernelSolutions leftTrace rightTrace
        leftExponent kernelExponent).card := by
      rw [Nat.card_eq_fintype_card, Fintype.card_coe]

/-- Published equation (35): the exact-order trace count is the Möbius-weighted sum of the
counts on right power-map images. -/
theorem moebius_sum_powerTraceRangeSolutions_card_eq_traceExactOrderSolutions_card
    [Finite G] [Finite H] [IsCyclic H]
    (leftTrace : G → T) (rightTrace : H → T) (leftExponent : ℕ) :
    ∑ x ∈ (Nat.card H).divisorsAntidiagonal,
        (μ x.fst : ℤ) *
          Nat.card (powerTraceRangeSolutions
            leftTrace rightTrace leftExponent x.fst) =
      (traceExactOrderSolutions
        leftTrace rightTrace leftExponent (Nat.card H)).card := by
  rw [← moebius_sum_tracePowerKernelSolutions_card_eq_traceExactOrderSolutions_card
    leftTrace rightTrace leftExponent (Nat.card H) Nat.card_pos]
  apply Finset.sum_congr rfl
  intro x hx
  congr 1
  have hproduct := (Nat.mem_divisorsAntidiagonal.mp hx).1
  have hleftNe : x.fst ≠ 0 := Nat.left_ne_zero_of_mem_divisorsAntidiagonal hx
  have hdvd : x.fst ∣ Nat.card H := ⟨x.snd, hproduct.symm⟩
  have hquotient : Nat.card H / x.fst = x.snd := by
    rw [← hproduct, Nat.mul_comm x.fst x.snd,
      Nat.mul_div_left x.snd (Nat.pos_of_ne_zero hleftNe)]
  rw [natCard_powerTraceRangeSolutions_eq_tracePowerKernelSolutions_card
    leftTrace rightTrace leftExponent x.fst x.snd]
  simpa [hquotient] using
    powMonoidHom_range_eq_ker_complementaryExponent (H := H) x.fst hdvd

/-- Swapping the two coordinates preserves a power-range trace equation. -/
def powerTraceRangeSolutionsSwapEquiv
    [Finite G] [Finite H]
    (leftTrace : G → T) (rightTrace : H → T) (leftExponent rightExponent : ℕ) :
    powerTraceRangeSolutions leftTrace rightTrace leftExponent rightExponent ≃
      powerTraceRangeSolutions rightTrace leftTrace rightExponent leftExponent where
  toFun z := ⟨(z.1.2, z.1.1), z.2.symm⟩
  invFun z := ⟨(z.1.2, z.1.1), z.2.symm⟩
  left_inv z := by rfl
  right_inv z := by rfl

theorem natCard_powerTraceRangeSolutions_swap
    [Finite G] [Finite H]
    (leftTrace : G → T) (rightTrace : H → T) (leftExponent rightExponent : ℕ) :
    Nat.card (powerTraceRangeSolutions leftTrace rightTrace leftExponent rightExponent) =
      Nat.card (powerTraceRangeSolutions rightTrace leftTrace rightExponent leftExponent) :=
  Nat.card_congr
    (powerTraceRangeSolutionsSwapEquiv leftTrace rightTrace leftExponent rightExponent)

/-- The number of divisor-antidiagonal pairs equals the number of divisors. -/
theorem card_divisorsAntidiagonal_eq_card_divisors (n : ℕ) :
    n.divisorsAntidiagonal.card = n.divisors.card := by
  simpa only [Finset.card_eq_sum_ones] using
    (Nat.sum_divisorsAntidiagonal (fun _ _ => (1 : ℕ)) (n := n))

/-- Summing individually bounded errors with Möbius coefficients costs at most the divisor count. -/
theorem abs_moebius_weighted_sum_sub_le_divisors_card_mul
    (n : ℕ) (count mainTerm : ℕ × ℕ → ℝ) (error : ℝ)
    (hterm : ∀ x ∈ n.divisorsAntidiagonal,
      |count x - mainTerm x| ≤ error) :
    |(∑ x ∈ n.divisorsAntidiagonal, (μ x.fst : ℝ) * count x) -
        ∑ x ∈ n.divisorsAntidiagonal, (μ x.fst : ℝ) * mainTerm x| ≤
      (n.divisors.card : ℝ) * error := by
  let s := n.divisorsAntidiagonal
  have hrewrite :
      (∑ x ∈ s, (μ x.fst : ℝ) * count x) -
          ∑ x ∈ s, (μ x.fst : ℝ) * mainTerm x =
        ∑ x ∈ s, (μ x.fst : ℝ) * (count x - mainTerm x) := by
    rw [← Finset.sum_sub_distrib]
    apply Finset.sum_congr rfl
    intro x hx
    ring
  rw [hrewrite]
  calc
    |∑ x ∈ s, (μ x.fst : ℝ) * (count x - mainTerm x)| ≤
        ∑ x ∈ s, |(μ x.fst : ℝ) * (count x - mainTerm x)| :=
      Finset.abs_sum_le_sum_abs _ _
    _ ≤ ∑ _x ∈ s, error := by
      apply Finset.sum_le_sum
      intro x hx
      rw [abs_mul]
      have hmu : |(μ x.fst : ℝ)| ≤ 1 := by
        exact_mod_cast ArithmeticFunction.abs_moebius_le_one (n := x.fst)
      calc
        |(μ x.fst : ℝ)| * |count x - mainTerm x| ≤ 1 * error :=
          mul_le_mul hmu (hterm x hx) (abs_nonneg _) zero_le_one
        _ = error := one_mul error
    _ = (s.card : ℝ) * error := by simp
    _ = (n.divisors.card : ℝ) * error := by
      rw [card_divisorsAntidiagonal_eq_card_divisors]

/-- Equation (36), before simplifying its main term: pointwise range-count estimates give a
divisor-count error envelope for the primitive trace count. -/
theorem traceExactOrderSolutions_card_error_le_moebiusMain
    [Finite G] [Finite H] [IsCyclic H]
    (leftTrace : G → T) (rightTrace : H → T) (leftExponent : ℕ)
    (mainTerm : ℕ → ℝ) (error : ℝ)
    (hRange : ∀ d : ℕ, d ∣ Nat.card H → 0 < d →
      |(Nat.card (powerTraceRangeSolutions
          leftTrace rightTrace leftExponent d) : ℝ) - mainTerm d| ≤ error) :
    |((traceExactOrderSolutions
        leftTrace rightTrace leftExponent (Nat.card H)).card : ℝ) -
        ∑ x ∈ (Nat.card H).divisorsAntidiagonal,
          (μ x.fst : ℝ) * mainTerm x.fst| ≤
      ((Nat.card H).divisors.card : ℝ) * error := by
  have hExact :=
    moebius_sum_powerTraceRangeSolutions_card_eq_traceExactOrderSolutions_card
      leftTrace rightTrace leftExponent
  have hExactReal :
      ((traceExactOrderSolutions
        leftTrace rightTrace leftExponent (Nat.card H)).card : ℝ) =
        ∑ x ∈ (Nat.card H).divisorsAntidiagonal,
          (μ x.fst : ℝ) *
            (Nat.card (powerTraceRangeSolutions
              leftTrace rightTrace leftExponent x.fst) : ℝ) := by
    exact_mod_cast hExact.symm
  rw [hExactReal]
  apply abs_moebius_weighted_sum_sub_le_divisors_card_mul
    (Nat.card H)
    (fun x => (Nat.card (powerTraceRangeSolutions
      leftTrace rightTrace leftExponent x.fst) : ℝ))
    (fun x => mainTerm x.fst) error
  intro x hx
  have hproduct := (Nat.mem_divisorsAntidiagonal.mp hx).1
  have hdvd : x.fst ∣ Nat.card H := ⟨x.snd, hproduct.symm⟩
  exact hRange x.fst hdvd
    (Nat.pos_of_ne_zero (Nat.left_ne_zero_of_mem_divisorsAntidiagonal hx))

/-- A positive Möbius main term larger than the error envelope forces an actual primitive trace
solution. -/
theorem traceExactOrderSolutions_nonempty_of_divisorsError_lt_moebiusMain
    [Finite G] [Finite H] [IsCyclic H]
    (leftTrace : G → T) (rightTrace : H → T) (leftExponent : ℕ)
    (mainTerm : ℕ → ℝ) (error : ℝ)
    (hRange : ∀ d : ℕ, d ∣ Nat.card H → 0 < d →
      |(Nat.card (powerTraceRangeSolutions
          leftTrace rightTrace leftExponent d) : ℝ) - mainTerm d| ≤ error)
    (hpositive :
      ((Nat.card H).divisors.card : ℝ) * error <
        ∑ x ∈ (Nat.card H).divisorsAntidiagonal,
          (μ x.fst : ℝ) * mainTerm x.fst) :
    (traceExactOrderSolutions
      leftTrace rightTrace leftExponent (Nat.card H)).Nonempty := by
  have henvelope := traceExactOrderSolutions_card_error_le_moebiusMain
    leftTrace rightTrace leftExponent mainTerm error hRange
  have hcardReal :
      0 < ((traceExactOrderSolutions
        leftTrace rightTrace leftExponent (Nat.card H)).card : ℝ) := by
    have hlower :
        (∑ x ∈ (Nat.card H).divisorsAntidiagonal,
          (μ x.fst : ℝ) * mainTerm x.fst) -
            ((traceExactOrderSolutions
              leftTrace rightTrace leftExponent (Nat.card H)).card : ℝ) ≤
          |((traceExactOrderSolutions
              leftTrace rightTrace leftExponent (Nat.card H)).card : ℝ) -
            ∑ x ∈ (Nat.card H).divisorsAntidiagonal,
              (μ x.fst : ℝ) * mainTerm x.fst| := by
      simpa only [neg_sub] using
        neg_le_abs
          (((traceExactOrderSolutions
            leftTrace rightTrace leftExponent (Nat.card H)).card : ℝ) -
              ∑ x ∈ (Nat.card H).divisorsAntidiagonal,
                (μ x.fst : ℝ) * mainTerm x.fst)
    linarith
  exact Finset.card_pos.mp (by exact_mod_cast hcardReal)

/-- The common Möbius main term for a field of size `fieldCard`, a fixed power exponent, and a
primitive target group of order `groupOrder`. -/
noncomputable def primitiveTraceMoebiusMainTerm
    (groupOrder fieldCard fixedExponent : ℕ) : ℝ :=
  ∑ x ∈ groupOrder.divisorsAntidiagonal,
    (μ x.fst : ℝ) *
      ((fieldCard : ℝ) / ((x.fst : ℝ) * (fixedExponent : ℝ)))

/-- Möbius inversion of `sum_totient`: the signed complementary-divisor sum is the totient. -/
theorem sum_moebius_mul_complementaryDivisor_eq_totient (n : ℕ) (hn : 0 < n) :
    ∑ x ∈ n.divisorsAntidiagonal,
        (μ x.fst : ℤ) * (x.snd : ℤ) = (n.totient : ℤ) := by
  have hsum : ∀ m : ℕ, m > 0 →
      ∑ d ∈ m.divisors, (d.totient : ℤ) = (m : ℤ) := by
    intro m hm
    exact_mod_cast Nat.sum_totient m
  exact
    (ArithmeticFunction.sum_eq_iff_sum_mul_moebius_eq
      (R := ℤ)
      (f := fun d : ℕ => (d.totient : ℤ))
      (g := fun m : ℕ => (m : ℤ))).mp hsum n hn

/-- Closed form of the primitive-trace Möbius main term. -/
theorem primitiveTraceMoebiusMainTerm_eq_totient
    (groupOrder fieldCard fixedExponent : ℕ)
    (hgroup : 0 < groupOrder) (hfixed : 0 < fixedExponent) :
    primitiveTraceMoebiusMainTerm groupOrder fieldCard fixedExponent =
      (fieldCard : ℝ) * (groupOrder.totient : ℝ) /
        ((fixedExponent : ℝ) * (groupOrder : ℝ)) := by
  have hfixedReal : (fixedExponent : ℝ) ≠ 0 := by positivity
  have hgroupReal : (groupOrder : ℝ) ≠ 0 := by positivity
  unfold primitiveTraceMoebiusMainTerm
  calc
    (∑ x ∈ groupOrder.divisorsAntidiagonal,
      (μ x.fst : ℝ) *
        ((fieldCard : ℝ) / ((x.fst : ℝ) * (fixedExponent : ℝ)))) =
        ∑ x ∈ groupOrder.divisorsAntidiagonal,
          ((fieldCard : ℝ) / ((fixedExponent : ℝ) * (groupOrder : ℝ))) *
            ((μ x.fst : ℝ) * (x.snd : ℝ)) := by
      apply Finset.sum_congr rfl
      intro x hx
      have hproduct := (Nat.mem_divisorsAntidiagonal.mp hx).1
      have hleftNe := Nat.left_ne_zero_of_mem_divisorsAntidiagonal hx
      have hleftReal : (x.fst : ℝ) ≠ 0 := by exact_mod_cast hleftNe
      have hproductReal : (x.fst : ℝ) * (x.snd : ℝ) = groupOrder := by
        exact_mod_cast hproduct
      field_simp
      rw [← hproductReal]
      ring
    _ = ((fieldCard : ℝ) / ((fixedExponent : ℝ) * (groupOrder : ℝ))) *
        ∑ x ∈ groupOrder.divisorsAntidiagonal,
          ((μ x.fst : ℝ) * (x.snd : ℝ)) := by
      rw [Finset.mul_sum]
    _ = ((fieldCard : ℝ) / ((fixedExponent : ℝ) * (groupOrder : ℝ))) *
        (groupOrder.totient : ℝ) := by
      congr 1
      exact_mod_cast sum_moebius_mul_complementaryDivisor_eq_totient
        groupOrder hgroup
    _ = (fieldCard : ℝ) * (groupOrder.totient : ℝ) /
        ((fixedExponent : ℝ) * (groupOrder : ℝ)) := by ring

/-- The totient times the divisor count dominates the integer itself. -/
theorem le_totient_mul_card_divisors (n : ℕ) (hn : 0 < n) :
    n ≤ n.totient * n.divisors.card := by
  calc
    n = ∑ d ∈ n.divisors, d.totient := (Nat.sum_totient n).symm
    _ ≤
        ∑ _d ∈ n.divisors, n.totient := by
      apply Finset.sum_le_sum
      intro d hd
      exact Nat.le_of_dvd (Nat.totient_pos.mpr hn)
        (Nat.totient_dvd_of_dvd (Nat.dvd_of_mem_divisors hd))
    _ = n.totient * n.divisors.card := by
      simp [Nat.mul_comm]

/-- The elementary lower envelope for the Möbius main term used in the endgame. -/
theorem fieldCard_div_fixed_mul_divisors_le_primitiveTraceMoebiusMainTerm
    (groupOrder fieldCard fixedExponent : ℕ)
    (hgroup : 0 < groupOrder) (hfixed : 0 < fixedExponent) :
    (fieldCard : ℝ) /
        ((fixedExponent : ℝ) * (groupOrder.divisors.card : ℝ)) ≤
      primitiveTraceMoebiusMainTerm groupOrder fieldCard fixedExponent := by
  rw [primitiveTraceMoebiusMainTerm_eq_totient
    groupOrder fieldCard fixedExponent hgroup hfixed]
  have hdivisors : 0 < groupOrder.divisors.card :=
    (Nat.nonempty_divisors.mpr hgroup.ne').card_pos
  have hfixedReal : (0 : ℝ) < fixedExponent := by exact_mod_cast hfixed
  have hgroupReal : (0 : ℝ) < groupOrder := by exact_mod_cast hgroup
  have hdivisorsReal : (0 : ℝ) < groupOrder.divisors.card := by exact_mod_cast hdivisors
  have htotientBound :
      (groupOrder : ℝ) ≤
        (groupOrder.totient : ℝ) * (groupOrder.divisors.card : ℝ) := by
    exact_mod_cast le_totient_mul_card_divisors groupOrder hgroup
  have hfieldNonnegative : (0 : ℝ) ≤ fieldCard := by positivity
  have hratio :
      (1 : ℝ) / (groupOrder.divisors.card : ℝ) ≤
        (groupOrder.totient : ℝ) / (groupOrder : ℝ) := by
    apply (div_le_div_iff₀ hdivisorsReal hgroupReal).2
    simpa using htotientBound
  have hscale : 0 ≤ (fieldCard : ℝ) / (fixedExponent : ℝ) :=
    div_nonneg hfieldNonnegative hfixedReal.le
  calc
    (fieldCard : ℝ) /
        ((fixedExponent : ℝ) * (groupOrder.divisors.card : ℝ)) =
      ((fieldCard : ℝ) / (fixedExponent : ℝ)) *
        ((1 : ℝ) / (groupOrder.divisors.card : ℝ)) := by field_simp
    _ ≤ ((fieldCard : ℝ) / (fixedExponent : ℝ)) *
        ((groupOrder.totient : ℝ) / (groupOrder : ℝ)) :=
      mul_le_mul_of_nonneg_left hratio hscale
    _ = (fieldCard : ℝ) * (groupOrder.totient : ℝ) /
        ((fixedExponent : ℝ) * (groupOrder : ℝ)) := by field_simp

/-- The explicit inequality used after the divisor bound is sufficient for primitive-trace
positivity. -/
theorem divisorsError_lt_primitiveTraceMoebiusMainTerm_of_explicitInequality
    (groupOrder fieldCard fixedExponent coefficient : ℕ)
    (hgroup : 0 < groupOrder) (hfixed : 0 < fixedExponent)
    (hexplicit :
      (fixedExponent : ℝ) * (groupOrder.divisors.card : ℝ) ^ 2 *
          ((coefficient : ℝ) * Real.sqrt (fieldCard : ℝ)) < fieldCard) :
    (groupOrder.divisors.card : ℝ) *
        ((coefficient : ℝ) * Real.sqrt (fieldCard : ℝ)) <
      primitiveTraceMoebiusMainTerm groupOrder fieldCard fixedExponent := by
  have hlower :=
    fieldCard_div_fixed_mul_divisors_le_primitiveTraceMoebiusMainTerm
      groupOrder fieldCard fixedExponent hgroup hfixed
  have hfixedReal : (0 : ℝ) < fixedExponent := by exact_mod_cast hfixed
  have hdivisorsReal : (0 : ℝ) < groupOrder.divisors.card := by
    exact_mod_cast (Nat.nonempty_divisors.mpr hgroup.ne').card_pos
  apply lt_of_lt_of_le ?_ hlower
  apply (lt_div_iff₀ (mul_pos hfixedReal hdivisorsReal)).2
  calc
    (groupOrder.divisors.card : ℝ) *
          ((coefficient : ℝ) * Real.sqrt (fieldCard : ℝ)) *
        ((fixedExponent : ℝ) * (groupOrder.divisors.card : ℝ)) =
      (fixedExponent : ℝ) * (groupOrder.divisors.card : ℝ) ^ 2 *
        ((coefficient : ℝ) * Real.sqrt (fieldCard : ℝ)) := by ring
    _ < fieldCard := hexplicit

/-- Uniformly for large `p`, an orbit exponent at most `p^(1/2-δ)` satisfies the explicit
primitive-trace inequality.  This is the asymptotic calculation behind the last sentence after
published equation (36). -/
theorem eventually_endgamePrimitiveTrace_explicitInequality
    (coefficient : ℕ) {δ : ℝ} (hδ : 0 < δ) :
    ∀ᶠ p : ℕ in atTop, ∀ orbitExponent : ℕ,
      (orbitExponent : ℝ) ≤ (p : ℝ) ^ ((1 : ℝ) / 2 - δ) →
        (orbitExponent : ℝ) * ((p - 1).divisors.card : ℝ) ^ 2 *
          ((coefficient : ℝ) * Real.sqrt (p : ℝ)) < p := by
  let ε : ℝ := δ / 8
  have hε : 0 < ε := by dsimp [ε]; positivity
  obtain ⟨divisorThreshold, hDivisorThreshold⟩ :=
    BGS.NumberTheory.exists_threshold_card_divisors_le_rpow hε
  have hExponent : 1 - δ + 2 * ε < 1 := by
    dsimp [ε]
    linarith
  have hDominance :
      ∀ᶠ p : ℕ in atTop,
        (coefficient : ℝ) * (p : ℝ) ^ (1 - δ + 2 * ε) < (p : ℝ) ^ (1 : ℝ) :=
    eventually_const_mul_rpow_lt_rpow hExponent
  filter_upwards [hDominance, eventually_ge_atTop (divisorThreshold + 1),
    eventually_ge_atTop 1] with p hDominance hpThreshold hpOne
  intro orbitExponent horbit
  have hpMinusThreshold : divisorThreshold ≤ p - 1 := by omega
  have hDivisorRaw := hDivisorThreshold (p - 1) hpMinusThreshold
  have hpRealPos : (0 : ℝ) < p := by exact_mod_cast (show 0 < p by omega)
  have hpRealNonnegative : (0 : ℝ) ≤ p := hpRealPos.le
  have hpMinusLe : (((p - 1 : ℕ) : ℝ)) ≤ (p : ℝ) := by exact_mod_cast Nat.sub_le p 1
  have hDivisorPower : (((p - 1 : ℕ) : ℝ)) ^ ε ≤ (p : ℝ) ^ ε :=
    Real.rpow_le_rpow (Nat.cast_nonneg _) hpMinusLe hε.le
  have hDivisor : ((p - 1).divisors.card : ℝ) ≤ (p : ℝ) ^ ε :=
    hDivisorRaw.trans hDivisorPower
  have hCoefficientNonnegative : (0 : ℝ) ≤ coefficient := by positivity
  have hOrbitNonnegative : (0 : ℝ) ≤ orbitExponent := by positivity
  have hDivisorNonnegative : (0 : ℝ) ≤ (p - 1).divisors.card := by positivity
  have hPowerIdentity :
      (p : ℝ) ^ ((1 : ℝ) / 2 - δ) * ((p : ℝ) ^ ε) ^ 2 *
          Real.sqrt (p : ℝ) =
        (p : ℝ) ^ (1 - δ + 2 * ε) := by
    rw [Real.sqrt_eq_rpow]
    rw [← Real.rpow_mul_natCast hpRealNonnegative ε 2]
    rw [← Real.rpow_add hpRealPos, ← Real.rpow_add hpRealPos]
    congr 1
    ring
  calc
    (orbitExponent : ℝ) * ((p - 1).divisors.card : ℝ) ^ 2 *
        ((coefficient : ℝ) * Real.sqrt (p : ℝ)) =
      (coefficient : ℝ) *
        ((orbitExponent : ℝ) * ((p - 1).divisors.card : ℝ) ^ 2 *
          Real.sqrt (p : ℝ)) := by ring
    _ ≤ (coefficient : ℝ) *
        ((p : ℝ) ^ ((1 : ℝ) / 2 - δ) * ((p : ℝ) ^ ε) ^ 2 *
          Real.sqrt (p : ℝ)) := by
      gcongr
    _ = (coefficient : ℝ) * (p : ℝ) ^ (1 - δ + 2 * ε) := by
      rw [hPowerIdentity]
    _ < (p : ℝ) ^ (1 : ℝ) := hDominance
    _ = p := by simp

/-- Threshold form of `eventually_endgamePrimitiveTrace_explicitInequality`. -/
theorem exists_threshold_endgamePrimitiveTrace_explicitInequality
    (coefficient : ℕ) {δ : ℝ} (hδ : 0 < δ) :
    ∃ threshold : ℕ, ∀ p : ℕ, threshold ≤ p → ∀ orbitExponent : ℕ,
      (orbitExponent : ℝ) ≤ (p : ℝ) ^ ((1 : ℝ) / 2 - δ) →
        (orbitExponent : ℝ) * ((p - 1).divisors.card : ℝ) ^ 2 *
          ((coefficient : ℝ) * Real.sqrt (p : ℝ)) < p :=
  eventually_atTop.mp (eventually_endgamePrimitiveTrace_explicitInequality coefficient hδ)

/-- A large orbit order gives the upper bound on its complementary power exponent used by the
primitive-trace asymptotic. -/
theorem orbitExponent_le_rpow_of_mul_order_eq_card_sub_one
    (p orbitExponent orbitOrder : ℕ) {δ : ℝ} (hp : 0 < p)
    (hmul : orbitExponent * orbitOrder = p - 1)
    (horder : (p : ℝ) ^ ((1 : ℝ) / 2 + δ) ≤ orbitOrder) :
    (orbitExponent : ℝ) ≤ (p : ℝ) ^ ((1 : ℝ) / 2 - δ) := by
  have hpRealPos : (0 : ℝ) < p := by exact_mod_cast hp
  have horderPositive : (0 : ℝ) < orbitOrder :=
    (Real.rpow_pos_of_pos hpRealPos _).trans_le horder
  have hmulReal :
      (orbitExponent : ℝ) * (orbitOrder : ℝ) = ((p - 1 : ℕ) : ℝ) := by
    exact_mod_cast hmul
  have hproductLe :
      (orbitExponent : ℝ) * (orbitOrder : ℝ) ≤ (p : ℝ) := by
    rw [hmulReal]
    exact_mod_cast Nat.sub_le p 1
  have horbitExponentLe :
      (orbitExponent : ℝ) ≤ (p : ℝ) / (orbitOrder : ℝ) :=
    (le_div_iff₀ horderPositive).2 hproductLe
  calc
    (orbitExponent : ℝ) ≤ (p : ℝ) / (orbitOrder : ℝ) := horbitExponentLe
    _ ≤ (p : ℝ) / ((p : ℝ) ^ ((1 : ℝ) / 2 + δ)) := by
      exact div_le_div_of_nonneg_left (Nat.cast_nonneg p)
        (Real.rpow_pos_of_pos hpRealPos _)
        horder
    _ = (p : ℝ) ^ (1 : ℝ) / ((p : ℝ) ^ ((1 : ℝ) / 2 + δ)) := by
      rw [Real.rpow_one]
    _ = (p : ℝ) ^ ((1 : ℝ) - ((1 : ℝ) / 2 + δ)) :=
      (Real.rpow_sub hpRealPos (1 : ℝ) ((1 : ℝ) / 2 + δ)).symm
    _ = (p : ℝ) ^ ((1 : ℝ) / 2 - δ) := by
      congr 1
      ring

/-- In the nonsplit torus, whose order is `p + 1`, a large orbit gives the same complementary
exponent bound up to the harmless fixed factor two. -/
theorem orbitExponent_le_two_mul_rpow_of_mul_order_eq_card_add_one
    (p orbitExponent orbitOrder : ℕ) {δ : ℝ} (hp : 0 < p)
    (hmul : orbitExponent * orbitOrder = p + 1)
    (horder : (p : ℝ) ^ ((1 : ℝ) / 2 + δ) ≤ orbitOrder) :
    (orbitExponent : ℝ) ≤ 2 * (p : ℝ) ^ ((1 : ℝ) / 2 - δ) := by
  have hpRealPos : (0 : ℝ) < p := by exact_mod_cast hp
  have horderPositive : (0 : ℝ) < orbitOrder :=
    (Real.rpow_pos_of_pos hpRealPos _).trans_le horder
  have hmulReal :
      (orbitExponent : ℝ) * (orbitOrder : ℝ) = ((p + 1 : ℕ) : ℝ) := by
    exact_mod_cast hmul
  have hproductLe :
      (orbitExponent : ℝ) * (orbitOrder : ℝ) ≤ 2 * (p : ℝ) := by
    rw [hmulReal]
    exact_mod_cast (show p + 1 ≤ 2 * p by omega)
  have horbitExponentLe :
      (orbitExponent : ℝ) ≤ (2 * (p : ℝ)) / (orbitOrder : ℝ) :=
    (le_div_iff₀ horderPositive).2 hproductLe
  calc
    (orbitExponent : ℝ) ≤ (2 * (p : ℝ)) / (orbitOrder : ℝ) := horbitExponentLe
    _ ≤ (2 * (p : ℝ)) / ((p : ℝ) ^ ((1 : ℝ) / 2 + δ)) := by
      exact div_le_div_of_nonneg_left (by positivity)
        (Real.rpow_pos_of_pos hpRealPos _) horder
    _ = 2 * ((p : ℝ) / ((p : ℝ) ^ ((1 : ℝ) / 2 + δ))) := by ring
    _ = 2 * ((p : ℝ) ^ ((1 : ℝ) / 2 - δ)) := by
      congr 1
      calc
        (p : ℝ) / ((p : ℝ) ^ ((1 : ℝ) / 2 + δ)) =
            (p : ℝ) ^ (1 : ℝ) /
              ((p : ℝ) ^ ((1 : ℝ) / 2 + δ)) := by rw [Real.rpow_one]
        _ = (p : ℝ) ^ ((1 : ℝ) - ((1 : ℝ) / 2 + δ)) :=
          (Real.rpow_sub hpRealPos (1 : ℝ) ((1 : ℝ) / 2 + δ)).symm
        _ = (p : ℝ) ^ ((1 : ℝ) / 2 - δ) := by
          congr 1
          ring

/-- Nonsplit threshold form: a complementary exponent in the norm-one torus of order `p + 1`
satisfies the same primitive-trace inequality for all sufficiently large `p`. -/
theorem exists_threshold_endgamePrimitiveTrace_explicitInequality_of_largeNonsplitOrder
    (coefficient : ℕ) {δ : ℝ} (hδ : 0 < δ) :
    ∃ threshold : ℕ, ∀ p : ℕ, threshold ≤ p →
      ∀ orbitExponent orbitOrder : ℕ,
        orbitExponent * orbitOrder = p + 1 →
        (p : ℝ) ^ ((1 : ℝ) / 2 + δ) ≤ orbitOrder →
          (orbitExponent : ℝ) * ((p - 1).divisors.card : ℝ) ^ 2 *
            ((coefficient : ℝ) * Real.sqrt (p : ℝ)) < p := by
  have hhalfδ : 0 < δ / 2 := by linarith
  obtain ⟨inequalityThreshold, hInequality⟩ :=
    exists_threshold_endgamePrimitiveTrace_explicitInequality coefficient hhalfδ
  have hexponents : (1 : ℝ) / 2 - δ < (1 : ℝ) / 2 - δ / 2 := by linarith
  have hAbsorb :
      ∀ᶠ p : ℕ in atTop,
        2 * (p : ℝ) ^ ((1 : ℝ) / 2 - δ) <
          (p : ℝ) ^ ((1 : ℝ) / 2 - δ / 2) :=
    eventually_const_mul_rpow_lt_rpow hexponents
  obtain ⟨absorbThreshold, hAbsorbThreshold⟩ := eventually_atTop.mp hAbsorb
  refine ⟨max (max inequalityThreshold absorbThreshold) 1, ?_⟩
  intro p hp orbitExponent orbitOrder hmul horder
  have hpInequality : inequalityThreshold ≤ p :=
    (le_max_left inequalityThreshold absorbThreshold).trans
      ((le_max_left (max inequalityThreshold absorbThreshold) 1).trans hp)
  have hpAbsorb : absorbThreshold ≤ p :=
    (le_max_right inequalityThreshold absorbThreshold).trans
      ((le_max_left (max inequalityThreshold absorbThreshold) 1).trans hp)
  have hpPositive : 0 < p := by omega
  apply hInequality p hpInequality orbitExponent
  exact (orbitExponent_le_two_mul_rpow_of_mul_order_eq_card_add_one
    p orbitExponent orbitOrder hpPositive hmul horder).trans
      (hAbsorbThreshold p hpAbsorb).le

/-- Threshold form directly in terms of the large orbit order and its complementary exponent. -/
theorem exists_threshold_endgamePrimitiveTrace_explicitInequality_of_largeOrder
    (coefficient : ℕ) {δ : ℝ} (hδ : 0 < δ) :
    ∃ threshold : ℕ, ∀ p : ℕ, threshold ≤ p →
      ∀ orbitExponent orbitOrder : ℕ,
        orbitExponent * orbitOrder = p - 1 →
        (p : ℝ) ^ ((1 : ℝ) / 2 + δ) ≤ orbitOrder →
          (orbitExponent : ℝ) * ((p - 1).divisors.card : ℝ) ^ 2 *
            ((coefficient : ℝ) * Real.sqrt (p : ℝ)) < p := by
  obtain ⟨threshold, hthreshold⟩ :=
    exists_threshold_endgamePrimitiveTrace_explicitInequality coefficient hδ
  refine ⟨max threshold 1, ?_⟩
  intro p hp orbitExponent orbitOrder hmul horder
  have hpThreshold : threshold ≤ p := (le_max_left threshold 1).trans hp
  have hpPositive : 0 < p := by omega
  exact hthreshold p hpThreshold orbitExponent
    (orbitExponent_le_rpow_of_mul_order_eq_card_sub_one
      p orbitExponent orbitOrder hpPositive hmul horder)

/-- A numerical main-term domination criterion turns a point-count envelope into nonemptiness. -/
theorem finset_nonempty_of_card_error_le_and_error_lt_main
    {α : Type*} (s : Finset α) (mainTerm error : ℝ)
    (henvelope : |(s.card : ℝ) - mainTerm| ≤ error)
    (hpositive : error < mainTerm) : s.Nonempty := by
  apply Finset.card_pos.mp
  have hlower : mainTerm - (s.card : ℝ) ≤ |(s.card : ℝ) - mainTerm| := by
    simpa only [neg_sub] using neg_le_abs ((s.card : ℝ) - mainTerm)
  have hcardReal : (0 : ℝ) < s.card := by linarith
  exact_mod_cast hcardReal

section SplitApplication

/-- Split trace coincidences with the orbit coordinate in the fixed power image and the other
coordinate primitive in the full base-field multiplicative group. -/
abbrev splitPrimitiveTraceSolutions
    (p : ℕ) [Fact p.Prime]
    (alpha beta : ZMod p) (orbitExponent : ℕ) :=
  traceExactOrderSolutions
    (weightedSplitTorusTrace alpha beta)
    (splitTorusTrace : (ZMod p)ˣ → ZMod p)
    orbitExponent (Nat.card (ZMod p)ˣ)

/-- Published equation (36) for the split branch, with every error and multiplicity supplied by
the preceding formal interfaces. -/
theorem splitPrimitiveTraceSolutions_card_error_le_of_weilBoundAssumption
    (p : ℕ) [Fact p.Prime]
    (coefficient : ℕ) (hWeil : WeightedSplitTraceWeilBoundAssumption coefficient)
    (alpha beta : ZMod p) (orbitExponent : ℕ)
    (halpha : alpha ≠ 0) (hbeta : beta ≠ 0) (hnondegenerate : alpha * beta ≠ 1)
    (horbitPositive : 0 < orbitExponent)
    (horbitChar : (orbitExponent : ZMod p) ≠ 0)
    (horbitDvd : orbitExponent ∣ Nat.card (ZMod p)ˣ) :
    |((splitPrimitiveTraceSolutions p alpha beta orbitExponent).card : ℝ) -
        primitiveTraceMoebiusMainTerm
          (Nat.card (ZMod p)ˣ) p orbitExponent| ≤
      ((Nat.card (ZMod p)ˣ).divisors.card : ℝ) *
        ((coefficient : ℝ) * Real.sqrt (p : ℝ)) := by
  have hRange : ∀ d : ℕ, d ∣ Nat.card (ZMod p)ˣ → 0 < d →
      |(Nat.card (powerTraceRangeSolutions
          (weightedSplitTorusTrace alpha beta)
          (splitTorusTrace : (ZMod p)ˣ → ZMod p) orbitExponent d) : ℝ) -
        (p : ℝ) / ((d : ℝ) * (orbitExponent : ℝ))| ≤
          (coefficient : ℝ) * Real.sqrt (p : ℝ) := by
    intro d hdvd hd
    have hestimate :=
      splitTracePowerRangeSolutions_count_error_le_of_weilBoundAssumption
        (ZMod p) coefficient hWeil alpha beta d orbitExponent
        halpha hbeta hnondegenerate hd horbitPositive horbitChar hdvd horbitDvd
    rw [natCard_powerTraceRangeSolutions_swap
      (weightedSplitTorusTrace alpha beta)
      (splitTorusTrace : (ZMod p)ˣ → ZMod p) orbitExponent d]
    simpa [ZMod.card] using hestimate
  simpa [splitPrimitiveTraceSolutions, primitiveTraceMoebiusMainTerm] using
    traceExactOrderSolutions_card_error_le_moebiusMain
      (weightedSplitTorusTrace alpha beta)
      (splitTorusTrace : (ZMod p)ˣ → ZMod p)
      orbitExponent
      (fun d => (p : ℝ) / ((d : ℝ) * (orbitExponent : ℝ)))
      ((coefficient : ℝ) * Real.sqrt (p : ℝ)) hRange

/-- Once the explicit Möbius main term dominates the accumulated Weil errors, an actual split
primitive trace pair exists. -/
theorem splitPrimitiveTraceSolutions_nonempty_of_moebiusMain_gt_divisorsError
    (p : ℕ) [Fact p.Prime]
    (coefficient : ℕ) (hWeil : WeightedSplitTraceWeilBoundAssumption coefficient)
    (alpha beta : ZMod p) (orbitExponent : ℕ)
    (halpha : alpha ≠ 0) (hbeta : beta ≠ 0) (hnondegenerate : alpha * beta ≠ 1)
    (horbitPositive : 0 < orbitExponent)
    (horbitChar : (orbitExponent : ZMod p) ≠ 0)
    (horbitDvd : orbitExponent ∣ Nat.card (ZMod p)ˣ)
    (hmain :
      ((Nat.card (ZMod p)ˣ).divisors.card : ℝ) *
          ((coefficient : ℝ) * Real.sqrt (p : ℝ)) <
        primitiveTraceMoebiusMainTerm
          (Nat.card (ZMod p)ˣ) p orbitExponent) :
    (splitPrimitiveTraceSolutions p alpha beta orbitExponent).Nonempty := by
  apply finset_nonempty_of_card_error_le_and_error_lt_main
    (splitPrimitiveTraceSolutions p alpha beta orbitExponent)
    (primitiveTraceMoebiusMainTerm (Nat.card (ZMod p)ˣ) p orbitExponent)
    (((Nat.card (ZMod p)ˣ).divisors.card : ℝ) *
      ((coefficient : ℝ) * Real.sqrt (p : ℝ)))
  · exact splitPrimitiveTraceSolutions_card_error_le_of_weilBoundAssumption
      p coefficient hWeil alpha beta orbitExponent halpha hbeta hnondegenerate
      horbitPositive horbitChar horbitDvd
  · exact hmain

/-- The fully numerical split inclusion--exclusion criterion produces a primitive trace pair. -/
theorem exists_splitPrimitiveTracePair_of_explicitInequality
    (p : ℕ) [Fact p.Prime]
    (coefficient : ℕ) (hWeil : WeightedSplitTraceWeilBoundAssumption coefficient)
    (alpha beta : ZMod p) (orbitExponent : ℕ)
    (halpha : alpha ≠ 0) (hbeta : beta ≠ 0) (hnondegenerate : alpha * beta ≠ 1)
    (horbitPositive : 0 < orbitExponent)
    (horbitChar : (orbitExponent : ZMod p) ≠ 0)
    (horbitDvd : orbitExponent ∣ Nat.card (ZMod p)ˣ)
    (hexplicit :
      (orbitExponent : ℝ) * ((Nat.card (ZMod p)ˣ).divisors.card : ℝ) ^ 2 *
          ((coefficient : ℝ) * Real.sqrt (p : ℝ)) < p) :
    ∃ z : (powMonoidHom orbitExponent : (ZMod p)ˣ →* (ZMod p)ˣ).range × (ZMod p)ˣ,
      weightedSplitTorusTrace alpha beta z.1 = splitTorusTrace z.2 ∧
        orderOf z.2 = Nat.card (ZMod p)ˣ := by
  have hmain :=
    divisorsError_lt_primitiveTraceMoebiusMainTerm_of_explicitInequality
      (Nat.card (ZMod p)ˣ) p orbitExponent coefficient
      Nat.card_pos horbitPositive hexplicit
  obtain ⟨z, hz⟩ :=
    splitPrimitiveTraceSolutions_nonempty_of_moebiusMain_gt_divisorsError
      p coefficient hWeil alpha beta orbitExponent halpha hbeta hnondegenerate
      horbitPositive horbitChar horbitDvd hmain
  exact ⟨z, (mem_traceExactOrderSolutions_iff
    (weightedSplitTorusTrace alpha beta)
    (splitTorusTrace : (ZMod p)ˣ → ZMod p)
    orbitExponent (Nat.card (ZMod p)ˣ) z).mp hz⟩

end SplitApplication

section NonsplitApplication

/-- Corrected seeded nonsplit trace coincidences with primitive base-field right coordinate. -/
abbrev existingConicSeedNonsplitPrimitiveTraceSolutions
    (p : ℕ) [Fact p.Prime]
    (t : ZMod p) (ht : t ^ 2 ≠ 4) (ht0 : t ≠ 0)
    (s : ↥(quadraticConicNormFiber p t ht ht0))
    (orbitExponent : ℕ) :=
  traceExactOrderSolutions
    (existingConicSeedNonsplitTorusTrace p t ht ht0 s)
    (splitTorusTrace : (ZMod p)ˣ → ZMod p)
    orbitExponent (Nat.card (ZMod p)ˣ)

/-- Published equation (36) for the corrected seeded nonsplit branch. -/
theorem existingConicSeedNonsplitPrimitiveTraceSolutions_card_error_le_of_weilBoundAssumption
    (p : ℕ) [Fact p.Prime]
    (coefficient : ℕ) (hWeil : SeededNonsplitTraceWeilBoundAssumption coefficient)
    (hpTwo : p ≠ 2)
    (t : ZMod p) (ht : t ^ 2 ≠ 4) (ht0 : t ≠ 0)
    (s : ↥(quadraticConicNormFiber p t ht ht0))
    (orbitExponent : ℕ) (horbitPositive : 0 < orbitExponent)
    (horbitChar : (orbitExponent : quadraticFiniteField p) ≠ 0)
    (horbitDvd : orbitExponent ∣ Nat.card (quadraticNormOneTorus p)) :
    |((existingConicSeedNonsplitPrimitiveTraceSolutions
        p t ht ht0 s orbitExponent).card : ℝ) -
        primitiveTraceMoebiusMainTerm
          (Nat.card (ZMod p)ˣ) p orbitExponent| ≤
      ((Nat.card (ZMod p)ˣ).divisors.card : ℝ) *
        ((coefficient : ℝ) * Real.sqrt (p : ℝ)) := by
  have hRange : ∀ e : ℕ, e ∣ Nat.card (ZMod p)ˣ → 0 < e →
      |(Nat.card (powerTraceRangeSolutions
          (existingConicSeedNonsplitTorusTrace p t ht ht0 s)
          (splitTorusTrace : (ZMod p)ˣ → ZMod p) orbitExponent e) : ℝ) -
        (p : ℝ) / ((e : ℝ) * (orbitExponent : ℝ))| ≤
          (coefficient : ℝ) * Real.sqrt (p : ℝ) := by
    intro e hedvd he
    have hestimate :=
      existingConicSeedNonsplitPowerRangeSolutions_count_error_le_of_weilBoundAssumption
        p coefficient hWeil hpTwo t ht ht0 s orbitExponent e
        horbitPositive he horbitChar horbitDvd hedvd
    simpa [mul_comm] using hestimate
  simpa [existingConicSeedNonsplitPrimitiveTraceSolutions,
    primitiveTraceMoebiusMainTerm] using
    traceExactOrderSolutions_card_error_le_moebiusMain
      (existingConicSeedNonsplitTorusTrace p t ht ht0 s)
      (splitTorusTrace : (ZMod p)ˣ → ZMod p)
      orbitExponent
      (fun e => (p : ℝ) / ((e : ℝ) * (orbitExponent : ℝ)))
      ((coefficient : ℝ) * Real.sqrt (p : ℝ)) hRange

/-- Numerical main-term domination produces an actual primitive base-field trace pair in the
corrected nonsplit branch. -/
theorem existingConicSeedNonsplitPrimitiveTraceSolutions_nonempty_of_moebiusMain_gt_divisorsError
    (p : ℕ) [Fact p.Prime]
    (coefficient : ℕ) (hWeil : SeededNonsplitTraceWeilBoundAssumption coefficient)
    (hpTwo : p ≠ 2)
    (t : ZMod p) (ht : t ^ 2 ≠ 4) (ht0 : t ≠ 0)
    (s : ↥(quadraticConicNormFiber p t ht ht0))
    (orbitExponent : ℕ) (horbitPositive : 0 < orbitExponent)
    (horbitChar : (orbitExponent : quadraticFiniteField p) ≠ 0)
    (horbitDvd : orbitExponent ∣ Nat.card (quadraticNormOneTorus p))
    (hmain :
      ((Nat.card (ZMod p)ˣ).divisors.card : ℝ) *
          ((coefficient : ℝ) * Real.sqrt (p : ℝ)) <
        primitiveTraceMoebiusMainTerm
          (Nat.card (ZMod p)ˣ) p orbitExponent) :
    (existingConicSeedNonsplitPrimitiveTraceSolutions
      p t ht ht0 s orbitExponent).Nonempty := by
  apply finset_nonempty_of_card_error_le_and_error_lt_main
    (existingConicSeedNonsplitPrimitiveTraceSolutions
      p t ht ht0 s orbitExponent)
    (primitiveTraceMoebiusMainTerm (Nat.card (ZMod p)ˣ) p orbitExponent)
    (((Nat.card (ZMod p)ˣ).divisors.card : ℝ) *
      ((coefficient : ℝ) * Real.sqrt (p : ℝ)))
  · exact
      existingConicSeedNonsplitPrimitiveTraceSolutions_card_error_le_of_weilBoundAssumption
        p coefficient hWeil hpTwo t ht ht0 s orbitExponent
        horbitPositive horbitChar horbitDvd
  · exact hmain

/-- The fully numerical nonsplit inclusion--exclusion criterion produces a primitive base-field
trace pair on the corrected seeded norm-one orbit. -/
theorem exists_existingConicSeedNonsplitPrimitiveTracePair_of_explicitInequality
    (p : ℕ) [Fact p.Prime]
    (coefficient : ℕ) (hWeil : SeededNonsplitTraceWeilBoundAssumption coefficient)
    (hpTwo : p ≠ 2)
    (t : ZMod p) (ht : t ^ 2 ≠ 4) (ht0 : t ≠ 0)
    (s : ↥(quadraticConicNormFiber p t ht ht0))
    (orbitExponent : ℕ) (horbitPositive : 0 < orbitExponent)
    (horbitChar : (orbitExponent : quadraticFiniteField p) ≠ 0)
    (horbitDvd : orbitExponent ∣ Nat.card (quadraticNormOneTorus p))
    (hexplicit :
      (orbitExponent : ℝ) * ((Nat.card (ZMod p)ˣ).divisors.card : ℝ) ^ 2 *
          ((coefficient : ℝ) * Real.sqrt (p : ℝ)) < p) :
    ∃ z : (powMonoidHom orbitExponent :
        quadraticNormOneTorus p →* quadraticNormOneTorus p).range × (ZMod p)ˣ,
      existingConicSeedNonsplitTorusTrace p t ht ht0 s z.1 = splitTorusTrace z.2 ∧
        orderOf z.2 = Nat.card (ZMod p)ˣ := by
  have hmain :=
    divisorsError_lt_primitiveTraceMoebiusMainTerm_of_explicitInequality
      (Nat.card (ZMod p)ˣ) p orbitExponent coefficient
      Nat.card_pos horbitPositive hexplicit
  obtain ⟨z, hz⟩ :=
    existingConicSeedNonsplitPrimitiveTraceSolutions_nonempty_of_moebiusMain_gt_divisorsError
      p coefficient hWeil hpTwo t ht ht0 s orbitExponent
      horbitPositive horbitChar horbitDvd hmain
  exact ⟨z, (mem_traceExactOrderSolutions_iff
    (existingConicSeedNonsplitTorusTrace p t ht ht0 s)
    (splitTorusTrace : (ZMod p)ˣ → ZMod p)
    orbitExponent (Nat.card (ZMod p)ˣ) z).mp hz⟩

end NonsplitApplication

end


end BGS.Markoff
