import GenMarkoff.Core.Action

/-!
# Formal statements for generalized strong approximation

This file fixes the quantifiers and keeps four claims separate:

1. divisibility for orbits of the individual Vieta moves;
2. divisibility for the even-word rotation subgroup;
3. transitivity of the full Vieta group on the punctured surface;
4. transitivity of the rotation subgroup on the punctured surface.

The generic coefficient branch of the first claim is Theorem 1.1 of
arXiv:2509.02187v3 and is proved in
`GenMarkoff.Divisibility.GenericMartin`.  The source's additional
exceptional-compatible branch is recorded below as a specification but is not
claimed as a proved theorem in this submission.
-/

namespace GenMarkoff

/-- Reduction of a fixed integral coefficient triple modulo `p`. -/
def modCoefficients (a : Coefficients ℤ) (p : ℕ) : Coefficients (ZMod p) :=
  a.intCast (ZMod p)

/-- The generic coefficient hypotheses over a prime residue ring. -/
def GenericAdmissible {p : ℕ} (a : Coefficients (ZMod p)) : Prop :=
  a.multiplier ≠ 0 ∧ a.a1 ^ 2 ≠ 4 ∧ a.a2 ^ 2 ≠ 4 ∧ a.a3 ^ 2 ≠ 4

/-- The generic hypotheses after reducing a fixed integral coefficient triple. -/
def GenericAdmissibleAt (a : Coefficients ℤ) (p : ℕ) : Prop :=
  GenericAdmissible (modCoefficients a p)

/-- The exceptional-coefficient compatibility conditions from arXiv:2509.02187.

For cyclic indices they say `aᵢ² = 4 → 2 aᵢ₋₁ = aᵢ₊₁ aᵢ`.
-/
def ExceptionalCompatibility {p : ℕ} (a : Coefficients (ZMod p)) : Prop :=
  (a.a1 ^ 2 = 4 → 2 * a.a3 = a.a2 * a.a1) ∧
    (a.a2 ^ 2 = 4 → 2 * a.a1 = a.a3 * a.a2) ∧
    (a.a3 ^ 2 = 4 → 2 * a.a2 = a.a1 * a.a3)

/-- Exceptional compatibility after reducing fixed integral coefficients. -/
def ExceptionalCompatibilityAt (a : Coefficients ℤ) (p : ℕ) : Prop :=
  ExceptionalCompatibility (modCoefficients a p)

/-- The coefficient part of the generalized orbit-divisibility theorem. -/
def DivisibilityAdmissible {p : ℕ} (a : Coefficients (ZMod p)) : Prop :=
  a.multiplier ≠ 0 ∧ ExceptionalCompatibility a

/-- Divisibility hypotheses after reducing fixed integral coefficients. -/
def DivisibilityAdmissibleAt (a : Coefficients ℤ) (p : ℕ) : Prop :=
  DivisibilityAdmissible (modCoefficients a p)

/-- Strong approximation for the group generated by the individual Vieta moves. -/
def VietaStrongApproximationAt (a : Coefficients ℤ) (p : ℕ) (hp : p.Prime) : Prop :=
  letI : Fact p.Prime := ⟨hp⟩
  ∀ x y : PuncturedSolutionSurface (modCoefficients a p),
    ∃ g : VietaGroup (modCoefficients a p), g • x = y

/-- Strong approximation for the graph generated by the three two-Vieta rotations. -/
def RotationStrongApproximationAt (a : Coefficients ℤ) (p : ℕ) (hp : p.Prime) : Prop :=
  letI : Fact p.Prime := ⟨hp⟩
  ∀ x y : PuncturedSolutionSurface (modCoefficients a p),
    ∃ g : RotationGroup (modCoefficients a p), g • x = y

/-- Every punctured Vieta orbit for a residue-field coefficient triple has
cardinality divisible by `p`. -/
noncomputable def VietaOrbitDivisibility
    (p : ℕ) (hp : p.Prime) (a : Coefficients (ZMod p)) : Prop :=
  letI : Fact p.Prime := ⟨hp⟩
  ∀ x : PuncturedSolutionSurface a,
    p ∣ (puncturedVietaOrbit x).ncard

/-- The Vieta-orbit divisibility statement for reduced integral coefficients. -/
noncomputable def VietaOrbitDivisibilityAt
    (a : Coefficients ℤ) (p : ℕ) (hp : p.Prime) : Prop :=
  VietaOrbitDivisibility p hp (modCoefficients a p)

/-- Every punctured rotation orbit for a residue-field coefficient triple has
cardinality divisible by `p`. -/
noncomputable def RotationOrbitDivisibility
    (p : ℕ) (hp : p.Prime) (a : Coefficients (ZMod p)) : Prop :=
  letI : Fact p.Prime := ⟨hp⟩
  ∀ x : PuncturedSolutionSurface a,
    p ∣ (puncturedRotationOrbit x).ncard

/-- The rotation-orbit divisibility statement for reduced integral coefficients. -/
noncomputable def RotationOrbitDivisibilityAt
    (a : Coefficients ℤ) (p : ℕ) (hp : p.Prime) : Prop :=
  RotationOrbitDivisibility p hp (modCoefficients a p)

/-- The number of punctured points outside the rotation orbit of `x`. -/
noncomputable def rotationOrbitComplementCard
    {p : ℕ} {a : Coefficients (ZMod p)}
    (x : PuncturedSolutionSurface a) : ℕ :=
  (Set.univ \ puncturedRotationOrbit x).ncard

/-- At `p`, the fixed integral coefficient triple has a rotation orbit whose
complement has at most `p ^ epsilon` points. -/
def HasGiantRotationOrbitAt
    (a : Coefficients ℤ) (p : ℕ) (hp : p.Prime) (epsilon : ℝ) : Prop :=
  letI : Fact p.Prime := ⟨hp⟩
  ∃ x : PuncturedSolutionSurface (modCoefficients a p),
    (rotationOrbitComplementCard x : ℝ) ≤ Real.rpow p epsilon

/-- Rotation-orbit divisibility for every sufficiently large prime. -/
def EventuallyRotationOrbitDivisibility (a : Coefficients ℤ) : Prop :=
  ∃ p0 : ℕ, ∀ (p : ℕ) (hp : p.Prime), p0 ≤ p →
    RotationOrbitDivisibilityAt a p hp

/-- A Lean specification of the punctured form of Theorem 1.1 of
arXiv:2509.02187v3.  The generic restriction is proved by
`generalizedMartinGenericDivisibility`; the exceptional-compatible branch is
not part of the proved submission endpoint. -/
noncomputable def GeneralizedMartinDivisibilityStatement : Prop :=
  ∀ (p : ℕ) (hp : p.Prime) (a : Coefficients (ZMod p)),
    5 ≤ p → DivisibilityAdmissible a → VietaOrbitDivisibility p hp a

/-- The generic branch of generalized Martin divisibility.  Unlike
`GeneralizedMartinDivisibilityStatement`, this excludes every exceptional
coefficient `aᵢ² = 4`; it is the branch proved internally by the raw-angle
argument. -/
noncomputable def GeneralizedMartinGenericDivisibilityStatement : Prop :=
  ∀ (p : ℕ) (hp : p.Prime) (a : Coefficients (ZMod p)),
    5 ≤ p → GenericAdmissible a → VietaOrbitDivisibility p hp a

/-- Punctured strong approximation for the rotation graph.  It uses rotations,
not the larger Vieta group. -/
def RotationStrongApproximationConjecture : Prop :=
  ∀ (a : Coefficients ℤ) (p : ℕ) (hp : p.Prime),
    GenericAdmissibleAt a p → RotationStrongApproximationAt a p hp

/-- Eventual strong approximation for the full Vieta group at a fixed
integral coefficient triple. -/
def EventuallyVietaStrongApproximation (a : Coefficients ℤ) : Prop :=
  ∃ p0 : ℕ, ∀ (p : ℕ) (hp : p.Prime), p0 ≤ p →
    VietaStrongApproximationAt a p hp

/-- Eventual strong approximation for the rotation group at a fixed integral
coefficient triple. -/
def EventuallyRotationStrongApproximation (a : Coefficients ℤ) : Prop :=
  ∃ p0 : ℕ, ∀ (p : ℕ) (hp : p.Prime), p0 ≤ p → RotationStrongApproximationAt a p hp

/-- Nondegeneracy over the integers, which excludes only finitely many bad
reductions and is the natural hypothesis for an eventual theorem. -/
def IntegrallyNondegenerate (a : Coefficients ℤ) : Prop :=
  a.multiplier ≠ 0 ∧ a.a1 ^ 2 ≠ 4 ∧ a.a2 ^ 2 ≠ 4 ∧ a.a3 ^ 2 ≠ 4

/-- Every positive exponent eventually gives a giant rotation orbit for a
fixed integral coefficient triple. -/
def EventuallyHasGiantRotationOrbit (a : Coefficients ℤ) : Prop :=
  ∀ epsilon : ℝ, 0 < epsilon →
    ∃ p0 : ℕ, ∀ (p : ℕ) (hp : p.Prime), p0 ≤ p →
      HasGiantRotationOrbitAt a p hp epsilon

/-- The generalized analogue, for every fixed coefficient triple, of the
giant-orbit half of BGS Theorem 1. -/
def GeneralizedGiantOrbitStatement : Prop :=
  ∀ a : Coefficients ℤ,
    IntegrallyNondegenerate a → EventuallyHasGiantRotationOrbit a

/-- The project's eventual strong-approximation target. -/
def EventualStrongApproximationStatement : Prop :=
  ∀ a : Coefficients ℤ, IntegrallyNondegenerate a → EventuallyRotationStrongApproximation a

/-- The analogous eventual statement for the larger group generated by the
three individual Vieta involutions. -/
def EventualVietaStrongApproximationStatement : Prop :=
  ∀ a : Coefficients ℤ, IntegrallyNondegenerate a →
    EventuallyVietaStrongApproximation a

end GenMarkoff
