import GenMarkoff.General.Opening.RotationBridge

/-!
# Actual rotation order from a quadratic-extension eigenvalue

The BGS trace matrix has eigenvalues `q` and `q⁻¹`, so its order is
`orderOf q` away from the parabolic locus.  The linear part of an actual
two-Vieta rotation is the square of that matrix.  Accordingly, its orbit
parameter subgroup is generated by `q ^ 2`, and both sides have cardinality

`orderOf q / gcd (orderOf q) 2`.

This is the finite-field order bridge required by the general regular middle
game.  The hypothesis `q ^ 2 ≠ 1` is essential for the reused eigenvalue
diagonalization theorem; nonzero trace discriminant implies it.
-/

namespace GenMarkoff.General.MiddleGame

open BGS.Markoff

noncomputable section

/-- A nonparabolic quadratic-extension eigenvalue identifies the cardinality
of its square-generated subgroup with the actual rotation linear order. -/
theorem card_zpowers_sq_eq_rotationLinearOrder_of_eigenvalue
    (p : ℕ) [Fact p.Prime] [Fintype (quadraticFiniteField p)]
    (t : ZMod p) (q : (quadraticFiniteField p)ˣ)
    (hq : (q : quadraticFiniteField p) ^ 2 ≠ 1)
    (heigen :
      algebraMap (ZMod p) (quadraticFiniteField p) t =
        splitTorusTrace q) :
    Nat.card (Subgroup.zpowers (q ^ 2)) =
      rotationLinearOrder t := by
  rw [Nat.card_zpowers, orderOf_pow]
  rw [← rotationOrder_eq_orderOf_extensionEigenvalue t q hq heigen]
  rw [Opening.rotationLinearOrder_eq_bgsRotationOrder_div_gcd]

/-- Nonzero base-field discriminant rules out the two parabolic
quadratic-extension eigenvalues. -/
theorem quadraticEigenvalue_sq_ne_one_of_discriminant_ne_zero
    (p : ℕ) [Fact p.Prime] [Fintype (quadraticFiniteField p)]
    (t : ZMod p) (q : (quadraticFiniteField p)ˣ)
    (hD : discriminant t ≠ 0)
    (heigen :
      algebraMap (ZMod p) (quadraticFiniteField p) t =
        splitTorusTrace q) :
    (q : quadraticFiniteField p) ^ 2 ≠ 1 := by
  let f : ZMod p →+* quadraticFiniteField p :=
    algebraMap (ZMod p) (quadraticFiniteField p)
  have hDE :
      discriminant (f t) ≠ 0 := by
    have hmap : f (discriminant t) ≠ 0 :=
      (map_ne_zero f).mpr hD
    simpa [discriminant, f, map_sub, map_pow, map_ofNat] using hmap
  intro hq
  have hinv :
      ((q⁻¹ : (quadraticFiniteField p)ˣ) : quadraticFiniteField p) =
        (q : quadraticFiniteField p) := by
    apply mul_right_cancel₀ (Units.ne_zero q)
    simpa [pow_two] using hq.symm
  apply hDE
  rw [heigen, splitTorusTrace, hinv, discriminant]
  calc
    ((q : quadraticFiniteField p) +
          (q : quadraticFiniteField p)) ^ 2 - 4 =
        4 * ((q : quadraticFiniteField p) ^ 2 - 1) := by
      ring
    _ = 0 := by rw [hq]; ring

/-- Discriminant form of the actual rotation eigenvalue-order bridge. -/
theorem card_zpowers_sq_eq_rotationLinearOrder_of_discriminant_ne_zero
    (p : ℕ) [Fact p.Prime] [Fintype (quadraticFiniteField p)]
    (t : ZMod p) (q : (quadraticFiniteField p)ˣ)
    (hD : discriminant t ≠ 0)
    (heigen :
      algebraMap (ZMod p) (quadraticFiniteField p) t =
        splitTorusTrace q) :
    Nat.card (Subgroup.zpowers (q ^ 2)) =
      rotationLinearOrder t :=
  card_zpowers_sq_eq_rotationLinearOrder_of_eigenvalue
    p t q
      (quadraticEigenvalue_sq_ne_one_of_discriminant_ne_zero
        p t q hD heigen)
      heigen

end

end GenMarkoff.General.MiddleGame
