import BGS.Markoff.Opening.CompatibleRoots
import BGS.Markoff.Opening.CyclotomicNorm
import Mathlib.FieldTheory.IsAlgClosed.AlgebraicClosure
import Mathlib.NumberTheory.NumberField.Cyclotomic.Basic
import Mathlib.RingTheory.Polynomial.Cyclotomic.Roots

/-!
# A compatible prime and reduction for the cyclotomic opening

For `p ∤ n`, a prescribed primitive `n`-th root in an algebraic closure of `ZMod p`
determines a homomorphism from the ring of integers of `ℚ(ζₙ)`.  Its kernel is a prime above
`(p)`, and the induced quotient map sends all powers of the characteristic-zero generator to the
corresponding powers of the prescribed finite-characteristic root.
-/

open scoped NumberField
open Polynomial

namespace BGS.Markoff

/-- The canonical cyclotomic number field used for a common order `n`. -/
abbrev OpeningCyclotomicField (n : ℕ) := CyclotomicField n ℚ

/-- The ring of integers of the canonical cyclotomic number field. -/
abbrev OpeningCyclotomicIntegers (n : ℕ) :=
  NumberField.RingOfIntegers (OpeningCyclotomicField n)

/-- The algebraic closure in which the prescribed characteristic-`p` roots live. -/
abbrev OpeningResidueClosure (p : ℕ) [Fact p.Prime] := AlgebraicClosure (ZMod p)

private theorem neZero_ratCast (n : ℕ) [NeZero n] : (n : ℚ) ≠ 0 := by
  exact_mod_cast (NeZero.ne n)

/-- Coprimality with the characteristic makes `n` nonzero in the chosen residue closure. -/
theorem residueClosure_natCast_ne_zero_of_coprime
    (p n : ℕ) [Fact p.Prime] (hcoprime : Nat.Coprime p n) :
    (n : OpeningResidueClosure p) ≠ 0 := by
  have hnmod : (n : ZMod p) ≠ 0 := by
    rw [ne_eq, ZMod.natCast_eq_zero_iff]
    intro hpn
    have hdiv : p ∣ Nat.gcd p n := Nat.dvd_gcd (dvd_refl p) hpn
    rw [hcoprime.gcd_eq_one] at hdiv
    exact (Fact.out : p.Prime).not_dvd_one hdiv
  change algebraMap (ZMod p) (OpeningResidueClosure p) (n : ZMod p) ≠ 0
  exact (map_ne_zero_iff _ (algebraMap (ZMod p) (OpeningResidueClosure p)).injective).2 hnmod

/-- Three `n`-th roots in the residue closure are powers of one primitive `n`-th root.  The
coprimality hypothesis supplies the nonvanishing of `n` that was previously obtained from
characteristic zero. -/
theorem exists_residue_common_primitiveRoot_powers
    (p n : ℕ) [Fact p.Prime] [NeZero n] (hcoprime : Nat.Coprime p n)
    (w₁ w₂ w₃ : OpeningResidueClosure p)
    (hw₁ : w₁ ^ n = 1) (hw₂ : w₂ ^ n = 1) (hw₃ : w₃ ^ n = 1) :
    ∃ ω : OpeningResidueClosure p, ∃ a₁ a₂ a₃ : ℕ,
      IsPrimitiveRoot ω n ∧ a₁ < n ∧ a₂ < n ∧ a₃ < n ∧
      ω ^ a₁ = w₁ ∧ ω ^ a₂ = w₂ ∧ ω ^ a₃ = w₃ := by
  letI : NeZero (n : OpeningResidueClosure p) :=
    ⟨residueClosure_natCast_ne_zero_of_coprime p n hcoprime⟩
  obtain ⟨ω, hω⟩ := HasEnoughRootsOfUnity.exists_primitiveRoot (OpeningResidueClosure p) n
  obtain ⟨a₁, ha₁lt, ha₁⟩ := hω.eq_pow_of_pow_eq_one hw₁
  obtain ⟨a₂, ha₂lt, ha₂⟩ := hω.eq_pow_of_pow_eq_one hw₂
  obtain ⟨a₃, ha₃lt, ha₃⟩ := hω.eq_pow_of_pow_eq_one hw₃
  exact ⟨ω, a₁, a₂, a₃, hω, ha₁lt, ha₂lt, ha₃lt, ha₁, ha₂, ha₃⟩

/-- The canonical primitive `n`-th root in the chosen characteristic-zero cyclotomic field. -/
noncomputable def openingCyclotomicRoot (n : ℕ) [NeZero n] : OpeningCyclotomicField n := by
  letI : NeZero (n : ℚ) := ⟨neZero_ratCast n⟩
  letI : IsCyclotomicExtension {n} ℚ (OpeningCyclotomicField n) :=
    CyclotomicField.isCyclotomicExtension n ℚ
  exact IsCyclotomicExtension.zeta n ℚ (OpeningCyclotomicField n)

/-- The canonical characteristic-zero root has exact order `n`. -/
theorem openingCyclotomicRoot_isPrimitive (n : ℕ) [NeZero n] :
    IsPrimitiveRoot (openingCyclotomicRoot n) n := by
  letI : NeZero (n : ℚ) := ⟨neZero_ratCast n⟩
  letI : IsCyclotomicExtension {n} ℚ (OpeningCyclotomicField n) :=
    CyclotomicField.isCyclotomicExtension n ℚ
  simp [openingCyclotomicRoot]

/-- The canonical cyclotomic root, regarded as an algebraic integer. -/
noncomputable def openingCyclotomicIntegerRoot (n : ℕ) [NeZero n] :
    OpeningCyclotomicIntegers n :=
  (openingCyclotomicRoot_isPrimitive n).toInteger

/-- The integral power basis generated by the canonical cyclotomic root. -/
noncomputable def openingCyclotomicIntegralPowerBasis (n : ℕ) [NeZero n] :
    PowerBasis ℤ (OpeningCyclotomicIntegers n) := by
  letI : NeZero (n : ℚ) := ⟨neZero_ratCast n⟩
  letI : IsCyclotomicExtension {n} ℚ (OpeningCyclotomicField n) :=
    CyclotomicField.isCyclotomicExtension n ℚ
  exact (openingCyclotomicRoot_isPrimitive n).integralPowerBasis

@[simp]
theorem openingCyclotomicIntegralPowerBasis_gen (n : ℕ) [NeZero n] :
    (openingCyclotomicIntegralPowerBasis n).gen = openingCyclotomicIntegerRoot n := by
  letI : NeZero (n : ℚ) := ⟨neZero_ratCast n⟩
  letI : IsCyclotomicExtension {n} ℚ (OpeningCyclotomicField n) :=
    CyclotomicField.isCyclotomicExtension n ℚ
  exact (openingCyclotomicRoot_isPrimitive n).integralPowerBasis_gen

private theorem primitiveRoot_isRoot_integralPowerBasis_minpoly
    (p n : ℕ) [Fact p.Prime] [NeZero n] (_hcoprime : Nat.Coprime p n)
    (ω : OpeningResidueClosure p) (hω : IsPrimitiveRoot ω n) :
    aeval ω (minpoly ℤ (openingCyclotomicIntegralPowerBasis n).gen) = 0 := by
  letI : NeZero (n : OpeningResidueClosure p) :=
    ⟨residueClosure_natCast_ne_zero_of_coprime p n _hcoprime⟩
  have hrootCyclotomic : aeval ω (cyclotomic n ℤ) = 0 := by
    rw [aeval_def, ← eval_map, map_cyclotomic]
    exact hω.isRoot_cyclotomic (NeZero.pos n)
  letI : NeZero (n : ℚ) := ⟨neZero_ratCast n⟩
  letI : IsCyclotomicExtension {n} ℚ (OpeningCyclotomicField n) :=
    CyclotomicField.isCyclotomicExtension n ℚ
  simpa [openingCyclotomicIntegralPowerBasis,
    ← NumberField.RingOfIntegers.minpoly_coe,
    ← cyclotomic_eq_minpoly (openingCyclotomicRoot_isPrimitive n) (NeZero.pos n)] using
      hrootCyclotomic

/-- The compatible reduction homomorphism determined by the prescribed primitive root `ω`. -/
noncomputable def openingCyclotomicReduction
    (p n : ℕ) [Fact p.Prime] [NeZero n] (hcoprime : Nat.Coprime p n)
    (ω : OpeningResidueClosure p) (hω : IsPrimitiveRoot ω n) :
    OpeningCyclotomicIntegers n →ₐ[ℤ] OpeningResidueClosure p :=
  (openingCyclotomicIntegralPowerBasis n).lift ω
    (primitiveRoot_isRoot_integralPowerBasis_minpoly p n hcoprime ω hω)

/-- The compatible reduction sends the characteristic-zero generator to the prescribed root. -/
@[simp]
theorem openingCyclotomicReduction_integerRoot
    (p n : ℕ) [Fact p.Prime] [NeZero n] (hcoprime : Nat.Coprime p n)
    (ω : OpeningResidueClosure p) (hω : IsPrimitiveRoot ω n) :
    openingCyclotomicReduction p n hcoprime ω hω (openingCyclotomicIntegerRoot n) = ω := by
  rw [← openingCyclotomicIntegralPowerBasis_gen n]
  exact PowerBasis.lift_gen _ _ _

/-- The prime ideal of the cyclotomic integers selected by the prescribed residue root. -/
noncomputable def openingCyclotomicPrime
    (p n : ℕ) [Fact p.Prime] [NeZero n] (hcoprime : Nat.Coprime p n)
    (ω : OpeningResidueClosure p) (hω : IsPrimitiveRoot ω n) :
    Ideal (OpeningCyclotomicIntegers n) :=
  RingHom.ker (openingCyclotomicReduction p n hcoprime ω hω).toRingHom

/-- The selected kernel is prime because the residue closure is a field. -/
theorem openingCyclotomicPrime_isPrime
    (p n : ℕ) [Fact p.Prime] [NeZero n] (hcoprime : Nat.Coprime p n)
    (ω : OpeningResidueClosure p) (hω : IsPrimitiveRoot ω n) :
    (openingCyclotomicPrime p n hcoprime ω hω).IsPrime :=
  RingHom.ker_isPrime _

/-- The selected prime lies above the rational prime `(p)`. -/
theorem openingCyclotomicPrime_under
    (p n : ℕ) [Fact p.Prime] [NeZero n] (hcoprime : Nat.Coprime p n)
    (ω : OpeningResidueClosure p) (hω : IsPrimitiveRoot ω n) :
    (openingCyclotomicPrime p n hcoprime ω hω).under ℤ =
      Ideal.span {(p : ℤ)} := by
  unfold openingCyclotomicPrime Ideal.under
  rw [RingHom.comap_ker]
  have hcomp :
      (openingCyclotomicReduction p n hcoprime ω hω).toRingHom.comp
          (algebraMap ℤ (OpeningCyclotomicIntegers n)) =
        algebraMap ℤ (OpeningResidueClosure p) := by
    ext z
    exact (openingCyclotomicReduction p n hcoprime ω hω).commutes z
  rw [hcomp]
  exact CharP.ker_intAlgebraMap_eq_span p

/-- The quotient by the compatible prime embeds in the chosen residue closure. -/
noncomputable def openingCyclotomicQuotientReduction
    (p n : ℕ) [Fact p.Prime] [NeZero n] (hcoprime : Nat.Coprime p n)
    (ω : OpeningResidueClosure p) (hω : IsPrimitiveRoot ω n) :
    (OpeningCyclotomicIntegers n ⧸ openingCyclotomicPrime p n hcoprime ω hω) →+*
      OpeningResidueClosure p :=
  (openingCyclotomicReduction p n hcoprime ω hω).toRingHom.kerLift

/-- The quotient reduction is injective: its source is exactly the quotient by the kernel. -/
theorem openingCyclotomicQuotientReduction_injective
    (p n : ℕ) [Fact p.Prime] [NeZero n] (hcoprime : Nat.Coprime p n)
    (ω : OpeningResidueClosure p) (hω : IsPrimitiveRoot ω n) :
    Function.Injective (openingCyclotomicQuotientReduction p n hcoprime ω hω) := by
  unfold openingCyclotomicQuotientReduction openingCyclotomicPrime
  exact RingHom.kerLift_injective _

/-- The quotient reduction sends every power of the integral generator to the matching power of
the prescribed residue root. -/
theorem openingCyclotomicQuotientReduction_integerRoot_pow
    (p n a : ℕ) [Fact p.Prime] [NeZero n] (hcoprime : Nat.Coprime p n)
    (ω : OpeningResidueClosure p) (hω : IsPrimitiveRoot ω n) :
    openingCyclotomicQuotientReduction p n hcoprime ω hω
        (Ideal.Quotient.mk (openingCyclotomicPrime p n hcoprime ω hω)
          (openingCyclotomicIntegerRoot n ^ a)) =
      ω ^ a := by
  unfold openingCyclotomicQuotientReduction openingCyclotomicPrime
  rw [RingHom.kerLift_mk, map_pow]
  exact congrArg (fun z : OpeningResidueClosure p ↦ z ^ a)
    (openingCyclotomicReduction_integerRoot p n hcoprime ω hω)

/-- One chosen prime therefore realizes three prescribed powers simultaneously. -/
theorem openingCyclotomicQuotientReduction_three_powers
    (p n a₁ a₂ a₃ : ℕ) [Fact p.Prime] [NeZero n]
    (hcoprime : Nat.Coprime p n)
    (ω : OpeningResidueClosure p) (hω : IsPrimitiveRoot ω n) :
    let reduce := openingCyclotomicQuotientReduction p n hcoprime ω hω
    let quotient := Ideal.Quotient.mk (openingCyclotomicPrime p n hcoprime ω hω)
    reduce (quotient (openingCyclotomicIntegerRoot n ^ a₁)) = ω ^ a₁ ∧
      reduce (quotient (openingCyclotomicIntegerRoot n ^ a₂)) = ω ^ a₂ ∧
      reduce (quotient (openingCyclotomicIntegerRoot n ^ a₃)) = ω ^ a₃ := by
  dsimp only
  exact ⟨openingCyclotomicQuotientReduction_integerRoot_pow p n a₁ hcoprime ω hω,
    openingCyclotomicQuotientReduction_integerRoot_pow p n a₂ hcoprime ω hω,
    openingCyclotomicQuotientReduction_integerRoot_pow p n a₃ hcoprime ω hω⟩

end BGS.Markoff
