import BGS.Markoff.TraceCurve.SyntacticNormalForm

/-!
# The degenerate split trace cover has no principal syntactic division theorem

At `sigma = 1` and `d = e = 1`, the cleared cover polynomial is the product
`(y - x) * (x * y - 1)`.  The Kummer tower selects the component `x * y = 1`.
Consequently its evaluation kernel strictly contains the ideal generated by the whole cleared
polynomial.  This file records that obstruction explicitly: the source-side division statement
must assume the nondegeneracy condition `sigma != 1`.
-/

namespace BGS.Markoff

open Polynomial

noncomputable section

variable {K : Type*} [Field K]

/-- The component selected by the Kummer parametrization when `sigma = d = e = 1`. -/
def splitTraceDegenerateKummerComponent : MvPolynomial (Fin 2) K :=
  MvPolynomial.X 0 * MvPolynomial.X 1 - 1

private lemma ratFunc_X_mul_splitTraceRadicand_one :
    RatFunc.X * splitTraceRadicand (1 : K) = 1 := by
  have h := splitTraceRadicand_equation (K := K) (1 : K)
  norm_num at h
  have hne : (1 : RatFunc K) - RatFunc.X ≠ 0 := by
    intro hzero
    have hx : (1 : RatFunc K) = RatFunc.X := sub_eq_zero.mp hzero
    have hdegree := congrArg RatFunc.intDegree hx
    norm_num at hdegree
  have hfactor :
      ((1 : RatFunc K) - RatFunc.X) *
          (RatFunc.X * splitTraceRadicand (1 : K) - 1) = 0 := by
    linear_combination h
  exact sub_eq_zero.mp ((mul_eq_zero.mp hfactor).resolve_left hne)

private lemma splitTraceBaseU_mul_V_sq_one :
    splitTraceBaseU (1 : K) * splitTraceBaseV (1 : K) ^ 2 = 1 := by
  rw [splitTraceBaseV_sq]
  rw [splitTraceBaseU, ← map_mul, ratFunc_X_mul_splitTraceRadicand_one]
  simp

private lemma splitTraceKummer_roots_mul_one :
    splitTraceXiRoot (1 : K) 1 1 * splitTraceEtaRootInXiField (1 : K) 1 1 = 1 := by
  have hxi := splitTraceXiRoot_pow (K := K) (1 : K) 1 1
  have heta := splitTraceEtaRootInXiField_pow (K := K) (1 : K) 1 1
  simp only [pow_one] at hxi heta
  rw [hxi, heta]
  simp only [splitTraceXiRadicand, splitTraceBaseElementInXiField, map_mul]
  rw [← map_mul]
  rw [← map_mul]
  rw [← map_mul]
  rw [← map_mul]
  rw [show splitTraceBaseU (1 : K) * splitTraceBaseV (1 : K) *
      splitTraceBaseV (1 : K) =
    splitTraceBaseU (1 : K) * splitTraceBaseV (1 : K) ^ 2 by ring]
  rw [splitTraceBaseU_mul_V_sq_one]
  simp

/-- The Kummer-selected component has zero syntactic normal form. -/
theorem splitTraceDegenerateKummerComponent_syntacticNormalForm_eq_zero :
    splitTracePolynomialSyntacticNormalForm (1 : K) one_ne_zero 1 1
      (by decide) (by decide) (splitTraceDegenerateKummerComponent (K := K)) = 0 := by
  apply (splitTracePolynomialSyntacticNormalForm_eq_zero_iff
    (1 : K) one_ne_zero 1 1 (by decide) (by decide) (by decide)
    (splitTraceDegenerateKummerComponent (K := K))).2
  simp [splitTraceDegenerateKummerComponent, splitTracePolynomialToKummerTop,
    splitTraceKummer_roots_mul_one]

/-- The Kummer-selected component is not a multiple of the full degenerate cover polynomial.
Evaluation at the affine origin separates them. -/
theorem splitTraceDegenerateKummerComponent_not_mem_coverIdeal :
    splitTraceDegenerateKummerComponent (K := K) ∉
      Ideal.span {splitTraceCoverPolynomial (1 : K) 1 1 1} := by
  intro hmem
  let ev : MvPolynomial (Fin 2) K →+* K := MvPolynomial.eval ![0, 0]
  have hle : Ideal.span {splitTraceCoverPolynomial (1 : K) 1 1 1} ≤ RingHom.ker ev := by
    rw [Ideal.span_le]
    intro p hp
    simp only [Set.mem_singleton_iff] at hp
    subst p
    simp [ev, splitTraceCoverPolynomial]
  have hzero := hle hmem
  have hone : ev (splitTraceDegenerateKummerComponent (K := K)) = -1 := by
    simp [ev, splitTraceDegenerateKummerComponent]
  rw [RingHom.mem_ker, hone] at hzero
  exact one_ne_zero (neg_eq_zero.mp hzero)

/-- Therefore the source-side division assertion used by the affine injectivity endpoint is false
without the paper's nondegeneracy hypothesis `sigma != 1`. -/
theorem not_splitTraceSyntacticNormalForm_division_at_degenerateParameter :
    ¬ (∀ p : MvPolynomial (Fin 2) K,
      splitTracePolynomialSyntacticNormalForm (1 : K) one_ne_zero 1 1
          (by decide) (by decide) p = 0 →
        p ∈ Ideal.span {splitTraceCoverPolynomial (1 : K) 1 1 1}) := by
  intro hdivision
  exact splitTraceDegenerateKummerComponent_not_mem_coverIdeal (K := K)
    (hdivision (splitTraceDegenerateKummerComponent (K := K))
      splitTraceDegenerateKummerComponent_syntacticNormalForm_eq_zero)

/-- At the degenerate parameter, the affine comparison map itself is not injective: the nonzero
class of `x * y - 1` maps to zero. -/
theorem not_splitTraceAffineToKummerTop_injective_at_degenerateParameter :
    ¬ Function.Injective
      (splitTraceAffineToKummerTop (1 : K) one_ne_zero 1 1
        (by decide) (by decide) (by decide)) := by
  intro hinjective
  let I : Ideal (MvPolynomial (Fin 2) K) :=
    Ideal.span {splitTraceCoverPolynomial (1 : K) 1 1 1}
  let q : MvPolynomial (Fin 2) K := splitTraceDegenerateKummerComponent
  have hqeval :
      splitTracePolynomialToKummerTop (1 : K) one_ne_zero 1 1
          (by decide) (by decide) (by decide) q = 0 :=
    (splitTracePolynomialSyntacticNormalForm_eq_zero_iff
      (1 : K) one_ne_zero 1 1 (by decide) (by decide) (by decide) q).1
      splitTraceDegenerateKummerComponent_syntacticNormalForm_eq_zero
  have hqmap :
      splitTraceAffineToKummerTop (1 : K) one_ne_zero 1 1
          (by decide) (by decide) (by decide) (Ideal.Quotient.mk I q) = 0 := by
    change splitTracePolynomialToKummerTop (1 : K) one_ne_zero 1 1
      (by decide) (by decide) (by decide) q = 0
    exact hqeval
  have hqclass : Ideal.Quotient.mk I q = 0 := by
    apply hinjective
    simpa using hqmap
  have hqmem : q ∈ I := Ideal.Quotient.eq_zero_iff_mem.mp hqclass
  exact splitTraceDegenerateKummerComponent_not_mem_coverIdeal hqmem

end

end BGS.Markoff
